newrelic/newrelic-dotnet-agent

src/Agent/NewRelic/Agent/Core/Aggregators/SpanEventAggregatorInfiniteTracing.cs, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs, src/Agent/NewRelic/Agent/Core/Segments/DatastoreSegmentData.cs, src/Agent/NewRelic/Agent/Core/Segments/Segment.cs, src/Agent/NewRelic/Agent/Core/Spans/SpanEventMaker.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, src/NewRelic.Core/NewRelic.Collections/PartitionedBlockingCollection.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventAggregatorInfiniteTracingTests.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
* Creates a new `PartitionedBlockingCollection<T>` that allows the unification of multiple blocking collections into a single structure.  The rationale is that multiple smaller collections use less memory that a single larger collection.
* Modifies Infinite Tracing `SpanEventAggregatorInfiniteTracing` and the `SpanDataStreamingService` to use this collection.
=> Infinite Tracing - PartitionedBlockingCollection

src/Agent/NewRelic/Agent/Core/Attributes/AttributeValueCollection.cs, src/Agent/NewRelic/Agent/Core/Segments/AbstractSegmentData.cs, src/Agent/NewRelic/Agent/Core/Segments/DatastoreSegmentData.cs, src/Agent/NewRelic/Agent/Core/Segments/ExternalSegmentData.cs, src/Agent/NewRelic/Agent/Core/Segments/Segment.cs, src/Agent/NewRelic/Agent/Core/Spans/SpanEventMaker.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, tests/Agent/UnitTests/Core.UnitTest/Segments/CustomSegmentDataTests.cs, tests/Agent/UnitTests/Core.UnitTest/Segments/ExternalSegmentDataTests.cs, tests/Agent/UnitTests/Core.UnitTest/Segments/ExternalSegmentTests.cs, tests/Agent/UnitTests/Core.UnitTest/Segments/MessageBrokerSegmentDataTests.cs, tests/Agent/UnitTests/Core.UnitTest/Segments/MethodSegmentDataTests.cs, tests/Agent/UnitTests/Core.UnitTest/Segments/SegmentTests.cs, tests/Agent/UnitTests/Core.UnitTest/Segments/SimpleSegmentDataTests.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/CustomSegmentTransformersTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/DatastoreSegmentTransformerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/ExternalSegmentTransformerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/MessageBrokerTransformerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/MethodSegmentTransformersTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/SimpleSegmentTransformersTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/ErrorEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/SqlTraceMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TestTransactions.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTraceMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTransformerTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/SqlTraceWireModelTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/AgentWrapperApiTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/Builders/TransactionTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/TransactionFinalizerTests.cs
* Defer the creation of the `SpanAttributeValueCollection` until later in the lifecycle of the transaction.  The rationale is to save memory by:
* avoiding the creation of this object unless a Span will actually be created (DT sampled, or Infinite Tracing has capacity)
* Making the `SpanAttributeValueCollection` a shorter-lived object to help in GC
=> Infinite Tracing - Defer Creation of SpanAttributeValueCollection

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs, src/Agent/NewRelic/Agent/Core/DataTransport/GrpcWrapper.cs, src/Agent/NewRelic/Agent/Core/DataTransport/SpanStreamingService.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
Manages Response Streams on a single thread
* Creates `ResponseStreamInfo` class 
* Hold the Stream and the Task for obtaining the next response
* Exposes GetAwaiter which will use existing task or create new one as needed
* Exposes IsInvalid flag identifying failure conditions
* Modifies `GrpcWrapper` to return both Request and Response Streams as `out` parameters to the CreateChannel call
* Modifies `DataStreamingService` to manage response streams
=> Infinite Tracing - Manage Response Streams with a single thread

src/Agent/NewRelic/Agent/Core/Aggregators/SpanEventAggregatorInfiniteTracing.cs, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventAggregatorInfiniteTracingTests.cs
Updates the Infinite Tracing version of the span event aggregator to respect the SpanEventsEnabled and DistributedTracingEnabled configuration settings, and adds some caching to the SpanEventsEnabled configuration setting.
=> Fixing SpanEventsEnabled and DistributedTracingEnabled checks for Infinite Tracing

build/build_functions.ps1
Migration over to new home builder scripting reintroduced the x86 GRPC SO file that we didn't want in the package.
No only copies the x64 version.
=> Fixed build_functions.ps1 to not include x86 GRPC .SO file

src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs, src/Agent/NewRelic/Agent/Core/DataTransport/Delayer.cs
Ensures that our delayer doesn't bubble up an exception when the cancellation token is triggered, and ensures that the span batch is not sent when the cancellation token is triggered and the items are added back to the queue.
=> Small bug fixes.

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/AgentInstallConfiguration.cs, src/Agent/NewRelic/Agent/Core/DependencyInjection/AgentServices.cs, src/Agent/NewRelic/Agent/Core/Transformers/MemorySampleTransformer.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/MemorySampleTransformerTests.cs
Fixes issue where applications running on Linux were either reporting no physical memory usage or using VmData to report the physical memory usage of the application. The agent now uses VmRSS through a call to [`Process.WorkingSet64`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.workingset64) to report physical memory usage. See the [dotnet runtime discussion](https://github.com/dotnet/runtime/issues/28990) and the [proc man pages](https://man7.org/linux/man-pages/man5/proc.5.html) for more details about this change.
=> Update memory physical metric source for linux

src/Agent/NewRelic/Agent/Core/Aggregators/SpanEventAggregatorInfiniteTracing.cs, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionTransformer.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTransformerTests.cs
* Update Default value for Infinite Tracing Batch size to 700
* When Infinite Tracing Queue Capacity is not available during transaction transform, update both Seen and Sent supportability metrics (add Seen)
=> Infinite Tracing - Record Seen supportability metric when dropping b/c of no capacity; update default for batch size

tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplication.cs, tests/Agent/IntegrationTests/IntegrationTests/ConnectResponseHandlingTests.cs, tests/Agent/IntegrationTests/IntegrationTests/HighSecurityModeEnabled.cs, tests/Agent/IntegrationTests/IntegrationTests/SecurityPoliciesMostRestrictiveTests.cs
* Modifies requestTimeout for test projects to be 10sec by default
* Because tests Force Send On Exit, the default was 2s.
* Modifies High Security Mode and Security Policies Most Restrictive Tests
* To validate existence of Apdex, but not the value for a passing transaction b/c that value can vary and makes the test flaky.
* Modifies Connect Response Tests
* To Force Transaction Traces to make it less flaky.
=> Integration Tests - Cleanup

src/Agent/CHANGELOG.md
Adds a CHANGELOG.md file for the net35/main (6.x agent versions) branch.
=> Add changelog for net35/main (6.x)

src/Agent/NewRelic/Agent/Core/Errors/ErrorService.cs, src/Agent/NewRelic/Agent/Core/Segments/Segment.cs, src/Agent/NewRelic/Agent/Core/Spans/SpanEventMaker.cs, src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionAttributeMaker.cs, src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionTransformer.cs, tests/Agent/UnitTests/Core.UnitTest/Errors/ErrorServiceTests.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transactions/ImmutableTransactionBuilder.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTransformerTests.cs
With this PR we should now match the behavior of other New Relic agents with how the error collector enabled setting is used.
When the error collector is disabled the following should occur:
- Error metrics should not be generated
- Error Events and Error Traces should not be generated
- Transaction Events should not have error attributes generated
- Span events should not have error attributes generated
- "Frustrated" Apdex metrics should still be generated if a transaction has an error, because errors usually result in "frustrated" users
- apdex perf zone attribute should still be generated
=> Error collector enabled setting updates

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
- Adds a PR template based on what I saw in other agents' repos.
- Adds PR guidelines to the contributions guide based on a proposed skeleton and .NET agent specific details.
=> Pull request template and guidelines

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Errors/ErrorData.cs, src/Agent/NewRelic/Agent/Core/Errors/ErrorService.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/MetricNames.cs, src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionTransformer.cs, src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/Errors/ErrorServiceTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TestTransactions.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTransformerTests.cs
Expected error classes and error messages implementation.
- When an error is expected, Frustrated Apdex metric should not be created automatically for the error transaction.
- When an error is expected, increments count for "ErrorsExpected/all" metric, but MUST NOT increment any of the Errors/* metrics.
- When an error is expected, still increments count for "Supportability/Events/TransactionError/Seen" and "Supportability/Events/TransactionError/Sent".
- When an error is expected, traced errors and error events, span event error attributes are still generated.
- When an error is expected, error trace should include `error.expected` attribute, but this will be addressed in a different PR.
- If an error is set to be ignored and expected, it will be ignored.
=> Expected error classes and error messages implementation.

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Samplers/GcSampler.cs, src/AwsLambda/CHANGELOG.md, src/NewRelic.Core/NewRelic.SystemInterfaces/IProcess.cs, src/NewRelic.Core/NewRelic.SystemInterfaces/PerformanceCounterProxy.cs, tests/Agent/UnitTests/CompositeTests/Samplers/GcSamplerTests.cs, tests/NewRelic.Core.Tests/NewRelic.SystemInterfaces/PerformanceCounterProxyFactoryTests.cs
Redesigns the GC Sampler for Windows to account for missing performance counters and performance counter instance name changes.
* **Performance Counter Instance Name can change during the lifetime of the application**
* Removes caching of this value and pulls it once for every sampling cycle.
* When Performance Counter Instance Name Changes, recreate performance counters and dispose the old ones.
* Because a race condition can occur where the instance name changes between the time it is captured and the time the values are collected, the GC Sampler is more resilient when failures occur.  Allows up to 5 consecutive failures before shutting down.
* **Reverse lookup using PID to obtain Performance Counter Instance Name will not work until a GC has been reported**
* Attempts to obtain the …
=> Garbage Collection Performance Counters Fixes

src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, src/Agent/NewRelic/Agent/Core/Segments/Segment.cs, src/Agent/NewRelic/Agent/Core/Spans/SpanEventMaker.cs, src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionAttributeMaker.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs
Generates `error.expected` attribute for Error Events, Error Traces and Span Events
Generates `error.expected` intrinsic attribute for Error Events and Error Traces if error is expected.
Generates `error.expected` agent attribute for Span Events if error is expected.
=> Generates `error.expected` attribute for Error Event, Error Trace and Span Event

src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/ServerConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
`expectedStatusCodes` configuration should accept a comma separated list of status codes string. The current implementation made it to accept a list of individual status codes.
=> Fixes the expectedStatusCodes configuration

build/Packaging/NugetAgentApi/NewRelic.Agent.Api.nuspec, build/Packaging/NugetAzureCloudServices/NewRelicWindowsAzure.nuspec, build/Packaging/NugetAzureWebSites-x64/NewRelic.Azure.WebSites.x64.nuspec, build/Packaging/NugetAzureWebSites-x86/NewRelic.Azure.WebSites.nuspec, build/Packaging/ScriptableInstaller/NewRelic.Net.Agent.nuspec, build/Packaging/ScriptableInstaller/NewRelic.Net.Agent.x64.nuspec
Update the `license` element of .nuspec files on the `net35/main` branch to be Apache-2.0.
=> Add/update license in nuspec files to be Apache-2.0

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, src/Agent/CHANGELOG.md
This adds and/or updates some of the standard repository documentation assets to the net35/main branch:
* Add CONTRIBUTING.md
* This has been modified from the main branch version to call out specific guidelines for this branch.
* Add CODE_OF_CONDUCT.md
* Modify README.md to match the version from the `main` branch, except for places where it calls out specific details of this branch, such as the lack of a roadmap.
=> Add repository documentation for net35 branch

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Errors/ErrorService.cs, tests/Agent/UnitTests/Core.UnitTest/Errors/ErrorServiceTests.cs
- Wiring up to mark error with expected status code as expected.
- Limit expected classes and expected messages configuration entries to 50 entries.
- Refactoring.
=> Mark error data as expected if response status code is listed as expected 

src/Agent/NewRelic/Agent/Parsing/SqlWrapperHelper.cs
This reduces the amount of garbage created and should be higher-performance.
This uses `string.IndexOf(text, StringComparion)` instead of calling `.ToLowerInvariant` then `.Contains`. 
From https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings#specifying-string-comparisons-explicitly:
> We recommend that you select an overload that does not use default values, for the following reasons:
> 
> * Some overloads with default parameters (those that search for a Char in the string instance) perform an ordinal comparison, whereas others (those that search for a string in the string instance) are culture-sensitive. It is difficult to remember which method uses which default value, and easy to confuse the overloads.
`string.Contains(String, StringComparison)` is not …
=> Use StringComparison.OrdinalIgnoreCase for case-insensitive searches

src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs, src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs
This PR adds the configuration value for distributed tracing to the `agent_settings` payload sent to NR when the agent connects.  This lets the value of DT config appear in the agent settings page in the UI, which is helpful to both customers and our support team in troubleshooting DT issues.
=> Add the configuration of distributed tracing to agent settings reported to New Relic

src/Agent/NewRelic.Api.Agent/NewRelic.cs, src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs, src/Agent/NewRelic/Agent/Core/Api/AgentApiImplementation.cs, src/Agent/NewRelic/Agent/Core/Errors/ErrorService.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/IAgentApi.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/InternalApi.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/ErrorTraceMakerTests.cs
Add `NoticeError(string message, IDictionary<string, string> parameters, bool isExpected)` and `NoticeError(string message, IDictionary<string, object> parameters, bool isExpected)` calls to the public apis.
=> Add new overloading public api calls to expect errors

tests/Agent/IntegrationTests/Applications/BasicWebService/BasicWebService.csproj, tests/Agent/IntegrationTests/Applications/OwinRemotingClient/OwinRemotingClient.csproj, tests/Agent/IntegrationTests/Applications/OwinRemotingServer/OwinRemotingServer.csproj
Recent PR inadvertently altered some .csproj files with unnecessary and undesirable effects in IntegrationTests resulting in a project conversion when opening the solution(s) in Visual Studio.
=> remove tooling additions causing a conversion

build/Linux/build/deb/build.sh, build/Linux/build/deb/conffiles, src/Agent/CHANGELOG.md
While issue #81 only mentioned rpm/yum package upgrades, the same issue existed for deb/apt package upgrades on Debian distros.  This PR fixes that.
=> Preserve newrelic.config on .deb package upgrade

build/Packaging/CoreInstaller/installAgent.ps1
1. On the -X86 install path, there was a space between `-` and `Recurse` in the command to copy the agent files to the supplied destination, which broke any attempt to use this script to install the 32-bit core agent on Windows.
2. There was a typo in a variable name which broke the logic which should allow the user to install the agent to an existing folder as long as it was empty.
=> Fix two bugs in core installer script

.github/workflows/stale.yml
Issues labeled with `roadmap` will be exempted from the stale check.
=> Adds roadmap to stale exemptions

tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml, tests/Agent/IntegrationTests/UnboundedServices/rabbitmq/Dockerfile
This adds a docker-compose file and associated Dockerfile for hosting a RabbitMq service locally to be used by the unbounded integration tests.
We manually tested running the RabbitMq unbounded tests against this local service and they passed.  Otherwise, no agent or test code changes are made by this PR.
No changelog entry required.
=> Dockerized rabbitmq test dependencies

tests/Agent/IntegrationTests/IntegrationTestHelpers/CommonUtils.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDB2_6_AsyncCursorTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDB2_6_DatabaseTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDB2_6_IndexManagerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDB2_6_MongoCollectionTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDB2_6_MongoQueryProviderTests.cs, tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml, tests/Agent/IntegrationTests/UnboundedServices/mongodb32/Dockerfile, tests/Agent/IntegrationTests/UnboundedServices/mongodb36/Dockerfile
This PR adds dockerized MongoDB services for both groups of MongoDB integration tests (one set uses the 1.10 version of the MongoDB .NET client driver and the other uses the 2.6 version).  This is for issues #123 and #125.
A change was needed in the assertions for the `Datastore/instance` metrics because the agent has some special-case logic to use the local hostname (from Dns.GetHostname()) if the server's address is "localhost" or "127.0.0.1".
No changelog entry required.
=> Add dockerized services for both MongoDB test groups

build/Scripts/run-integration-tests.ps1, tests/Agent/IntegrationTests/UnboundedServices/unbounded-services-control.ps1
This PR introduces a script for starting and stopping the dockerized unbounded services, `unbounded-services-control.ps1`.  At the moment it is essentially a wrapper around `docker-compose up/down`.  However, we anticipate needing to add some setup commands for some services after they are started; they should be added to this new script.
This PR also modifies `run-integration-tests.ps1` to call this new script to start the services before running the unbounded tests and then stop the services after the tests finish.
I tested the scripts locally; our CI for the unbounded tests calls the `run-integration-tests.ps1` script so it will get tested on PR merge.  There are no agent behavior changes in this PR.
No changelog entry needed.
=> Script changes for dockerized unbounded services

tests/Agent/IntegrationTests/UnboundedServices/couchbase/Dockerfile, tests/Agent/IntegrationTests/UnboundedServices/couchbase/configure-server.sh, tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml
This PR is for issue #120.  It adds a Dockerfile and associated docker-compose.yml entry to run a Couchbase server to be used by the Couchbase unbounded integration tests.
`configure-server.sh` is added to the container image in the Dockerfile and is run when the container is launched to perform the necessary Couchbase server setup steps we used to perform manually when setting up a Couchbase server in our internal environment.
I verified that the Couchbase unbounded integration tests pass when run against this local container.
=> Dockerized couchbase test dependencies

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
New Relic specific environment variables should have "NEW_RELIC" prefix. This PR changes the obscuring key environment variable name from "OBSCURING_KEY" to "NEW_RELIC_CONFIG_OBSCURING_KEY".
=> Changes obscuring key environment variable name.

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Mvc3/AsyncBeginInvokeActionWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Mvc3/Mvc3.csproj, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Mvc3/MvcRouteNamingHelper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Mvc3/SyncInvokeActionWrapper.cs
Removes dependency on `System.Web.Mvc` in the Agent's Mvc3 instrumentation to avoid exceptions such as `System.InvalidCastException: Expected argument 0 to be of type System.Web.Mvc.ControllerContext (v3.0.0.1), but was of type System.Web.Mvc.ControllerContext (v4.0.0.1)` .
This was accomplished using `<dynamic>` instead of specific `System.Web.Mvc` type `ContextController`.
Use of `ControllerContext` in `System.Web.Mvc` was checked via decompilervfor use by restricted methods (internal, private) and none were found, so use of it in the Agent should not pose a problem.
Attempts were made to create an Mvc4 test app, as in the reporting customer's case, but the exception was not reproducible.
Removal of Agent instrumentation dependency on the dll should prevent the assembly version mismatch …
=> Fix assembly version mismatch

tests/Agent/IntegrationTests/ApplicationHelperLibraries/ConsoleMultiFunctionApplicationHelpers/NetStandardLibraries/GitCommand.cs, tests/Agent/IntegrationTests/IntegrationTests/W3CValidation.cs
On 8/19/2020 a change was made to the tracecontext tests to perform additional checking prior to running tests to fix an issue they had.
Issue: https://github.com/w3c/trace-context/issues/416
PR: https://github.com/w3c/trace-context/pull/417
This changed a number of tests, including "test_tracestate_empty_header"
https://github.com/w3c/trace-context/pull/417/files#diff-3eb4d995269f8dd7de58cb236d151d7bR505
That change for this test was to ensure that tracestate was null (at least it appears so with my limited Python)
There were a couple of other additional checks added, but we are not hitting them as of yet due to this initila problem.
I am not entirely sure if our agent is doing anything wrong at this point.  It looks like the test is expecting to NOT get back a tracestate, whcich seems …
=> Update GitCommand to support checkouts and W3CValidation to checkout

build/Scripts/run-integration-tests.ps1, tests/Agent/IntegrationTests/UnboundedIntegrationTests/IbmDb2AsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/IbmDb2Tests.cs, tests/Agent/IntegrationTests/UnboundedServices/db2/Dockerfile, tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml, tests/Agent/IntegrationTests/UnboundedServices/unbounded-services-control.ps1
Resolves issue #118.  Adds a dockerfile and docker-compose.yml entry to host IBM Db2 in a docker container for use by our integration tests for the Db2 instrumentation wrapper.
Some assertions in the Db2 tests were updated to use the `NormalizeHostname` method to get the correct database instance metric string based on local vs. remote db host.  I verified the Db2 tests pass when pointed at the local service in Docker.
N/A
=> Dockerized db2 test dependencies

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
rename `encryptedPassword` attribute in `<Proxy>` to `passwordObfuscated`
Tests already exist, just renamed variables in them
Updated ChangeLog.
Updating Online docs draft.
=> Proxy Password Obfuscation: rename encryptedPassword to passwordObfuscated

tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml, tests/Agent/IntegrationTests/UnboundedServices/oracle/Dockerfile
Resolves issue #129.  Adds a Dockerfile and docker-compose.yml entry to provide an Oracle 11 express edition database for use by the unbounded tests that test our Oracle DB instrumentation wrapper.
I've verified that the unbounded tests for Oracle pass when using this service, and we'll make sure our CI job for the unbounded tests pass before merging this.
N/A
=> Dockerized oracle test dependencies

build/Scripts/run-integration-tests.ps1
This PR adds a switch (`-startUnboundedServices`) to make auto-starting of the dockerized test services from the integration test runner script optional.  This is primarily to allow our internal CI to bypass starting and stopping of the services.
I manually tested the switch to make sure it had the intended effect.
N/A
=> Make use of the dockerized unbounded services optional

tests/Agent/IntegrationTests/Applications/BasicMvcApplication/BasicMvcApplication.csproj, tests/Agent/IntegrationTests/Applications/BasicMvcApplication/Web.config, tests/Agent/IntegrationTests/Applications/BasicWebApplication/BasicWebApplication.csproj, tests/Agent/IntegrationTests/Applications/ConsoleInstrumentationLoaderCore/Program.cs, tests/Agent/IntegrationTests/Applications/ConsoleMultiFunctionApplicationFW/ConsoleMultiFunctionApplicationFW.csproj, tests/Agent/IntegrationTests/Applications/RejitMvcApplication/Web.config, tests/Agent/IntegrationTests/Applications/WebForms45Application/Web.config, tests/Agent/IntegrationTests/Applications/WebForms45Application/WebForms45Application.csproj, tests/Agent/IntegrationTests/IntegrationTests.sln, tests/Agent/IntegrationTests/IntegrationTests/CallStackFallbackMvc.cs, tests/Agent/IntegrationTests/Shared/MsSqlOleDbConfiguration.cs
This PR reduces the number of build warnings when building the integration tests solution, primarily by modifying package references in .csproj files and some assembly binding redirections in web.config files.  These warnings were recently introduced by project file changes to support StyleCop.
It also fixes some test failures caused by a) asserting on the value of the ApdexPerfZone attribute rather than just asserting on its presence and b) fixing a copyright header format issue in one file.
The integration tests solution builds with fewer warnings, and the tests pass for me locally (as reliably as usual, meaning that out of 900+ tests I typically get 5-15 test flickers (failures which pass upon re-test)).
N/A because no agent functionality changed.
=> Integration test fixes

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Sql/Instrumentation.xml
Fixes #85.
This causes MySqlConnector to be instrumented by default; it supports the namespaces for both MySqlConnector v0.x (`MySql.Data.MySqlClient`) and v1.x (`MySqlConnector`).
I've performed local ad-hoc testing with MySqlConnector 0.69.9 and 1.0.1 in a local ASP.NET Web API project under IIS. Results were logged to this project: https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJuZXJkbGV0SWQiOiJkaXN0cmlidXRlZC10cmFjaW5nLW5lcmRsZXRzLmRpc3RyaWJ1dGVkLXRyYWNlLWxpc3QiLCJlbnRpdHlJZCI6Ik9UazNOelY4UVZCTmZFRlFVRXhKUTBGVVNVOU9mRGczTXprME5UQTFOZyJ9&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJPVGszTnpWOFFWQk5mRUZRVUV4SlEwRlVTVTlPZkRnM016azBOVEExTmciLCJzZWxlY3RlZE5lcmRsZXQiOnsibmVyZGxldElkIjoiZGlzdHJpYnV0ZWQtdHJhY2luZy1uZXJkbGV0cy5kaXN0cmlidXRlZC10cmFjZS1saXN0I …
=> Instrument MySqlConnector

tests/Agent/IntegrationTests/UnboundedServices/README.md, tests/Agent/IntegrationTests/UnboundedServices/example-secrets.json, tests/Agent/IntegrationTests/UnboundedServices/unbounded-services-control.ps1
Adds a README.md on how to use the unbounded service containers when running unbounded integration tests.
N/A
N/A
=> Document use of the containerized services for the unbounded integration tests

tests/Agent/IntegrationTests/Shared/Db2Configuration.cs, tests/Agent/IntegrationTests/Shared/IntegrationTestConfiguration.cs, tests/Agent/IntegrationTests/Shared/MsSqlConfiguration.cs, tests/Agent/IntegrationTests/Shared/MySqlConfiguration.cs, tests/Agent/IntegrationTests/Shared/OracleConfiguration.cs, tests/Agent/IntegrationTests/Shared/PostgresConfiguration.cs, tests/Agent/IntegrationTests/Shared/StackExchangeRedisConfiguration.cs
Refactor connection string/uri parsing in unbounded integration test configuration classes to be more robust by use of standard classes:
* DbConnectionStringBuilder
* UriBuilder
Verified that unbounded integration tests passed locally.
N/A
=> Refactor connection string parsing (#206)

tests/Agent/IntegrationTests/UnboundedServices/README.md, tests/Agent/IntegrationTests/UnboundedServices/example-secrets.json, tests/Agent/IntegrationTests/UnboundedServices/unbounded-services-control.ps1
Port documentation of docker services for unbounded int. tests to the net35/main branch
N/A
N/A
=> Net35 - Document docker services for unbounded tests

docs/integration-tests.md
Fixes issue #204 by documenting the need to download and install the IBM DB2 Data Server Client software in order to build and run our unbounded integration tests suite.
No testing required for a docs change.
N/A
=> Add DB2 client install instructions

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Providers/Wrapper/Delegates.cs
If the `Task` has already completed, we call `EndSegment` (synchronously) immediately. Otherwise, we always continue with `TaskContinuationOptions.ExecuteSynchronously` on the default `TaskScheduler`, which runs our continuation as soon as possible (on the thread that completed the task).
This avoids task continuations being delayed until much later in the ASP.NET pipeline (due to when `AspNetSynchronizationContext` posts them), which causes inaccurate timings.
Tested in prod as per https://github.com/newrelic/newrelic-dotnet-agent/issues/85#issuecomment-690669280.
=> Change how EndSegment is called for Tasks

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/GenericHostWebHostBuilderExtensionsWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Owin/ResolveAppWrapper.cs
The current agent is not compatible with .Net 5.0 RC1. This is due to an introduction of a new method overload of the ConfigureWebHost method in .Net 5.0 RC1. The agent currently subscribes to any of this method overload to add the custom AddNewRelicStartupFilter startup filter into the application pipeline in order to instrument Asp.net core calls. Since introduction of the new method overload, the agent subscribed to two method overloads and they were both executed. As a result, the agent added more than one AddNewRelicStartupFilter startup filter into the pipeline. It should add only one. This PR fixes this.
=> AddNewRelicStartupFilter should only be added once.

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Fixes #195 
Updated the Contributing.md file to reference the organization Code_of_conduct.md file.  Remove the local Code_of_Conduct.md file.
N/A - Documentation change.
=> Updated Contributing.md to reference org Code_of_Conduct.md file

.github/workflows/all_solutions.yml
Resolves #237 
Saves the linux and windows profiler artifacts so that they can be used later on in the workflow during the integration tests.  Will create 3 artifact packages, 2 for windows and 1 for linux:
- `windowsprofiler-x86-<github.run_id>`
- `windowsprofiler-x64-<github.run_id>`
- `linuxprofiler-<github.run_id>`
Workflow completes.  
Windows artifacts will come in two packages, one for x86 and one for x64 to avoid confusion since the names are all the same. Both packages should have the follow files at a minimum:
- NewRelic.Profiler.dll
- NewRelic.Profiler.pdb
Linux: 
- libNewRelicProfiler.so
Please remember to update our [changelog](/src/Agent/CHANGELOG.md) if applicable (or [this changelog](/src/AwsLambda/CHANGELOG.md) for Lambda agent changes),
=> Save Profiler artifacts for later use in workflow

docs/integration-tests.md, tests/Agent/IntegrationTests/UnboundedServices/example-secrets.json
Updates `example-secrets.json` file to include HSM & CSP keys, and AWS credentials, providing an example for all possible secrets.
Updates docs file to point to example-secrets.json.
No testing as this is just an example/documentation and has placeholders for the actual values.
N/A
=> Update example secrets file

.github/workflows/all_solutions.yml
Resolves #236
Add a step to archive the integration test artifacts.
- Only save the bin and Deploy folders since the checkout will have the rest of the files
- Relies on the checkout to pull the code (won't be needed most of the time, bit its already getting pulled in)
- Artifacts are currently ~400mb in size and take ~5 minutes to upload (full download should be about the same)
- Artifacts have been built to have the repo root as the root of the package to make overlaying the files easier.  (Was done by adding `test.runsettings` to artifacts -- also noted in yml).
The idea is that after checking out the branch, the artifacts can be pulled down on top of the branch resulting in all the required files being in place.
Adds `if-no-files-found: error` to all the artifacts uploads so that jobs …
=> Save integration test artifacts

src/Agent/NewRelic/Profiler/linux/build_profiler.sh
Resolves #254 
Fixes a problem where runs of the linux profiler are reported as successful despite the build failing.   Updates build_profiler.sh to include workflow commands to report up errors as well as some scripting to catch errors and return them as the exit code.
I ran this in my fork and it failed as expected when errors were manually introduced by editing build_profiler.sh with some bad command and the like.
n/a
=> Updates build_profiler.sh to explicitly fail on errors

.github/workflows/all_solutions.yml
Resolves #256
- The publishing of the test results is failing if the workflow is re-run due to the folder structure already existing.
- Updates the script that moves the results to also check if the run folder exists before attempting to create it.
First run passed as expected so I re-ran the workflow and that also ran fine, no publishing issues.
n/a
=> Fixes the test results publishing issue with re-running a workflow

.github/workflows/all_solutions.yml
Resolves #255 
Reorders workflow
- Moves profiler builds to top of workflow so they occur first
- Profiler builds clear our _profilerBuild to ensure fresh files are use
- FullAgent now needs profiler builds
- Full Agent also clears _profilerBuild and pulls new profiler artifacts
- As a result homefolders now contain only files built during that run
- Build should complete.
- The profiler-<runid>  should have 3 folders: linux-release, x64-Release, x86-Release.  This folders should have the profiler assemblies.
- Check that the profiler assemblies in the profiler-<runid> artifact match the one in the homefolder-<runid> artifact.
n/a
=> Fixes the problem of home folders not using profiler built during workflow run

tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
This unit test has been flickering (failing sometimes and not others) in our new GitHub CI, which has been slowing down testing and PRs.  This change ignores the test until November 1st.
N/A
N/A
=> Ignore flickering test until next month

tests/Agent/IntegrationTests/UnboundedServices/Windows/docker-compose.yml, tests/Agent/IntegrationTests/UnboundedServices/Windows/mssql/Dockerfile, tests/Agent/IntegrationTests/UnboundedServices/Windows/mssql/entrypoint.ps1, tests/Agent/IntegrationTests/UnboundedServices/Windows/mssql/restore.sql, tests/Agent/IntegrationTests/UnboundedServices/Windows/mssql/setup.ps1, tests/Agent/IntegrationTests/UnboundedServices/Windows/mssql/start.ps1
Description
Resolves #244. Adds a Windows docker image for MSSQL.
Testing
The mssql unbounded integration tests pass locally, although with occasional flickers. These flickers will be addressed when implementing the Unbounded Test execution in GitHub CI, the intended use case for Windows containers.
Changelog
N/A
=> Ms sql windows container

tests/Agent/IntegrationTests/UnboundedServices/linux/docker-compose.yml, tests/Agent/IntegrationTests/UnboundedServices/linux/mssql/Dockerfile
Removes unused environment variables leftover from initial development and testing.
Unbounded MsSql tests pass locally without them.
N/A
=> remove unnecessary confusing env vars

src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs
When an exception is thrown while the agent is initializing its log4net file appender, the agent falls back to setting up an event log appender. This is only true for .NET Framework applications - not .NET Core.
For example, one way to cause an exception during the file appender initialization is to use the following agent configuration:
```xml
<log level="info" directory="C:\SomeBogusDirectory" />
```
Since the directory does not exist, this code throws an exception:
https://github.com/newrelic/newrelic-dotnet-agent/blob/2b8e8cdc71146b1196e6a455e981be37fe789532/src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs#L390-L399.
The exception is caught and the event log appender is set up here:
https://github.com/newrelic/newrelic-dotnet-agent/blob/2b8e8cdc71146b1196e6a455e981be37fe7895 …
=> Set log level to warn for event log appender

.github/workflows/all_solutions.yml
In order to make troubleshooting our integration test failures easier, this PR does the following:
1. XUnit outputs XML instead of HTML reports
2. These reports are consolidated into a single downloadable artifact for easier processing of all test results.
3. Some additional data is gathered before and after running the integration tests - ports in use, and Windows event log errors and warnings for HostableWebCore and the .NET Runtime.
N/A
N/A
=> Gather additional data and consolidate integration test results

.github/workflows/all_solutions.yml
Adds aiohttp library installation, a dependency of the W3CValidationTest Integration Test.
Run Action  `.NET Agent All Solutions Build`, verify W3CValidationTest passes (in DistributedTracing namespace).
Example output expected:
```
<test name="NewRelic.Agent.IntegrationTests.DistributedTracing.W3CInstrumentationTests.W3CValidation.Test" type="NewRelic.Agent.IntegrationTests.DistributedTracing.W3CInstrumentationTests.W3CValidation" method="Test" time="26.2680708" result="Pass">
```
N/A
=> adds aiohttp install in yml

src/Agent/NewRelic/Agent/Core/Api/AgentApiImplementation.cs, src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, src/Agent/NewRelic/Agent/Core/Attributes/AttributeValueCollection.cs, src/Agent/NewRelic/Agent/Core/Transactions/ITransactionAttributeMetadata.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/TransactionMetadata.cs, src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionAttributeMaker.cs, tests/Agent/UnitTests/CompositeTests/AgentApiTests.cs, tests/Agent/UnitTests/Core.UnitTest/Attributes/AttributeCollectionTests.cs, tests/Agent/UnitTests/Core.UnitTest/CrossAgentTests/RumTests/RumClientConfigTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transactions/ImmutableTransactionBuilder.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/ErrorEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/AgentWrapperApiTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/Builders/TransactionMetadataTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/Builders/TransactionTests.cs, tests/Agent/UnitTests/NewRelic.Agent.TestUtilities/AttributeComparer.cs
… backing it; Modified AttributeValueCollection to use a list as its backing structure
Thank you for submitting a pull request.  Please review our [contributing guidelines](/CONTRIBUTING.md) and [code of conduct](/CODE_OF_CONDUCT.md).
* Modifies the Agent to store Request Paramters and Custom Attribute Values (via API) in an AttributeValueCollection, instead of an intermediate dictionaries.
* Modifies AttributeDefintions to not use lambda function for GetOrAdd for Custom Attributes, Request Attributes, and the type attributes.
* Modifies AttributeValueCollection to use a List<AttributeValue> with locks as its backing store instead of ConcurrentDictionary<string,AttributeValue>
Existing Test framework should be sufficient to test this performance change
=> Attribute Performance - v2

.github/workflows/all_solutions.yml, tests/Agent/IntegrationTests/UnboundedIntegrationTests.sln, tests/Agent/IntegrationTests/UnboundedServices/linux/docker-compose.yml
Resolves #299 
If you have questions about any change please reach out!
Adds job to run unbounded integration tests as a matrix
- Updated docker-compose.yml to properly map all exposed ports instead of a subset.
- docker-compose.yml and linux container folders are already copied to linux server and running
- This PR does not remove the Windows containers, saving that for a cleanup PR
- Updated build-unbounded-tests to save artifacts
- Added run-unbounded-tests matrix job to run tests
- Unbounded tests havce many dependencies so the steps for these items have been expanded
- Artifacts for both run-unbounded-tests and run-integration-tests have been synced and updated to only save working folders on failure
- Due to how GHA hosts servers we may see some failures due to how the firewall on …
=> Adds Running Unbounded Integration Tests to workflow

.github/workflows/all_solutions.yml
Resolves  #325
- Added release trigger
- Added step to build-test-fullagent-msi to create agent_version.txt
- Added step to build-test-fullagent-msi to save agent_version.txt as an artifact
- Added step to build-test-fullagent-msi to save /src/_build as an artifact
- Add new Job run-artifactbuilder to run ArtifactBuilder, depends on build-test-fullagent-msi
- Job run-artifactbuilder  creates deploy-artifacts artifact
- Fixed formatting of steps to match yaml spec
- Renamed the profiler jobs to remove "test" from the naame
- minor formatting cleanup
- Job build-test-fullagent-msi  should pass
- Workflow should have these new artifacts: build-folder-artifacts, agent-version, deploy-artifacts, NewRelic.OpenTracing.AmazonLambda.Tracer,NewRelic.NuGetHelper,NewRelic.Agent.Extensions
- Job …
=> Deployment mainyaml

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Metrics/MetricNameService.cs
Fixes #337.  A while back, we removed functionality from the agent that capped the total number of metric names that could be created.  That change made the `IsMetricNameAllowed()` method obsolete, and caused the `_transactionNames` collection to grow without bound.  Since the only reason that collection existed in the first place was to enable the functionality that was removed, it should have been removed at that time as well.
All unit tests passed for me locally.  All but two integration tests passed, and those two failures appear to be due to unrelated connectivity issues.
CHANGELOG was updated.
=> Remove is metric name allowed

.github/workflows/all_solutions.yml, build/Linux/build/rpm/build.sh, build/Linux/docker-compose.yml
Resolves #327 
**Very Important Notes**: 
- The jobs and steps added here will not run until a release occurs. 
- Until the Debian packaging is done, the artifact builder will fail since it needs all the packages.  If you look at the error [here](https://github.com/jaffinito/newrelic-dotnet-agent/runs/1349858453?check_suite_focus=true#step:8:64) you will see that it is not missing the RPM package.
- The GPG version of the build command is commented out since it will not work until the GPG work in #334 is completed.  This was left in as a comment to be clear that this not the final version.
Changes:
- Updated rpm/build.sh to make agent version defects clearer (wraps it in pipes '|')
- Updated Linux/docker-compose.yml to chomd 777 the sh files
- Added create-package-rpm to build RPM package …
=> Package rpm (without GPG signing) and make available to artifactbuilder

tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresExecuteScalarCoreTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresExecuteScalarTests.cs
The Integration Test AgentLogBase specifiies regexes for searching lines in the Agent log file. The regex for thread id needs to accommodate more than just digits. This PR fixes the regex to match other kinds of thread ids.
Here is an example log line generated by the Agent that failed to match a "...transform completed." log entry (see part after `tid:`):
```
2020-11-03 01:22:29,897 NewRelic FINEST: [pid: 27596, tid: WorkPool-Session#1:Connection(0073d28b-f109-4e86-9347-a19c7b38634e,amqp://127.0.0.1:5672)] Transaction 6a30542b7a651433 (OtherTransaction/Message/RabbitMQ/Queue/Named/integrationTestQueue-d09f6321-917c-48d9-a7a9-ad89fb360853) transform completed.
```
Affects both IntegrationTests and UnboundedIntegrationTests. None should fail due to:
`"Log line did not appear a minimum of …
=> tid is not always a digit

.github/workflows/all_solutions.yml
Resolves #334 
- Adds step to rebuild gpg key from secret
- Passes in the key zip from rebuild step to docker-compose
- Removes previous step that had no gpg
- Creates keys dir
- Copies GPG to keys
With the key being provided it should use that to succeed. However, this code will not run since it only runs on release.  See [here ](https://github.com/jaffinito/newrelic-dotnet-agent/actions/runs/344856818)for a run that shows the key being used.  Starting [here ](https://github.com/jaffinito/newrelic-dotnet-agent/runs/1351113936?check_suite_focus=true#step:8:973)is the log you can see the key being applied with the passphrase.
n/a
=> Use Base64 to store key in secrets and then recreate the key as needed.

src/Agent/CHANGELOG.md, src/Agent/NewRelic.Api.Agent/NewRelic.cs
A customer reported exceptions being thrown from one of our API methods when called without the agent attached (meaning that the stub methods in `NewRelic.cs` were being executed, rather than the "real" API methods that the stubs get rewritten to when the agent is attached).  This PR attempts to guard against any potential exceptions in two ways:
Add try/catch blocks around System.Diagnostics.Trace.WriteLine calls to prevent any exceptions thrown from use of this method from affecting a customer app.
Put nameof() around parameters passed to string.format to prevent any issues that might arise from trying to .ToString() objects passed in by users.
Unit tests pass.  Did a quick smoke test of an app which used the API without the agent attached and it behaved as expected.
Changelog updated
=> Guard code in api stub methods

src/Agent/CHANGELOG.md
Update CHANGELOG to add .NET 5 RC2 support announcement to 8.34 release.
=> 8.35 release CHANGELOG updates

.github/workflows/deploy.yml
Removes the --profiler bit from the previous_release aws s3 sync command.  Was already removed from latest_release.
=> Remove profile from download site push

.github/workflows/all_solutions.yml, src/Agent/CHANGELOG.md, tests/Agent/IntegrationTests/IntegrationTests.sln, tests/Agent/IntegrationTests/IntegrationTests/HttpClientInstrumentation/NetCore/HttpClientInstrumentationNet5.cs
- Now .NET 5 is GA, the `HttpClientInstrumentationNet5`  can now be enabled to run as part of GHA.
- Updates the Changelog to announce .NET 5 GA support.
=> Enable httpclient 5 test

.gitignore, build/ArtifactBuilder/Artifacts/DownloadSiteArtifact.cs
This will help reduce toil in the release process.  The `DownloadSite` target of the ArtifactBuilder now creates a `checksum.md` file in the `BuildArtifacts/DownloadSite/SHA256` folder, which has the table of filenames and SHA256 checksum values that we add to the release notes as part of the release process.  It should be as simple as copying and pasting the contents of this file into the appropriate portion of the release notes.
*Note*: this also adds `build/Linux/keys` to the `.gitignore` file.  Let's not accidentally check in a signing key!
To test, run `build/package.ps1` with the `-IncludeDownloadSite` option.  This assumes you have built all the other things that the artifact builder expects to be there.
N/A
=> Output checksum table in markdown for release notes

.github/workflows/all_solutions.yml
In order to allow forks to build and test, we need to have add back the self-signing cert step.
- Add back self-signed cert step
- Self-signed step only runs on PR
- Update actual cert steps to only run on release
Workflow should build using self-signed cert for PR since it is not a release build.
N/A
=> - Add back self-signed cert step

.github/workflows/all_solutions.yml
The day has come were GH is blocking any actions that use add-path, set-env, and the like. It appears that some of the actions we use are still using these methods.
- Moved from @v1 for microsoft/setup-msbuild to get updates
- Replaced base64 steps with scripting to fix add-path issue
Workflow doesn't have errors related to the disabled methods.
n/a
=> Update or replace actions that use now disabled methods

.github/workflows/all_solutions.yml, build/build.ps1, src/Agent/NewRelic/Profiler/build/build.ps1
This fixes a build problem that recently started happening due to a mismatch between MSBuild and NuGet versions on the GHA runners, described here: https://developercommunity.visualstudio.com/content/problem/1248649/error-netsdk1005-assets-file-projectassetsjson-doe.html
The fix is to use MSBuild for package restore instead of using NuGet directly.
This PR also fixes an issue with the workflow logic which was gating the creation of a self-signed certificate on manual (workflow_dispatch) runs.
If the PR build works as expected (i.e. all build steps pass, but there will be some expected failures in integration tests) this should be good to go.
N/A
=> Restore using msbuild

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Parsing/SqlParser.cs, tests/Agent/UnitTests/ParsingTests/SqlParserTests.cs
Resolves #224:
For a compound SQL statement like `SET @foo = 1; EXEC dbo.someStoredProcedure`, the parsed DB operation will be the `EXEC`, not the `SET`.  (This case *was* previously handled for SELECT, but no other operations.) 
Additional unit tests were added to `SqlParserTests.cs` to ensure coverage.
Changelog is updated.
=> SQL parsing: ignore leading SET statements

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs
Starting from .Net Core 2.1, for AspNetCore applications, the value from the `ASPNETCORE_ENVIRONMENT` environment variable will determine which  `appsettings.{environment}.json` files will be loaded. The agent currently does not use the `ASPNETCORE_ENVIRONMENT` environment variable for environment name; therefore, it ignores any New Relic specific settings in the `appsettings.{environment}.json`.
Manually tested. Steps that I did for testing:
1. Create an AspNetCore application targets .Net Core 2.1 or greater.
2. Updates the value of the `ASPNETCORE_ENVIRONMENT` as `Staging` in the `launchSettings.json`
3. Creates an `appsettings.Staging.json` file with the following content:
```
{
"Logging": {
"LogLevel": {
"Default": "Warning"
}
},
"NewRelic.AppName": "Staging",
"AllowedHosts": "*"
} …
```
=> Fix agent failed to read settings from appsettings.{environment}.json

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs
This fixes #116 by using `AppDomain.CurrentDomain.BaseDirectory` instead of `Directory.GetCurrentDirectory()` to get the path where an application's `appsettings.json` file(s) should be.
Manually tested an ASP.NET Core 2.2 application hosted in a Windows service.  Prior to this fix, this app could not read its New Relic application name setting from `appsettings.json` even though it was there.  After the fix, the app is named correctly as expected.  I also tested some other cases (.NET 5.0 console application, ASP.NET Core 2.2 and 3.1 apps hosted in IIS in-process) and app naming via appsettings.json worked as expected.
Will update changelog once I have a PR # for this PR.
=> Use AppDomain.CurrentDomain.BaseDirectory to get path of appsettings*.json

src/Agent/NewRelic/Agent/Core/JsonConverters/JsonSerializerHelpers.cs, tests/Agent/UnitTests/CompositeTests/AgentApiTests.cs, tests/Agent/UnitTests/CompositeTests/CompositeTests.csproj
Resolves #377 
Adds an if statement to JsonSerializerHelpers.cs to check if this the type is Microsoft.Extensions.Primitives.StringValues.
Went with strings since VS was not happy with using just the types as the conditional.
Added a small unit test to AgentApiTests.cs that checks StringValues.
Tests should pass as normal.
Fixes a bug where using AddCustomAttribute throws Newtonsoft.Json.JsonWriterException: Unsupported type error when used to add header values.
=> Fixes AddCustomAttribute throws Newtonsoft.Json.JsonWriterException: Unsupported type error when used to add header values

build/ArtifactBuilder/CoreAgentComponents.cs, src/Agent/MsiInstaller/Installer/Product.wxs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/RabbitMq.csproj, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/RabbitMqHelper.cs
Resolves #380 
- Multitargets the rabbitmq instrumentation project to support both net45 and netstandard2.0.
- Adds netstandard rabbitmq extensions files to:
- ArtifactBuilder
- MsiInstaller
There are no unbounded tests for this yet, but the story is in progress.  The existing RabbitMq tests, net45 only, passed locally and should pass in GHA.
- Updates RabbitMQ instrumentation to support netstandard32.0
=> Rabbitmq netstandard20

.github/workflows/all_solutions.yml
This repo's main CI build started failing in GHA last week, with a NuGet package restore issue being the point of failure.  This appears to be a failure introduced by some change behind the scenes in GHA; there were no code changes associated with this problem suddenly appearing.
To investigate the issue, I attempted to get more visibility into what the NuGet package source configuration was on the GHA runner for the build jobs.  Eventually, I got around to putting a `dotnet nuget list source` command before running builds that were failing - and this somehow caused the failures to stop! 😕 
Since we have other work in progress we want to get merged to `main`, I'm willing to go with this fix for the problem without us really understanding why it fixes things. 🤷‍♂️  
CI builds were failing …
=> Fix NuGet restore issue in GHA builds

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Config/ConfigurationLoader.cs, src/NewRelic.Core/Strings.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/ChangeLogDirectoryTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/ChangeLogFilenameTests.cs, tests/Agent/UnitTests/Core.UnitTest/Utilities/StringsTest.cs
Resolves Issue #406.
Adds NEW_RELIC_LOG environment variable to specify the unqualified filename for the agent's log file.
This environment variable takes precedence over other log file name settings.
Fixes and optimizes SafeFileName method.
Updates ChangeLogFilenameTests (Integration Tests) and adds SafeFileName tests (Unit tests).
=> adds NEW_RELIC_LOG

build/build_functions.ps1, src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Core.csproj
Updating gprc nuget packages to version 2.34.0 causes `System.TypeLoadException` when streaming span data. This PR reverts the change.
=> Reverts grpc packages update due to 8T breaking

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/MethodInvokerWrapper.cs
Intended `finest` logging is missing in some WCF instrumentation, hampering the ability to diagnose WCF issues.
Also a consequence, the extra logic intended only if logging is set to finest is always (unnecessarily) executed for the other log settings.
Unit tests and IntegrationTests pass locally.
=> flipped finest boolean in WCF logging

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/RabbitMqHelper.cs
GetType() returns a Type object that already has the string needed to compare. No need to create another one.
RabbitMQ unbounded tests pass locally.
N/A
=> use existing string instead of creating a new one

tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs, tests/Agent/IntegrationTests/IntegrationTests/AgentMetrics/DotNetPerfMetricsTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Api/ApiCallsTests.cs, tests/Agent/IntegrationTests/IntegrationTests/BasicInstrumentation/NetStandardLibraryInstrumentation.cs, tests/Agent/IntegrationTests/IntegrationTests/DataTransmission/FasterEventHarvestTests.cs, tests/Agent/IntegrationTests/IntegrationTests/InfiniteTracing/InfiniteTracingTests.cs, tests/Agent/IntegrationTests/Shared/IntegrationTestConfiguration.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/ConsoleDynamicMethodFixture.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/InfiniteTracingTester.cs, tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationCore/ConsoleMultiFunctionApplicationCore.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqDistributedTracingTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqTests.cs, tests/Agent/IntegrationTests/UnboundedServices/example-secrets.json
This PR adds initial integration tests for the Agent Infinite Tracing functionality. The scope of this PR is limited to Infinite Tracing smoke tests on different flavors of .NET Frameworks and Core. The set of tests doesn't test all infinite tracing case scenarios.
In order to run the tests, trace observer url need to be configured in the local secrets.json. Adds the line at the root node of your local secret file.
```
{
...
...
"TraceObserverUrl" : "_REPLACE_WITH_A_TRACE_OBSERVER_URL_"
}
```
=> 8T integration tests

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/markdowncheck.config.json, .github/workflows/markdowncheck.yml, CONTRIBUTING.md, README.md, docs/development.md, src/Agent/CHANGELOG.md, src/Agent/NewRelic/Profiler/README.md, src/AwsLambda/CHANGELOG.md, tests/Agent/IntegrationTests/UnboundedServices/README.md
This adds a workflow to check for broken links in all our markdown files.  It also fixes a bunch of links that have been broken for a while, which should explain why this is a good idea.
Since this action is configured to run on push, I was able to see it run on this branch before PRing it.  The last run was successful.
N/A
=> Markdown dead link check

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs, src/Agent/NewRelic/Agent/Core/DataTransport/SpanStreamingService.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
1. Updates the handling of GRPC responses to catch `FAILED_PRECONDITION` and restart the infinite tracing service per the spec.
2. Added support for an additional internal testing parameter which specifies which GRPC status code the backend should randomly throw (the `flaky_code`).
3. Improved handling of the `INTERNAL` GRPC response code, which indicates that the current stream has been reset due to inactivity, and which the agent handles by disposing of the current stream and then recreating it.
4. General tweaks to log message levels and wording.
1. Added a unit test to cover handling of the `INTERNAL` status code response when sending spans.
2. Verified that the 8T integration tests pass.
N/A
=> 8t more failed precondition handling

.github/workflows/deploy.yml
Update the deployment workflow for the `net35/main` (6.x agent) branch to go to the `6.x_release` folder, not the `latest_release` folder.  It also removes the step of deploying to the "previous releases" folder since we did not do that for any previous 6.x release.
Can't test until we actually try deploying. 😞
N/A
=> Update download site target folder

.github/workflows/all_solutions.yml
The Lambda tracer doesn't exist on the `net35/main` branch, so the artifact builder workflow (on release creation) shouldn't try to download it. 😄 
N/A
N/A
=> Remove attempt to download non-existent Lambda tracer artifacts

tests/Agent/IntegrationTests/UnboundedServices/mssql/Dockerfile
This resolves issues with unbounded integration tests on the `main` branch that require the MS SQL Server service.
It's not clear from git history, because things recently got moved around and deleted when we got rid of the Windows/Linux services split on the main branch, how these two env vars got removed from the Dockerfile for the mssql service.  However, the version on the `net35/main` branch was working, and these two vars were the only difference.  I think that, somehow, not having these vars set prevented the `NewRelic` database from being restored from the backup file.
MS SQL unbounded integration tests now pass for me locally when running against the local docker `mssql` service.
N/A
=> Add password setting env vars to dockerfile

tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusBasicMvcApplication/Controllers/MessageQueueController.cs
Resolves #361.
The name of the destination handler specified in the test app controller method used by the failing test was incorrect.  This PR fixes that and also makes it a constant across all of the controller methods.
Verified all NServiceBus int tests passed locally for me.
N/A
=> Fix nservicebus test

.github/workflows/deploy.yml
This PR fixes a few issues with the `deploy.yml` workflow on the `net35/main` branch (for deploying 6.x agent versions).
1. The `deploy` tools folder doesn't exist in 6.x, because those tools are for pushing the .NET Core Linux packages to APT and YUM repos.  We don't build any .NET Core assets for 6.x because customers wanting to monitor .NET Core apps can use the latest agent versions.
2. The `NugetAgent` nuget package doesn't exist in 6.x, so it doesn't need to be deployed.
I did a test deploy run on the latest version of this branch and it succeeded: https://github.com/newrelic/newrelic-dotnet-agent/actions/runs/518358727
N/A
=> Fixes for net35/main deploy issues

build/build_functions.ps1, src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Core.csproj
Fixes #394 by updating GRPC nuget package to fix loading on Linux hosts for .NET 5.0.
- Integration test passed.
- Manually test 8T in a linux docker container with a .Net 5.0 application.
=> Fix 8t in linux dotnet 5.0 docker container

src/NewRelic.Core/DotnetVersion.cs
Add  `Supportability/Dotnet/NetCore/net5` for .Net 5.
Manually tested. Steps I did for testing:
1. Created a vanilla .net core 3.0 app from Visual studio template.
2. Changed the target framework in the app project file to the following target framework and checked for the following supportability metrics.
`netcoreapp20` expects `Supportability/Dotnet/NetCore/LessThan30`
`netcoreapp21` expects `Supportability/Dotnet/NetCore/LessThan30`
`netcoreapp22` expects `Supportability/Dotnet/NetCore/LessThan30`
`netcoreapp30` expects `Supportability/Dotnet/NetCore/netcoreapp30`
`netcoreapp31` expects `Supportability/Dotnet/NetCore/netcoreapp31`
`net50` expects `Supportability/Dotnet/NetCore/net5`
=> Add dotnet version supportability metrics for net5

README.md, src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Reflection/VisibilityBypasser.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/RabbitMqHelper.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqDistributedTracingTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Reflection/VisibilityBypasserTests.cs
Fixes #464 by no longer caching the Action returned from the `VisibilityBypasser` that allows the RabbitMQ `BasicProperties.Headers` dictionary to be set by our instrumentation wrapper. 
RabbitMQ DT integration tests updated to make multiple pub/sub calls across the queue to verify it works the second time.
Added unit tests for the `VisibilityBypasser.Instance.GeneratePropertySetter` method.
Changelog updated.
=> Do not cache property setter actions from VisibilityBypasser

.github/workflows/all_solutions.yml
Resolves #468 
Adds conditional to cancel-previous-workflow-runs job to prevent the release build from running when a release for lambda is triggered.
Conditional: `github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || ( github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v') )`
Workflow should just work as normal.
=> Adds condition to cancel-previous-workflow-runs for alternate releases

.github/workflows/awslambda_release.yml, .github/workflows/deploy_awslambda.yml
Resolves #469 
Creates a new workflow for building and testing AWS Lambda releases
- Only runs on a release event with a tag that starts with `refs/tags/AwsLambdaOpenTracer_v` OR manually
- Only builds the Lambda Wrapper, Tracer, and NewRelic.Core
- Runs the Lambda Unit tests and save results
- Runs ArtifactBuilder for the Tracer only and saves results
- All steps are pulled from all_solutions,yml with limited changes to keep things simple
Creates new deploy workflow for AWS Lambda releases
- Use the same pattern as the agent deploy: copy artifacts>same them locally>deploy
- Deploys to nuget only
- Only inputs are run_id and deploy switch
Create two fake releases, one with the proper tag and one without it.   It should only fully run the correct release. Note: do not use a tag that starts …
=> Create AWS Lambda release build and test workflow

.github/workflows/deploy_awslambda.yml
Agent deploy has an extra conditional for deploying that lambda doesn't need.
=> Removes nuget check from AWS Lambda

build/generateBuildProperties.ps1
There is problem with the generateBuildProperties.ps1 script to generate release versions for all of our packages. In that script, we use this command git describe --match "$tagPrefix[0-9]*" --abbrev=0 HEAD to pull up recently created tags that match whatever prefixes, however, that command only works with annotated tags. The tags created with Github releases are “lightweighted” tags. This PR fixes it.
=> Fixes generateBuildProperties.ps1 to work with lightweighted tags

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/DistributedTracing/DistributedTracePayloadHandler.cs, src/NewRelic.Core/DistributedTracing/W3CTracestate.cs, tests/Agent/IntegrationTests/Applications/AspNetCoreMvcBasicRequestsApplication/Controllers/HomeController.cs, tests/Agent/UnitTests/Core.UnitTest/DistributedTracing/W3CTracestateTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/DistributedTracing/DistributedTracePayloadHandlerTests.cs
- This PR is a fix for the issue [#22](https://github.com/newrelic/newrelic-dotnet-agent/issues/22).
- The call `PriorityFormat, transaction.Priority` in the `BuildTracestate` function, under “Arabic” culture, yields two different string interpretations of the same float number in 2 different platforms (Window vs Unix). In windows, the decimal point is converted into an ascii character (.colon). In contrast, in Linux, the decimal point is converted into an unicode character (٫ Arabic decimal separator).
This difference is the real main cause of this exception `System.Net.Http.HttpRequestException: Request headers …
=> Language independently convert float number value to string for tracestate Priority value

build/Packaging/AzureSiteExtension/CHANGELOG.md, src/Agent/CHANGELOG.md
Resolves #491: add changelog for site extension since it is a separately versioned and released product.
Additionally, this updates the agent changelog in preparation for 8.39.1 release.
=> Add changelog for site extension

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Utils/StackTraces.cs, tests/Agent/UnitTests/Core.UnitTest/NewRelic.Agent.Core.Utils.Fromlegacy/StackTracesTest.cs
This fixes #522 by adjusting the logic of the `StackTraces.ScrubAndTruncate` method to return an empty list when the `maxDepth` parameter is set to 0.
Added one unit test to cover this case.  I also manually tested a test app that threw an exception from a stack depth of 3 and verified that no stack trace lines are sent in the `error` data when `maxStackTraceLines` is set to 0 in the agent config file.
Changelog is updated.
=> Update StackTraces.ScrubAndTruncate to handle zero max depth

tests/Agent/MultiverseTesting/ConsoleScanner/DownloadedNugetInfo.cs, tests/Agent/MultiverseTesting/ConsoleScanner/InstrumentationSet.cs, tests/Agent/MultiverseTesting/ConsoleScanner/NugetSet.cs, tests/Agent/MultiverseTesting/ConsoleScanner/Program.cs, tests/Agent/MultiverseTesting/ConsoleScanner/Properties/launchSettings.json, tests/Agent/MultiverseTesting/ConsoleScanner/ScannerConfiguration.cs, tests/Agent/MultiverseTesting/ConsoleScanner/config.yml, tests/Agent/MultiverseTesting/MultiverseScanner/AssemblyAnalyzer.cs, tests/Agent/MultiverseTesting/MultiverseScanner/InstrumentationValidator.cs, tests/Agent/MultiverseTesting/MultiverseScanner/Models/AssemblyAnalysis.cs, tests/Agent/MultiverseTesting/MultiverseScanner/Models/AssemblyModel.cs, tests/Agent/MultiverseTesting/MultiverseScanner/Reporting/InstrumentationReport.cs
Refactoring the Multi Version Scanner to do the followings:
- One AssemblyAnalyzer instance is responsible to validate one instrumented assembly per target framework at a time.
- The Muti Version Scanner will validate the instrumented assemblies for all target frameworks that the validated nuget packages support.
=> Refactors the Multi Version Scanner

tests/Agent/MultiverseTesting/ConsoleScanner/ConsoleScanner.csproj, tests/Agent/MultiverseTesting/ConsoleScanner/NugetClient.cs, tests/Agent/MultiverseTesting/ConsoleScanner/NugetSet.cs, tests/Agent/MultiverseTesting/ConsoleScanner/Program.cs, tests/Agent/MultiverseTesting/ConsoleScanner/Properties/launchSettings.json
Resolves: #516 
Uses NuGet.Protocol and NuGet.Packaging
Downloads packages in memory and extracts files, no zip
Finds latest non-prerelease version of package
Adds latests version to versions list for download and checking
Version in NugetSet change from sting[] to List<string> to make it easy to append to
Should build fine, cannot test since it is not run.
N/A
=> Mvs replace nuget

.github/workflows/all_solutions.yml
This is to support the new release process not having to immediately publish a release before all the necessary steps are actually completed. Publishing a release will be moved to the final step instead of first, so the workflow will need to trigger on creation.
Testing will be completed/verified after this merge is completed.
=> Changed GHA All Solutions Build to trigger on Release creation instead of publish

.github/workflows/multiverse_run.yml
Resolves: #518 
WIll run MultiverseScanner  on the 1st and 15th of every month, at 12AM Pacific.  Actions uses UTC so the cron expression shows 19 instead of 0 for the time.
- Downloads the scanner from S3
- Uploads the scanner as a local artifact
- Gets the current date for use in report name
- Sets up .NET Core 3.1 so scanner can run
- Runs scanner
- Uploads the report as an artifact
- Uploads the report to S3 for later review
Will run on its own on the 1st and 15th, but can be run manually for testing.
=> Adds workflow to run MultiverseScanner on schedule

.github/workflows/all_solutions.yml
Reverts newrelic/newrelic-dotnet-agent#535 as it proved unworkable due to GHA not being able to trigger on Release drafts.
=> Revert "Changed GHA All Solutions Build to trigger on Release creation instead of publish"

build/Linux/build/deb/Dockerfile, build/Linux/build/deb/build.sh, build/Linux/build/rpm/Dockerfile, build/Linux/build/rpm/build.sh, build/build.ps1, deploy/linux/container/Dockerfile
This PR:
1. Updates two `debian:jessie` container images to `debian:stable`.  These containers are used by the build and deploy processes for the agent's Linux packages (.deb and .rpm).
2. Removes a stray debugging early exit from `build.ps1` that got committed accidentally.
3. Fixes a bug in the `build.sh` scripts for both the .deb and .rpm builds, introduced when we restructured the codebase.  What broke was the scripts' ability to automatically determine the agent version.  (FYI, when these scripts are used in our actual CI build process, the agent version is explicitly passed in to the container, so this feature is just for developers' convenience when doing local package builds.)
I tested building the containers and running them to build the .rpm and .deb packages after my changes …
=> Update debian container images to latest stable and fix bugs

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Transformers/GcSampleTransformer.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/GCStatsSampleTransformerTests.cs
This PR fixes #264 . Essentially, we occasionally encounter negative GC counts which cause an exception to be thrown. This exception can cause the GC sampler to be shut down after multiple errors are encountered. In order to prevent this from happening, we want to clamp all negative count metrics coming from the GC.
The fix is implemented at the GC layer, and will work for both .NET framework, and .NET standard.
A new unit test was added that verifies that negative GC counts are clamped to 0. As we do not have a repro path, an integration test was not written.
=> Clamp negative GC counts to 0

.gitignore
The following file keeps showing up in git after I have built. I believe this should be ignored:
src/Agent/NewRelic/Profiler/out/build/x64-Debug/VSInheritEnvironments.txt
No tests required (.gitignore change)
=> Ignore file that keeps showing up in git after I build.

tests/Agent/IntegrationTests/Applications/AspNetCore3BasicWebApiApplication/AspNetCore3BasicWebApiApplication.csproj, tests/Agent/IntegrationTests/Applications/ConsoleAsyncApplication/AsyncFireAndForgetUseCases.cs, tests/Agent/IntegrationTests/Applications/DistributedTracingApiApplication/Program.cs, tests/Agent/IntegrationTests/Applications/ServiceStackApplication/ServiceStackApplication.csproj, tests/Agent/IntegrationTests/Applications/WebApiAsyncApplication/Controllers/AsyncFireAndForgetController.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AspNetCore3BasicWebApiApplicationFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/app.config, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationCore/ConsoleMultiFunctionApplicationCore.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests/app.config
This PR reduces the number of build/restore warnings seen in the integration test and unbounded integration test solutions.  There were more than 70 warnings in the integration test solution before this work and the number is now down to 6 (all caused by the same issue which may be addressed in a separate PR, but I believe it will require a slightly more significant change).
Part of the motivation for doing this now is that as we begin to test .NET 6 preview versions, we want to make sure that any new warnings don't get lost in the noise.  However, this should help anybody either internally or externally to notice new warnings that may appear.
The following things were done to reduce the number of warnings:
* ServiceStackApplication was modified to reference 5.5.0 versions of ServiceStack …
=> Reduce integration test solution build warnings

src/Agent/Configuration/newrelic.config, src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
This PR does the followings:
1. allowAllHeaders is introduced at the root configuration level and enabled by default (the default newrelic.config will include this config). If this config isn't specified, it is set to `false`.
2. The excluded headers mentioned in this [specs](https://source.datanerd.us/agents/agent-specs/blob/master/Agent-Attributes-PORTED.md#request-headers) is explicitly listed in the global attribute exclusion list to satisfy the Security team.
Note: I attempted to add this new config setting to the Connect payload but our agent is currently not setup to do so. Deferring this work for later time.
Unit tests added.
=> Adds allowAllHeaders config setting.

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
This PR updates the followings:
1. High security mode will disable request header capturing. This is for spec compliance.
2. When allowAllHeaders config is set to "true", automatically add "request.header.*" to the inclusion list even when users don't explicitly specify it in the attribute element. This is doing similar to the `captureParameters` configuration.
Unit tests.
=> High security mode will disable request header capturing

src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, src/Agent/NewRelic/Agent/Core/Transactions/NoOpTransaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ITransaction.cs, tests/Agent/UnitTests/Core.UnitTest/Attributes/AttributeDefinitionServiceTests.cs
This PR adds the `SetRequestHeaders` method in the `ITransaction` so that upstream code can use to add request headers data as user attributes. 
Unit tests.
=> Introduces SetRequestHeaders api method

src/Agent/NewRelic/Agent/Core/Transactions/NoOpTransaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ITransaction.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs
Changes `SetRequestHeaders` method signature to generically handle any header collection implementation.
No tests as this is not being used anywhere yet.
=> Change SetRequestHeaders method signature.

src/NewRelic.Core/DotnetVersion.cs
We were not detecting .net core framework version 6. 
@nr-ahemsath tested the changes locally.
=> Add dotnet 6 supportability metric

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Attributes/AttributeDefinitionServiceTests.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs
When `allowAllHeaders` set to `true`, don't implicitly add "request.header.*" to the global attribute inclusion list. This allows users to specifically tell the agent to include specific headers. 
Unit tests modified/added.
=> Fixes allowAllHeaders setting logic

src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs
When high security mode is enabled, don't collect any request headers according to the agent specs.
Unit test added.
=> When high security mode is enabled, don't collect any request headers.

.github/workflows/all_solutions.yml, src/Agent/CHANGELOG.md, src/Agent/Configuration/newrelic.config, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Providers/Wrapper/Constants.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Asp35/Shared/HttpContextActions.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/WrapPipelineMiddleware.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/MethodInvokerWrapper.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/AspNetCore/AllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/AspNetCore/AllowAllHeadersEnabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/WCF/AllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/WCF/AllowAllHeadersEnabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/WCF/BaseTests.cs, tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFLogHelpers.cs, tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFTestBase.cs, tests/Agent/IntegrationTests/Shared/WCF/WcfEnums.cs, tests/Agent/IntegrationTests/Shared/WCF/WcfService.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/ConsoleDynamicMethodFixture.cs, tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationFW/NetFrameworkLibraries/WCF/WCFClient.cs, tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationFW/NetFrameworkLibraries/WCF/WCFLibraryHelpers.cs, tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationFW/NetFrameworkLibraries/WCF/WCFServiceIISHosted.cs, tests/Agent/IntegrationTests/SharedApplications/WcfAppIisHosted/Web.config
Fixes #561 by adding HTTP request header capturing support into the WCF wrapper.
Includes some new WCF integration tests that should yield consistent results.
=> Request Header capturing support for WCF

src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs
This PR makes sure that the agent will trip query string from the Referer, Location and Refresh request headers when capturing them as attributes.
https://source.datanerd.us/agents/agent-specs/blob/master/Agent-Security.md#request--response-headers
unit tests.
=> Removes query string in Referer, Location and Refresh request header attributes.

src/Agent/CHANGELOG.md
Updated changelog with better detail about what's supported with the http request header capturing.
=> Updated changelog for Header capturing

src/Agent/NewRelic/Agent/Core/Database/DatabaseService.cs, src/Agent/NewRelic/Agent/Core/Database/SqlObfuscator.cs, src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionTransformer.cs, tests/Agent/UnitTests/CompositeTests/CrossAgentTests/SqlObfuscation/SqlObfuscationCrossAgentTests.cs, tests/Agent/UnitTests/Core.UnitTest/Database/SqlObfuscatorTest.cs
Fixes #168 
Summary:
Explain plans are only capture if TransactionTracer.explainPlan is true and either TransactionTracer.enabled and/or slowSql.enabled  are true.  This prevents an explain plan from being capture when it is never going to be sent up.  It prevent a capture explain plan from being dropped (very expensive to capture) and replaced using a "null" SqlObfuscator if TransactionTracer.enabled is false, but slowSql.enabled  is true. 
Note: By default, the agent will not capture explain plans, but it will capture transaction traces and slow sql traces. This should not affect most customers.  Customers with the following configuration will start seeing explain plans and the performance hit to generate them:
- TransactionTracer.explainPlan is **true**
- TransactionTracer.enabled is …
=> Explain plan generation fixes

src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs
Fixes minor issue in recent `DataStreamingService` change to wait for data to be flushed on exit where the `_collection` it was trying to count could already be disposed.
Also slightly tweaked the comments/logs for a little more clarity.
=> DataStreamingService fix for trying to grab potentially disposed count 

.github/workflows/all_solutions.yml
Self-signed step was missing 'scheduled' event so no cert was available for building MSI files.
=> Added missing event to self-signed step

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Parsing/SqlParser.cs, tests/Agent/UnitTests/ParsingTests/SqlParserTests.cs
Resolves #476 
Replaces string.replace with regex.replace
Regex is: @\b{paramName}\b
This looks for a parameter with a word-boundary on either side with an @ before the first boundary
This is needed to handle the @ symbol not being a word character
Old method used the length of the string to get around not looking for whole words
This needed a sorted list, a custom comparer, and other code, all of this was removed
Added new SqlParser.FixParameterizedSql to cover different scenarios.
No integration tests since unit test are pretty thorough
Tested performance and there was not appreciable difference between the two …
=> Fix sqlparser word matching

.github/workflows/deploy.yml, deploy/linux/.gitignore, deploy/linux/README.md, deploy/linux/deploy.bash, deploy/linux/deploy_scripts/deploy-packages.bash, deploy/linux/deploy_scripts/libexec/repoman-rebuild.bash
Resolves #606.
1. Modified `deploy.yml` to add a new input called `linux-deploy-to-production` with a default value of `false`.  The workflow adds values from the secrets store for a) the S3 bucket to operate on for the deployment and b) the AWS access keys to use to operate on that bucket.  When the new value is false, it will operate on an S3 bucket that the team owns and is set up to simulate the "real" S3 bucket that backs `apt.newrelic.com` and `yum.newrelic.com`.  When set to true (as in a real release deploy), it will operate on the "real" S3 bucket.
2. Updated the README.md file for the deploy system to be more understandable and fix some inaccuracies leftover from old versions.
3. Added some progress/troubleshooting output to the `repoman_rebuild.bash` script.
I tested the …
=> Add Linux package deploy test mode

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Logging/Logger.cs, src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs, tests/Agent/IntegrationTests/Applications/AspNetCoreMvcAsyncApplication/Program.cs, tests/Agent/IntegrationTests/IntegrationTests/AspNetCore/AspNetCoreMvcAsyncTests.cs, tests/Agent/UnitTests/Core.UnitTest/NewRelic.Agent.Core.FromLegacy/AgentLoggerTest.cs
While testing out .NET 6, we noticed that thread names were being logged for .NET managed threads instead of the actually desired thread id in agent logfiles. This happened because Log4Net prefers to log a thread name versus a thread id, and Microsoft began setting thread names for their managed threads in .NET 6. The behavior is reproducible in previous versions of the product, but only if a user explicitly set the name of a thread.
The resolution is to check/set a thread id in the log4net thread context object, and update the logging layout to log this property. This is the same approach we use to log the process id, with the exception of only ever needing to set the process id once.
Resolves #600. 
Unit tests were added to verify that the thread id property is set in log4net by every …
=> Always use thread id in agent logs

build/Linux/build/rpm/Dockerfile
This PR adds a checked-in version of a tool ([exiftool](https://exiftool.org/index.html)) needed by the rpm package building process and modifies the Dockerfile to use the checked in version rather than pulling it from the web.  The reason for doing this is that we found out that the exiftool.org website regularly deletes older versions from their site and we don't want to have to update this Dockerfile every few months to bump to the latest version.
Note: Exiftool is free software per their [license](https://exiftool.org/index.html#license), so no issue adding this to our repo.
Tested building the rpm_build container and then building the .rpm package on my local system.
N/A for an internal process.
=> Add exiftool tarball to repo and install it in container

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Parsing/MySqlExplainPlanActions.cs, src/Agent/NewRelic/Agent/Parsing/SqlParser.cs, src/Agent/NewRelic/Agent/Parsing/SqlServerExplainPlanActions.cs, tests/Agent/UnitTests/ParsingTests/SqlParserTests.cs
Resolves #477
Big change tl;dr: If DbType.Binary and DbType.Object are detected while parsing, we will exit and not collect an explain plan.  There is a debug message indicating as such.  This prevent any errors with custom objects or objects that are not easily serialized.
Prevents explain plans from being created when Binary or Object parameters are detected
- SqlParser.FixParameterizedSqlnow returns a bool to indicate if we should try to run the plan
- MySqlExplainPlanActions and SqlServerExplainPlanActions hasve been update to honor this boolean
- Without a large amount of overhead, we are not able to determine how to write the underlying objects as strings.  With the SqlParser we want to keep it very lightweight since it is already a large performance hit.  This should mean less …
=> Improve sqlparsing tostring in FixParameterizedSql

tests/Agent/IntegrationTests/Applications/AspNetCoreMvcAsyncApplication/CustomMiddleware.cs, tests/Agent/IntegrationTests/Applications/AspNetCoreMvcFrameworkAsyncApplication/CustomMiddleware.cs, tests/Agent/IntegrationTests/Applications/ConsoleOtherTransactionWrapperApplication/Program.cs, tests/Agent/IntegrationTests/Applications/DistributedTracingApiApplication/Program.cs, tests/Agent/IntegrationTests/Applications/Owin2WebApi/CustomMiddleware.cs, tests/Agent/IntegrationTests/Applications/Owin3WebApi/CustomMiddleware.cs, tests/Agent/IntegrationTests/Applications/Owin4WebApi/CustomMiddleware.cs, tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/DTSupportabilityMetricTests.cs
This PR improves integration test reliability by adding the `MethodImplOptions.NoInlining` attribute to methods in test applications also decorated with `Transaction` or `Trace` attributes.
At least one integration test, `DistributedTracingApiTests_Legacy`, has been failing when the tests are built and run in `Release` mode (as they are when run in GHA as part of our CI) because some test methods in the underlying test application were being inlined by the compiler.  These methods were decorated with `[Transaction]` and were expected to create transactions in the agent to make the test work.  Preventing these methods from being inlined causes the test to pass reliably when built and run in `Release` mode.
I found other examples of transaction- or trace-decorated methods similarly …
=> Prevent inlining in integration test app methods

tests/Agent/IntegrationTests/IntegrationTestHelpers/RandomPortGenerator.cs, tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFServiceTests.cs
Issues have been identified with differences in ASP pipeline events generated between the release and debug runs of our WCF distributed tracing events. Additionally, issues have been identified where we think a port is available for use because no one is listening, but it is actually prevented from being used by the OS. 
The first issue was resolved by adjusting the static number of expected pipeline events between debug and release builds. I left some commented code in the PR which was useful in comparing the span contents of debug/release runs of the WCF DT tests.
The second issue was resolved by starting a TcpListener instead of using a TcpClient to test if a port is available. The TcpListener will get an error if the port is unavailable.
I ran integration tests locally in debug and …
=> Improve integration test reliability

.github/workflows/all_solutions.yml
A common failure in our GitHub Actions all solutions build is in the debian/rpm artifact upload steps. It is common to get 500 errors during artifact upload, and then 400 errors causing the deb or rpm artifacts to be missed. I believe this is due to the use/re-use of the 'build-folder-artifact' that is generated in the MSI build step. The deb/rpm builds were both downloading this artifact, adding 1-3 files to it, then simultaneously trying to upload the entire build folder again in to the same artifact name, including the already downloaded files from the MSI build step. This was causing simultaneous uploads of the same artifact name/file, which I believe is why we were encountering intermittent errors. GitHub warns against doing what we were doing here: …
=> Separate MSI/Debian/RPM build artifacts

src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, src/Agent/NewRelic/Agent/Core/Transactions/ITransactionAttributeMetadata.cs, src/Agent/NewRelic/Agent/Core/Transactions/NoOpTransaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/TransactionMetadata.cs, src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionAttributeMaker.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ITransaction.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Asp35/Shared/HttpContextActions.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/WrapPipelineMiddleware.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Owin/OwinStartupMiddleware.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/MethodInvokerWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/AspNetCore/AspNetCoreMvcBasicRequestsTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/Asp35/AllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/Asp35/AllowAllHeadersEnabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/AspNetCore/AllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/AspNetCore/AllowAllHeadersEnabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/Owin/AllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/Owin/AllowAllHeadersEnabledTestsBase.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/Owin/AsyncAllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/Owin/AsyncAllowAllHeadersEnabledTestsBase.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/WCF/AllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/WCF/AllowAllHeadersEnabledTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transactions/ImmutableTransactionBuilder.cs
Resolves #611 by adding a new `request.method` attribute to the Agent, and implementing its capture in the `AspNetCore`, `Asp35`, `Wcf3`, and `Owin` wrappers.
Leveraged the new request capturing integration tests, adding a simple method assertion to each.
=> Capture HTTP Request Method

tests/Agent/IntegrationTests/Shared/DbParameterData.cs
Fixes #359 by modifying the types of some of the parameters used in the `OracleParameterizedStoredProcedure` test.  The previous parameter types worked at some point in the past (before we open sourced the agent and migrated the CI from private Jenkins to public GHA), but they haven't worked for some time (most likely because the Oracle server version we're testing against changed in the shuffle).
I based the mapping of Oracle type names to .NET data types on this document: https://docs.oracle.com/database/121/ODPNT/featTypes.htm#ODPNT281 Note that the .NET data type for `binary_integer` should be `decimal`, and that the Oracle data type that corresponds to `System.Byte[]` is `raw`.
Changing "double" to "double precision" fixed a compilation error (on the Oracle server side) when creating …
=> Update DbParameterData for Oracle

tests/Agent/IntegrationTests/Shared/MySqlConfiguration.cs, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/BasicMvcApplication.csproj, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/Web.config, tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj, tests/Agent/MultiverseTesting/ConsoleScanner/config.yml
Addresses #545 by updating the unbounded integration tests to use the latest `MySql.Data` version of `8.0.25`, also added `MySql.Data` package to MVS.
Versions after `6.10.9` require .NET Framework 4.5.2 so I also had to bump up one of the projects to use it - this project does host a few things for other tests so we may want to break out the `MySqlController` into its own project, but so far I have not seen any issues with other tests because of this.
With this version update `Network Address` is not supported in connection strings, so any existing secrets will need to be updated to use `Server` instead - GH secrets have been updated.
=> Update integration tests to use MySql.Data 8.0.25

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/HandleBasicDeliverWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/RabbitMqHelper.cs, src/Agent/NewRelic/Profiler/README.md, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RabbitMQ.cs
Fixes #639 by modifying the RabbitMQ instrumentation to read and write RabbitMQ message headers via the generic `IDictionary<string,object>` interface rather than casting everything to a concrete Dictionary.  This will prevent the instrumentation from accidentally overwriting existing message headers if they were set using an IDictionary collection other than Dictionary. 
Updated the test application used by the RabbitMQ integration tests to set some user headers in a `SortedDictionary` when sending messages and then verify they still exist and are correct when receiving messages.  Verified the tests pass locally.
Changelog updated.
=> RabbitMQ: Use generic IDictionary interface when manipulating headers

.github/workflows/all_solutions.yml
Disable running the unbounded integration tests in GHA CI, because the external services these tests depend upon are currently offline.
N/A
N/A
=> Disable unbounded int test job in GHA

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/RabbitMqHelper.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RabbitMQ.cs
Further resolves #639 by working around `IReadOnlyDictionary` header collections.
RabbitMq integration tests were updated to use one, demonstrating that the Agent can successfully handle them.
=> Updated RabbitMq wrapper to work around read-only header dictionaries

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/IConfigurationManagerStatic.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/Environment.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Models/Environment.cs, tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/EnvironmentTests.cs, tests/Agent/UnitTests/CompositeTests/CrossAgentTests/SecurityPolicies/SecurityPoliciesCrossAgentTests.cs, tests/Agent/UnitTests/CompositeTests/EventHarvestConfigSupportabilityMetricsTests.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/NewRelic.Agent.Core.FromLegacy/EnvironmentTest.cs
Resolves #580 by adding `Application Names`, `Application Names Source`, `New Relic Conffig`, and `Application Config` to the `Environment` data sent up in the connect payload.
For .Net Core I leveraged the [existing code](https://github.com/newrelic/newrelic-dotnet-agent/blob/2379aace42dc1ddc7ce6bc6a1cd105b380c4f842/src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs#L58..L59) in the Agent to try to grab the application config, however this approach is not ideal as it currently only supports default (`appsettings.json` and `appsettings.{environment}.json`) files. I tried finding a better way to do this, but I believe for a complete solution we would need to be instrumenting the `ConfigurationBuilder` so we can intercept all the files it's utilizing to build …
=> Add App Name and Source + NR and App configs to Environment

src/AwsLambda/AwsLambdaWrapper/LambdaWrapper.cs, src/AwsLambda/CHANGELOG.md, tests/AwsLambda/UnitTests/AwsLambdaWrapperTests/LambdaWrapperTests.cs
The Lambda Tracing Wrapper uses Async over Sync and Reflection to call `.Result` on the task returned from lambda execution. Calling `.Result` can result in deadlocks and is considered bad practise.
This PR adds overloads to `LambdaWrapper` that support tasks correctly
What unit or integration tests were added or modified, or why no testing changes were required.
Please remember to update our [changelog](/newrelic/newrelic-dotnet-agent/src/Agent/CHANGELOG.md) if applicable (or [this changelog](/newrelic/newrelic-dotnet-agent/blob/main/src/AwsLambda/CHANGELOG.md) for Lambda agent changes),
=> Fix async await in lambda tracer

.github/ISSUE_TEMPLATE/bug_report.md, README.md, docs/integration-tests.md, src/Agent/CHANGELOG.md, src/Agent/Configuration/newrelic.config
The link to our agent config documentation in the default `newrelic.config` was incorrect, this PR updates it to be current.
=> Update config docs link in default config

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Utils/StackTraces.cs, tests/Agent/UnitTests/Core.UnitTest/NewRelic.Agent.Core.Utils.Fromlegacy/StackTracesTest.cs
Resolves: https://github.com/newrelic/newrelic-dotnet-agent/issues/683
Basically if any of the stack frames within the requested depth are from NewRelic, then we don't save the requested number of frames.
Updated an existing unit test, and added one to capture an edge case where more stack frames are requested than available
=> Fix issue with how stack trace depth is managed

tests/Agent/IntegrationTests/UnboundedServices/mssql/Dockerfile
This fixes a problem which prevented the MS SQL Server service used for the unbounded integration tests from starting in Docker.
Verified the SQL Server service would start (when running `docker-compose run --service-ports mssql`) and that the unbounded integration tests (for MS SQL) passed.
N/A
=> Update source of MS SQL Server docker image

src/Agent/CHANGELOG.md, src/Agent/Configuration/newrelic.config, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/ServerConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/SingleEventHarvestConfig.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Resolves #671 by adding a new `spanEvents.maximumSamplesStored` local setting, and implementing the new `span_event_harvest_config` values sent down by the server.
Note - somehow the new setting already got pulled into this feature branch, so I removed them from this PR to not have any conflicts.
Two related unit tests were updated to check these configurations and validate they are being set correctly.
=> Make maximum Span Events configurable, and use new cycle and maximums sent from server

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Parsing/SqlParser.cs
Resolves #707
Fixes bug was introduced in 8.40.1 that results in SQL explain plans not being captured for parameterized SQL statements.
=> Fix bug when capturing explain plans for paramaterized SQL

src/Agent/CHANGELOG.md
Adds Castle.Monorail deprecation statement
=> Add Castle.Monorail deprecation statement

src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
Resolves #703 with the `spanEvent.maximumSamplesStored` default updated to 2000.
=> Update maximum Span Event samples to 2000

src/Agent/CHANGELOG.md, src/Agent/Configuration/newrelic.config, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs, src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/IntegrationTests/IntegrationTests/CustomAttributes/CustomAttributesIgnoredErrorAttributesNotInTransactionTrace.cs, tests/Agent/IntegrationTests/IntegrationTests/Errors/ErrorTraceMvc.cs, tests/Agent/IntegrationTests/IntegrationTests/Errors/ErrorTraceWebApi.cs, tests/Agent/IntegrationTests/IntegrationTests/Errors/ErrorTraceWebService.cs, tests/Agent/UnitTests/CompositeTests/TransactionTests.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs, tests/Agent/UnitTests/Core.UnitTest/Errors/ErrorServiceTests.cs
Resolves #668 with the updated config, some now unnecessary `errorCollector.ignoreErrors` code removed, and a warning logged when the old configuration is still being used.
Unit and integration tests have been updated and passed, with one unneeded unit test being removed.
=> Update `errorCollector.ignoreErrors` to `errorCollector.ignoreClasses`

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Core.csproj
The version of gRPC that we are currently using in the agent has extra debug symbols included which greatly increases the size of our deliverable. By upgrading to a newer version of gRPC we can reduce the size of our install files.
Resolves: #679
Unit/Integration/Unbounded tests all pass
Updated
=> Update gRPC libraries to v2.40.0

tests/Agent/IntegrationTests/Shared/RabbitMqConfiguration.cs, tests/Agent/IntegrationTests/Shared/StackExchangeRedisConfiguration.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RabbitMQ.cs, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/Controllers/RedisController.cs, tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml, tests/Agent/IntegrationTests/UnboundedServices/example-secrets.json, tests/Agent/IntegrationTests/UnboundedServices/mssql/Dockerfile, tests/Agent/IntegrationTests/UnboundedServices/rabbitmq/Dockerfile, tests/Agent/IntegrationTests/UnboundedServices/redis/Dockerfile
The changes in this PR help enable better security for the Docker-hosted external services needed by the unbounded integration tests.  Summary of changes:
1. Enable the use of a username and password for some services that were previously set up to use no authentication at all (e.g. redis)
2. Allow (almost) all services to have credentials specified from the environment in `docker-compose.yml`, although default values are still specified to make it easy to use these containers for testing on a local machine.
3. Remove unnecessary port mappings from the `docker-compose.yml` file.
4. In some cases, the version of the container image for the service was updated to a more recent version.
I've verified that all unbounded integration tests still pass for me locally using this version of the …
=> Better unbounded service security

.github/workflows/all_solutions.yml, build/build_functions.ps1, src/Agent/NewRelic/Profiler/CMakeLists.txt
Adds new profiler build job for arm64
New job adds its profiler bits to _profilerBuild 
Updates existing linuc job name to callout out arch
Updates conditionals to match new job names
Updates _profilerBuild deletion list to include new paths
Updates build_functions.ps1 to support new folder names 
While the new profiler artifacts are saved, the main agent build does not create a home folder for the new arch.
This simply gets the arm64 profiler building in GH with some new folders.
Tested (mostly) in private repo: https://github.com/jaffinito/newrelic-dotnet-agent/actions/runs/1292485552
Manually tested GH built profiler in a graviton instance using a .NET 5 webapi app and it was fine (link posted in slack)
=> A workflow to build linux arm64 profiler

.github/workflows/all_solutions.yml, src/Agent/NewRelic/Profiler/linux/Dockerfile
Updates profiler depends to use https
Updates wget commands to not use caching
=> Move to https and no caching for wget

src/Agent/NewRelic/Profiler/linux/Dockerfile
Added commands to remove the expired root cert before trying to pull down files for build.
=> Remove expired cert before building

src/Agent/CHANGELOG.md, src/Agent/MsiInstaller/Installer/Product.wxs
Closes #781.
The windows MSI installer was not deploying gRPC libraries for netcore applications. This has been tested locally and it appears to deploy the missing unmanaged libraries.
=> Add grpc unmanaged libraries to the .net core MSI installer

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs, src/Agent/NewRelic/Agent/Core/DataTransport/GrpcWrapper.cs, src/Agent/NewRelic/Agent/Core/DataTransport/SpanGrpcWrapper.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
Resolves #780 
A recent certificate expiration event exposed a defect where unmanaged gRPC channels can cause an increase in TCP connection requests. This PR corrects the connection management issues and allows for proper backoff during failure events.
BEFORE FIX - TCP connection attempts for 50 agents during a certificate event:
WITH FIX - TCP connection attempts for 50 agents during a certificate event:
=> Improve management of gRPC channels 

tests/Agent/IntegrationTests/Shared/CosmosDBConfiguration.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/CosmosDB/CosmosDBExerciser.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/CosmosDB/CosmosDBTests.cs, tests/Agent/IntegrationTests/UnboundedServices/example-secrets.json
This PR lays ground work for testing Cosmos DB instrumentation. More specific tests will be added in later PRs.
The integration test secret need to be updated with the new CosmosDB server secret
```
"CosmosDBTests": {
"CustomSettings": {
"AuthKey": "your CosmosDB secret",
"Server": "you CosmosDB endpoint"
}
}      
```
=> CosmosDB Intial Integration Test

src/Agent/NewRelic/Agent/Core/Segments/DatastoreSegmentData.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs
Fixes an issue where `db.collection` attribute was created even when a collection/model was empty.
=> Fix dbcollection attribute.

.github/workflows/multiverse_run.yml
This has to be done before changing the all_solutions.yml since GHA performs some checks on reusable workflows.
Refactors multiverse_run.yml:
- Made into a reusable workflow
- workflow_dispatch is setup as well for manual runs
- Pulled in the build portion from all_solutions.yml so that it is self-contained
- Added continue-on-error to job to prevent failures from affecting release job
=> Makes multiverse scanner reusable

.github/workflows/all_solutions.yml
Refactors all_solutions.yml:
- Adds an output of agentVersion to the build-test-fullagent-msi as part of remove agent_version.txt
- Replaces build-test-fullagent-msi.Create agentVersion with new script that set the agentVersion job output
- Removes the step that pushed the agent_version.txt file as an artifact
- Replaced agent_version.txt code in Debian and RPM steps with new output code
- Removed MVS build job
- Add new workflow caller job for MVS that will run the now reusable multiverse_run.yml from main (reusable limitation)
=> Updates all_solutions.yml to call MVS as a reusable workflow

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/Environment.cs
Resolves #800.  To send the correct value for the .NET Framework version a profiled app is running on in the environment data, use the same logic that our supportability metrics do.
Since we're just ToString()ing the enum returned by `DotnetVersion.GetDotnetFrameworkVersion()`, the values reported will look like `net461` or `net48`.  If we want a different string format for this data we can implement some kind of mapping method.  For .NET Core apps, this data looks like `.NET 5.0.4` (for example).  I'm not sure how much we care about maintaining symmetry between the two.
=> Use registry query logic to send .NET Framework version in environment data

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Providers/Wrapper/Delegates.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/HttpClient/SendAsync.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
Resolves #803 by synchronizing the Agent's access of the HttpClient headers.
=> Fix .Net 6 HttpClient header thread safety issue

.github/workflows/all_solutions.yml
Enable running the CosmosDB integration tests in CI.  The CosmosDB service has been enabled on the server used by the CI.
=> Enable CosmosDB tests

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/CosmosDB/CosmosDBExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/CosmosDB/StoredProcedures/HelloWorldStoredProc.js, tests/Agent/IntegrationTests/UnboundedIntegrationTests/CosmosDB/CosmosDBTests.cs
Implemetation for https://github.com/newrelic/newrelic-dotnet-agent/issues/808
At level, this PR tests:
- Creates a simple stored procedure and stores it in the test cosmosdb database. CosmosDB stored procedures are basically javascript scripts that can be executed from the server side. The created test stored  procedure doesn’t do database related things much. All it does is returning “Hello, World” string to the client call.
- Executes the stored procedure.
=> Cosmosdb stored procedure tests

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/NServiceBusHelpers.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/PipelineWrapper.cs
Adds the `PipelineWrapper` to instrument message send/publish instrumentation.
=> Adds PipelineWrapper for message send/publish instrumentation.

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Utilities/SystemInfo.cs
Resolves #36.
Total system memory will now be reported by .NET core agents running on Linux systems.  The agent reads `/proc/meminfo` and pulls out the `MemTotal` value.
Regarding testing: I considered adding a unit test for this, but the only real logic is the regex parsing of the `MemTotal: 12345 kB` line, and so a unit test using mock/fake `/proc/meminfo` data would just be testing that the regex works or doesn't.  I can still add a unit test like this if desired; some refactoring would be required to make the method in question testable.  We don't have any existing integration tests for this feature of the agent, and an integration test seems too heavyweight for this.
I did test this change manually on Ubuntu 20.04 and verified that the total physical memory was being sent in the …
=> Report total physical system memory on Linux

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/LoadHandlersConnectorWrapper.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbAsyncCmdHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbAsyncEventHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbCmdHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbEventHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbThrowingHandlerTests.cs
After reviewing some of the CI failures, the throwingHandler tests were relying on GC to close the transactions.
This updates the Handler wrapper to close the segment and transaction if the task is cancelled/failed/complete. I also added a check to all the handler tests to make sure we aren't relying on GC to close transactions.
=> NSB: Fix issue with Handler transactions being ended by GC

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Configuration/ServerConfiguration.cs
Before the fix:
When the agent is set to ignore SSC, the agent didn't set the `serverConfiguration.ServerSideConfigurationEnabled` flag so that it would report the SSC Enabled/Disable correctly.
After the fix:
Regardless whether or not the agent is set to ignore SSC, `serverConfiguration.ServerSideConfigurationEnabled` flag will still reflect SSC Enable/Disable correctly.
This is manually tested.
=> Fix correctly report whether SSC is enabled.

.github/workflows/deploy_agent.yml
Need to fix a path in the agent deploy workflow based on the changes in this previous PR: https://github.com/newrelic/newrelic-dotnet-agent/pull/862/files
I tested this by running a test deploy and it succeeded: https://github.com/newrelic/newrelic-dotnet-agent/runs/4707961644?check_suite_focus=true
=> Fix path for signing keys

src/Agent/CHANGELOG.md
Two changelog updates:
1. Added shoutout to community contributor for the unreleased database segment naming feature.
2. Retroactively added fix for config file schema validation guard code to 9.3 fixes.
=> CHANGELOG updates

src/Agent/NewRelic/Profiler/Configuration/Configuration.h, src/Agent/NewRelic/Profiler/Logging/DefaultFileLogLocation.h, src/Agent/NewRelic/Profiler/LoggingTest/DefaultFileLogLocationTest.cpp, src/Agent/NewRelic/Profiler/MethodRewriter/ISystemCalls.h, src/Agent/NewRelic/Profiler/MethodRewriterTest/MockSystemCalls.h, src/Agent/NewRelic/Profiler/Profiler/CoreCLRCorProfilerCallbackImpl.h, src/Agent/NewRelic/Profiler/Profiler/FrameworkCorProfilerCallbackImpl.h, src/Agent/NewRelic/Profiler/Profiler/ICorProfilerCallbackBase.h, src/Agent/NewRelic/Profiler/Profiler/SystemCalls.h, src/Agent/NewRelic/Profiler/Profiler/UnixSystemCalls.h
Before combining the `CoreCLRCorProfilerCallbackImpl.h` and `FrameworkCorProfilerCallbackImpl.h` into once, this PR lays some ground work. More specially, this PR adds the CLR type detection logic inside the `Initialize()` method which helps with the later combining work.
I manually tested the new profiler in both Core and Framework. It attached and the agent successfully started.
=> Automatically detect CLR type.

docs/integration-tests.md
This updates our instructions on how to run our integration tests to include Linux instructions.
=> Add Linux integration test instructions

src/Agent/NewRelic/Agent/Core/Transactions/IInternalTransaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/NoOpTransaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/ITransactionExperimental.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Instrumentation.xml, tests/Agent/UnitTests/Core.UnitTest/Transactions/TransactionTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TestTransactions.cs
* Adds RecordLogMessage to ITransactionExperimental.  This is mainly so that its possible to change without requiring deprecation or other warning.
* Adds RecordLogMessage to NewRelic.Agent.Core.Transactions.Transaction.
* Adds LogEvents ConcurrentList to NewRelic.Agent.Core.Transactions.Transaction and IInternalTransaction to store the LogEventWireModels before they are transformed.
* Includes Tests for RecordLogMessage that also checks the LogEvents collection.
* Updated TestTransaction fixture to include logging settings (metrics as well as forwarding to be thorough)
Also updates the logging intrumentation XML to make it UTF-8 no BOM (somehow it got setup with a BOM).  
Resolves #905
=> Adds RecordLogMessage and LogEvents to Transaction with tests

tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj
I don't know why the unbounded integration tests project had a reference to log4net, but I removed it and the solution still builds.  I ran the MS SQL tests locally and they still run and pass as expected.  The server CI will run all of the tests and let us know for sure.
=> Remove log4net from unbounded integration tests project

src/Agent/NewRelic/Agent/Core/DataTransport/DataTransportService.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/DataTransportServiceTests.cs
Closes #903
Adds the ability to send log event data to the Collector. With tests. Also, establishes a pattern to easily test all different variants of Send() methods on DataTransportService.
=> Add Send Method for LogEvent Data

src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/IAgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/Aggregators/LogEventAggregator.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/MetricNames.cs, src/Agent/NewRelic/Agent/Core/WireModels/IMetricBuilder.cs, src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs, tests/Agent/UnitTests/Core.UnitTest/AgentHealth/AgentHealthReporterTests.cs, tests/Agent/UnitTests/Core.UnitTest/Aggregators/LogEventAggregatorTests.cs
- Adds LogEventsAggregator using ErrorEventAggregator as a reference
- Adds new supportability metrics in AgentHealthReporter to track was is collected, sent, and recollect
- Adds tests for new supportability metrics
- Adds new test class for LogEventAggregator using ErrorEventAggregatorTests as a reference
Resolves #907
=> Adds LogEventAggregator with supportability metrics and tests

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
Resolves #924
Adds environment variable overrides for logging configuration options. I did not see any unit tests for env var overrides so did not add any.
=> Add environment variable overrides for Log Sending

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Profiler/build/build.ps1, src/Agent/NewRelic/Profiler/linux/Dockerfile, src/Agent/NewRelic/Profiler/linux/Dockerfile.new, src/Agent/NewRelic/Profiler/linux/README.md
This fixes #918 where the agent was segfaulting customer application on Alpine Linux in release 9.5.0.
Summary of changes:
1. Revert to previous Linux profiler build container image.
2. Store the newer-but-broken profiler build container image as `Dockerfile.new` and add a README.md to describe what's going on.
3. New checked-in `libNewRelicProfiler.so` for dev builds.
I tested the new `libNewRelicProfiler.so` with integration tests on both Ubuntu and Alpine and it appears to be working as expected.
=> Revert Linux profiler build process to fix Alpine Linux crash

src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs
- Refactors log4net wrapper to make it more readable by pulling out the message forwarding and decorating into different methods.
- Adds log decoration to log4net wrapper
- Adds configuration for enable/disable of log decorating with env var
- No tests since we don't test wrappers in unit tests
Closes #914
=> Adds log decorating to log4net wrapper with config

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/LoggingHelpers.cs
Refactors local log decoration to use a single entry which contains the entire metadata string in the proper format and with jsut the data that is available.  This me that if we are missing trace and span IDs, there will not be an empty or null entry in the properties list.  This also enables this to just work for Json layouts/sinks.
Adds a new LoggingHelpers static class with a single method currently.
No unit tests since its a wrapper change and no integration tests as of yet.
Closes #943
=> Refactors local log decoration to use a single entry

src/Agent/NewRelic/Agent/Core/WireModels/LogEventWireModel.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelTests.cs
Resolves #941.  The log message part of the LogEventWireModel is truncated to 32K bytes. There's an open question as to whether this means 32 * 1000 (kilobytes) or 32 * 1024 (kibibytes) but I've gone with the more conservative 32 * 1000 at this point.
The story says that integration tests are required; I did a unit test and I think that should be sufficient.    I reused an well-tested internal method for truncating the message string.  I think an integration test would be overkill for this.
=> Truncate log event message string to 32Kb

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Resolves #950 
There was an issue where our instrumentation for log4net wasn't working properly for versions < 2.0.6. After digging in to it, this was because we were trying to access a UTC timestamp that is not available in older versions.
We can now support log4net v1.2.10+
=> Support log4net back to version 1.2.10

src/Agent/NewRelic/Agent/Core/WireModels/LogEventWireModel.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelTests.cs
Implement decision to use kibibytes for the log message limit
=> Use kibibytes instead of kilobytes for log message limit

src/Agent/NewRelic/Agent/Core/Aggregators/LogEventAggregator.cs, src/Agent/NewRelic/Agent/Core/JsonConverters/LogEventWireModelCollectionJsonConverter.cs, src/Agent/NewRelic/Agent/Core/WireModels/LogEventWireModelCollection.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/LoggingHelpers.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Models/LogData.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/Log4netMaxSamplesStoredTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/Log4netMetricsAndForwardingTests.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LogEventWireModelCollectionJsonConverterTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelCollectionTests.cs
Closes #951 by removing `entity.name`, `entity.type`, and `plugin.type` from both in-agent log forwarding and local log decoration.
=> Remove entity name and type

src/Agent/NewRelic/Agent/Core/Utilization/VendorHttpApiRequestor.cs, src/Agent/NewRelic/Agent/Core/Utilization/VendorInfo.cs, tests/Agent/UnitTests/Core.UnitTest/Utilization/VendorHttpApiRequestorTests.cs
Closes #961
- Updates CallVendorApi to require passing in the request method you want it to use with the WebRequest
- Setup constants in VendorInfo for GET and PUT (put will be used shortly)
- Update the calls to CallVendorApi  to use new consts in VendorInfo 
- Updated the one test used CallVendorApi to include a method (GET)
=> Adds request method to CallVendorApi for IMDSv2

src/Agent/NewRelic/Agent/Core/Utilization/VendorInfo.cs
- Updates utilization metadata to use IMDSv2 for AWS. 
- Json did not change so no parsing changes.
- No unit tests broke 
- no integration tests
- Tested on my AWS server, worked like a charm.
Closes #963
=> Migrate AWS metadata to use IMDSv2

tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/Log4netJsonLayoutDecorationTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/Log4netPatternLayoutDecorationTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/Log4netTester.cs
Closes: #916 
Tests log4net decoration with a layout formatter, and JSON formatter. The JSON formatter only works for newer versions of log4net starting at version 2.0.5, so only some framework/core versions are targetted.
=> Log4Net decoration integration tests

tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/Log4netMetricsAndForwardingTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/Log4netTester.cs
Closes #972 
Adds async use case test coverage for log4net forwarding.
The only undesirable finding is that if logs are delegated to a background thread and not awaited, then they will not show up as part of a transaction that initiated them. I do not think there is much we can do about this.
=> Async Log4net forwarding integration test coverage

tests/AwsLambda/UnitTests/AwsLambdaOpenTracerTests/AwsLambdaOpenTracerTests.csproj, tests/AwsLambda/UnitTests/AwsLambdaWrapperTests/AwsLambdaWrapperTests.csproj, tests/NewRelic.Core.Tests/NewRelic.Core.Tests.csproj
Update the AWS Lambda OpenTracer unit tests and associated `NewRelic.Core.Tests` dependency to target `netcoreapp3.1`.  This should fix CI failures caused by the removal of .NET Core 2.1 assets from the `windows-2019` GHA runner used: https://github.com/actions/virtual-environments/issues/4871
=> Update lambda tracer unit tests to netcoreapp3.1

FullAgent.sln, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Logging/LogProviders.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/SerilogWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/LoggerFactoryWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/MicrosoftExtensionsLogging.csproj
- Adds Wrapper to instrument the constructor where logging providers are added to allow us to detect when an already instrumented logger is added and store that for later use.
- Adds a static class to holder an enum of the supported log providers, names that the providers use, and an array to store if the providers are in use.
- Updates the CanWrap for Log4net and Serilog to check if the wrapper should not be used since Micrsoft.Extensions.Logging  is in use.
Resolves #989
=> Adds Micrsoft.Extensions.Logging providers wrapper and detection

src/Agent/NewRelic/Agent/Core/JsonConverters/LogEventWireModelCollectionJsonConverter.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Models/LogData.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LogEventWireModelCollectionJsonConverterTests.cs
We were adding `traceid` and `spanid` attributes to the JSON sent to the `log_event_data` collector endpoint instead of the expected `trace.id` and `span.id` attributes. This caused logs to not be linked properly to distributed traces, errors, or errors inbox.
I verified that changing this causes everything to work properly, and updated unit/integration tests for the new attribute name.
=> Update log_event_data json to use `trace.id` and `span.id`

src/Agent/NewRelic/Agent/Core/Aggregators/LogEventAggregator.cs, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/DataTransport/ConnectModel.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Aggregators/LogEventAggregatorTests.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TestTransactions.cs
The max samples for log events is supposed to be 10000 per 60 seconds, not 5 seconds.  The config setting is correctly set at 10000, but that needs to be passed up during connect so that the 5 second samples limit (833) is passed back.
- Renamed LogEventsMaximumPerPeriod to LogEventsMaxSamplesStored to match the other settings.
- Adds log_event_data to harvest limits payload using during connect so that it pulls down the correct value
Note: the log_event_data limit has not be added to the connect payload so that raw 10000 value will be used.  If the connect payload is not added before our testing begins, we might want to consider setting it to 833 in the short term
=> Fixes sampling limits for log_event_data

src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/IAgentExperimental.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/AgentWrapperApiTests.cs
This PR updates the `RecordLogMessage()` experimental agent API to take getter functions that know how to extract the timestamp, log level and log message from an arbitrary log event object, rather than those values themselves.  This allows us to avoid doing unnecessary and expensive reflection work to get values if they aren't needed due to config settings.
I went with this approach rather than just putting the config checks in the wrapper itself for two reasons:
1. Per the current logging instrumentation engineering brief/design doc, we need to create a supportability metric that indicates that our instrumentation matched a given logging framework, even if all logging features are disabled by config.  That happens at the very top of `RecordLogMessage`, and so we can't short-circuit …
=> Avoid unnecessary work in logging wrappers

src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Core/Aggregators/LogEventAggregator.cs, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/DataTransport/ConnectModel.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/IAgentExperimental.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/SerilogWrapper.cs, tests/Agent/UnitTests/Core.UnitTest/Aggregators/LogEventAggregatorTests.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TestTransactions.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/AgentWrapperApiTests.cs
Update the Serilog wrapper to use the new shape of the `RecordLogMessage` API, as well as bring in other work from the upstream `logsinst-feature-branch` in preparation for merging `serilog-instrumentation-feature-branch` back into it.
=> Update Serilog wrapper to use new RecordLogMessage API shape

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
- After some lengthy discussions we decided to have the connect config take precedence over the local values since we want the maxSamplesSize to be spread over the individual faster event harvests.
- Includes setting the default value in the GetValueOrDefault as well to ensure we always get a good value.
- Not test changes since this just swaps precedence.
=> Swap logs maxsamples config precedence

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Final part of #1002.  Test multiple versions of Serilog back to 2.0.0.
We can only test Serilog <2.5.0 in .NET Framework, because of how our tests for Microsoft.Extensions.Logging also depend on Serilog - specifically Serilog.Extensions.Hosting, whose earliest version (2.0.0) depends on Serilog >= 2.5.0.  However, I see no particular reason to suspect that we would not support Serilog 2.0.0 in .NET Core as well.
=> Test multiple versions of Serilog back to 2.0.0

src/Agent/NewRelic/Agent/Core/Aggregators/LogEventAggregator.cs, src/Agent/NewRelic/Agent/Core/JsonConverters/LogEventWireModelCollectionJsonConverter.cs, src/Agent/NewRelic/Agent/Core/WireModels/LogEventWireModelCollection.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Logging/LoggingHelpers.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Models/LogData.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/LocalDecorationTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/MetricsAndForwardingTests.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LogEventWireModelCollectionJsonConverterTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelCollectionTests.cs
Add `entity.name` (which is just the first (and usually only) application name the agent knows about) back to the log data payload and the local decoration metadata blob.
I updated the local decoration integration tests to be a bit more specific about the data it is looking for (not just asserting on the regex match, but asserting on the individual values as far as specifically as we can - in the case of the `entity.name` we know it should match the application name so we can be very specific about that one).
=> Add back entity.name to log data payload and local decoration

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Logging/LoggingHelpers.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/LocalDecorationTests.cs
The `entity.name` value written to the metadata blob in local decoration needs to be URL encoded.  Updated the integration tests for local decoration to account for this.
=> URLEncode entity name in local decoration

src/Agent/NewRelic/Agent/Core/Aggregators/IAllMetricStatsCollection.cs, src/Agent/NewRelic/Agent/Core/Aggregators/MetricAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/MetricStatsCollection.cs, src/Agent/NewRelic/Agent/Core/Aggregators/MetricStatsCollectionQueue.cs, src/Agent/NewRelic/Agent/Core/Aggregators/TransactionMetricStatsCollection.cs, src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs, tests/Agent/UnitTests/Core.UnitTest/Aggregators/MetricAggregatorTests.cs, tests/Agent/UnitTests/Core.UnitTest/Aggregators/MetricStatsCollectionTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/MetricWireModelTests.cs
* Rename anything with "engine" to "collection", i.e. MetricStatsEngineQueue ->MetricStatsCollectionQueue
* Refactors MetricStatsEngineQueue 
* Pulls this class out of MetricAggregator.cs into its own file
* Renames MetricStatsEngineQueue to MetricStatsCollectionQueue
* Changes the Queue<MetricStatsCollection> to a ConcurentQueue<MetricStatsCollection>
* Remove all explicit lock statements and associated objects
* Removes _statsEngineCount since that was only used for minor error check and testing.  This eliminates another lock and simplifies the class. Removed some code for this from MetricWireModel as well.
* Removes some catch statements, one that was literally labelled as "should never happen".
* Cleaned up MetricAggregator after nested class removed
* Updated Unit tests to point at …
=> Refactor MetricStatsEngineQueue to MetricStatsCollectionQueue

tests/Agent/IntegrationTests/IntegrationTests/Logging/ZeroMaxSamplesStoredTests.cs
Adds tests to ensure that when the server sends back a 0 for maxSamplesStored we stop forwarding log lines.  This is used as part of the system to disable log forwarding account-wide.
It does this in the tests by setting the value locally to 1, which causes the server to sen back 0 (server divides the local value by 12 - 5 seconds harvests)
=> Adds test for server sending back 0 for maxSamples

src/Agent/NewRelic.Api.Agent/NewRelic.cs, src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs, src/Agent/NewRelic/Agent/Core/Api/AgentApiImplementation.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/IAgentApi.cs
The docs indicate that there is a 1000 character limit for the message parameter. This is not correct.
My testing has show the following:
- This 1000 character limit doc was added to the code in v2.0.8 and expanded out into other areas in v8.28.
- The is no 1000 character limit for NoticeError
- NoticeError creates both Error Events and ErrorTraces
- The limit is different for Error Events and Error Traces
- Error Events: The message is stored as an attribute with a limit of 255 characters per the Attribute spec.  The Errors spec defers to this for the limit.
- Error Traces: There does not appear to be a limit on message outside of a total payload limit of 1MB.  I was able to send over a 1000 character message with no issues.
The UI displays data from both types in different areas and …
=> Fixes, updates,and adds NoticeError docs - removes 1000 character limit note in docs

build/Packaging/AzureSiteExtension/CHANGELOG.md, build/Packaging/AzureSiteExtension/Content/applicationHost.xdt, build/Packaging/AzureSiteExtension/Content/install.ps1, build/Packaging/AzureSiteExtension/Content/uninstall.cmd
Closes #1005
Updates the location where the New Relic agent is deployed by our Azure Site Extension. This resolves the following issues:
1. Installs the agent to `%HOME%/NewRelicAgent` instead of `%WEBROOT_PATH%`. This allows the agent to install properly when a site is [Run From a ZIP Package](https://docs.microsoft.com/en-us/azure/app-service/deploy-run-package) and the site root is read only.
2. Uses the `%HOME%` environment variable for installation and profiler environment variables instead of assuming everything will live on the `C:\` drive. This will more gracefully handle cases where Azure uses a `D:\` root instead of a `C:\` root.
3. As the agent has been moved out of the `%WEBROOT_PATH%`, customers should experience fewer issues where deploying their application code deletes the …
=> Azure Site Extension improvements

src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinition.cs, src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, tests/Agent/UnitTests/Core.UnitTest/Attributes/AttributeTests.cs
* Renames the "CreateString" method used by errors into "CreateErrorMessage".
* CreateErrorMessage takes a new const for the length which is set at 1023 instead 255
* Added unit tests to test error length and one for other strings length.
* Unit and Integration tests pass locally
Closes #1007
=> error.message accepts uo to 1023 chars insread of 255 with unit tests

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Parsing/SqlParser.cs, tests/Agent/IntegrationTests/Shared/DbParameterData.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureTests.cs
This PR mostly resolves the scenario 1 from the issue #185. The reason why Agent fails to execute explain plan for this scenario is, unlike other sql commands, the command text for a parameterized stored procedure doesn't need to have parameters specified, our `bool FixParameterizedSql` function didn't work based on this difference. Since the `bool FixParameterizedSql` function turns parameterized SQLs to non-parameterized and parameterized stored procedures don't need this, in order to fix this, we need to make a special case for stored procedures.
PS: I removed the `binary` type in testing parameterized stored procedures because this type disables the explain plan creation ability in the agent.( https://github.com/newrelic/newrelic-dotnet-agent/blob/0cebc8545acdd8d09d72184cf29a9dd7f3a549 …
=> Fix fail to execute explain plan 

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/SerilogWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/Common.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/MetricsAndForwardingTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/Controllers/TestController.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/LoggingTester.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/SerilogLoggingWebAdapter.cs
Updates serilog wrapper to check for duplicate log entries by looking at the stackframes and checking for additional "Dispatch" methods.
There are two different versions of the stack trace, one that places the initial Dispatch method at 7 and one that places it at 8.  The logic in the wrapper handles this.
Tests all pass and performance is acceptable (let me know if you want to go over it)
Closes #1070
=> Serilog dupe stackframe fix

docs/config-development.md
Added documentation around how configuration classes are generated in the agent to the `/docs` folder.
Currently, the only documentation exists in the readme file in `.\build\Tools\xsd2code` which requires knowing that we already use that or searching around once you see the code comments that the classes are generated. I only knew to go track this down due to previous times working on the agent. 
To help out future devs/open-source contributors, I recommend we have something with the docs so submitting as a PR.
This content is very duplicative of the readme but I figured I'd leave the readme with the utility so there is context directly there. Could also just link back from there but I don't think the duplication really hurts here. What is most likely to happen is changing tooling (or …
=> Adds configuration development doc 

.github/workflows/markdowncheck.config.json
Adds 403 status as indicator of 'alive' URL to markdown link checking.
GitHub docs pages return a 403 when requests are not from a browser.
I'm guessing this is due to checking for a user agent header or some such to preventing doing a bunch of work for automated scripts. Given 403 indicates the page exists but you are not authorized, it seemed like the right solution here is to add that to the "alive" indicators. It is unlikely we'll add links to truly unauthorized pages we'd need this checking to catch. An alternative approach (I almost went with first) would be to add an ignore rule for GitHub pages in which case we might miss truly bad GitHub links. Lastly one could experiment with manually adding user headers but who knows if GitHub would eventually flag where our requests come from.
=> Adds 403 status as indicator of 'alive' URL to markdown link checking.

src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Segments/NoOpSegment.cs, src/Agent/NewRelic/Agent/Core/Segments/Segment.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/ISegmentExperimental.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/IntegrationTests/Applications/AgentApiExecutor/Program.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/FrameworkCustomInstrumentationCodeAttributesTest.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/NetCoreCustomInstrumentationCodeAttributesTests.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Plumbs in initial capture of `code.namespace` and `code.function` attributes on spans. Enables mapping of code of custom-instrumented methods.
* Captures instrumented method and type for all spans which apply to instrumented code (not artificial root spans). 
* Plumbs in ability to override to update instrumentation such as MVC Controllers to point to actual customer code.
* Introduces code level metric configuration with enabled defaulting to `false`.
Closes: https://github.com/newrelic/newrelic-dotnet-agent/issues/1090
=> Adds default capture of code level metric attributes

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/InvokeActionMethodAsyncWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/AspNetCoreMvcCodeAttributesTest.cs
Overrides the default capture of `code.namespace` and `code.function` on spans to point to the customer's controller action function that is represented by our instrumentation.
closes: https://github.com/newrelic/newrelic-dotnet-agent/issues/1091
=> Adds user/customer code level span attributes for ASP.NET Core MVC 

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/WebApi2/InvokeActionAsyncWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/OwinWebApi2CodeAttributesTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/WebApi2CodeAttributesTest.cs
Overrides the default capture of `code.namespace` and `code.function` on spans to point to the customer's controller action function that is represented by our instrumentation.
closes: https://github.com/newrelic/newrelic-dotnet-agent/issues/1096
Went ahead and added Owin-based Web API tests so it is clear that case is supported in the future.
=> Adds user/customer code level span attributes for Web API 2

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Introduces `NEW_RELIC_CODE_LEVEL_METRICS_ENABLED` ENV var which maps to: `codeLevelMetrics.enabled`.
closes: https://github.com/newrelic/newrelic-dotnet-agent/issues/1101
=> Adds environment variable for new CLM configuration.

build/Linux/build/deb/postinst, build/Linux/build/rpm/newrelic-netcore20-agent.spec, build/Packaging/AzureSiteExtension/Content/install.ps1, src/Agent/CHANGELOG.md, src/Agent/MsiInstaller/InstallerActions/CustomActions.cs
- Updates MSI installer custom actions to remove the  deprecated logging instrumentation files from their default locations (what we have access to).  This is done using a preexisting system that won't throw errors if the files don't exist - it already has several.
- Updates the Azure  Site Extension script to add a new function that removes deprecated files .  This is called at the end of the install script.  Uses `ErrorAction Ignore` to prevent any errors from causing problems like in other areas of the script.
- Updates both the RPM and DEB install scripts to attempt to remove deprecated instrumentation from the `$NEWRELIC_HOME` directory (available in the script already).    Uses `2> /dev/null` to prevent any errors from causing problems like in other areas of the script.
**Note:** …
=> Adds ability to remove deprecated instrumentation files post installation

tests/Agent/IntegrationTests/Applications/AgentApiExecutor/Program.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/AspNetCoreMvcCodeAttributeTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/FrameworkAspNetMvcCodeAttributeTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/FrameworkCustomInstrumentationCodeAttributeTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/NetCoreCustomInstrumentationCodeAttributeTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/OwinWebApi2CodeAttributeTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/WebApi2CodeAttributeTests.cs
Turns out one of the code level metrics tests has issues in CI. The tests weren't originally wired up to CI.
This PR attempts to resolve the one known issue, prevent another class of issue and make it easier to narrow in on individual problems.
- Waits for span event data log lines.
- Asserts each span is found.
- Prevents inlining of custom instrumented code.
=> Code level metrics test stability

.github/workflows/all_solutions.yml, tests/Agent/IntegrationTests/IntegrationTests/Logging/HSMOrCSPDisablesForwardingTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/LocalDecorationTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/MaxSamplesStoredTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/MetricsAndForwardingTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/ZeroMaxSamplesStoredTests.cs
Adds unique namespaces to different logging integration test fixtures, matrixes CI runs on those new namespaces, and enables parallel test execution for Logging integration tests.
The first full run completed in 1 hour!
=> Speed up CI integration test runs

tests/Agent/IntegrationTests/Applications/BasicMvcApplication/Controllers/DefaultController.cs, tests/Agent/IntegrationTests/IntegrationTests/CatInbound/CatEnabledWithServerRedirect.cs
The test was calling two web methods and it was a toss up as to which one would take longer and be sampled. This new approach should be more reliable
=> Make CatInbound integration test more reliable

src/Agent/NewRelic/Home/Home.csproj
- Splits out the commands in the Home project ()home builder) into individual commands
- Removes the "cd" portion of the "build_home.ps1" command and instead uses "WorkingDirectory" option.
- Added a description to the Home project csproj that explains what this does and why it is empty.
=> Update and fix Home.csproj to make errors more visible

.github/workflows/all_solutions.yml, src/Agent/NewRelic/Agent/Core/Core.csproj
- Updates the Google.Protobuf  package to latest version
- Moved some PackageReferences around to support the updated Google.Protobuf   package use of System.Span - cannot ILRepack the assemblies in Core.
- Updated ILRepack counts to match the new steup
Change log not updated:  Didn't know how we wanted to (if we wanted) to call out the update.
=> Updates gRPC Google.Protobuf to latest version

src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/JsonConverters/LogEventWireModelCollectionJsonConverter.cs, src/Agent/NewRelic/Agent/Core/WireModels/LogEventWireModel.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Log4NetLogging/Log4netWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/MicrosoftLoggingWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NLogLogging/NLogWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/SerilogLogging/NewRelicSerilogSink.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Models/LogData.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/MaxSamplesStoredTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/MetricsAndForwardingTests.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LogEventWireModelCollectionJsonConverterTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelCollectionTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/AgentWrapperApiTests.cs
- Use level instead of log.level
- Move span and trace id to root of log event instead of under attributes
- Update the various identifiers in code to use a variation of "Level" instead of "LogLevel" to keep naming consistent
- Updated unit and integration tests to account for changes
All unit and integration tests pass locally.
=> Update logging attributes to match spec

tests/Agent/IntegrationTests/Applications/Owin2WebApi/Controllers/ValuesController.cs, tests/Agent/IntegrationTests/Applications/Owin3WebApi/Controllers/ValuesController.cs, tests/Agent/IntegrationTests/Applications/Owin4WebApi/Controllers/ValuesController.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteService.cs, tests/Agent/IntegrationTests/IntegrationTests/CustomInstrumentation/ConsoleAsynConsoleAsyncForceNewTransactionTests.cs, tests/Agent/IntegrationTests/IntegrationTests/DataTransmission/ConnectResponseHandlingTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/MetricsAndForwardingTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Owin/OwinWebApiTests.cs, tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFLegacyTestBase.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/ConsoleDynamicMethodFixture.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplication.cs
* Doesn't send exit signal to console multi app until after all actions have completed by moving to the shutdown function of the fixture. This enables adding additional execute actions to the console multi runner.
* Adds metric log line waiting to a couple tests that seem like they may occasionally be asserting against incomplete metrics.
* Adds a 1 second thread sleep to the multi runner when no commands found. We don't need real time reading.
=> Minor test stability improvement attempts

tests/Agent/IntegrationTests/IntegrationTestHelpers/RandomPortGenerator.cs
I noticed a random CI failure where we detected an available port, but the remote application was unable to claim said port when it actually tried starting up. After reviewing the existing logic, the attempt to release a port could fail, but the port could still be reported as available. This change requires the port to be successfully opened AND closed to be considered available.
The failure I saw in CI could still be a race condition for ports, but it doesn't look like it after reviewing logs. I believe this refactored port availability check will improve CI reliability.
=> Improve port availability check for integration tests

.github/workflows/run_integration_tests.yml
In another branch I am working on a new manually-run workflow to run integration tests using the built assets from a previous all_solutions.yml workflow run.  This will let us more quickly and easily run integration tests in CI, improving developer productivity  in debugging and testing our ongoing CI instability issues.
GitHub Actions only lets you manually run workflows that exist on the main branch of your repo, although once there, you can choose to run a version of that workflow from another branch.  So, I need to get a placeholder version of this workflow merged to main so I can begin testing the real thing.
=> Placeholder integration test workflow

tests/Agent/IntegrationTests/Applications/Owin2WebApi/Controllers/AsyncAwaitController.cs, tests/Agent/IntegrationTests/Applications/Owin3WebApi/Controllers/AsyncAwaitController.cs, tests/Agent/IntegrationTests/Applications/Owin4WebApi/Controllers/AsyncAwaitController.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RandomPortGenerator.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplication.cs, tests/Agent/IntegrationTests/IntegrationTests/Owin/OwinWebApiAsyncTests.cs
CI reliability improvements:
- Increases the collector web request timeout to 60 seconds, from 10 seconds. This should improve CI stability with the staging collector timeouts we have experienced. 
- Increases transaction time for hopefully sampled transactions.
- Experimental changes to random port selection.
=> CI Reliability: Increase collector timeout to 60 seconds, but wait there's more!

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Aggregators/TransactionTraceAggregator.cs, src/Agent/NewRelic/Agent/Core/TransactionTraces/ITransactionCollector.cs, src/Agent/NewRelic/Agent/Core/TransactionTraces/KeyTransactionCollector.cs, src/Agent/NewRelic/Agent/Core/TransactionTraces/SlowestTransactionCollector.cs, src/Agent/NewRelic/Agent/Core/TransactionTraces/SyntheticsTransactionCollector.cs, tests/Agent/UnitTests/Core.UnitTest/TransactionTraces/KeyTransactionCollectorTests.cs, tests/Agent/UnitTests/Core.UnitTest/TransactionTraces/SlowestTransactionCollectorTests.cs, tests/Agent/UnitTests/Core.UnitTest/TransactionTraces/SyntheticsTransactionCollectorTests.cs
We have seen some test runs recently where the slowest transaction trace was not actually captured by the transaction trace aggregator. After reviewing the code there is a potential race condition where two transactions can be set as the 'slowest', but the actual slowest may not be retained due to a lack of locking.
This solution attempts to keep locking to a minimum, while ensuring we actually capture the slowest transaction.
=> Resolve transaction trace aggregation race conditions

build/Linux/build/deb/postinst, build/Linux/build/rpm/newrelic-dotnet-agent.spec
Improve the process of migrating user data from the old `newrelic-netcore20-agent` folder to the new `newrelic-dotnet-agent` folder, to make it no longer necessary to remove the old folder after migration to prevent any changes to the content in the new folder from being overwritten on subsequent upgrades.
=> Improve Linux package user data migration process

tests/Agent/IntegrationTests/Applications/AgentApiExecutor/Program.cs, tests/Agent/IntegrationTests/Applications/ApiAppNameChange/Program.cs, tests/Agent/IntegrationTests/Applications/DistributedTracingApiApplication/Program.cs
Potential fix for #1197 
I found that the test that had been failing semi-regularly in recent CI runs (`CustomInstrumentation.OtherTransaction`) with the "failed to send shutdown signal to $NAME_OF_APP_WAIT_HANDLE" error had a test app that wasn't actually waiting on its event wait handle...so it would be possible to encounter this error if the timing of things was just right.
~Draft PR to see if these changes actually fix the problem in CI~ The tests that had been failing before this didn't fail on the CI run for this PR, so it's ready for review.
=> Fix three test apps that weren't actually waiting on their wait handles

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Transactions/IInternalTransaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionTransformer.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteService.cs, tests/Agent/UnitTests/Core.UnitTest/Transactions/TransactionLogEventTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTransformerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/AgentWrapperApiTests.cs
Resolves an issue where un-awaited async code that logs could add log events to a transaction even after the log events had been transformed. 
Closes #1156
=> Resolve issue with missing logs

tests/Agent/IntegrationTests/IntegrationTestHelpers/CommonUtils.cs
This is a minor fix for a source of local integration test failures I've been seeing off and on for a while now.
1. The test harness, as part of the setting up each individual test, copies both the test application bits and the appropriate `newrelichome_` folder from `$repo_root/src/Agent` to a temp directory.
2. It's possible for there to already be existing log files in one or more of the homedirs.
3. Those existing logs can cause problems for the test logic since it assumes it's starting from a clean slate.
4. We already had logic to skip copying those logs if they were in a dir called `Logs` but apparently we can also get them in a dir called `logs`, so this PR modifies that logic to be case-insensitive.
=> Integration test framework should skip copying a `logs` subfolder of the home dirs

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
I have added support for Labels to be added/modified via AppSettings.json or app/web.config file. 
Our internal system does not allow to change of process variables or modification of other files than appsettings.json (cannot use newrelic.config).
So I cannot use the currently supported ways.
=> Added support for Labels to be set from AppSettings.json or web/app.config

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Internal PR for community contribution from @quigamdev : https://github.com/newrelic/newrelic-dotnet-agent/pull/1204.
.NET team added caching for the Labels field, and unit tests.
=> Community: Added support for Labels to be set from AppSettings.json or web/app.config

src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs, src/Agent/NewRelic/Agent/Core/DataTransport/HttpCollectorWire.cs, src/Agent/NewRelic/Agent/Core/DataTransport/ICollectorWire.cs, src/Agent/NewRelic/Agent/Core/DataTransport/NoOpCollectorWire.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTests/CSP/AspNetCoreLocalHSMDisabledAndServerSideHSMEnabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CSP/AspNetCoreLocalHSMEnabledAndServerSideHSMDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CSP/HighSecurityModeServerDisabled.cs, tests/Agent/IntegrationTests/IntegrationTests/CSP/HighSecurityModeServerEnabled.cs, tests/Agent/IntegrationTests/IntegrationTests/CustomAttributes/Labels.cs, tests/Agent/UnitTests/CompositeTests/CrossAgentTests/SecurityPolicies/SecurityPoliciesCrossAgentTests.cs, tests/Agent/UnitTests/CompositeTests/EventHarvestConfigSupportabilityMetricsTests.cs
Closes #1152 
Refactor log messages that are written for collector web requests to include a guid for continuity, and log before/after request.
Update test framework to inspect collector request payloads from SUCCESSFUL  requests only. This also eliminates race conditions where test applications were waiting on a log line that only indicated an external request was initiated, versus completed...
=> Improve quality of log based assertions for collector requests

.github/workflows/all_solutions.yml
Github is deprecating its `ubuntu-18.04` runners: https://github.com/actions/runner-images/issues/6002
Upgrade all workflow references of `ubuntu-18.04` to `ubuntu-22.04`.
Note: was not able to upgrade the `distro` parameter in the `run-on-arch` jobs for building and testing the ARM version of the Linux profiler, due to build problems.  Doing this will take more effort as it's unclear what the cause of the problem is, but it seems to be in the general area of cmake/clang/llvm tooling.  This doesn't seem to be a problem since we don't have any indication that the `run-on-arch` action is deprecating the `ubuntu18.04` distro option.
=> Update all ubuntu 18.04 runners to 22.04

tests/Agent/IntegrationTests/Applications/BasicMvcApplication/Controllers/RestAPIController.cs
This change should ensure that this code executes as expected: https://github.com/newrelic/newrelic-dotnet-agent/blob/ffcf0d4ce27efa7e35cf751658b16ccdffed55df/tests/Agent/IntegrationTests/Applications/BasicMvcApplication/Controllers/RestSharpController.cs#L171-L173
by ensuring that the client times out before the request to `RestAPI/4` returns successfully.
This should fix this CI failure seen recently (also seen locally, and I verified that it passes reliably locally after the change): https://github.com/newrelic/newrelic-dotnet-agent/runs/7784160572?check_suite_focus=true
=> Fix timing issue with RestSharpClientTaskCancelled requests

tests/Agent/IntegrationTests/IntegrationTestHelpers/RandomPortGenerator.cs
See issue #1214 for details on how we concluded that this change was necessary.  However, I believe that this is the solution to the random CI failures caused by port availability conflicts.  See the documentation for [TcpListener.ExclusiveAddressUse](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcplistener.exclusiveaddressuse?view=net-6.0) for an explanation.  Setting this property to true appears to make our port availability check actually work as expected.
=> Set ExclusiveAddressUse to true in RandomPortGenerator

tests/Agent/IntegrationTests/Applications/AspNetCore3Features/Controllers/HomeController.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplicationFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/ThreadProfileStressTests.cs, tests/Agent/IntegrationTests/IntegrationTests/AspNetCore/AspNetCoreGenericWebHostTests.cs, tests/Agent/IntegrationTests/IntegrationTests/IntegrationTests.csproj, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/BasicAspWebService.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/EnvironmentVariables/AllowAllHeadersEnabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RestSharp/RestSharpClientInstrumentationCAT.cs, tests/Agent/IntegrationTests/IntegrationTests/RestSharp/RestSharpClientInstrumentationDistributedTracing.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/ConsoleDynamicMethodFixture.cs, tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationFW/NetFrameworkLibraries/HostedWebCore.cs, tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationFW/NetFrameworkLibraries/WCF/WCFClient.cs
I spent around 10 hours running CI on a powerful VM and dug in to any random failures I encountered locally. Here are the results of my adventures.
Resolves the following issues with CI runs:
- Adds a sleep to a AspNetCore3 test app to a method that is expected to be the traced transaction
- Eliminates test harness retries as the retry obfuscates the initial failure, and causes unrelated failures in some cases. This should allow us to see the actual failures. We may decide to turn retries back on, but for now I believe we should disable retries.
- Upgrades the selenium IE driver. I attempted to migrate to the Chrome driver, but there are issues with incompatibilities with the version of chrome on the GHA CI Runners... Since IE hasn't been updated in forever, it seems to work everywhere …
=> CI Improvements

.github/workflows/all_solutions.yml, .github/workflows/run_integration_tests.yml, src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/MicrosoftExtensionsLogging.csproj, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/MicrosoftLoggingWrapper.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/Common.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/LogLevelTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/MetricsAndForwardingTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/ILoggingAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/Log4NetLoggingAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/LoggingTester.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/MicrosoftLoggingLoggingAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/NLogLoggingAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/SerilogLoggingAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/SerilogLoggingWebAdapter.cs
Our instrumentation point for Microsoft Extensions Logging in agent log forwarding is invoked before any of the built in log level filtering has taken place. Due to this, logs with a lower level than what was configured in MEL were being forwarded to New Relic. 
These changes resolve that issue by querying MEL to see if the level of observed log events are enabled or disabled.
Resolves #1230
=> Resolve issue where more logs were forwarded than desired from MEL

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
At the current state, when MAX_EVENT_SAMPLES_STORED env var is set, the agent uses value from the env var for the preconnect request. The server replies with a smaller value (whatver the value sent up get divided by 12). However, the agent won't use the value from the server because our current logic allows the env to override any config values. This causes configuration mismatched as well as incorrect `...\EvenHarvest\CustomEventData\HarvestLimit` supportability metric value being reported.
The same story happens to the MAX_TRANSACTION_SAMPLES_STORED env var usage.
The right approach is to let the server config to dictate the final value that the agent will use.
=> Setting from NR backend should override setting from MAX_EVENT_SAMPLES_STORED and MAX_TRANSACTION_SAMPLES_STORED env var

src/Agent/CHANGELOG.md, src/Agent/NewRelic.Api.Agent/ISpan.cs, src/Agent/NewRelic.Api.Agent/NoOpSpan.cs, src/Agent/NewRelic.Api.Agent/Span.cs, src/Agent/NewRelic/Agent/Core/Api/SpanBridgeApi.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/ApiSupportabilityMetricCounters.cs, src/Agent/NewRelic/Agent/Core/Segments/CustomSegmentData.cs, src/Agent/NewRelic/Agent/Core/Segments/MethodSegmentData.cs, src/Agent/NewRelic/Agent/Core/Segments/NoOpSegment.cs, src/Agent/NewRelic/Agent/Core/Segments/Segment.cs, src/Agent/NewRelic/Agent/Core/Segments/SimpleSegmentData.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ISegment.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ISpan.cs, tests/Agent/IntegrationTests/Applications/ConsoleInstrumentationLoaderCore/ConsoleInstrumentationLoaderCore.csproj, tests/Agent/IntegrationTests/IntegrationTestHelpers/IntegrationTestHelpers.csproj, tests/Agent/IntegrationTests/IntegrationTests.sln, tests/Agent/IntegrationTests/IntegrationTests/Api/CustomSpanNameApiTests.cs, tests/Agent/IntegrationTests/Shared/Shared.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/AttributeInstrumentation.cs, tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationCore/ConsoleMultiFunctionApplicationCore.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests.sln
Closes #1023 
Adds a `SetName()` method to ISpan in the agent API. Using this new API will change the Segment/Span/Metric names. As it wasn't obvious how to apply this over-ride to metrics for all segment types, metric names are only modified for CustomSegments, MethodSegments, and SimpleSegments (these are the segment types used by some built in instrumentation, custom instrumentation XML, and agent API custom instrumentation). 
Segment/Span names should be updated for all instrumented methods, but metric names will not be updated for DatastoreSegments, MessageBrokerSegments, or ExternalSegments (using to the agent API to even attempt to mutate these segment types would take great effort).
A new supportability metric is recorded/reported for this API usage: …
=> Add new API to set a custom span name

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Sql/Instrumentation.xml, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/BasicMvcApplication.csproj, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/Controllers/MicrosoftDataSqlClientController.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/EnterpriseLibraryMsSqlTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlAsyncLegacyAspPipelineTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlAsyncParameterizedQueryTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureUsingOdbcDriverTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureUsingOleDbDriverTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlWithParameterizedQueryTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/MicrosoftDataSqlClientFixtureCore.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/MicrosoftDataSqlClientFixtureCoreFramework.cs
Our existing Microsoft.Data.SqlClient instrumentation only had test coverage for .NET Core. This allowed a bug to slip under the radar where not all forms of `ExecuteReader` and `ExecuteReaderAsync` were properly profiled in .NET Framework. The existing instrumentation points worked fine for .NET Core, but the Microsoft Implementation for .NET Framework and .NET Core differ. A  new internal form of `ExecuteReaderAsync`, and a new form of `ExecuteReader` are now included in the instrumentation XML for Microsoft.Data.SqlClient. The newly added integration tests will break if the new instrumentation entries are removed, so there is high confidence that this resolves the issues with missing instrumentation reported by customers.
Closes #620.
=> Add missing Microsoft.Data.SqlClient instrumentation for .NET Framework

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/BrowserMonitoring/BrowserMonitoringWriter.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/JavaScriptAgent.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Models/ConnectResponseData.cs, tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/BrowserAgentAutoInjection.cs, tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/DisableBrowserAutoInjectionWhenGetBrowserTimingHeaderIsCalled.cs, tests/Agent/UnitTests/Core.UnitTest/BrowserMonitoring/BrowserMonitoringWriter.cs
We identified a defect in the .Net agent with v1219 of the Browser agent. The newest browser agent script includes polyfills to help support some of the older browsers in use. As part of this the javascript includes `$1` and the .Net agent replaces that with the matched `<meta http-equiv="X-UA-Compatible" content="IE=edge" />` tag found. This is because of the use of the `Regex.Replace` method. 
This was reported through a customer case during the rollout of v1219 of the browser agent before the release was rolled back.
=> Fix browser monitoring writer

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
This PR adds new environment variables to control SendDataOnExit functionality:
- `NEW_RELIC_SEND_DATA_ON_EXIT`: (boolean) enables/disables send data on exit
- `NEW_RELIC_SEND_DATA_ON_EXIT_THRESHOLD_MS`: (uint) sets the minimum number of MS that the application must have been running before data will be sent on exit (when enabled).
Includes unit tests.
=> Add environment variables for SendDataOnExit functionality

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NLogLogging/NLogWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/LocalDecorationTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/Log4NetLoggingAdapter.cs
Fixes a bug in NLog instrumentation where the original message was not being included in output if the local decoration option was enabled.
Integration tests are updated to verify the inclusion of the original message in the output for local decoration scenarios.
This PR is in draft until I verify end-to-end functionality.
=> Include original message in NLog output when local decoration is enabled

src/Agent/NewRelic/Agent/Core/Aggregators/AbstractAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/LogEventAggregator.cs, src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionManager.cs, src/Agent/NewRelic/Agent/Core/Events/StopHarvestEvent.cs, tests/Agent/UnitTests/CompositeTests/HarvestDisableWhileReconnectingTest.cs
In an edge case where a user sets to disable event collection for specific event types from the New Relic APM UI and the agent is issued a reconnect, the agent still sends up the disabled events during the agent reconnecting period.
During the agent reconnecting window, all of the configuration settings get reset to the default values while waiting for the configuration setting backend negotiation to complete. This causes some events still being collected and sent up during this time period regardless some events collection were explicitly disabled.
This PR proposes a fix where the agent stops any scheduled `Harvest` during the agent's reconnecting process.
=> Stop any harvests while reconnecting

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Core/DataTransport/DataTransportService.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/AgentManager.cs
During application shutdown, if the SendDataOnExit configuration option is enabled, and the minimum timespan for it to trigger has elapsed, the agent attempts to trigger one final harvest cycle before shutting down as well. This works well, but there is an edge case where the collector may return an HTTP response code indicating that the agent should reconnect during these final Harvest cycles. 
The current behavior of the agent is to attempt to reconnect even though the application is already shutting down. This behavior can result in unexpected exceptions which can cause an ungraceful application shutdown. 
This PR adds a new global boolean to allow application code to behave differently in the event that the application is shutting down. The only application logic that is currently …
=> Fix application crash when trying to reconnect during application shutdown

tests/Agent/IntegrationTests/generateTestSubclasses.ps1
I figure people might be tired of creating all the test subclasses for ConsoleMF tests, so I made a script to do it for us.  I've placed it in `tests/Agent/IntegrationTests` and you can run it like (using RabbitMqTests as an example):
`./generateTestSubclasses.ps1 -BaseClassName RabbitMqTestsBase`
and you'll get output you can copy/paste into the test file.
Of course, this would be much cooler if we made it a Visual Studio extension so it could just happen in VS without having to open up a Powershell console, run a command with the correct input parameter, copy/paste text, etc.  But I figured I could get this done in a few minutes, I don't know how hard writing a VS extension is.  Going for "good enough" first.
=> Add utility script for generating ConsoleMF test classes

tests/Agent/IntegrationTests/Shared/MongoDbConfiguration.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDBDriverAsyncCursorTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDBDriverCollectionTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDBDriverDatabaseTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDBDriverIndexManagerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDBDriverQueryProviderTests.cs, tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml, tests/Agent/IntegrationTests/UnboundedServices/mongodb36/Dockerfile, tests/Agent/IntegrationTests/UnboundedServices/mongodb60/Dockerfile
Update the version of mongodb server used in our integration tests (for MongoDB.Driver >2.3) from 3.6 to 6.0.  Tested locally and the tests all pass.  There won't be any effect in CI tests until the CI service host is updated.
=> Update mongo server version from 3.6 to 6.0

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/SerilogLoggingAdapter.cs, tests/Agent/MultiverseTesting/ConsoleScanner/config.yml
- Updates Serilog integration tests to test version 1.5.14 with net462 since we do have instrumentation for that version.
- Version 1.5.14 Console sink does not accept formatters so no Json testing with that version (we didn't test local json decorating in net462 originally)
- In SerilogLoggingAdapter changed the Logger type to ILogger to support 1.5.14 since that version has the Logger type in a different namespace.  ILogger is in the same location with mostly the same interface so works without any other changes.
- Updates MVS with Serilog covering the major versions
=> Adds tests for Serilog 1.5.14 and updates MVS with Serilog

tests/Agent/UnitTests/Core.UnitTest/BrowserMonitoring/BrowserMonitoringWriter.cs
Adds a unit test to the Browser Agent Injection test suite that should catch any future regressions in the module. This includes `$1`, `$&`, and a bunch of other expressions with special meaning in C#.
=> Add Browser Agent injection unit test for .NET special characters

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MsSql/SystemDataSqlClientExerciser.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlQueryParamAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlQueryParamTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureUsingOdbcDriverTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureUsingOleDbDriverTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlTests.cs
Add integration tests for `System.Data.SqlClient` in .NET Core/5+.
Testing driver package versions 4.4.0 through 4.8.4.  4.4.0 is the oldest version where our explain plan feature works.
I also renamed other tests that already existed to help normalize the test class names according to the following pattern:
TestFileName_ExerciserName_{Options}_TargetFrameworkMoniker
I added some comments to explain why we don't have ODBC or OleDb tests for System.Data.SqlClient (our instrumentation currently doesn't support .NET Core).
=> System.Data.SqlClient (.NET Core/5+) tests

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlQueryParamAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlQueryParamTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlTests.cs
Quick follow-on PR to update System.Data.SqlClient tests to account for the merge of the .NET 7 branch.  I should have merged main into my branch before merging my last PR, but it didn't say anything about merge conflicts.  Unfortunately, I don't think the current state of `main` will build without these changes.
=> Update MsSql System.Data.SqlClient tests for .NET 7

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Update Custom Event sample size default value from 10,000 to 30,000.
=> Update Custom Event sample size default value.

tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/BasicMvcApplicationTestFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RestSharp/RestSharpClientInstrumentationAsyncAwaitCAT.cs, tests/Agent/IntegrationTests/IntegrationTests/RestSharp/RestSharpClientInstrumentationCAT.cs, tests/Agent/IntegrationTests/IntegrationTests/RestSharp/RestSharpClientInstrumentationDistributedTracing.cs, tests/Agent/IntegrationTests/IntegrationTests/RestSharp/RestSharpClientInstrumentationTaskResultCAT.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Owin/Startups.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RestSharp/RestAPIController.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RestSharp/RestSharpExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RestSharp/RestSharpService.cs
- Migrates almost all RestSharp tests to use ConsoleMF app.
- Uses the existing OwinService to build a host service for the controllers and added a new Startup to support the controllers.
- Only DT specfic tests, which are not migrated to ConsoleMF, need the old BasicMvcApplication tests so those are still present
- The unused methods in the BasicMvcApplicationTestApplicationFixture for RestSharp were removed.
- Expands our test coverage to the versions of RestSharp we state that we support
- 105.2.3
- 106.0.0
- 106.6.10
- No changes were made to the instrumentation
=> Updates RestSharp testing to use ConsoleMF app and expands tested versions

src/AwsLambda/AwsLambdaOpenTracer/LambdaTracer.cs, src/AwsLambda/CHANGELOG.md
The previous exception type, ArgumentNullException, was incorrect.  The new type, ArgumentException, is better fit.
=> Updates the LambdaTracer.Extract exception type

tests/AwsLambda/UnitTests/AwsLambdaOpenTracerTests/LambdaTracerTests.cs
Updates lambda test assertions to match new exception type introduced by https://github.com/newrelic/newrelic-dotnet-agent/pull/1287
=> Fix lambda test assertions

build/ArtifactBuilder/AgentComponents.cs, build/ArtifactBuilder/ArtifactBuilder.csproj, build/ArtifactBuilder/Artifacts/NugetAgent.cs, build/ArtifactBuilder/CoreAgentComponents.cs
Adds the linux-arm64 profiler and grpc libraries to the Agent Nuget package. This will allow customers to deploy to ARM using only the nuget package.
The AgentComponents class likely needs to be refactored to be specific to Linux/Windows targets in the future, but I worked around that for now.
=> Add arm64 profiler to nuget package

src/Agent/NewRelic/Agent/Core/JsonConverters/LogEventWireModelCollectionJsonConverter.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LogEventWireModelCollectionJsonConverterTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelCollectionTests.cs
Serialize ContextData from LogEventWireModel.
=> Serialize ContextData from LogEventWireModel

src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/IAgentExperimental.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Log4NetLogging/Log4netWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/MicrosoftLoggingWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NLogLogging/NLogWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/SerilogLogging/NewRelicSerilogSink.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/AgentWrapperApiTests.cs
Implements https://issues.newrelic.com/browse/NEWRELIC-4758.  Includes unit tests to test context data filtration based on include and exclude lists in config (caveat: wildcard filtering support not implemented yet, will be implemented in a follow-on PR).
=> Update RecordLogMessage() API to take getter function for context data

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/SerilogLogging/NewRelicSerilogSink.cs
Add custom attribute support for Serilog logging. Basic object types are left as-is; complex object types are converted to a string.
Because logging integration tests are shared among loggers, that will be done in a separate PR.
Changelog will be updated when all functionality has been merged.
=> Add custom attribute support for Serilog logging

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Attributes/AttributeValueCollection.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/TransactionMetadata.cs, tests/Agent/UnitTests/Core.UnitTest/BrowserMonitoring/BrowserMonitoringPrereqCheckerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/ErrorEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/ErrorTraceMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/SqlTraceMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TestTransactions.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTraceMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/SqlTraceWireModelTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/Builders/TransactionMetadataTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/TransactionFinalizerTests.cs
When troubleshooting attribute limit errors in busy applications, it is difficult to know which transaction the errors are coming from.  This PR updates those log messages to include the transaction guid at finest like most other log messages,
- Attribute limit error messages include the transaction guid
- Updates AttributeValueCollection.cs with a new constructor that takes and stores the transaction guid.  It leaves the other constructors alone.
- Updates AttributeValueCollection.ValidateCollectionLimits to use a helper method to decide when the new finest logs format should be used
- Updates TransactionMetadata to have an explicit constructor that takes in and stores the transaction guid while also instantiating the AttributeValueCollection using its new constructor.  
- Updates …
=> Updates attribute limit error log messages with transaction guid

.github/workflows/nuget_slack_notifications.yml, .github/workflows/scripts/nugetSlackNotifications/Program.cs, .github/workflows/scripts/nugetSlackNotifications/newrelic.config, .github/workflows/scripts/nugetSlackNotifications/nugetSlackNotifications.csproj
Improvements to our tool that checks for new releases of our core instrumented libraries:
1. Add console logging so you can see what the tool is doing.
2. Changed the name of the env var for the Slack webhook from "webhook" to "DOTTY_WEBHOOK".
3. Added env var "DOTTY_DAYS_TO_SEARCH" to allow setting the number of days of NuGet history to search for package updates.  Defaults to the previously hardcoded value of 1.
4. Added env var "DOTTY_TEST_MODE" to allow running the tool without sending the Slack notification.
5. Modified the action workflow to allow setting these env vars when run manually.
6. Added monitoring the tool with the .NET agent:
1. Added a newrelic.config with the necessary sendDataOnExit config that gets copied to the output dir.
2. Modified the action workflow to install …
=> Dotty improvements

src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/IAgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/MetricNames.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/MetricsAndForwardingTests.cs
- Adds new `Supportability/Logging/Forwarding/DotNET/{expectedFrameworkName}/enabled` to occur after log forwarding configuration has been confirmed enabled.  This allows metric to account for both the logging framework being instrumented AND log forwarding being enabled.
- Updates integrations tests to account for the new metric
=> Move supportability metric create for enabled logging framework to location

src/Agent/CHANGELOG.md
Adds the following notice to the release notes for versions 9.7.0 to 10.1.0 
```
**Notice:** If using Microsoft.Extensions.Logging as your logging framework of choice, please use .NET agent version 10.1.0 or newer.  We encourage you to adopt the newer version due to bug [#1230](https://github.com/newrelic/newrelic-dotnet-agent/issues/1230), which we fixed in [#1237](https://github.com/newrelic/newrelic-dotnet-agent/pull/1237), that was resolved in .NET agent version 10.1.0.
```
Please don't merge after approval, we are timing the push.
=> Updates release notes for versions 9.7.0 to 10.1.0 with a notice about MEL log levels

tests/Agent/IntegrationTests/Applications/WebApiAsyncApplication/Web.config, tests/Agent/IntegrationTests/Applications/WebApiAsyncApplication/WebApiAsyncApplication.csproj
This PR removes unneeded package references from the `WebApiAsyncApplication` test app used in our integration tests.  These references are left over from when the app was initially created from a template, but the test app code doesn't use them.
This was brought to our attention by this community-submitted PR that wanted to upgrade one of the package references to patch a CVE: https://github.com/newrelic/newrelic-dotnet-agent/pull/1327  However, it's better long term to just not have the references at all.
=> Remove unneeded package references from test app

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
MySqlConnector recently released version 2.2.4. This PR updates our unbounded integration tests to cover this version.
=> Update MySqlConnector test coverage

build/Packaging/NugetAgent/NewRelic.Agent.nuspec, build/Packaging/NugetAgentApi/NewRelic.Agent.Api.nuspec, build/Packaging/NugetAzureCloudServices/NewRelicWindowsAzure.nuspec, src/Agent/CHANGELOG.md
Fixes #1346 
PR #1321 broke the following NuGet packages that we deployed in release 10.5.0:
NewRelic.Agent
NewRelic.Agent.Api
NewRelicWindowsAzure
These packages' `.nuspec` files previously did not have a `<files>...</files>` section.  When we added one to include the new icon file, we did not realize that if you have a files section, it disables automatic inclusion of content - everything you want to be in the package has to be in the `<files>...</files>` section.  This PR corrects that.
The team swarmed on these changes, including building the packages locally and comparing their content to the previous good release (10.4.0) so the PR review process is primary going to be testing the built artifacts from this PR's CI to make sure they do what we want them to do (since we currently …
=> Fix NuGet package missing content issues

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RestSharp/RestSharp107andBeyondExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RestSharp/RestSharpExerciser.cs
This PR adds integration test coverage for the latest released 107 and 108 versions of RestSharp. As we only have 4 targets to test RestSharp in .NET Framework, I chose to keep coverage for the latest released versions of 105, 106, 107, and 108. This will allow us to confidently tell customers who experience issues that if they upgrade to the latest version of whatever major release they are using, things will work.
Interestingly, the assertions in the RestSharp tests can't tell a difference between external segments generated by RestSharp, HttpWebRequest, or HttpClient instrumentation. This probably means we did a …
=> Add integration test coverage for RestSharp v107+

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Sql/Instrumentation.xml, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/PostgresSql/PostgresSqlExerciser.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresIteratorAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresIteratorTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj, tests/Agent/IntegrationTests/UnboundedServices/postgres/Dockerfile
Updates instrumentation configuration and unbounded integration tests to support all current versions of Postgres for .NET (`npgsql`) NuGet v4.0.0 through 7.0.1
=> Adds support for Postgres v4.1 through v7

.github/workflows/all_solutions.yml, src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionManager.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs, tests/Agent/IntegrationTests/IntegrationTests/DataTransmission/ConnectSetApplicationNameTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/ApiCalls.cs
Now, there is a bool that can be set if a runtime update has occurred, meaning the names have changed.  If this occurs during a Connect, a restart is scheduled.  I used ScheduleRestart so that we will follow the backoff pattern and hopefully not spam connect attempts of there is an issue.  This also lets the connect process complete before we start another.  I didn't think we needed a flag for "connecting" since all the work is done in the Connect method.
The code isn't really unit testable.  I tried to see if I could capture some part of the reconnect happening, but the methods just aren't available.
Adds a new integration test that ensures they process is working.  I only added for the oldest (net462, net6) and latest supported frameworks since framework version shouldn't affect …
=> Fix a race condition when using SetApplicationName

build/ArtifactBuilder/CoreAgentComponents.cs, build/build_functions.ps1, licenses/THIRD_PARTY_NOTICES.txt, src/Agent/MsiInstaller/Installer/Product.wxs, src/Agent/NewRelic/Agent/Core/Core.csproj
We were including the grpc native dlls in the core agent on windows which was not needed. We were also defining the TRACE constant, which doesn't seem right for production code. I also upgraded the grpc libraries. While searching the entire codebase I also noticed a missing license for grpc/grpc.core. Interestingly, we had a license block for grpc-dotnet, but we are only just starting to use it in this feature branch.
=> Remove gRPC binaries from core agent, upgrade gRPC packages

src/Agent/NewRelic/Agent/Core/Core.csproj
When Infinite Tracing is used in a .NET Core application that does not include Microsoft.Extensions.Logging.Abstractions, errors are encountered and 8t doesn't work. This change includes the abstractions assembly in the core agent to avoid this issue.
I tested that this works in a console app that does not include MEL, as well as asp.net core web app that does, as well as a console app that does. I did not see any errors, infinite tracing works, and MEL log forwarding works.
=> ILRepack Microsoft.Extensions.Logging.Abstractions for grpc-dotnet

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs, src/Agent/NewRelic/Agent/Core/DataTransport/SpanStreamingService.cs
* Updates the ResponseStreamWrapper exception message to detect when a stream is automatically cancelled due to inactivity and use a more descriptive lg message.  The updated log message explains that this happened and that a new stream will be created when one is needed.
* Adds the consumer ID to the log messages in more places
* Updates the usage of "gRPC" to match the format.
=> Update grpc stream cancelled due to in-activity log message

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/MicrosoftLoggingWrapper.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/Common.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/ContextDataNotSupportedTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/DummyMELAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/LoggingTester.cs
* Added error handling in `MicrosoftLoggingWrapper.GetContextData()` for cases where a logger implements `MEL.ILogger` but doesn't also expose an `IExternalScopeProvider` property named `ScopeProvider`. If that happens, we log a message and disable further attempts at collecting context data.
* Added integration tests and a dummy implementation of `MEL.ILogger` to verify the fix is working as expected.
=> Added error handling for MEL.ILogger related to context data

src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs, src/Agent/NewRelic/Agent/Core/DataTransport/SpanStreamingService.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
gRPC-dotnet does not support proxy configuration using the `grpc_proxy` environment variable that gRPC.Core supports. Both gRPC libraries support the `https_proxy` environment variable. In this PR we add a warning to the agent log file when Infinite Tracing is enabled and the `grpc_proxy` environment variable is detected (and the `https_proxy` is not detected). This log message can be used to help with troubleshooting Infinite Tracing connection issues when a proxy is involved.
- ~~[ ] Performance testing completed with satisfactory results (if required)~~ Not required for a one-time warning
- ~~[ ] [Agent …
=> Add warning when grpc_proxy is detected

src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs, src/Agent/NewRelic/Agent/Core/DataTransport/GrpcWrapper.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
The grpc-dotnet based implementation of our grpcWrapper does not provide any actual way to check for stream connectivity until there is data to send. We were previously interpreting `internal` status responses to mean that our stream consumer was been gracefully closed by the server, but this is not always the case as we have seen. 
This PR prevents DDOS behavior by waiting for 15 seconds before recreating streams when we identify that they have become invalid with the `internal` status code.
=> Delay retries when 'internal' gRPC errors are encountered

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NLogLogging/NLogLogging.csproj, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NLogLogging/NLogWrapper.cs
Changes how the NLog instrumentation updates the log message for local log decoration.
* Instead of examining and using LogEventInfo.Message, the new instrumentation uses LogEventInfo.FormattedMessage and its backing field, (v4.5+ _formattedMessage)|(Pre v4.5 formattedMessage).  This property has additional logic that Message does not and appears to be the source for the actual log message we see.  Calling FormattedMessage causes NLog to build the message and store it in the backing field.  
* Using the visibility bypasser, we get the setter for the backing field and use it to set the field to itself with our decoration token.  The Action is stored staticly, same as with other bypasser setups.
* Since we can only get the major assembly version from NLog assembly we cannot use minVersion …
=> Update NLog to improve local log decoration coverage

src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/TransactionService.cs
Partial fix for issue with Transactions created in an async context. See [#1366](https://github.com/newrelic/newrelic-dotnet-agent/issues/1366)
I believe there is still an general issue with Transactions created in an async context; this is just one of the places where it can happen.
Because this is an async timing issue, I wasn't able to come up with a consistent unit or integration test to capture it, unfortunately.
=> Partial fix for Segment out-of-range error

src/Agent/NewRelic.Api.Agent/NewRelic.cs, src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs, src/Agent/NewRelic/Agent/Core/Api/AgentApiImplementation.cs, src/Agent/NewRelic/Agent/Core/Configuration/ConfigurationService.cs, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/RunTimeConfiguration.cs, src/Agent/NewRelic/Agent/Core/Events/ErrorGroupCallbackUpdateEvent.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/IAgentApi.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/InternalApi.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/UnitTests/CompositeTests/AgentApiTests.cs, tests/Agent/UnitTests/CompositeTests/ApiSupportabilityMetricTests.cs, tests/Agent/UnitTests/Core.UnitTest/Api/AgentApiImplementationTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ExhaustiveTestConfiguration.cs
Updates the code referenced in #1400 
- Renames the API for ErrorFingerprintingCallback to SetErrorGroupCallback.
- Updates the API SetErrorGroupCallback implementation to behave similarly to the SetApplicationName API method
- Adds a documentation summary to the SetErrorGroupCallback method
- ~~[ ] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated~~ Will be updated in a separate PR
=> Update error group callback api implementation

src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, src/Agent/NewRelic/Agent/Core/Errors/ErrorData.cs, src/Agent/NewRelic/Agent/Core/Errors/ErrorService.cs, src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/ErrorEventMaker.cs, src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/ErrorTraceMaker.cs, tests/Agent/UnitTests/Core.UnitTest/Errors/ErrorServiceTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/ErrorEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/ErrorTraceMakerTests.cs
Updates the error group functionality mentioned in #1401. 
- Renames groupFingerprint to errorGroup
- Update error group attribute to not get generated if the error group is null, empty string, or just whitespace
- Gets the error group callback from configuration instead of the agent class
- ~~[ ] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated~~ to be updated in a separate PR
=> Use configured errorgroupcallback

src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/ErrorEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/ErrorTraceMakerTests.cs
Follow up to https://github.com/newrelic/newrelic-dotnet-agent/pull/1418#issuecomment-1453912439 that renames `error_group` to `error.group.name`.
=> Rename error_group to error.group.name

.github/workflows/deploy_agent.yml
The s3 index currently runs at the same time/before the download site deploy. This should make the index job wait until deploy has completed
=> Run S3 index after deploy

tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteWebApplication.cs, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/BasicMvcApplication.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/EnterpriseLibraryMsSqlTests.cs
This reduces the number of build warnings seen when building the unbounded integration tests solution by removing unnecessary package references from the BasicMvcApplication project.
This PR also fixes a problem I saw where some HostedWebCore-based tests were failing on my local machine because:
1. I had the `NEWRELIC_LOG_LEVEL` env var set globally on my machine with a value of `info`
2. The test harness wasn't removing that env var before starting the test app
3. None of the test assertions could pass because the agent log data they depend on are logged at `debug` level
I made the list of env vars removed before launching a HostedWebCore test app (i.e. `RemoteWebApplication`) look more like the list of env vars removed before launching a console test app (`RemoteService`).
=> Reduce build warnings in the unbounded integration tests solution

.github/workflows/release-please.yml
I'm in the process of configuring release-please, but I need the workflow to exist on `main` in order to be able to run it in my feature branch. This shouldn't do anything to `main` in its current state.
=> Adding workflow to test release automation

tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml
Adds elastic search and kibana to the UnboundedServices `docker-compose.yml`. All security and SSL/TLS configurations are disabled in elastic search to work around the auto-generated certificate file issue. Shouldn't be a problem for our environment. 
Tested that a test app can send data to Elastic Search via http://localhost:9200 and that I can view the data using Kibana (http://localhost:5601).
=> Added elastic search and kibana to unbounded services

tests/Agent/IntegrationTests/Shared/ElasticSearchConfiguration.cs, tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml
* Modified docker-compose to configure ElasticSearch and Kibana to require authentication. 
* Added a configuration helper class to get to the secrets for ElasticSearch from integration tests (Note that the helper class is presently untested, but should work correctly once the appropriate local secrets are in place.)
=> Enabled authentication for ElasticSearch and Kibana

.github/workflows/scorecard.yml
Adds the OSSF Scorecard workflow as recommended by the NR Security team.  Workflow file was entirely generated by following the instructions here https://github.com/marketplace/actions/ossf-scorecard-action
Skipping the use of a Personal Access Token for now, will add it later if it becomes necessary. According to the docs, the only check that requires the PAT is the "Branch-Protection" check
=> ci: add OSSF Scorecard workflow

src/Agent/CHANGELOG.md
Remove `[Unreleased]` section from changelog.md since it's no longer needed with Release Please automation
=> chore: remove [Unreleased] section from changelog

.github/workflows/all_solutions.yml, .github/workflows/awslambda_release.yml, .github/workflows/deploy_agent.yml, .github/workflows/repolinter.yml, .github/workflows/run_integration_tests.yml, .github/workflows/set_community_label.yml, .github/workflows/siteextension_release.yml
* Updates several workflows to apply top-level permissions and per-action permissions, as recommended by Step Security. (Not sure how I missed this the other day...)
* Removes usage of the deprecated `rokroskar/workflow-run-cleanup-action`, instead making use of the built-in `concurrency:` element.
=> ci: update top-level permissions and remove deprecated action

src/Agent/NewRelic/Agent/Core/Segments/DatastoreSegmentData.cs, src/Agent/NewRelic/Agent/Core/Transactions/NoOpTransaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/IDatastoreSegmentData.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/ITransactionExperimental.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Elasticsearch/RequestWrapper.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Elasticsearch/ElasticsearchAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Elasticsearch/ElasticsearchSyncTests.cs
* Adds the necessary interface and methods to support being able to update the ConnectionInfo (which contains the URI) of a `DatastoreSegment` after initial creation.
* Updates integration tests for Elasticsearch to check for the `peer.address` attribute in the datastore segment span, which is what the URI is used to populate
* Comment cleanup in the wrapper
=> Set URI after datastore segment creation

src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs, src/Agent/NewRelic/Agent/Core/DataTransport/HttpCollectorWire.cs, src/NewRelic.Core/Strings.cs, tests/Agent/UnitTests/Core.UnitTest/Utilities/StringsTest.cs
There were a couple of cases where the agent would log your entire New Relic license key value to a local log file:
- When audit logging is enabled
- When Infinite Tracing is enabled, and the agent's log level is set to FINEST
This PR fixes this by only logging the first 8 characters of the key for troubleshooting purposes, and replacing the rest with asterisks.
=> chore: Obfuscate license keys in logs.

.github/workflows/stale_issue.yml, .github/workflows/stale_pr.yml
After bumping the `actions/stale` action by several major versions, issues were being marked as stand and getting closed when running the `stale_pr.yml` workflow. This was due to a missing configuration that effectively disables checking for stale issues. 
Updated both `stale_pr.yml` and `stale_issue.yml` to address this problem.
=> ci: fix errors in stale_pr and stale_issue workflows

.github/workflows/all_solutions.yml, .github/workflows/assignproj.yml, .github/workflows/deploy_agent.yml, .github/workflows/markdowncheck.yml, .github/workflows/nuget_slack_notifications.yml, .github/workflows/release-please.yml, .github/workflows/repolinter.yml, .github/workflows/run_unit_tests.yml, .github/workflows/scorecard.yml, .github/workflows/set_community_label.yml, .github/workflows/stale_issue.yml, .github/workflows/stale_pr.yml
Applies the recommended configuration for the `harden-runner` action to most of our workflows. Note that some workflows haven't been executed yet, so there is no recommended configuration available at this time.
=> ci: apply harden-runner egress policy config

.github/workflows/all_solutions.yml, .github/workflows/assignproj.yml, .github/workflows/build_profiler.yml, .github/workflows/deploy_agent.yml, .github/workflows/deploy_awslambda.yml, .github/workflows/deploy_siteextension.yml, .github/workflows/get_release_checksums.yml, .github/workflows/multiverse_run.yml, .github/workflows/release-please.yml, .github/workflows/repolinter.yml, .github/workflows/run_integration_tests.yml, .github/workflows/scorecard.yml, .github/workflows/set_community_label.yml, .github/workflows/stale_issue.yml, .github/workflows/stale_pr.yml
Using `egress-policy: block` in the `harden-runner` action has proven unreliable (the recommended allow-list is incomplete for some jobs), so I'm reverting all usages to `egress-policy: audit` - that will allow all outbound traffic but will also generate artifacts that will let us see the egress traffic from a workflow, in case there is ever a question or issue.
=> ci: change egress-policy to audit for all harden-runner usages

src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/Environment.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/RuntimeEnvironmentInfo.cs
Moved all calls to `RuntimeInformation.IsOsPlatform()` within a `#if NETSTANDARD2_0` block.
=> fix: IsOsPlatform() fails on older .NET Framework Versions

.github/workflows/all_solutions.yml, .github/workflows/awslambda_release.yml, .github/workflows/deploy_agent.yml, .github/workflows/deploy_awslambda.yml, .github/workflows/deploy_siteextension.yml, .github/workflows/get_release_checksums.yml, .github/workflows/markdowncheck.yml, .github/workflows/multiverse_run.yml, .github/workflows/nuget_slack_notifications.yml, .github/workflows/release-please.yml, .github/workflows/repolinter.yml, .github/workflows/run_integration_tests.yml, .github/workflows/run_unit_tests.yml, .github/workflows/scorecard.yml, .github/workflows/siteextension_release.yml
chore(deps): bump github/codeql-action from 2.2.11 to 2.2.12
chore(deps): bump google-github-actions/release-please-action from 3.7.7 to 3.7.8
chore(deps): bump codecov/codecov-action from 3.1.1 to 3.1.2
chore(deps): bump dawidd6/action-download-artifact from 2.26.1 to 2.27.0
chore(deps): bump actions/checkout from 3.5.0 to 3.5.2 and make version usage consistent across all workflows
=> summary: Bumped action versions in multiple workflows

.github/workflows/all_solutions.yml, .github/workflows/run_integration_tests.yml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Elasticsearch/Elasticsearch.csproj, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Elasticsearch/RequestWrapper.cs, src/NewRelic.Core/NewRelic.SystemExtensions/StringExtensions.cs, tests/NewRelic.Core.Tests/NewRelic.SystemExtensions/StringExtensions.cs
Elasticsearch.net does not report the request parameters in a nice object like the other libraries, so we need to parse the path to find the actual operation performed. This should be accurate for all Index, Document, and Search requests. Other APIs may not match up exactly because there are a lot of special cases (abbreviations, etc.), but it should be pretty close.
=> Report Elasticsearch.net operations more accurately

src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/AgentManager.cs
Moves logging of TLS configuration from early during initialization to just before the PreConnect call. This should ensure that we log the "current" TLS configuration at the moment we are connecting, which may be different from what we found during startup (i.e., client app can change the configuration at any time). 
Tested by changing the TLS configuration after application startup, then making a change to newRelic.config, which forced a re-connect. Verified that the TLS config logged on re-connect matched the changed value.
=> feat: Move TLS config logging closer to connect. (#1558)

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchElasticClient.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchNestClient.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchNetClient.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Elasticsearch/ElasticsearchTests.cs
This PR adds assertions to check the success of the client API calls being made to the Elasticsearch server.  A few details:
- In order to get the latest 7.x clients to communicate successfully with the 8.x server we're using it's necessary to set the following environment variable to true: `ELASTIC_CLIENT_APIVERSIONING`
- Unfortunately this doesn't work for older 7.x clients, so this PR reverts the previous change to start testing back to 7.0.0
This PR also changes how the async calls were being invoked, letting the return task bubble up to the `DynamicMethodExecutor` where the task is waited on.  This allows the tests to pass reliably without needing to add any unnecessary delay.
=> Add client call success validation to Elasticsearch integration tests

src/Agent/NewRelic/Profiler/linux/Dockerfile
Uses a multistage docker file to clone the core clr repo to workaround expired certificates that prevent cloning the repo within the older ubuntu image.
- ~~[ ] Unit tests, Integration tests, and Unbounded tests completed~~
- ~~[ ] Performance testing completed with satisfactory results (if required)~~
=> ci: Use multistage docker to clone clr repo for linux build

docs/integration-tests.md
The integration tests doc contained a url that was purposely removed and there is no planned replacement for it. For now we can just remove the link from our doc which should allow our markdown url checker to start passing again.
- ~~[ ] Unit tests, Integration tests, and Unbounded tests completed~~
- ~~[ ] Performance testing completed with satisfactory results (if required)~~
=> docs: Remove invalid CSP link

build/ArtifactBuilder/Artifacts/MsiInstaller.cs, src/Agent/MsiInstaller/Installer/Product.wxs
The MSI installer was not configured to install the CosmosDb instrumentation files. This PR adds the missing files to the MSI installer, and restores the tests that attempt to detect if instrumentation is missing from the MSI installer configuration files.
The ArtifactBuilder was run locally to validate that the configuration tests are working. These tests detected that the MSI installer did not include the CosmosDb instrumentation.
- ~~[ ] Unit tests, Integration tests, and Unbounded tests completed~~
- ~~[ ] Performance testing completed with satisfactory results (if required)~~
=> fix: Add missing instrumentation to MSI installer

.github/workflows/deploy_agent.yml
Attempted to deploy the agent and got an error saying that the `index-download-site` job in the agent deploy workflow needed the `packages:read` permission.  This PR adds that permission.
=> Add read packages permissions to agent deploy job

build/ArtifactBuilder/Artifacts/MsiInstaller.cs
Updates the ArtifactBuilder for the Msi installer so that it will grab the correct version of the profiler (the one that matches that locally built agent) so that it compare the correct agent components. This PR also includes another case where we can use Path.Join to build out the file paths.
=> chore: Look for specific msi version and file path cleanup.

tests/UnitTests.runsettings
Updated exclusion list for unit test code coverage. Also verified that all files marked in the Code Coverage Analysis spreadsheet as "exclude" are, indeed, excluded. 
We gained a whopping [0.6% increase in code coverage](https://app.codecov.io/github/newrelic/newrelic-dotnet-agent/commit/d230125bfc11ffbdb13b9a96188822b6795cdeb6/tree/src/NewRelic.Core) as a result!
=> test: Update code coverage exclusion list

tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTests/AgentMetrics/DataUsageSupportabilityMetricsTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Api/CustomSpanNameApiTests.cs, tests/Agent/IntegrationTests/IntegrationTests/AppDomainCaching/AppDomainCachingTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CustomInstrumentation/ForceNewTransactionTests.cs, tests/Agent/IntegrationTests/IntegrationTests/DataTransmission/ConnectSetApplicationNameTests.cs, tests/Agent/IntegrationTests/IntegrationTests/InfiniteTracing/InfiniteTracingFlakyTests.cs, tests/Agent/IntegrationTests/IntegrationTests/InfiniteTracing/InfiniteTracingTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/ConsoleDynamicMethodFixture.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/NServiceBus/NServiceBusDriver.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbAsyncCmdHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbAsyncEventHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbCmdHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbEventHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbPublishTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbSendTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbThrowingHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus5/NServiceBus5ReceiveTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus5/NServiceBus5SendTests.cs
In order to help reduce the overall execution time of our CI, as well as be more deterministic, this PR eliminates the use of `RootCommands DelaySeconds` from a bunch of ConsoleMF-based integration tests.  The primary way this has been accomplished is to have the test harness wait for certain agent log lines to appear instead of just sleeping for an arbitrary amount of time.
A few other things:
* The NServiceBus exerciser has been updated to do a more proper async-await pattern that returns a `Task` to the ConsoleMF app that waits on it, rather than doing its own waiting.
* In order to eliminate the need for a 15-second sleep in the 8T tests, which was to allow the SpanStreamingService to connect to the trace observer before exercising the app to generate spans, a new pattern of usage for …
=> test: eliminate use of arbitrary delays in ConsoleMF integration tests, part 1

.github/workflows/all_solutions.yml, .github/workflows/run_integration_tests.yml, tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTests/AgentMetrics/DataUsageSupportabilityMetricsTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Api/CustomSpanNameApiTests.cs, tests/Agent/IntegrationTests/IntegrationTests/AppDomainCaching/AppDomainCachingTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CustomInstrumentation/ForceNewTransactionTests.cs, tests/Agent/IntegrationTests/IntegrationTests/DataTransmission/ConnectSetApplicationNameTests.cs, tests/Agent/IntegrationTests/IntegrationTests/InfiniteTracing/InfiniteTracingFlakyTests.cs, tests/Agent/IntegrationTests/IntegrationTests/InfiniteTracing/InfiniteTracingTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/ContextDataNotSupportedTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/ContextDataTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/HSMOrCSPDisablesForwardingTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/LocalDecorationTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/LogLevelTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/MaxSamplesStoredTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/MetricsAndForwardingTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/ZeroMaxSamplesStoredTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/ConsoleDynamicMethodFixture.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/LoggingTester.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/NServiceBus/NServiceBusDriver.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbAsyncCmdHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbAsyncEventHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbCmdHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbEventHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbPublishTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbSendTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbThrowingHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus5/NServiceBus5ReceiveTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus5/NServiceBus5SendTests.cs
Reduce logging (application logging instrumentation) integration test cycle time.  Summary of changes:
- Eliminate use of artificial delays (`RootCommands DelaySeconds`) and instead wait on agent log messages where necessary
- Reduce testing of configuration options.  The feature config option logic for logging metrics and log forwarding is handled in a central agent API method `RecordLogMessage` and is sufficiently unit tested there.  The logic for the local decoration config option is in the individual instrumentation wrappers and so the local decoration tests continue to test the feature being enabled or disabled.
- We don't need to test fire-and-forget async scenarios in the `MetricsAndForwarding` tests in addition to async-wait scenarios.  There is no special logic in the wrappers to …
=> test: reduce logging integration testing time

src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/ServiceChannelProxyWrapper.cs, tests/Agent/UnitTests/CompositeTests/TransactionTests.cs
There are 2 changes in this PR to address 2 different but related problems caught by the WCF client integration tests.
1. When asynchronous instrumentation uses the hold-release pattern, the transaction is not removed from the transaction context storage when the response time for that transaction is captured. This can lead to, in some situations, where instrumented code that runs after the "held" but not yet "released" transaction will reuse that transaction instead of creating a new one.
2. The continuation used to end the async segment/span for the WCF client call can sometimes be delayed too long (waiting until …
=> fix: Clearing transaction context for held transactions and async WCF client instrumentation timing.

tests/Agent/UnitTests/Core.UnitTest/Config/ConfigurationLoaderTests.cs
If you try to run the ConfigurationLoader unit tests locally and you have the NEWRELIC_HOME environment variable set to a valid location, the tests will fail. This PR updates the tests so that the NEWRELIC_HOME environment variable will be overridden to the value that the tests expect (when necessary).
=> test: Update ConfigurationLoaderTests to run even when NEWRELIC_HOME is set

src/Agent/NewRelic/Agent/Core/DataTransport/GrpcWrapper.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/GrpcWrapperTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTransformerTests.cs
This was a bit tricky, since we can't have unit tests that connect to a live gRPC server. I was able to cover most of the class by pretending the connect call was successful in a new override method.
The only missing coverage now is a couple exception catches, though I'm not convinced the code in question will ever throw.
=> test: Increase code coverage for GrpcWrapper class

tests/UnitTests.runsettings
Exclude all files in Agent\Extensions\Providers and subfolders from Unit Test code coverage until we can implement proper testing for wrappers.
=> test: Exclude all files in Agent\Extensions\Providers and subfolders

tests/NewRelic.Core.Tests/NewRelic.SystemExtensions/StringExtensionsTests.cs
Increases test coverage to 100% for `StringExtensions.cs`
=> test: Increase StringExtensions code coverage

build/build.ps1, build/build_functions.ps1
I accidentally hard-coded the build configuration in the paths for my  changes to `build_functions.ps1` - this PR addresses that issue. 
Also, I forgot to remove the profiler build from `build.ps1` after we moved it to a NuGet package. I intentionally left the profiler build section commented out in case we ever need to come back to it.
=> ci: Fixed issues with building debug locally

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Sql/Instrumentation.xml
This adds support for auto instrumentation for the Devart Oracle driver
=> feat: Adds minimal support for Devart Oracle client.

tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDBDriverAsyncCursorTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDBDriverCollectionTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDBDriverDatabaseTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDBDriverIndexManagerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDBDriverQueryProviderTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDBTests.cs
Adds:
- config forcing metric harvests to happen in 15 seconds
- WaitForLogLine check on metric harvest
Goal:  Give the app time it needs to get all the metrics since we are seeing missing metric flickers.
=> test: Add WaitForLog and shorter metric harvest for Mongodb tests

tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlConnectorTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlStoredProcedureTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlTests.cs
Adds:
- Additional WaitForLogLine for SQL traces to be sure the tests are okay to proceed
- Updates MySQL unbounded integration tests to use SQL trace override with other overrides
=> test: Add additional WaitForLogLine and faster harvests for MySQL tests.

src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Core/Config/ConfigurationLoader.cs, src/Agent/NewRelic/Agent/Core/Config/ILogConfig.cs, src/Agent/NewRelic/Agent/Core/Configuration/ConfigurationService.cs, src/Agent/NewRelic/Agent/Core/Core.csproj, src/Agent/NewRelic/Agent/Core/Labels/LabelsService.cs, src/Agent/NewRelic/Agent/Core/Logging/AuditLog.cs, src/Agent/NewRelic/Agent/Core/Logging/CustomAuditLogTextFormatter.cs, src/Agent/NewRelic/Agent/Core/Logging/CustomTextFormatter.cs, src/Agent/NewRelic/Agent/Core/Logging/LogLevelExtensions.cs, src/Agent/NewRelic/Agent/Core/Logging/Logger.cs, src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs, src/Agent/NewRelic/Agent/Core/Logging/ProcessIdEnricher - Copy.cs, src/Agent/NewRelic/Agent/Core/Logging/ProcessIdEnricher.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/AgentManager.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/AgentShim.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/RuntimeEnvironmentInfo.cs, src/Agent/NewRelic/Agent/Core/Utilities/EventBus.cs, src/Agent/NewRelic/Agent/Core/Utilities/RequestBus.cs, src/Agent/Shared/SharedLog4NetRepository.cs, tests/Agent/UnitTests/Core.UnitTest/Core.UnitTest.csproj
This PR represents the initial implementation of Serilog in place of log4net. 
* The Agent starts and runs and logs with the same format as log4net used to emit. 
* Many Unit tests and some Integration tests will fail at present. That's ok, we'll work on them later.
* There are a number of *TODO* comments (mostly in LoggerBootstrapper) representing work that is still remaining to be done. Future PRs will address those items.
* Support for logging to Windows EventLog is currently commented out until issues related to ILRepack'ing the right set of assemblies are ironed out.
=> Initial Serilog Logging Implementation

src/Agent/NewRelic/Agent/Core/Logging/InMemorySink.cs, src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs, tests/Agent/UnitTests/Core.UnitTest/NewRelic.Agent.Core.FromLegacy/AgentLoggerTest.cs
- Adds a simple in-memory Serilog sink using a ConcurrerntQueue for storage and to handle threading.
=> feat: Implement simple in-memory Serilog sink.

tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplicationFixture.cs
This re-enables existing retry logic for integration tests for two scenarios:
1. A known error unrelated to the tests. This can be applied globally or per-test. Right now the only error is 0xc0000005, for the recurring memory corruption issue.
2. An exception is thrown by the test fixture rather than the test application. I can't think of a scenario where this could hide an Agent bug.
=> test: Retry tests on known unrelated errors

README.md, codecov.yml
1. Updates README.md to include a few status badges. It's all the rage these days.  The build status badge comes from the nightly scheduled build.
2. Updates our Codecov configuration in a few important ways:
* Sets 80% as the minimum coverage level to get a "green" status in the Codecov UI
* Requires passing Codecov CI run for PR to be merged (admin override is still available, as always)
* Allows a PR to reduce code coverage by no more than 0.5% below the base commit's code coverage level (i.e., we really want code coverage to increase on every PR)
* For PRs, 80% of code changed in the PR must be covered by tests …
=> ci: Update codecov configuration, add some status badges to Readme.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/HttpClient/SendAsync.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/HttpWebRequest/SerializeHeadersWrapper.cs
When HttpClient is used in a .NET Framework application it executes both our HttpClient and HttpWebRequest, because on .NET Framework HttpClient relies on code in HttpWebRequest. HttpClient instrumentation always attempts to create the external segment and inject the appropriate outbound headers (and process the response). HttpWebRequest instrumentation uses 2 separate instrumentation points: 1. to create the external segment (and process the response), and 2. to inject the outbound headers. Most of the time when an application uses HttpClient on .net framework, the HttpWebRequest instrumentation does not find a …
=> fix: Stop double injecting headers with HttpClient on .NET Framework

build/ArtifactBuilder/AgentComponents.cs, build/ArtifactBuilder/Artifacts/NugetAgent.cs, build/ArtifactBuilder/Artifacts/NugetAgentApi.cs, build/ArtifactBuilder/Artifacts/NugetAzureCloudServices.cs, build/ArtifactBuilder/Artifacts/NugetAzureWebSites.cs
The Unpack() method in the content validation logic for NuGet packages needs to handle the possibility that the version string might only have three components (major.minor.patch) if the fourth component of the agent DLL string is zero.
=> ci: let the ArtifactBuilder's content validation logic handle semantic versioning of NuGet packages

.github/workflows/nuget_slack_notifications.yml, .github/workflows/scripts/nugetSlackNotifications/Program.cs, .github/workflows/scripts/nugetSlackNotifications/nugetSlackNotifications.csproj
Part of June 2023 Innovation Days.  Our nightly workflow that checks for new versions of core tech libraries will create issues in our repo so we don't lose track of the need to update the versions we test.
=> ci: Dotty will now create issues in our repo for new package versions it finds

build/ArtifactBuilder/Artifacts/AzureSiteExtension.cs, build/ArtifactBuilder/Artifacts/NugetAgent.cs, build/ArtifactBuilder/Artifacts/NugetAgentApi.cs, build/ArtifactBuilder/Artifacts/NugetAzureCloudServices.cs, build/ArtifactBuilder/Artifacts/NugetAzureWebSites.cs, build/ArtifactBuilder/NuGetHelpers.cs, build/ArtifactBuilder/NugetPackage.cs
Modifies ArtifactBuilder to parse the output from the `nuget pack` command via Regex to find the actual `.nupkg` filename that was created, eliminating the need to manually build the filename in the `Unpack()` step.
Validated by running `.\build\package.ps1` locally and verifying that all NuGet packages were successfully created and validated.
=> ci: Artifactbuilder parses output from nuget pack

.github/workflows/nuget_slack_notifications.yml
Part of June 2023 core tech milestone.  Added the following libraries to the list we scan for updates:
```
Microsoft.Extensions.Logging
NLog
log4net
Elasticsearch (NEST)
Elasticsearch (Elasticsearch.Net)
Elasticsearch (Elastic.Clients.Elasticsearch)
```
Here's output from a test run I did on this branch.  I sanity checked the results and they are correct (e.g. NEST and Elasticsearch.NET were updated 8 months ago, so they show as not updated in the past 90 days, but Elastic.Clients.Elasticsearch was updated last month so it shows as updated).
```
nugets: elasticsearch.net elastic.clients.elasticsearch log4net microsoft.extensions.logging microsoft.data.sqlclient microsoft.net.http mongocsharpdriver mongodb.driver mysql.data mysqlconnector nest nlog rabbitmq.client restsharp serilog …
```
=> ci: add new core tech libraries to the list to scan for updates

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
The latest library version tested by our integration tests is updated for the following libraries/versions:
* Microsoft.Data.SqlClient -> 5.1.1
* RabbitMQ -> 6.5.0
* StackExchange.Redis -> 2.6.111
* Serilog -> 2.12.0
* NLog -> 5.2.0
* Elastic.Clients.Elasticsearch -> 8.1.1
* Microsoft.Extensions.Logging -> 7.0.0
All integration tests associated with these changes are passing for me locally.  The CI should pass too of course.
There is already a separate issue for updating Mysql.Data to the latest, issue #1560.  This PR does not address that.
=> test: update latest tested versions of core tech libraries, June 2023 roundup

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/WrapPipelineMiddleware.cs
Addresses an obscure bug where the AspNetCore middleware could be called with an empty `HttpRequest.Path`. 
I was unable to create an integration test to verify this fix, but did validate that debugging and forcing `HttpRequest.Path` to be `PathString.Empty` doesn't cause an exception like it did in the previous code.
=> fix: Handle empty Request.Path values in AspNetCore middleware wrapper.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Sql/Instrumentation.xml, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
MySql.Data version 8.0.33 reorganized its methods internally so that all of the methods we instrumented previously (ExecuteReader, ExecuteNonQuery, Read, NextResult) became pass-throughs to async versions that perform the same work.
This PR updates the instrumentation file for the Sql wrapper to add the new async instrumentation points for MySql.Data 8.0.33 and higher.
=> feat: add support for MySql.Data version 8.0.33+

src/Agent/Configuration/newrelic.config
Adds request path exclusion rules for `WebResource.axd` and `ScriptResource.axd` to the default `newrelic.config` file.
=> fix: Exclude WebResource.axd and ScriptResource.axd from browser instrumentation (via default config).

src/Agent/MsiInstaller/InstallerActions/CustomActions.cs
Updates the custom actions in the msi installer to perform some additional validation before executing any actions that would copy, move, or remove files.
=> fix: Add more validation to msi installer.

src/Agent/NewRelic/Profiler/docker-compose.yml, src/Agent/NewRelic/Profiler/linux/Arm64Dockerfile
I needed to test some arm64 applications locally with a custom build of the profiler for arm64. I used the dockerfile and docker-compose definitions in this PR to build custom versions of the profiler locally so that I could use those custom builds to test within a test application.
This could be a first step in making the build/ci process more consistent between the x64 and arm64 linux profiler builds. In the meantime, this can simplify the process for testing the arm64 profiler locally.
=> chore: Add dockerfile and docker-compose to build arm64 profiler locally

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Caches the value of the `AgentEnabled` configuration setting when it is first read, rather than reading the value from config every time it is accessed.
=> fix: Cache the AgentEnabled setting value.

src/Agent/NewRelic/Profiler/linux/Arm64Dockerfile
Updates the Arm64 profiler build docker image to use a pinned image. This should resolve the problem reported by the code scanner. The image is pinned to the ubuntu 18.04 multi-platform image, which docker-compose will resolve the appropriate platform when the build and run commands are executed.
=> chore: Update Arm64 base image to use a pinned image.

.github/workflows/all_solutions.yml, .github/workflows/awslambda_release.yml, .github/workflows/build_profiler.yml, .github/workflows/markdowncheck.yml, .github/workflows/multiverse_run.yml, .github/workflows/nuget_slack_notifications.yml, .github/workflows/repolinter.yml, .github/workflows/run_integration_tests.yml, .github/workflows/run_unit_tests.yml, .github/workflows/scorecard.yml, .github/workflows/siteextension_release.yml
* Bump `actions/checkout` to v3.5.3
* Bump `github/codeql-action/upload-sarif` to v2.13.4
=> chore: Weekly dependabot roundup.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/Instrumentation.xml, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MongoDB/MongoDBDriverExerciser.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDBDriverCollectionTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDBDriverDatabaseTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDBDriverIndexManagerTests.cs
This PR resolves #1637 and adds instrumentation for the following `MongoDB.Driver` methods previously ignored by the agent:
- IMongoCollection:
- CountDocuments[Async]
- EstimatedDocumentCount[Async]
- AggregateToCollection[Async]
- IMongoDatabase:
- ListCollectionNames[Async]
- Aggregate[Async]
- AggregateToCollection[Async]
- Watch[Async]
This PR also refactors most of the MongoDB.Driver integration tests to use the `Theory` feature of XUnit to reduce test code duplication.
=> feat: MongoDB instrumentation update

src/Agent/NewRelic/Agent/Core/Config/ConfigurationLoader.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/AgentManager.cs
At startup, an exception is thrown when the agent is disabled via config. That message includes the path to the config file where the agent is disabled. For .NET 6+ applications, the path is empty. 
This PR modifies the logic in `ConfigurationLoader.GetConfigSetting()` to include looking at the `appsettings.json` file for .NET 6+ applications and to include the path to the file in the message. As a final fallback, the location of the `newrelic.config` file is used in the message.
=> fix: Include config file path in the "Agent is disabled " message on all platforms.

src/Agent/NewRelic/Agent/Core/DataTransport/HttpCollectorWire.cs, src/Agent/NewRelic/Agent/Core/Logging/AuditLog.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/HttpCollectorWireTests.cs, tests/Agent/UnitTests/Core.UnitTest/Logging/AuditLogTests.cs
Adds code to check whether audit logging is enabled before going to the trouble of formatting audit log messages and sending them to Serilog. 
(Note that Serilog would already suppress sending those messages if audit logging was disabled, so there's no functional change with this PR, only an optimization to reduce unnecessary string formatting and Serilog calls.)
=> fix: Format and log audit-level messages only when audit logging is enabled.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Update the latest version tested of the following instrumented libraries:
Serilog (3.0.1)
MongoDB.Driver (2.20.0)
Stackexchange.Redis (2.6.116)
Associated docs site updates: https://github.com/nr-ahemsath/docs-website/tree/add-new-mongodb-instrumented-methods-10-12-0 (not a PR yet because this contains updates that won't be valid until agent version 10.12.0 is released)
=> chore: update latest versions of instrumented libraries tested

.github/workflows/all_solutions.yml
Adds an input for the workflow_dispatch trigger to indicate whether we're manually running the workflow for purposes of creating a release. If `true`, we use the "real" code signing cert; otherwise, we use a self-signed cert.
=> ci: Update all solutions workflow to create self-signed cert only on non-release builds.

src/Agent/NewRelic/Agent/Core/Utilities/ExtensionsLoader.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Sql/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Sql/OpenConnectionWrapper.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MsSql/MicrosoftDataSqlClientExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MsSql/SystemDataExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MsSql/SystemDataSqlClientExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MySql/MySqlConnectorExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MySql/MySqlExerciser.cs, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/Controllers/OracleController.cs, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcCoreApplication/Controllers/MicrosoftDataSqlClientController.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresExecuteScalarAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresSimpleQueryAsyncTests.cs
This ended up being trickier than expected for a few reasons:
* The default implementation for `DbConnection.OpenAsync()` is not async. I had to check each library to see if they had an override that is actually async.
* MySql has its own implementation of `OpenAsync()`, but it is not async until 8.0.33.
* If an implementation of `OpenAsync()` calls Open(), we don't want to instrument both.
To minimize the test changes, I took existing async tests and switched the `Open` calls to `OpenAsync`.
=> feat: Instrument OpenAsync() for SQL libraries

licenses/LICENSE.rtf, src/Agent/MsiInstaller/Installer/LicenseKeyDialog.wxs, src/Agent/MsiInstaller/Installer/WizardUI.wxs
Updates the MSI UI to clean up some longstanding formatting and readability issues.
- Update license font in MSI to better fit inside UI.
- Update the MSI feature selection to improve readability.
No tests.  You can pull down the MSI from CI and compare with old ones.
=> fix: Update the MSI UI to clean up formatting and readability issues.

.github/workflows/run_unit_tests.yml, tests/AwsLambda/UnitTests/AwsLambdaOpenTracerTests/AwsLambdaOpenTracerTests.csproj, tests/AwsLambda/UnitTests/AwsLambdaWrapperTests/AwsLambdaWrapperTests.csproj
Fixes unit test workflow failure related to .NET Core 3.1 no longer being available on the test runners. (A better solution would be to either remove or exclude the AwsLambda unit test projects since we don't need them, but this will work for now.)
=> ci: Update AwsLamba unit tests to .NET 7.0

src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/IAgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/MetricNames.cs, src/Agent/NewRelic/Agent/Core/WireModels/IMetricBuilder.cs, src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/LogLevelDenyListTests.cs, tests/Agent/UnitTests/Core.UnitTest/Metrics/MetricNamesTests.cs
Adds metrics to track log lines discarded due to LogLevelDenyList configuration. Includes unit and integration tests. 
I'm open to suggestions for different metric naming if folks don't like what I chose... ;-)
=> Feature work: log level filtering metrics

deploy/linux/Dockerfile
Updates debian image to latest (buster-20230703-slim) to address security vulnerabilities reported by Snyk.
=> ci: Update debian image used in package deploy Dockerfile

deploy/linux/Dockerfile
Resolves a code security alert by pinning the debian:buster image with a sha.
=> ci: Add sha to pin debian:buster-slim image

src/Agent/NewRelic/Agent/Core/DistributedTracing/DistributedTracePayloadHandler.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/DistributedTracing/DistributedTracePayloadHandlerTests.cs
- Refactors DistributedTracePayloadHandler.BuildTracestate to detect empty vendor states and not use string.Join to create the tracestate which could result in trailing commas.
- Adds unit tests to confirm that we don't add trailing commas.
Resolves #1775
=> fix: Remove invalid trailing comma added to W3C tracestate header.

tests/Agent/IntegrationTests/Shared/ElasticSearchConfiguration.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchElasticClient.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchNestClient.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchNetClient.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchTestClient.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Elasticsearch/ElasticsearchTests.cs, tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml
This PR allows us to test older versions (all the way back to 7.0.0) of the 7.x clients (NEST and Elasticsearch.Net) to verify our instrumentation's compatibility with the full range of versions we want to support.  We needed to add a 7.x Elasticsearch server to our test infrastructure to enable this.
=> test: add an Elasticsearch 7.x server to test infrastructure and use it to test older clients

tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlConnectorTests.cs
Refactors `MySqlConnectorTests` to run all of the various commands in a single test, instead of running one command per test (times 6 framework targets). Should result in a significant reduction in total test execution time.
before:
after:
=> test: Refactor MySqlConnector tests for improved performance.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Resolves #1807 by updating to latest Elastic.Clients.ElasticSearch (8.9.1).
=> tests: update the latest version of Elastic.Clients.ElasticSearch tested to 8.9.1

tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs, tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/BrowserAgentAutoInjection.cs
Adds more browser agent auto injection tests to confirm that the dotnet agent does not modify the browser agent when it is injected. The dotnet agent previously only tested the "rum" loader. Now it will also test the "full" and "spa" loaders.
=> test: Add more browser agent injection tests.

tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplicationFixture.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Timing.cs, tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/ThreadProfileTests.cs, tests/Agent/IntegrationTests/IntegrationTests/InfiniteTracing/InfiniteTracingTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Owin/OwinWebApiAsyncTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Owin/OwinWebApiStatusCodeRollupTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AspNetCoreDistTraceRequestChainFixture.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/CosmosDB/CosmosDBTests.cs
Explanation of changes added as inline comments.
=> test: Improve integration test reliability

.github/workflows/deploy_agent.yml, .github/workflows/post_deploy_agent.yml, .github/workflows/publish_release_notes.yml
* Updates `deploy_agent.yml` to fix an error in the conditional for running the APM update. Also adjusts some of the dependencies for release notes and post-deploy actions.
* Updates `post_deploy.yml' to introduce a 2-minute delay before validating apt and yum, when the workflow is invoked by an external call. This is to give those repos time to refresh their indexes prior to attempting the validation step.
* Fixes a minor typo in `publish_release_notes.yml`
=> ci: Update workflows based on results of last release.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Updates the MySQL unbounded integration tests to use MySql.Data version 8.1.0 instead of 8.0.33.
Resolves #1781.
=> Test: Update MySql.Data version from 8.0.33 to 8.1.0 in the test apps.

tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplication.cs
Adds exception handling around calls to `RemoteProcess.Kill()` to ignore any exceptions that might get thrown due to the process having already terminated.
See https://github.com/newrelic/newrelic-dotnet-agent/actions/runs/5830835047/job/15813713007#step:9:74 for an example of this error.
=> ci: Add exception handling to reduce test failures

src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/AgentManager.cs, src/NewRelic.Core/DotnetVersion.cs, tests/NewRelic.Core.Tests/DotnetVersionTests.cs
Resolves #1850.
Adds a warning to the managed agent logs when an unsupported version of .net is detected. 
- For .net and .net core it checks the version of the runtime used by the application. 
- For .net framework it checks the installed .net framework version (not the targeted version) that the application is running on.
Additional profiler warnings are not generated.
- For .net/.net core the profiler will only attach if the application is running on netcoreapp3.1 or greater. We cannot specifically check for net6 in the profiler, but we could check for net5. However the differences between those versions are …
=> feat: Log a warning when an unsupported .NET version is detected.

.github/workflows/all_solutions.yml
Updates the schedule for `all_solutions.yml` so that it only runs on weekdays rather than every day.
=> ci: Run all solutions build only on weekdays

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Logging/LogProviders.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Reflection/VisibilityBypasser.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Log4NetLogging/Log4netWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/AddProviderRegistrationWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/MicrosoftLoggingWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NLogLogging/NLogWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/SerilogLogging/NewRelicSerilogSink.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/SerilogLogging/SerilogCreateLoggerWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/SerilogLogging/SerilogDispatchWrapper.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/Common.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/ContextDataNotSupportedTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/ContextDataTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/LoggingTester.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/NLogExtensionsLoggingAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/SerilogExtensionsLoggingAdapter.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Reflection/VisibilityBypasserTests.cs
Previously, if we detected Microsoft.Extensions.Logging and another logger, we would only instrument MEL, in order to avoid double collection of logs. This turned out to be a flawed approach, because MEL does not store any context data. It relies on the underlying logger to handle it. So now, if we detect that scenario, we disable MEL instrumentation. Only if we don't find another logger that we know how to instrument, will we instrument MEL.
In order for us to collect context data from an ILogger via MEL, the logger must implement `IExternalScopeProvider` (specifically the `ForEachScope` function). Scope data can be any object, but we will only collect it if it's a key-value pair (or collection of key-value pairs). This is how NLog and Serilog implement their scope provider, so this …
=> feat: Add support for Serilog.Extensions.Logging and NLog.Extensions.Logging

tests/Agent/IntegrationTests/IntegrationTests/HttpClientInstrumentation/HttpClientInstrumentation.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/EnterpriseLibraryMsSqlTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlQueryParamAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlQueryParamTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureUsingOdbcDriverTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureUsingOleDbDriverTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlWarmupHelper.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlConnectorTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlStoredProcedureTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlWarmupHelper.cs
Updates MySql and MsSql integration tests to run a query prior to launching the test app, in hopes of improving responsiveness in the test.
=> test: SQL warmup before starting test app.

tests/Agent/IntegrationTests/IntegrationTests/Owin/OwinWebApiAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlConnectorTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlStoredProcedureTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlTests.cs
The overnight run failed again, even after adding the "warmup" code. So we'll just extend the MySql harvest interval to 45 seconds which should make things more stable. Maybe. I hope.
=> test: Extend harvest from 15 to 45 seconds for MySql tests.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MySql/MySqlConnectorExerciser.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlConnectorTests.cs
* Refactor `MySqlConnectorExerciser` so that the sync tests actually run synchronously
* Refactor `MySqlConnectorTests` to change how we're checking for SQL trace metrics. Our previous assumption that the first query is always going to be the slowest query doesn't hold up reliably. But as long as there's only one SQL trace metric and it has the expected properties (other than transaction name), we're good.
=> test: Update MySqlConnectorTests

.github/workflows/all_solutions.yml, .github/workflows/assignproj.yml, .github/workflows/build_download_site_index_files.yml, .github/workflows/build_profiler.yml, .github/workflows/deploy_agent.yml, .github/workflows/deploy_awslambda.yml, .github/workflows/deploy_siteextension.yml, .github/workflows/get_release_checksums.yml, .github/workflows/markdowncheck.yml, .github/workflows/multiverse_run.yml, .github/workflows/nuget_slack_notifications.yml, .github/workflows/post_deploy_agent.yml, .github/workflows/publish_release_notes.yml, .github/workflows/release-please.yml, .github/workflows/repolinter.yml, .github/workflows/run_integration_tests.yml, .github/workflows/run_linux_smoke_tests.yml, .github/workflows/scorecard.yml, .github/workflows/set_community_label.yml, .github/workflows/stale_issue.yml, .github/workflows/stale_pr.yml
* Bump step-security/harden-runner to 2.5.1
* Bump aws-actions/configure-aws-credentials to 3.0.1
Manually tested `build_download_site_index_files` workflow to verify the major version bump in aws-actions didn't break anything.
=> chore(deps): Dependabot updates

.github/workflows/all_solutions.yml, .github/workflows/build_profiler.yml, .github/workflows/markdowncheck.yml, .github/workflows/repolinter.yml, .github/workflows/run_unit_tests.yml
Updates several workflows that run on `push` or `pull_request` so that they only run when *not* triggered by Dependabot. 
Given that our current Dependabot configuration only updates github action versions, there's no need to run these workflows on an update. The alternative, if we really want to run these workflows, would be to add a [parallel set of secrets for Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#accessing-secrets) as what we've configured for Actions, which seems like more toil than it's worth.
=> ci: Don't run workflows when triggered by Dependabot

.github/workflows/post_deploy_agent.yml
The yum / apt validation jobs are supposed to delay 2 minutes when called from another workflow but that apparently didn't work on the release today. This should fix the issue.
=> ci: Fix conditional delay for yum/apt validation jobs.

src/Agent/NewRelic/Agent/Core/DataTransport/Client/NRHttpClient.cs, src/Agent/NewRelic/Agent/Core/DataTransport/Client/NRHttpClientFactory.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/Client/NRHttpClientFactoryTests.cs
Adds a log line to NRHttpClient that reports the `HttpClientHandler.SslProtocols`.  This value can differ from the TLS settings capture in previous logging since `System.Net.ServicePointManager.SecurityProtocol` changes don't pass through to the HttpClientHandler.  This new log line should appear in the same general area as the current TLS message.  it does not replace that message.  it also only exists for HttpClient and not HttpWebRequest.
While adding this log line, I noticed that it was appearing multiple times when it should only occur once per the lifetime of the IoC container.  There was a bug in the NRHttpClientFactory that resulted in it creating a new client every time CreateClient was called instead of returning the cached client.
Refactored NRHttpClientFactory to return the …
=> fix: Fix NRHttpClientFactory so that it creates only one client.

.github/workflows/all_solutions.yml, .github/workflows/build_profiler.yml, .github/workflows/check_modified_files.yml, .github/workflows/markdowncheck.yml, .github/workflows/repolinter.yml, .github/workflows/run_unit_tests.yml
* Adds a new reusable workflow to check whether files outside the `.github/**` folder were modified.
* Modifies several workflows to skip running if the reusable workflow indicates nothing of merit was modified.
* Modifies `markdowncheck.yml` so that it only runs when `**.md` files are modified in a push to any branch and schedules it to run nightly to help catch any dead links.
=> ci: Workflow Updates

.github/workflows/all_solutions.yml
Adjusted the conditions for running the build-fullagent-msi job to make sure it runs when the nightly schedule triggers the workflow.
=> ci: ensure all_solutions does full build on nightly schedule

.github/workflows/all_solutions.yml
Turns out you can't have a branch protection rule that depends on a job that uses a matrix. This workaround seems to be the accepted way of handling that -- it adds a new job that checks the status of the matrix of integration and unbounded tests and fails if any of those jobs failed. Based on [this GH thread](https://github.com/orgs/community/discussions/4324#discussioncomment-3477871)
The branch protection rules will be updated (once this PR completes) to depend on this job instead of the two integration test jobs we're currently configured for.
=> ci: Add a integration test status check job that can be used in a branch protection rule.

src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs
Removes the 4-file limit on retained Agent log files. Logs will still roll at 50MB, but an unlimited number will be retained.
Resolves #1878
=> fix: Remove the retained file count limit for Agent log files.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/HttpClient/SendAsync.cs, tests/Agent/IntegrationTests/Applications/AspNetCoreDistTracingApplication/Controllers/SecondCallController.cs, tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/W3CInstrumentationTests/HttpClientW3CTestsNetCore.cs
Fixes #1843.
Prevents duplicate outgoing tracing headers, for HttpClient calls,  by ensuring that the headers are only present as request headers, and that they do not also appear as content headers. An existing Integration Test was updated to ensure that the distributed trace is not broken when tracing headers are part of the Content Headers collection.
=> Fix: Prevent broken traces when HttpClient content headers contain tracing headers. (#1843)

tests/Agent/IntegrationTests/ContainerApplications/docker-compose.yml, tests/Agent/IntegrationTests/ContainerIntegrationTests/ContainerFixtures/ContainerApplication.cs
Assigns a guid as the network name for each test that runs, this should avoid the occasional failures we've seen that have a message like 
```
Error response from daemon: network containerapplications_default is ambiguous (2 matches found on name)
```
=> ci: Assign a unique network name in docker compose for each test execution to avoid collisions.

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Reflection/VisibilityBypasser.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Log4NetLogging/Log4netWrapper.cs
Adds a couple of `TryXxx()` methods in `VisibilityBypasser` that simplify calling patterns where we attempt to get a particular property or method, then fall back to getting a different property or method. 
Resolves #1797.
=> chore: add new methods in VisbilityBypasser to simplify "this or that" usage pattern.

.github/workflows/post_deploy_agent.yml
The linux deploy validation tests failed for this release, but when rerun they passed.  We currently have a 2 minute wait time to help prevent this, but it is not enough.  Moving to a 5 minute wait.
=> ci: Extend the wait timer for validating the Linux deploys.

src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthEvent.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/Aggregators/MetricAggregator.cs, tests/Agent/UnitTests/Core.UnitTest/AgentHealth/AgentHealthHeartbeatTests.cs
Right now there is very little information logged by the Agent at Info level, by design. One of the things that does get logged is a simple `Metric harvest starting.`, which can be used to show that the Agent is still alive and doing work. The goal with this change is to record something a little more useful. Instead, every (5) minutes, the Agent will log how many events it has seen in that window.
Before:
```
2023-06-12 07:44:14,961 NewRelic   INFO: [pid: 5832, tid: 10] Metric harvest starting.
2023-06-12 07:45:15,501 NewRelic   INFO: [pid: 5832, tid: 17] Metric harvest starting.
2023-06-12 07:46:15,730 NewRelic   INFO: [pid: 5832, tid: 29] Metric harvest starting.
2023-06-12 07:47:15,947 NewRelic   INFO: [pid: 5832, tid: 11] Metric harvest starting.
2023-06-12 07:48:16,182 NewRelic …
```
=> feat: Add more detail to "heartbeat" message in log

.github/workflows/all_solutions.yml, .github/workflows/run_integration_tests.yml
Due to issues with the Oracle server used in GHA, temporarily disable running the Oracle integration tests in CI.  They can still be run locally using a local container to host the Oracle server.
=> Disable Oracle integration tests in CI

tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTests/InfiniteTracing/InfiniteTracingTests.cs
In https://github.com/newrelic/newrelic-dotnet-agent/actions/runs/6200910159/job/16837606190?pr=1920 the infinite tracing test failed because the test only waited for the grpc connection to be established before triggering the 1 instrumented method call. However, spans will only be transmitted over infinite tracing after at least 1 stream is connected. This delay between the grpc connection and the stream connection being established can lead to the generated span being sent via either infinite tracing or normal distributed tracing (depending on when the span is created). To make the test more stable, it now waits …
=> test: Make infinite tracing integration test more stable.

src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs
Reverts the max number of Agent logs to 4 (It is currently unlimited).
Resolves #1929
=> fix: Reinstate max number of log files.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests.sln
* Bumps `Elastic.Clients.Elasticsearch` from 8.9.2 to 8.9.3
* Adds `SharedApplicationHelpers.csproj` to the `UnboundedIntegrationTests` solution to facilitate building without having to build the `IntegrationTests` solution first.
Resolves #1914
=> test: Bump Elastic.Clients.Elasticsearch from 8.9.2 to 8.9.3

.github/workflows/all_solutions.yml, .github/workflows/deploy_agent.yml
* Removes the (unmaintained) `southpolesteve/cosmos-emulator-github-action` action from `all_solutions.yml` and replaces it with direct calls to Powershell to start the CosmosDB emulator. Tested and verified that the emulator starts as expected.
* Refactors `deploy_agent.yml` to make all relevant input options true booleans rather than strings, which makes the UI for manual invocation of the workflow quite a bit cleaner: 
Note that none of the comparisons in the workflow were modified - they *should* all continue to work as-is. I haven't been able to test, of course, because it's not trivial to do so in this workflow.
* Changes the defaults for "Deploy Build Artifacts" and "Deploy APT/YUM Packages to Production Repository" to `true` instead of `false`. This is the most common use case for …
=> ci: Misc workflow refactoring

tests/Agent/IntegrationTests/HostedWebCore/HostedWebCore.cs
Adds a bit of wait-and-retry logic to `HostedWebCore` to address intermittent failures when we use P/Invoke to start the hosted web service. 
The stack trace indicating the failure looks something like 
```
[9/27/2023 9:51:19 AM 1208-1] HostedWebCore: HostedWebCore.exe failed: Reason unknown.: System.IO.FileLoadException: The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
at HostedWebCore.HostedWebCore.Run() in D:\a\newrelic-dotnet-agent\newrelic-dotnet-agent\tests\Agent\IntegrationTests\HostedWebCore\HostedWebCore.cs:line 62
at …
```
=> test: Add retry logic when attempting to start the WebCore process

src/Agent/NewRelic/Agent/Core/Utilization/VendorInfo.cs, tests/Agent/UnitTests/Core.UnitTest/Utilization/VendorInfoTests.cs
Updates our Docker container id lookup to support the newer cgroup v2 standard, parsing `/proc/self/mountinfo` to obtain the container id. 
The new lookup is executed first and if not successful, we fall back to the original (cgroup v1) lookup.
Adds a unit test to verify the parsing logic for `/proc/self/mountinfo`.
Tested in staging and saw the container id being reported as expected:
=> fix: Detect Docker container id on cgroup v2.

tests/Agent/IntegrationTests/ContainerIntegrationTests/ContainerFixtures/LinuxSmokeTestFixtures.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/LinuxSmokeTests.cs
Changes the metric harvest override to 10 seconds instead of 5 and introduces a delay after exercising the app but before looking for metric harvest. These changes should help resolve flakiness in the linux smoke tests.
=> ci: Adjust metric harvest cycle and introduce a delay for linux smoke tests

src/Agent/NewRelic/Profiler/Profiler/Function.h
This PR improves the log message the profiler writes out (at finest/trace level) about ignoring certain assemblies (NewRelic.*, System.*, Microsoft.*) when searching for the `[Transaction]` and `[Trace]` instrumentation attributes.
=> other: update the profiler log message about ignored assemblies

.github/workflows/markdowncheck.yml
Modifies `markdowncheck.yml` to run only on a daily schedule. 
I'll subscribe the `dotnet-agent-github` channel to get notifications about the scheduled run.
=> ci: Update markdown check workflow to only run on schedule

src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs
Enables the `manageEventSource` parameter on the SeriLog `EventLog()` sink constructor. This will allow the Agent to attempt to create the `New Relic .NET Agent` event source on the local machine if it doesn't exist. Note that this attempt will only succeed if the application is running with Administrator privileges. Note that this code is currently applicable only to .NET Framework applications.
If source creation fails, Serilog will catch the exception internally. I've also added a just-in-case `try/catch` block around the call to configure the EventLog sink. In any case, the Agent will continue to operate, though it will be unable to log to EventLog.
=> fix: Update Serilog EventLog sink configuration to enable event source creation.

build/ArtifactBuilder/CoreAgentComponents.cs, build/ArtifactBuilder/FrameworkAgentComponents.cs, src/Agent/MsiInstaller/Installer/Product.wxs, src/Agent/NewRelic/Agent/Core/Utilities/ExtensionsLoader.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MassTransit/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MassTransit/NewRelicFilter.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MassTransit/TransportConfigWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MassTransitLegacy/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MassTransitLegacy/NewRelicFilter.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MassTransitLegacy/TransportConfigLegacyWrapper.cs
Refactor a constant string into a constant, and fix some comment typos, to clean up the proof-of-concept branch for MassTransit auto-instrumentation.
Edit: this also adds the new instrumentation assets to the installers.
=> Clean up POC branch

src/Agent/NewRelic/Agent/Core/Core.csproj, src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs
Enables configuration of the Event Log sink for Serilog during Agent startup when running on Windows in both .NET Framework and .NET 6+ applications. 
Note that the Event Log sink will only write to the event log if the `New Relic .NET Agent` Event Source already exists *or* if the application is running with administrator privileges. 
This change supersedes a previous commit (#4310e982) that was reverted.
=> feat: Enable startup logging to Event Log for all applications on Windows.

.github/workflows/all_solutions.yml
Removes previous changes that would only run Artifact Builder during a release. It now runs with every all_solutions CI run.
=> ci: Run artifact builder on every all_solutions CI run.

.github/workflows/deploy_agent.yml
As per the recent thread in #agent-dev, we no longer need to call the EU endpoint when updating the dotnet agent version.
=> ci: Remove API call to update dotnet agent version in EU.

.github/workflows/check_modified_files.yml
Minor update to ignore changes to `.md` files, there's no need to run the all_solutions build if that's the only file that was changed.
=> ci: Ignore .md file changes when deciding whether to run the all_solutions jobs.

.editorconfig
Updates `.editorconfig` so that Visual Studio always saves files as UTF-8 without the BOM header. Doesn't fix any existing files that have the header unless you open and save them, but maybe this will reduce occurrences in the future.
=> chore: Update .editorconfig to always save as UTF-8 without BOM

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MassTransit/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MassTransit/TransportConfigWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MassTransitLegacy/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MassTransitLegacy/TransportConfigLegacyWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/MassTransit/MassTransitConsumeTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MassTransit/MassTransitExerciser.cs
A few things to note, as this is still a work in progress:
* The preprocessor directives are needed because of the dependency on `Microsoft.Extensions.Hosting`, which we already have a dependency on elsewhere and the versions are tricky to align
* Naming the queue doesn't work yet, so the metric checks in the tests won't pass. We may need to give up on that approach.
* I'm not sure we need two different wrappers? The code seems to work and is identical in both.
* The tests call `Publish` but our `Send` filter is being invoked (I know they're all called "Send" but it's the one with a `SendContext` when I was expecting the one with a `PublishContext`). But it's getting the action as "Publish" so I'm not sure if that's correct or not.
=> Adding alternate instrumentation point and first pass at tests

src/Agent/NewRelic/Agent/Core/Utilization/VendorHttpApiRequestor.cs
Reduces exception logging during `CallVendorApi()` failures. 
```
2023-10-24 16:15:55,194 NewRelic  DEBUG: [pid: 6824, tid: 8] CallVendorApi (aws) failed: A socket operation was attempted to an unreachable network. [::ffff:169.254.169.254]:80 (169.254.169.254:80)
2023-10-24 16:15:55,350 NewRelic  DEBUG: [pid: 6824, tid: 8] CallVendorApi (azure) failed: A socket operation was attempted to an unreachable network. [::ffff:169.254.169.254]:80 (169.254.169.254:80)
2023-10-24 16:15:55,532 NewRelic  DEBUG: [pid: 6824, tid: 8] CallVendorApi (gcp) failed: No such host is known. (metadata.google.internal:80)
```
Resolves #2005
=> fix: Reduce exception logging on CallVendorApi failures.

src/Agent/NewRelic/Profiler/MethodRewriter/ApiFunctionManipulator.h, src/Agent/NewRelic/Profiler/MethodRewriter/FunctionManipulator.h, src/Agent/NewRelic/Profiler/MethodRewriter/HelperFunctionManipulator.h, src/Agent/NewRelic/Profiler/MethodRewriter/InstructionSet.h, src/Agent/NewRelic/Profiler/MethodRewriter/InstrumentFunctionManipulator.h, src/Agent/NewRelic/Profiler/Profiler/CorProfilerCallbackImpl.h, src/Agent/NewRelic/Profiler/Profiler/CorTokenizer.h, src/Agent/NewRelic/Profiler/Profiler/Module.h
Reduces the number of times we need to check the isCoreClr flag to determine which assembly to reference in an instruction.
This also includes a fix to ensure that the correct tokenizer is always used.
=> chore: Reduce profiler iscoreclr checks and use correct tokenizer

src/Agent/NewRelic/Profiler/ModuleInjector/IModule.h, src/Agent/NewRelic/Profiler/ModuleInjector/ModuleInjector.h, src/Agent/NewRelic/Profiler/Profiler/CorProfilerCallbackImpl.h, src/Agent/NewRelic/Profiler/Profiler/Module.h
Mostly replaces the duplicate methods that handled slight differences between .net framework and .net/.net core byte code injection.
Some other changes related to this cleanup include.
- Removes the code that created an instance of the ModuleInjector, because it only contains static methods.
- Removes the OverrideEventMask method because it no longer did anything.
- Moved some of the logic from the ModuleInjector into the Module class
- Removed unnecessary methods and fields from the Module class
=> chore: Reduce duplicate methods for handling .net framework and .net/.net core injection.

src/Agent/NewRelic/Profiler/MethodRewriter/AgentCallStyle.h, src/Agent/NewRelic/Profiler/MethodRewriter/ApiFunctionManipulator.h, src/Agent/NewRelic/Profiler/MethodRewriter/FunctionManipulator.h, src/Agent/NewRelic/Profiler/MethodRewriter/HelperFunctionManipulator.h, src/Agent/NewRelic/Profiler/MethodRewriter/ISystemCalls.h, src/Agent/NewRelic/Profiler/MethodRewriter/InstrumentFunctionManipulator.h, src/Agent/NewRelic/Profiler/MethodRewriter/Instrumentors.h, src/Agent/NewRelic/Profiler/MethodRewriter/MethodRewriter.h, src/Agent/NewRelic/Profiler/MethodRewriter/MethodRewriter.vcxproj, src/Agent/NewRelic/Profiler/MethodRewriterTest/AgentCallStyleTests.cpp, src/Agent/NewRelic/Profiler/MethodRewriterTest/FunctionManipulatorTest.cpp, src/Agent/NewRelic/Profiler/MethodRewriterTest/MethodRewriterTest.cpp, src/Agent/NewRelic/Profiler/MethodRewriterTest/MethodRewriterTest.vcxproj, src/Agent/NewRelic/Profiler/MethodRewriterTest/MockSystemCalls.h, src/Agent/NewRelic/Profiler/Profiler/CorProfilerCallbackImpl.h, src/Agent/NewRelic/Profiler/Profiler/Module.h, src/Agent/NewRelic/Profiler/Profiler/SystemCalls.h, src/Agent/NewRelic/Profiler/Profiler/UnixSystemCalls.h
Adds a new environment variable `NEW_RELIC_ENABLE_LEGACY_CACHING` in addition to the existing `NEW_RELIC_DISABLE_APPDOMAIN_CACHING` environment variable that allows someone to control which caching strategy is used.
If `NEW_RELIC_DISABLE_APPDOMAIN_CACHING` is set to `true` reflection without any caching will be used. This will happen even if the other environment variable is set to `true`.
If `NEW_RELIC_ENABLE_LEGACY_CACHING` is set to `true` (and the other variable is not set to `true`) AppDomain caching will be used.
The new In Agent cache will be enabled by default.
.Net Framework applications that want to …
=> Enables configuration of the profiler method caching strategy.

src/Agent/NewRelic/Agent/Core/Logging/AuditLog.cs, src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs, tests/Agent/UnitTests/Core.UnitTest/Logging/AuditLogTests.cs
Fixes an issue where audit logging wasn't correctly enabled at runtime.
Resolves #2028
=> fix: When audit logging is enabled, no logs are written to the audit log file.

README.md, deploy/linux/deploy_scripts/s3-index/README.md, licenses/LICENSE, licenses/LICENSE.rtf, licenses/LICENSE.txt, licenses/NewRelic.OpenTracing.AmazonLambda.Tracer/LICENSE, licenses/NewRelic.OpenTracing.AmazonLambda.Tracer/LICENSE.txt, licenses/NewRelic.OpenTracing.AmazonLambda.Tracer/THIRD_PARTY_NOTICES.txt, licenses/THIRD_PARTY_NOTICES.txt, src/Agent/NewRelic/Agent/Extensions/Providers/Storage/CallContext/readme.md
Update `http://` links to be `https://` in documentation files in our repo.  This includes markdown files as well as licenses and our third party notices files.
This also replaces the third party notice for `log4net` with `Serilog`, since we update the agent's logging library a few releases ago.
=> chore: https links in documentation files

.github/workflows/publish_release_notes.yml
Fix a minor issue with the workflow that generates the release notes PR for the docs website; it was using a hardcoded version string of 10.13.0 to create the branch instead of the actual release version.
=> ci: Use actual release version for release notes branch

src/Agent/NewRelic/Agent/Core/BrowserMonitoring/BrowserScriptInjectionHelper.cs, src/Agent/NewRelic/Agent/Core/BrowserMonitoring/BrowserScriptInjectionIndexHelper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore6Plus/BrowserInjectingStreamWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore6Plus/BrowserInjectionMiddleware.cs, tests/Agent/IntegrationTests/Applications/BasicAspNetCoreRazorApplication/Program.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/JavaScriptAgent.cs, tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/BrowserAgentAutoInjection6Plus.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/BasicAspNetCoreRazorApplicationFixture.cs
Adds more defensive coding and exception handling during ASP.NET Core 6+ browser agent injection. Also adds an integration test to validate that we're handling responses that don't set a `ContentType` header. 
Resolves #2035
=> fix: Defensive coding and exception handling during ASP.NET Core 6+ browser injection

tests/Agent/IntegrationTests/ContainerIntegrationTests/LinuxKafkaTests.cs
Uses a different random number generator for the kafka topic names, in hopes of squashing the name collision failures in the smoke tests.
=> test: Improve random topic naming for Kafka integration tests

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Toggles the default vale for the `EnableAspNetCore6PlusBrowserInjection` setting to `false`. This will disable browser injection unless explicitly enabled in `newrelic.config`.
=> chore: Disable ASP.NET Core 6+ browser injection by default.

tests/Agent/IntegrationTests/IntegrationTests/BasicInstrumentation/BasicAspNetCoreRazorTests.cs
Needed to enable browser injection for this test after it was disabled by default in the agent.
=> tests: Enable AspNetCore6 browser injection for razor test

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore6Plus/BrowserInjectingStreamWrapper.cs
Adds a check during browser agent injection for ASP.NET Core 6+ to determine if response headers have already been sent and only sets `Response.ContentLength` if headers have *not* been sent. 
Resolves #2051
=> fix: During browser agent injection, don't set ContentLength if headers have already been sent. (#2051)

CONTRIBUTING.md
New Relic no longer hosts newrelicusers.slack.com for community members.
=> chore: Remove public Slack info from CONTRIBUTING.md

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Update the latest tested versions of StackExchange.Redis, mysqlconnector, and Serilog.
Corresponding docs update PR: https://github.com/newrelic/docs-website/pull/15262
=> chore: update latest tested versions of core tech libraries

src/Agent/NewRelic/Agent/Core/Core.csproj, src/Agent/NewRelic/Agent/Core/Logging/AuditLog.cs, src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs, src/Agent/NewRelic/Agent/Core/Logging/ProcessIdEnricher.cs, src/Agent/NewRelic/Agent/Core/Logging/ThreadIdEnricher.cs, src/Agent/NewRelic/Agent/Core/Logging/UTCTimestampEnricher.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Owin/Owin.csproj, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/WebApi1/WebApi1.csproj, tests/Agent/IntegrationTests/IntegrationTests/AgentLogs/LogFileFormatTests.cs
Removes the dependency on the `Serilog.Expressions` package, which resolves issues experienced by some customers where the agent does not report data and does not create a log file. 
Added a new log enricher for the required timestamp format in the log file. Updated existing log enrichers to improve performance where possible.
An integration test was added to validate that the logfile output is in the expected format.
Resolves #2083 
Props to @chynesNR for sleuthing this one!
=> fix: Remove dependency on Serilog.Expressions.

tests/Agent/IntegrationTests/ContainerApplications/docker-compose.yml, tests/Agent/IntegrationTests/ContainerIntegrationTests/ContainerFixtures/ContainerApplication.cs
Updated linux smoke tests so that we don't try to prune the networks at the end of every container execution -- it looks like there are occasional concurrency issues where a network gets deleted out from under a container that's firing up.
=> chore: update linux smoke tests to only remove networks in debug build

tests/Agent/IntegrationTests/ContainerIntegrationTests/ContainerFixtures/ContainerApplication.cs
Minor change to log the actual container name when running container integration tests. Hoping it will help with diagnosing intermittent test failures.
=> ci: Use actual container name in logging

tests/Agent/IntegrationTests/ContainerApplications/docker-compose-kafka.yml, tests/Agent/IntegrationTests/ContainerApplications/docker-compose-smoketestapp.yml, tests/Agent/IntegrationTests/ContainerApplications/docker-compose.yml, tests/Agent/IntegrationTests/ContainerIntegrationTests.sln, tests/Agent/IntegrationTests/ContainerIntegrationTests/ContainerFixtures/ContainerApplication.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/ContainerFixtures/LinuxKafkaTestFixtures.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/LinuxKafkaTests.cs
Refactors the Kafka integration tests so they can run in parallel and have no conflicts with the other integration tests. 
* Moves the `smoketestapp` service to a separate docker compose file, which is then referenced by each service that extends that service.
* Move the Kafka test services to a separate docker compose file. This eliminates the need for a unique network name each time these tests run and allows the `kafka-broker` service to be shared between the two tests. 
* Added an additional parameter to specify the docker-compose file to use when running `docker compose ....` during the test. 
* Refactored so that each test runs in a separate container "project", rather than starting different services in the same container. This makes the tests truly isolated from each other and …
=> test: Refactor kafka integration tests to reduce flickers

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Updates integration tests for nlog to use v5.2.7
Resolves #2102
=> test: Update nlog to 5.2.7

tests/Agent/IntegrationTests/IntegrationTestHelpers/AuditLogFile.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplicationFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/AuditLogTests.cs
Adds integration tests for Audit logging. Primarily just validates that the logfile exists and contains the expected number of sent and received lines.
Resolves #2030
=> test: Add integration tests for Audit logging.

tests/Agent/IntegrationTests/ContainerApplications/SmokeTestApp/Dockerfile.amazon, tests/Agent/IntegrationTests/ContainerApplications/docker-compose.yml
Updates `Dockerfile.amazon` to install the ASP.NET Core runtime manually rather than via a package manager. The previous method doesn't include support for .NET 8 and using `dnf` to actually install the runtime takes about 20 minutes. So we install the packages needed for a manual dotnet install and then install dotnet using a script.
=> test: Amazon Arm64 container test wasn't using an Amazon linux image. Now it is.

.github/workflows/all_solutions.yml, .github/workflows/build_profiler.yml, src/Agent/NewRelic/Home/Home.csproj, tests/Agent/IntegrationTests/ContainerApplications/SmokeTestApp/Controllers/WeatherForecastController.cs, tests/Agent/IntegrationTests/ContainerApplications/SmokeTestApp/SmokeTestApp.csproj, tests/Agent/IntegrationTests/ContainerApplications/docker-compose.yml, tests/Agent/IntegrationTests/ContainerIntegrationTests/ContainerFixtures/LinuxUnicodeLogFileTestFixture.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/LinuxUnicodeLogFileTest.cs
Updates the profiler log file initialization to imbue a locale with a codecvt facet so that character codes can be mapped more appropriately. 
This change was tested locally on Windows and Linux. For Linux this was manually tested using the same distros and architectures used by our Linux smoke tests.
Fixes #1982
=> fix: Fix a crash that can occur when the profiler logs certain characters. (#1982)

src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/JsonConverters/MetricWireModelJsonConverter.cs, src/Agent/NewRelic/Agent/Core/Metrics/ApiSupportabilityMetricCounters.cs, src/Agent/NewRelic/Agent/Core/Metrics/CATSupportabilityMetricCounters.cs, src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs, tests/Agent/UnitTests/CompositeTests/Assertions.cs, tests/Agent/UnitTests/CompositeTests/AsyncLocalStorageContextTests.cs, tests/Agent/UnitTests/CompositeTests/StackExchangeRedisSessionCacheTests.cs, tests/Agent/UnitTests/CompositeTests/TransactionTests.cs, tests/Agent/UnitTests/Core.UnitTest/AgentHealth/AgentHealthReporterTests.cs, tests/Agent/UnitTests/Core.UnitTest/Aggregators/MetricAggregatorTests.cs, tests/Agent/UnitTests/Core.UnitTest/Aggregators/MetricStatsCollectionTests.cs, tests/Agent/UnitTests/Core.UnitTest/Metrics/ApiSupportabilityMetricCountersTests.cs, tests/Agent/UnitTests/Core.UnitTest/Metrics/CATSupportabilityMetricCounterTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/GCStatsSampleTransformerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/MemorySampleTransformerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/ThreadStatsSampleTransformerTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/MetricBuilderTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/MetricWireModelTests.cs
Resolves a naming conflict in `MetricWireModel` by renaming a couple of public properties and refactoring references to those properties as needed.
Resolves #1900
=> chore: Fix MetricName conflict in MetricWireModel.

tests/Agent/IntegrationTests/ContainerApplications/CustomBaseContainerBuild/Dockerfile.AmazonBaseImage, tests/Agent/IntegrationTests/ContainerApplications/CustomBaseContainerBuild/Dockerfile.FedoraBaseImage, tests/Agent/IntegrationTests/ContainerApplications/CustomBaseContainerBuild/README.md, tests/Agent/IntegrationTests/ContainerApplications/SmokeTestApp/Dockerfile.amazon
Updates `Dockerfile.amazon` to use a pre-built Amazon Linux image that has ASP.NET Core already installed, served from the DotNetReg private Azure container registry under our .NET Team Sandbox Azure subscription. This will significantly reduce the execution time for the Amazon container integration tests, specifically the arm64 version of that test.
Also includes instructions and a couple of new Dockerfiles to allow rebuilding the custom images.
=> test: Use a pre-built Amazon Linux image with ASP.NET Core already installed

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Updates integration tests to include `Microsoft.Extensions.Logging` v8.0.0 in the FWLatest and CoreLatest tests.
Resolves #2073
=> test: Update integration tests to include Microsoft.Extensions.Logging v8.0.0

tests/Agent/IntegrationTests/IntegrationTests/Api/ApiCallsTests.cs
Disabling EventListenerSamplers in another integration test to eliminate .NET 8 test failure/flickers. 
Ref: https://github.com/newrelic/newrelic-dotnet-agent/actions/runs/7105662195/job/19344415498#step:9:153
=> test: Disable EventListenerSamplers in ApiCalls tests

src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs, tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/EnvironmentTests.cs
Fixes #2081 by adding `appsettings.Production.json` to the list of files to search by default for New Relic config settings.  In addition, the agent will now look at `DOTNET_ENVIRONMENT` in addition to `ASPNETCORE_ENVIRONMENT` to determine the specific environment configured for the agent.
=> fix: improve handling of .NET environments and settings from appsettings.*.json files

.github/workflows/post_deploy_agent.yml
Fixes a bug in the post deploy workflow that was preventing the apt / yum repo validation steps from delaying for 5 minutes when called from another workflow.
=> ci: Fix bug in post deploy workflow

.github/workflows/all_solutions.yml, .github/workflows/deploy_agent.yml, .github/workflows/post_deploy_agent.yml, .github/workflows/publish_release_notes.yml, deploy/linux/deploy.bash
* Modifies `deploy.bash` to export a magic environment variable that keeps the aws cli from failing when running on a github hosted runner. Resolves #2140 
* Modifies the `deploy_agent` workflow so that it checks out the repo and uses the files in the deploy folder rather than downloading those files from the build artifact uploaded from the `all_solutions` workflow. This was necessary to allow for testing changes to the linux deploy Dockerfile and scripts.
* Removes the `deploy` folder from `deploy-artifacts` in the `all_solutions` workflow.
* Attempts (yet again) to fix a bug in the `post_deploy_agent` workflow where we want the workflow to delay 5 minutes when called from another workflow but not when invoked manually.
* Removes the (unnecessary) `get-external-artifacts` job from the …
=> ci: Deploy workflow fixes and other goodies

src/Agent/NewRelic/Agent/Core/AgentInstallConfiguration.cs
Update the hard-coded pathing in `GetAgentInfo()` to use `Path.Combine()` instead for Linux compatibility. 
Fixes #2156.
=> fix: Path to agentinfo.json was built incorrectly, leading to file not found errors when running on Linux. (#2156)

.github/workflows/all_solutions.yml, .github/workflows/run_integration_tests.yml, docs/integration-tests.md
Fix the main agent CI workflow after merging breaking artifacts changes (v3->v4) in Dependabot PRs.  The main issue is that you can't upload multiple artifacts to the same artifact name.  This is only really a problem for the matrixed integration test jobs.  The fix is to use a unique artifact name based on the matrix namespace value.  Additionally, the workflow is modified to only archive the test results on failure since it's highly unlikely anybody wants to look at them if everything passes.
An additional breaking change from artifacts v3->v4 is a limit on the number of artifacts that can be uploaded per job (10).  This means that if more than ten namespaces have integration tests failures, we would have failures uploading some of the test working directories and results files. …
=> ci: Update to artifacts v4

tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
Multiple threads were trying to add to the (unsynchronized) `List<T>`. A `ConcurrentBag<T>` fixed that right smart quick...
=> test: Fix flicker in SpanStreamingServiceTests

.github/workflows/codeql.yml, .github/workflows/scripts/nugetSlackNotifications/nugetSlackNotifications.csproj, Directory.Build.props, build/ArtifactBuilder/ArtifactBuilder.csproj, build/NugetValidator/NugetValidator.csproj, build/NugetVersionDeprecator/NugetVersionDeprecator.csproj, build/ReleaseNotesBuilder/ReleaseNotesBuilder.csproj, build/S3Validator/S3Validator.csproj, src/Agent/NewRelic.Api.Agent/Directory.Build.props, src/Agent/NewRelic/Agent/Directory.Build.props, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore6Plus/AspNetCore6Plus.csproj, src/Directory.Build.props, tests/Agent/IntegrationTests/Applications/AspNetCoreFeatures/AspNetCoreFeatures.csproj, tests/Agent/IntegrationTests/Applications/BasicAspNetCoreRazorApplication/BasicAspNetCoreRazorApplication.csproj, tests/Agent/IntegrationTests/Applications/BasicMvcApplication/BasicMvcApplication.csproj, tests/Agent/IntegrationTests/ContainerApplications/KafkaTestApp/KafkaTestApp.csproj, tests/Agent/IntegrationTests/ContainerApplications/SmokeTestApp/SmokeTestApp.csproj, tests/Agent/IntegrationTests/ContainerIntegrationTests/ContainerIntegrationTests.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationCore/ConsoleMultiFunctionApplicationCore.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj, tests/Agent/UnitTests/Core.UnitTest/Core.UnitTest.csproj, tests/AwsLambda/UnitTests/AwsLambdaWrapperTests/AwsLambdaWrapperTests.csproj
This PR introduces a new workflow to run CodeQL, superseding the "default" configuration that was recently enabled for all repos in the New Relic org. 
~~For the time being, we will only scan C# projects, as we can (apparently) have only a single CodeQL workflow per repo, and our C++ projects have to build on Windows 2019, while our C# projects have to build on Windows 2022.~~
I was able to get the scan to run on both C# and C++. Yay! 
Results for the analysis on this PR are at: https://github.com/newrelic/newrelic-dotnet-agent/security/code-scanning?query=tool%3ACodeQL+pr%3A2159 -- there doesn't seem to be anything for C++, so I guess that code is solid. The other items reported for C# are either used in tests or false positives.
The other (somewhat huge) set of changes in this PR is to …
=> ci: Configure CodeQL Workflow, Unify <langVersion>

tests/Agent/IntegrationTests/ContainerIntegrationTests/Applications/ContainerApplication.cs
The `NEW_RELIC_APP_NAME` value we're currently using in our container integration tests is causing a ridiculous proliferation of APM services in the staging environment since every run of every container includes a random id at the end of the name. This change removes the random id from the service name and should result in only a handful of distinct APM services in staging.
=> test: Reduce APM service name proliferation in container tests

src/Agent/NewRelic/Agent/Core/AgentShim.cs, tests/Agent/IntegrationTests/Applications/ConsoleInstrumentationStartup/ConsoleInstrumentationStartup.csproj, tests/Agent/IntegrationTests/Applications/ConsoleInstrumentationStartup/Program.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs, tests/Agent/IntegrationTests/IntegrationTests.sln, tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/InstrumentationStartupDeadlockTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/ConsoleInstrumentationStartupFixture.cs
This PR changes how the agent is initialized when running on the .NET Standard 2.0 build target so that it uses the same "deferred" initialization pattern that the .NET Framework build target currently uses. This will eliminate an intermittent deadlock that has been observed at agent startup which has the unfortunate side effect of freezing the customer application.
A new integration test was added that verifies the agent does not deadlock. This test was run against the agent from the current `main` branch and failed; the same test was run against this PR branch and succeeded.
Fixes #2183
=> fix: Eliminate intermittent deadlock on agent startup. (#2183)

src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/StackExchangeRedis2Plus/ConnectWrapperV2.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/StackExchangeRedis2Plus/SessionCache.cs
Prevents an edge case where multiple `SessionCache` instances could get created if `StackExchange.Redis.ConnectionMultiplexer.CreateMultiplexer()` is called multiple times. 
Improves resiliency in `SessionCache.Cleanup()` and adds logging.
Fixes #2180
=> fix: Prevent multiple SessionCache instances from being created. (#2180)

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Updates `System.Data.SqlClient` to v4.8.6
Fixes #2182
=> test(deps): Bump System.Data.SqlClient to 4.8.6 in unbounded tests. (#2182)

src/Agent/NewRelic/Agent/Core/JsonConverters/LoadedModuleWireModelCollectionJsonConverter.cs, src/Agent/NewRelic/Agent/Core/WireModels/LoadedModuleWireModelCollection.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LoadedModuleWireModelCollectionJsonConverterTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LoadedModuleWireModelCollectionTests.cs
Adds defensive coding to prevent null reference exceptions while serializing `LoadedModuleWireModelCollection`. Improves unit tests to check for null values.
Fixes #2185
=> fix: Prevent null reference exceptions while serializing LoadedModuleWireModelCollection. (#2185)

tests/Agent/IntegrationTests/IntegrationTests/Errors/ExpectedErrorTests.cs
Minor tweak in `ExpectedErrorTests` to help eliminate a flicker. An overnight CI run failed because metric and error harvest happened at the same time.
=> test: Timing adjustment in ExpectedErrorTests

.github/workflows/awslambda_release.yml, .github/workflows/deploy_agent.yml, .github/workflows/publish_release_notes.yml, .github/workflows/siteextension_release.yml
The pathing for some of our build artifacts changed due to some recent workflow changes. This is the branch I ran the Deploy workflow from, so it should be good to go.
=> Deploy workflow fixes

src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/Profiler/CorProfilerCallbackImpl.h
This PR fixes an issue with certain Profiler log messages that used the `_X()` macro to convert a string. On Linux platforms, those messages would print out as an address (like `0x7fc4e6afc77c`) rather than the string content. Modifying the log messages to use the `L` prefix instead results in the messages printing correctly as expected. 
There may be a deeper issue, but there were only a handful of log messages using `_X()` and I've changed the ones that might get emitted on Linux to `L` instead.
I also confirmed that this isn't an issue related to an old .NET Core version or an old Linux distro -- the test app I used to reproduce this issue behaved the same when built on the latest .NET SDK and Runtime. 
Fixes #2200
=> fix: Certain Profiler log messages did not print correctly when running under Linux. (#2200)

src/Agent/NewRelic.Api.Agent/NewRelic.Api.Agent.csproj, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/NewRelic.Agent.Extensions.csproj
Applying changes from two current Dependabot PRs so that we can validate the full solution build and test.
See #2205 and #2206 for reference.
=> chore(deps): Bump System.Reflection.Emit.Lightweight from 4.3.0 to 4.7.0 and bump Microsoft.CSharp from 4.5.0 to 4.7.0.

src/Agent/NewRelic/Agent/Core/Config/ConfigurationTracker.cs, src/Agent/NewRelic/Agent/Core/INativeMethods.cs, src/Agent/NewRelic/Agent/Core/NativeMethods.cs, src/Agent/NewRelic/Profiler/Profiler/CorProfilerCallbackImpl.h
Updates the managed agent to notify the profiler if the newrelic.config files changes. Updates the profiler so that it includes a method invoked by the managed agent so that it can reload the newrelic config, and update some of the logging settings. These changes allow the profiler log level to change without restarting the application.
This code was testing manually, with and without an updated profiler. Without an updated profiler, the agent logs an error stating that it couldn't notify the profiler about the configuration changing. With an updated profiler, the profiler log level was successfully changed and …
=> feat: Allow profiler to respond to log level changes.

tests/Agent/IntegrationTests/IntegrationTests/BasicInstrumentation/NetCoreAsyncTests.cs
Minor tweak to help prevent `Internal CLR Error` exceptions in `NetCoreAsyncTests`.
=> test: Disable event listener sampler for NetCoreAsyncTests to help stabilize ci runs.

src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h, src/Agent/NewRelic/Profiler/ConfigurationTest/InstrumentationConfigurationTest.cpp, src/Agent/NewRelic/Profiler/MethodRewriterTest/MethodRewriterTest.cpp, src/Agent/NewRelic/Profiler/Profiler/CorProfilerCallbackImpl.h
Updates the profiler to refresh the ignored instrumentation list. Applies the ignore list check to the collection of instrumentation points instead of functions so that we can get consistent behavior in all of the places that check instrumentation points.
These changes were validated manually by disabling and re-enabling some built in instrumentation.
=> feat: Update profiler to support responding to changes in ignored instrumentation.

tests/Agent/IntegrationTests/Applications/BasicMvcApplication/Views/Default/Index.cshtml
We have some integration tests that verify whether browser agent auto-injection is working as it should.  I found that these tests were still passing in a scenario where I would expect them to fail (browser agent version 1.219.0, with a .NET agent version older than 10.2.0).  The reason the tests were not failing as expected is because there was no `<meta http-equiv="X-UA-Compatible" content="IE=edge" />` tag in the webpage being tested for automatic browser agent injection.  This PR adds the tag.  I verified that the tests failed as expected in the scenario I was testing after making this change.
=> test: make browser agent injection tests break when they should

src/Agent/NewRelic/Agent/Core/Core.csproj, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/NewRelic.Agent.Extensions.csproj, src/Agent/NewRelic/Agent/Parsing/Parsing.csproj, src/NewRelic.Core/NewRelic.Core.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/SharedApplicationHelpers/ReflectionHelpers/ReflectionUtil.cs
This change is to enabled embedded PDBs in our debug builds of ILRepacked assemblies, to facilitate local debugging. 
This is intended to be a temporary change, pending resolution of an [issue where the DLL is written with an incorrect path to the .PDB file](https://github.com/gluck/il-repack/issues/352). 
There is no change to the release build at all.
=> chore: Change debug type to "embedded" instead of "PDB"

src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/Configuration/Configuration.h, src/Agent/NewRelic/Profiler/ConfigurationTest/IgnoreInstrumentationTest.cpp, tests/Agent/IntegrationTests/IntegrationTestHelpers/CommonUtils.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Updates the the ignored instrumentation configuration to appear either before or after the applications element in the instrumentation element. This will prevent the managed agent from reporting a configuration error if the ordering isn't what we expect. The code already did not care what order the elements appeared in.
The different xml layouts were tested manually.
=> feat: Update configuration.xsd to allow ignored instrumentation to appear in any order.

.github/workflows/all_solutions.yml, .github/workflows/run_integration_tests.yml
Use the same secrets in both kinds of integration tests.
Test run: https://github.com/newrelic/newrelic-dotnet-agent/actions/runs/7993740794
=> ci: consolidate test secrets

src/Agent/NewRelic/Agent/Core/Utilization/VendorInfo.cs, tests/Agent/UnitTests/Core.UnitTest/Utilization/VendorInfoTests.cs
Fixes #2256 by adding additional logic to try and parse the container ID out of cgroup v1 data if the newer regex fails to find anything.  Includes a new unit test to verify the intended result.
=> fix: Use original regex to get container id from cgroup v1 in fallback case

tests/Agent/IntegrationTests/IntegrationTests/IntegrationTests.csproj, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/BasicAspWebServiceFixture.cs
Removes a third-party Selenium driver package that is no longer needed, as Selenium will now download the required web driver and browser as needed for testing. Code was updated to use the Chromium web driver instead of Edge.
=> test: Fixes an issue with the Selenium web driver usage in BasicAspWebServiceFixture.

src/Agent/NewRelic/Agent/Core/Utilization/VendorInfo.cs, tests/Agent/UnitTests/Core.UnitTest/Utilization/VendorInfoTests.cs
Updates our container id parsing logic for CGroup v1 to match the agent spec and removes the "fallback" lookup we recently added. The spec requires that we find a line that has `cpu` in it and contains a 64-character hexadecimal string. The container ID is the 64-character string.
The logic should find a container id of `47cbd16b77c50cbf71401c069cd2189f0e659af17d5a2daca3bddf59d8a870b2` when parsing any of the following lines in `/proc/self/cgroup`:
```
1:cpuset:/docker/47cbd16b77c50cbf71401c069cd2189f0e659af17d5a2daca3bddf59d8a870b2
2:cpu:/docker/47cbd16b77c50cbf71401c069cd2189f0e659af17d5a2daca3bddf59d8a870b2
3:cpuacct,cpu:/docker/47cbd16b77c50cbf71401c069cd2189f0e659af17d5a2daca3bddf59d8a870b2
4:memory,cpu,cpuset:/docker/47cbd16b77c50cbf71401c069cd2189f0e659af17d5a2daca3bddf59d8a870b2 …
```
=> fix: Update regex parsing for CGroup v1 to match agent spec.

build/ReleaseNotesBuilder/data.yml
Makes a very minor change to the release notes builder to use wording that the docs team seems to want, based on a change to our most recent release notes PR.
=> chore: Minor verbiage change for the release notes builder

src/Agent/NewRelic/Agent/Core/AgentManager.cs, src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionManager.cs, src/Agent/NewRelic/Agent/Core/DependencyInjection/AgentServices.cs
Remove Autofac registration of `IConnectionManager` and `IConnectionHandler` when in Serverless mode. This ensures that there is no way to attempt to connect or reconnect to the collector.
=> Don't register IConnectionHandler or IConnectionManager in Serverless mode.

tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/EnvironmentTests.cs
Found another test that fails intermittently with `Internal CLR Error` https://github.com/newrelic/newrelic-dotnet-agent/actions/runs/8087172617/job/22098992766?pr=2289#step:9:84
=> test: Fix a .NET 8 integration test flicker in EnvironmentTests

src/Agent/NewRelic/Agent/Core/Config/configurationPartial.cs, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
* Disables CAT when in Serverless mode
* Adds support for `NEW_RELIC_APDEX_T` environment variable to set ApdexT when in Serverless mode
=> Miscellaneous config updates for serverless mode

.github/workflows/run_unit_tests.yml
Modifies the unit test workflow to run on a push to any `feature/*` branch. This will ensure that we have code coverage reports for the feature branch, which will make it easier to see the code coverage changes during PRs to the feature branch.
=> ci: Add support for running unit tests on feature branches

.github/workflows/run_unit_tests.yml
Ensures  that unit tests and code coverage will run on every push to `main` or `feature/*`, even if no files were changed.
=> ci: Update unit test workflow to always run on a push, even if there were no modified files.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/Instrumentation.xml, src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/Common/AssemblyVersion.h, src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h, src/Agent/NewRelic/Profiler/Configuration/Strings.h, src/Agent/NewRelic/Profiler/ConfigurationTest/IgnoreInstrumentationTest.cpp, src/Agent/NewRelic/Profiler/ConfigurationTest/InstrumentationConfigurationTest.cpp, src/Agent/NewRelic/Profiler/MethodRewriter/Instrumentors.h, src/Agent/NewRelic/Profiler/Profiler/CorProfilerCallbackImpl.h
This adds the ability to add an instrumentation point to the Profiler via an environment variable, `AWS_LAMBDA_FUNCTION_NAME`, in the format `assembly::class::method`. If the variable is not in the correct format it will log a Warning but continue running. It does not attempt to verify that the method exists.
The environment variable can be added at any point during the startup sequence and the Profiler will pick it up (as long as the method hasn't been invoked yet)..
When the named method is invoked it will call the wrapper `NewRelic.Providers.Wrapper.AwsLambda.HandlerMethod` in the managed Agent.
Unit tests are included.
This also removes the hard-coded method name in the `instrumentation.xml` that was used in the POC branch.
=> Add serverless mode support to Profiler

.github/dependabot.yml
Updates `dependabot.yml` to use the recently-added `groups` configuration which will group all updates for a single package ecosystem into a single PR, hopefully helping to reduce a bit of toil on our end. 
(Unfortunately, because of our use case where we have multiple entries for the `nuget` ecosystem, the [grouping doesn't quite work yet](https://github.com/dependabot/dependabot-core/issues/7547) and we'll still see multiple PRs for NuGet updates if they occur across different projects - I included the configuration anyway so it'll start working automatically when it's supported.)
=> ci: Add groups to dependabot.yml

.github/workflows/build_profiler.yml
Modifies the `build_profiler` workflow to: 
* Remove the check for modified files
* Run the Windows profiler build, unit tests and code coverage, Linux amd64 and arm64 builds on a push to `main` or `feature/**`, and on every pull request. 
* Modifies the input parameters for manual calls or calls from other workflows to have only a `Deploy NuGet Package` option, defaulting to `false`.
=> ci: Profiler build workflow updates

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Llm/EventHelper.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Llm/LlmErrorData.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Bedrock/InvokeModelAsyncWrapper.cs
Error handling for Bedrock, based on requirements in the spec. Generates error events similar to 
```
["BW7NK7CFbFXrAAQqrgglOVll6NSgAAQBIQArJQEAAFys5SnXZAIECBONVAMACjEwLjIxLjAuMzQACU5SREQ1WlZUMwAVQUkgTW9uaXRvcmluZyBTaWduYWxS", {
"reservoir_size": 8,
"events_seen": 1
}, [[{
"duration": 19.778362,
"error.class": "Custom Error",
"error.message": "You don't have access to the model with the specified model ID.",
"externalCallCount": 1.0,
"externalDuration": 0.6889039874076843,
"guid": "3b38fb9cbda92a6d",
"priority": 1.2292109727859497,
"sampled": true,
"spanId": "81f43eaa26391287",
"timestamp": 1709757514125,
"traceId": "930d051d14fe639dba54c70ec91025a8",
"transactionName": "WebTransaction/ASP/chathub",
"type": "TransactionError"
}, {
"completion_id": "2c606da9-4262-4dca-bc75-ed8ffc0937e0", …
```
=> Implemented error handling for Bedrock

.github/workflows/deploy_agent.yml, .github/workflows/post_deploy_agent.yml, .github/workflows/publish_release_notes.yml
Fix #2284 by using the `inputs.` input values instead of `github.event.inputs`.  See: https://docs.github.com/en/actions/learn-github-actions/contexts#example-usage-of-the-inputs-context-in-a-reusable-workflow
Apparently the "github event context" of a called workflow is that of the _caller_, not the _callee_.  That's why `github.event.inputs` was working in the sub-workflows when we ran the deploy workflow and manually specified the agent version and run id (because the agent version and run_id would be inputs to the `deploy_agent` workflow), but not when the agent version and run id were determined automatically.
TL;DR use `inputs` not `github.event.inputs` when working with reusable workflows.
=> ci: Fix issues in post-deploy sub-workflows

.github/workflows/post_deploy_agent.yml
This should resolve the issue where the workflow didn't delay to wait for apt/yum to update, when called from an external workflow.
=> ci: Update `wait_for_apt_and_yum` default value to true on workflow_dispatch

.github/workflows/deploy_agent.yml, .github/workflows/deploy_awslambda.yml, .github/workflows/deploy_siteextension.yml, .github/workflows/multiverse_run.yml, .github/workflows/nuget_slack_notifications.yml, .github/workflows/run_integration_tests.yml, .github/workflows/run_linux_container_tests.yml
Updates all workflows to use `inputs` instead of `github.event.inputs` for consistency. 
See [this GitHub blog](https://github.blog/changelog/2022-06-10-github-actions-inputs-unified-across-manual-and-reusable-workflows/) for more information.
=> ci: Update all workflows to use `inputs` instead of `github.event.inputs`.

.github/workflows/post_deploy_agent.yml
I should have remembered to do this when I updated the TFM for NugetVersionDeprecator to net8.0 in this PR: https://github.com/newrelic/newrelic-dotnet-agent/pull/2280
=> ci: Update run and config paths for NugetVersionDeprecator to net8.0

.github/workflows/deploy_agent.yml, .github/workflows/post_deploy_agent.yml
This PR makes the following improvements to the post-deploy workflow:
1. Add a test-mode input that lets us run this workflow without creating duplicate GitHub issues for deprecated Nuget package versions
2. Switch from `dotnet build` to `dotnet publish` for the two Nuget validation/deprecation tools, so we don't have to hardcode the .NET version (TFM) in the execution path.
3. (Finally!) fix the logic for the `wait_for_apt_and_yum` option.  Thanks @tippmar-nr for figuring this one out.
=> ci: Improve post-deploy workflow

.github/workflows/all_solutions.yml
Based on a suggestion by @nrcventura, we will add the `run-linux-container-tests` job to the list of jobs that are checked for successful status in `integration-test-status`, which will allow us to remove the `run-linux-container-tests` job as a required status check. 
This (hopefully) will resolve the strange issues we've seen with PRs expecting a status from the container test job, even though that job was skipped.
Also adds a "harden runner" step to that job, which was overlooked when we initially created it.
=> ci: add the linux container test job to the list of jobs checked in `integration-test-status`

.github/workflows/codeql.yml
Updates the CodeQL action to check for modified files before running. Brings the behavior of this action in line with our other "top-level" actions (`all_solutions`, `run_unit_tests`),
=> ci: Add check for modified files before analyzing code

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/MicrosoftLoggingWrapper.cs
Fixing issue #2261.  When there are multiple logging providers registered, only the last provider will have the ExternalScopeProvider set to a non-null value.  Because of this, new relic's logic to pull the first ScopeLogger from the array causes context data to be missed.  The simple fix is to simply grab the last value in the array.
=> Fix issue #2261

tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogFile.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/ProfilerLogFile.cs, tests/Agent/IntegrationTests/IntegrationTests/AgentLogs/ChangeLogFilenameTests.cs, tests/Agent/IntegrationTests/IntegrationTests/AgentLogs/LogLevelAndDirectoryEnvironmentTests.cs
There were a couple of cases where the integration test harness was waiting for three minutes for an agent log to appear in the default location, that wasn't ever going to be created because the test case involved changing the log file name or directory.  This PR fixes that, as well as tweaking some names to be make more sense (to me, anyway).
=> tests: Speed up execution time of AgentLogs integration test namespace

src/Agent/NewRelic/Agent/Core/AgentManager.cs, src/Agent/NewRelic/Agent/Core/Config/BootstrapConfiguration.cs, src/Agent/NewRelic/Agent/Core/Config/ConfigurationLoader.cs, src/Agent/NewRelic/Agent/Core/Config/configurationPartial.cs, src/Agent/NewRelic/Agent/Core/Configuration/ConfigurationService.cs, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/InternalConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Attributes/AttributeDefinitionServiceTests.cs, tests/Agent/UnitTests/Core.UnitTest/Attributes/LogContextDataFilterTests.cs, tests/Agent/UnitTests/Core.UnitTest/Config/ServerlessModeConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/CrossAgentTests/DataTransport/CollectorHostNameTests.cs, tests/Agent/UnitTests/Core.UnitTest/CrossAgentTests/RumTests/RumClientConfigTests.cs, tests/Agent/UnitTests/Core.UnitTest/CrossAgentTests/ServerSentEvent/ServerSentEventTests.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs
The agent has a need for a separate bootstrap config that can be used before the configuration service is available. The serverless config is a current example of some of the settings that can be moved. With this change, the logic for the serverless config is now in a separate object from the local config.
This is the start of a path that we can take so that there are only 2 places in the code that control the logic of which "configuration source" takes precedence for all of the agent settings (DefaultConfiguration and BootstrapConfiguration). The BootstrapConfiguration can also be used by DefaultConfiguration so …
=> chore: Refactor serverless bootstrap config into a separate bootstrap config.

src/NewRelic.Core/Caching/SimpleCache.cs, tests/NewRelic.Core.Tests/NewRelic.Cache/SimpleCacheTests.cs
Addresses a unit test flicker in `SimpleCacheTests` by making `SimpleCache.MaintainCache()` public and calling it directly in the unit tests rather than relying on `Thread.Sleep(1000)` to let the timer make the call.
=> test: Modify SimpleCache to allow direct call to MaintainCache(), update unit tests.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MsSql/MicrosoftDataSqlClientExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MsSql/SystemDataExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MsSql/SystemDataSqlClientExerciser.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureUsingOdbcDriverTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureUsingOleDbDriverTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlConnectorTests.cs
Refactors the MS SQL stored procedure integration tests to combine the "with" and "without" @ parameterization into a single test, reducing the number of tests by 50%. Execution time for MSSQL tests dropped from about 19 minutes to about 15 minutes.
=> test: Refactor MSSQL stored procedure tests for better performance

src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionAttributeMaker.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs, tests/Agent/IntegrationTests/IntegrationTests/Errors/ErrorTraceMvc.cs, tests/Agent/IntegrationTests/IntegrationTests/Errors/ErrorTraceWebApi.cs, tests/Agent/IntegrationTests/IntegrationTests/Errors/ErrorTraceWebService.cs, tests/Agent/IntegrationTests/IntegrationTests/Owin/OwinCATChainTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/ErrorEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionEventMakerTests.cs
To insure proper linking of error events and error traces to transactions, the transaction ID (guid) needs to be added to the intrinsic attributes of error events and error traces, regardless of whether distributed tracing is enabled or not.
=> feat: Add transaction ID to intrinsic attributes for error events and traces regardless of DT/CAT settings

src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h, src/Agent/NewRelic/Profiler/MethodRewriter/Instrumentors.h, src/Agent/NewRelic/Profiler/Profiler/CorProfilerCallbackImpl.h
The previous solution for auto-detecting the lambda instrumentation point in the profiler would not work in many cases. Now we try two environment variables:
* `_HANDLER` which should be auto-populated but may not be available in all environments (notably the test tool)
* `NEW_RELIC_LAMBDA_FUNCTION_HANDLER` which the user must provide
This is now only checked on startup instead of prior to each method's compilation.
=> Use custom var and fallback for lambda instrumentation point

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MySql/MySqlConnectorExerciser.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlConnectorTests.cs
Added an intentional delay in one of the MySql queries to ensure that we always know it will be the slowest, which should address a recent frequently-occurring failure. This same change may need to be more widely applied if other flickers show up, but for now it's just focused on a single test.
=> test: Fix a MySql flicker by introducing an intentional delay

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/HandlerMethodWrapper.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
* Adds an override for `SamplingTarget` and `SamplingTargetPeriodInSeconds` when in Serverless mode, as per the spec. 
* Minor cleanup in the function handler wrapper.
=> More Lambda / DT configuration tweaks

tests/Agent/IntegrationTests/IntegrationTests/Errors/ExpectedErrorTests.cs
Adjusts harvest cycle timing, uses CallCountAllHarvests just for good measure.
=> test: Fix a flicker in ExpectedErrorTests

src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h, src/Agent/NewRelic/Profiler/Configuration/InstrumentationPoint.h
This could result in (among other issues) a non-async method being flagged as async, and therefore not instrumenting properly
=> Fix profiler bug with tracer flags not being set properly

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/AwsLambdaEventType.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/AwsLambdaEventTypeExtensions.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaAttributeExtensions.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaEventHelpers.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/NewRelic.Agent.Extensions.csproj, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/HandlerMethodWrapper.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/AwsLambdaEventTypeExtensionsTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/LambdaAttributeExtensionsTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/LambdaEventHelpersTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/AmazonAPIGatewayEventsModel.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/AmazonKinesisEventsModel.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/AmazonKinesisFirehoseEventsModel.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/AmazonLoadBalancerEventsModel.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/AmazonS3EventsModel.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/AmazonSNSEventsModel.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/AmazonSQSEventsModel.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/AmazonScheduledEventsModel.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/AmazonSimpleMailEventsModel.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/DistributedTraceHeaderModel.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/NewRelic.Agent.Extensions.Tests.csproj
Adds support for all event types called out in the Lambda spec, with unit tests for each.
There are still some TODOs that need to be worked out eventually but are not blockers for this PR.
It's also not clear (and won't be until we have working integration tests) how much additional null checking might be required - the current code assumes the dynamic properties it references exist and are non-null in almost all cases.
=> Lambda: Event Support & Tests

src/Agent/NewRelic/Agent/Core/Core.csproj, src/NewRelic.Core/NewRelic.Core.csproj
Updates to latest ILRepack, no changes that will affect us. 
Though it seems they changed their command line parameter switches from `--` to `/` somewhere along the way.
=> chore(deps): Bump ILRepack to 2.0.28, fix commandline parameter formatting

src/Agent/NewRelic/Agent/Parsing/StringsHelper.cs, tests/Agent/UnitTests/ParsingTests/ParsingTests.csproj, tests/Agent/UnitTests/ParsingTests/SqlParserTests.cs, tests/Agent/UnitTests/ParsingTests/SqlWrapperHelperTests.cs, tests/Agent/UnitTests/ParsingTests/StringsHelperTest.cs
Adds handling for `InvalidOperationException` that can be thrown in certain cases (.NET 6 and later) when calling `Uri.GetComponents()`. 
Updates unit tests for the Parsing project to target .NET 8 in addition to .NET Framework 4.6.2. Had to make a number of tests run only in .NET Framework due to references to Framework-specific types.
Fixes #2373.
=> fix: Handle InvalidOperationException in StringsHelper.CleanUri() #2373

.github/workflows/all_solutions.yml, .github/workflows/awslambda_release.yml, .github/workflows/build_profiler.yml, .github/workflows/check_modified_files.yml, .github/workflows/codeql.yml, .github/workflows/deploy_agent.yml, .github/workflows/markdowncheck.yml, .github/workflows/multiverse_run.yml, .github/workflows/nuget_slack_notifications.yml, .github/workflows/post_deploy_agent.yml, .github/workflows/publish_release_notes.yml, .github/workflows/repolinter.yml, .github/workflows/run_integration_tests.yml, .github/workflows/run_linux_container_tests.yml, .github/workflows/run_unit_tests.yml, .github/workflows/scorecard.yml, .github/workflows/siteextension_release.yml
Duplicating changes from the current Dependabot PRs so we can run a full CI and verify there aren't any issues.
FullAgent run: https://github.com/newrelic/newrelic-dotnet-agent/actions/runs/8441773866 -- all looks good; checkout is working as expected.
Can't directly test the CodeQL update because the workflow kicks out when no relevant files were modified.
=> chore(deps): Bump actions/checkout and github/codeql-action

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Bedrock/InvokeModelAsyncWrapper.cs, src/NewRelic.Core/JsonConverters/BedrockHelpers.cs, src/NewRelic.Core/JsonConverters/BedrockPayloads/ClaudePayloads.cs, src/NewRelic.Core/JsonConverters/BedrockPayloads/CohereCommandPayloads.cs, src/NewRelic.Core/JsonConverters/BedrockPayloads/JurassicPayloads.cs, src/NewRelic.Core/JsonConverters/BedrockPayloads/Llama2Payloads.cs, src/NewRelic.Core/JsonConverters/BedrockPayloads/PayloadInterfaces.cs, src/NewRelic.Core/JsonConverters/BedrockPayloads/README.md, src/NewRelic.Core/JsonConverters/BedrockPayloads/TitanPayloads.cs, src/NewRelic.Core/JsonConverters/JsonHelpers.cs
This PR moves the Bedrock request/response models and the deserialization of their corresponding JSON from the Bedrock wrapper project to `NewRelic.Core`, which ILRepacks `Newtonsoft.Json`, so it will always be available for use.
This prevents assembly load exceptions I found while testing the Bedrock instrumentation with a standalone test app that, unlike our integration test applications, did not include a reference to Newtonsoft.Json.
=> Move JSON deserialization and models to NewRelic.Core

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Elasticsearch/Instrumentation.xml, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
MySqlConnector 2.3.5 -> 2.3.6 Fixes #2357 
Elastic.Clients.ElasticSearch 8.12.0 -> 8.12.1 Fixes #2371
=> chore(deps): Bump MySqlConnector and ElasticSearch in unbounded tests

src/Agent/NewRelic/Agent/Core/DistributedTracing/AdaptiveSampler.cs, src/Agent/NewRelic/Agent/Core/Transactions/TransactionService.cs, tests/Agent/UnitTests/CompositeTests/ServerlessAdaptiveSamplerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transactions/TransactionBuilderServiceTests.cs
As best I can tell, this is all the spec is asking for: moving the adaptive sampling interval logic to the start of a Transaction when in serverless mode. Unit tests included.
=> Implement adaptive sampling according to Lambda DT spec

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Bedrock/InvokeModelAsyncWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/LLM/LLMErrorTests.cs
A matching `LlmChatCompletionMessage` also needs to be sent on error, even if we don't get a response.
Also updated the corresponding integration test.
(Just noticed the branch name is wrong; sorry about that)
=> Fix issue with errors not appearing in the UI

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/DataTransport/ServerlessModeDataTransportService.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/HandlerMethodWrapper.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Allow cases where the lambda context is missing, or data within it is missing.
Also force `CompleteTransactionsOnThread` to be enabled in serverless mode.
=> Feature work/lambda missing data

src/Agent/NewRelic/Agent/Core/Core.csproj, src/NewRelic.Core/NewRelic.Core.csproj
Bumps ILRepack and Google.Protobuf as called out in #2390 and #2391.
=> chore(deps): Bump ILRepack to 2.0.30, Google.Protobuf to 3.26.1

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchElasticClient.cs
The latest `Elastic.Clients.Elasticsearch` appears to have removed a helper extension that we were using to test the library. I found nothing in the release notes about it going away. The new test code supports both old and new versions. The new release also marks some methods we're using as deprecated, which was causing a warning-as-error build failure.
=> test: Test latest versions of Elastic.Clients.Elasticsearch and MongoDB.Driver

src/Agent/NewRelic/Agent/Core/DataTransport/ServerlessModeDataTransportService.cs, src/Agent/NewRelic/Agent/Core/DataTransport/ServerlessModePayloadManager.cs, src/Agent/NewRelic/Agent/Core/DependencyInjection/AgentServices.cs, src/Agent/NewRelic/Agent/Core/Utilities/FileWrapper.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ServerlessModePayloadManagerTests.cs, tests/Agent/UnitTests/Core.UnitTest/DependencyInjection/AgentServicesTests.cs
* Refactors `ServerlessModeDataTransport` to separate the payload management (building / writing) to a separate class (`ServerlessModePayloadManager`) to allow for unit testing. 
* Adds unit tests to verify that the payload created in serverless mode is correct, including metadata and verification of the compressed portion of the payload. 
Additional tests will be added for `ServerlessModeDataTransport` in a separate PR.
=> Refactoring and tests for serverless mode payload

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Bedrock/InvokeModelAsyncWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/LLM/BedrockTests.cs, tests/Agent/IntegrationTests/IntegrationTests/LLM/LLMDisabledTests.cs
* Don't send LLM Supportability metrics (i.e. `Supportability/DotNet/ML/[library]/[version]` if AIM is disabled. Sending it results in UI being enabled that shouldn't be, and incorrect tags being applied
* Also adds integration tests for verifying the metric in both the enabled and disabled cases
=> fix: Fix incorrectly tagging AIM data when AIM is disabled

tests/NewRelic.Core.Tests/NewRelic.Cache/SimpleCacheTests.cs
Adjusted a `.Sleep()` to wait long enough for the cache maintenance thread to do it's thing.
=> test: Fix a flicker in SimpleCacheTests

src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, src/Agent/NewRelic/Agent/Core/Transactions/NoOpTransaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ITransaction.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaAttributeExtensions.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaEventHelpers.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/HandlerMethodWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaMultipleInvocationsTest.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transactions/TransactionTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/LambdaAttributeExtensionsTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/LambdaEventHelpersTests.cs
Variant of https://github.com/newrelic/newrelic-dotnet-agent/pull/2414 (closed in favor of this PR)
- Adds new attribute definition and method for creating lambda specific attributes as agent attributes.
- Adds `AddLambdaAttribute(string name, string value)` method to `API/ITransaction` for adding Lambda specific attributes.
- Removes dictionary for attributes and instead adds them directly to the transaction, changing `LambdaAttributeExtensions` to support only one method.
- Updates `TransactionTests`, `TransactionAttributeMakerTests`, and `SpanEventMakerTests` to test that the new agent attribute is working properly.
- Updates `LambdaAttributeExtensionsTests` to call `AddLambdaAttribute` instead of `AddCustomAttribute`.
=> Feature work/lambda agent attributes variant

build/ArtifactBuilder/ArtifactBuilder.csproj, build/NugetValidator/NugetValidator.csproj, build/NugetVersionDeprecator/NugetVersionDeprecator.csproj, build/ReleaseNotesBuilder/ReleaseNotesBuilder.csproj, build/S3Validator/S3Validator.csproj
Update build tool projects to .NET 8.  I tested everything locally other than ReleaseNotesBuilder (complex test setup) and it all worked as expected.
=> chore: Update build tools to net8.0

.github/workflows/post_deploy_agent.yml, .github/workflows/publish_release_notes.yml
Modifies the S3Validator job in the post_deploy workflow to use `dotnet publish` so we can avoid a hard-coded output path that changes with .NET version updates.
Also updates the publish_release_notes workflow to follow the same pattern.
=> chore: Update S3Validator to use dotnet publish in post-deploy workflow

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/KafkaConsumerWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/KafkaProducerWrapper.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/KafkaTests.cs
There were actually two bugs when using Kafka with Distributed Tracing:
* If headers were not present, we weren't creating them (due to a scoping error)
* We were not checking to see if the keys already existed before adding them. This did not cause an immediate problem because the headers are kept in a list rather than a dictionary, but can cause a validation failure later.
The first bug kept us from finding the second problem in our integration tests. Both have been addressed.
=> fix: Fix duplicate key error when using Kafka with DT enabled

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaEventHelpers.cs, tests/Agent/UnitTests/Core.UnitTest/DistributedTracing/W3CTraceparentTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/LambdaEventHelpersTests.cs
Update SQS tracing header processing to handle W3C trace context data as well as the New Relic proprietary DT data.
Update unit tests to cover both cases alone and combined.
=> Parse W3C trace context payloads from SQS message body

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaEventHelpers.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/LambdaEventHelpersTests.cs
Adds more guard code and associated unit tests, checking for null/empty `.Records` properties in applicable event types.
=> Guard against null/empty records in applicable event types

tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/LambdaSelfExecutingAssembly.csproj, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/Program.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaAPIGatewayRequestTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaApplicationLoadBalancerRequestTest.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaAPIGatewayProxyRequestTriggerFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaApplicationLoadBalancerRequestTriggerFixture.cs
Adds tests for APIGatewayProxy and ApplicationLoadBalancer requests where the Lambda function returns `Stream` instead of the actual response type.
=> Lambda - Add tests for `Stream` return type

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/AwsLambdaEventTypeExtensions.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaEventHelpers.cs, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/LambdaSelfExecutingAssembly.csproj, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/Program.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaKinesisEventTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaKinesisFirehoseEventTest.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaKinesisEventTriggerFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaKinesisFirehoseEventTriggerFixture.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/AwsLambdaEventTypeExtensionsTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/LambdaEventHelpersTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/AmazonKinesisEventsModel.cs
Adds integration tests for kinesis streams and firehose lambda event triggers, and fixes the bugs in their current implementation.
For now the KinesisTimeWindowEvents are tested with json from the simpler KinesisEvent, because we do not extract any details from the additional properties.
=> Test and fix data collected for kinesis firehose and streams.

.github/workflows/nuget_slack_notifications.yml, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/LambdaSelfExecutingAssembly.csproj
I rolled everything back as far as I could without hitting version conflicts, and all the tests still pass.
This also adds the event libraries to Dotty so we can watch for breaking changes.
=> Test a range of lambda event library versions

src/Agent/NewRelic/Agent/Core/DistributedTracing/DistributedTracePayloadHandler.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs, tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/W3CInstrumentationTests/HttpClientW3CTestsNetCore.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AspNetCoreDistTraceRequestChainFixture.cs
When the agent is [configured to exclude the `newrelic` proprietary distributed tracing header](https://docs.newrelic.com/docs/apm/agents/net-agent/configuration/net-agent-configuration/#excludeNewrelicHeader)  on outbound traces (and rely solely on the W3C trace context headers instead), an exception could occur which would show up in agent logs like this:
```
NewRelic  ERROR: [pid: 5412, tid: 73] InsertDistributedTraceHeaders() failed
System.InvalidOperationException: Nullable object must have a value.
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
at NewRelic.Agent.Core.DistributedTracing.DistributedTracePayloadHandler.BuildTraceParent(IInternalTransaction transaction)
at NewRelic.Agent.Core.DistributedTracing.DistributedTracePayloadHandler.GetOutboundH …
```
=> fix: Fix bug in distributed tracing when `excludeNewrelicHeader` is set to true

.github/workflows/nuget_slack_notifications.yml, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaEventHelpers.cs, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/LambdaSelfExecutingAssembly.csproj, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/Program.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaSqsEventTest.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaSqsEventTriggerFixture.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/LambdaEventHelpersTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/AmazonSQSEventsModel.cs
- Adds capturing the messageId attribute for SQS to instrumentation.  Spec doesn't list this, but it seems odd to not include this (if we don't want this, we can remove it easily).
- Updates unit tests to check for this new attribute.
- Add integration tests for SQS events with some attribute changes.
=> Add integration tests for SQS events with some attribute changes.

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/AwsLambdaEventType.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/AwsLambdaEventTypeExtensions.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaEventHelpers.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/HandlerMethodWrapper.cs, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/Program.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaAPIGatewayHttpApiV2ProxyRequestTest.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaAPIGatewayHttpApiV2ProxyRequestTriggerFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaTestToolFixture.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/AwsLambdaEventTypeExtensionsTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/LambdaEventHelpersTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/AmazonAPIGatewayEventsModel.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/AmazonAPIGatewayV2EventsModel.cs
Adds support for `APIGatewayHttpApiV2ProxyRequest` and `APIGatewayHttpApiV2ProxyResponse` in AWS Lambda instrumentation. 
Includes unit and integration tests.
=> feat: Add support for AWS Lambda `APIGatewayHttpApiV2ProxyRequest`

.github/workflows/deploy_agent.yml, .github/workflows/post_deploy_agent.yml
Fixed a bug in how we were specifying the `--test_mode` flag for the NugetDeprecator.
=> ci: Fix test_mode flag in post_deploy_agent workflow

src/Agent/NewRelic/Agent/Core/AgentManager.cs, src/NewRelic.Core/DotnetVersion.cs, tests/NewRelic.Core.Tests/DotnetVersionTests.cs
Adds .NET 7 to the list of unsupported .NET versions, updates the warning message
Resolves #2429
=> chore: Deprecate .NET 7, update warning message.

src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/Program.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaTestToolFixture.cs
Changing `NEW_RELIC_LAMBDA_FUNCTION_HANDLER` to `NEW_RELIC_LAMBDA_HANDLER` to match what the other agents are using.
Requires rebuilding the Profiler, which will be included shortly.
=> chore: Update lambda handler environment variable to match other Agents

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
This PR resolves #2181 by introducing two new environment variables for configuring agent behavior:
`NEW_RELIC_ERROR_COLLECTOR_IGNORE_ERROR_CODES`
`NEW_RELIC_ERROR_COLLECTOR_EXPECTED_ERROR_CODES`
Both env vars support defining multiple HTTP status codes in a comma-separated list, e.g.:
`NEW_RELIC_ERROR_COLLECTOR_IGNORE_ERROR_CODES="401,503"`
The env var for expected error codes also supports defining a range of codes like this:
`NEW_RELIC_ERROR_COLLECTOR_EXPECTED_ERROR_CODES="401,500-505"`
The internal logic of the error collector doesn't currently support ranges for ignored error codes, hence the difference.
I will update the description of this PR with a link to the docs site update PR once that is created.
=> feat: Enable configuration of ignored and expected HTTP status code errors with environment variables

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/KafkaConsumerWrapper.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/KafkaTests.cs
This PR fixes a bug in our instrumentation for `Confluent.Kafka`.  On the message `Consume` side, we were not property processing inbound distributed tracing headers.  This is now fixed.
I verified with manual testing of two separate test applications, one a Kafka producer and the other a consumer, that before this change, the two application entities would not be shown as linked in the Distributed Tracing UI.  After this change, they are.
The Kafka containerized integration test is updated to assert for the relevant supportability metrics for trace context payload create and accept.
=> fix: Accept inbound tracing headers in Kafka consume method instrumentation

.github/workflows/deploy_agent.yml
Simple update to the existing deploy_agent workflow to create "version-less" `.zip` and `.tar.gz` files to make it easier to reference the "latest" release without needing to know a version number.
=> chore: Update deploy workflow to create version-less .zip and .tar.gz files

.github/workflows/deploy_agent.yml
The `.tar.gz` files in my previous PR were using the wrong name prefix. Copy pasta got me!
=> ci: fix bug in deploy_agent workflow

build/S3Validator/config.yml
Update the config of the S3Validator tool:
1. The MSIs are slightly smaller after the WIX version upgrade.
2. We have new versionless zips and tarballs to validate.
=> chore: update S3Validator config to expect different file sizes for MSIs, etc

src/Agent/NewRelic/Agent/Core/AgentManager.cs, src/Agent/NewRelic/Agent/Core/BrowserMonitoring/BrowserMonitoringScriptMaker.cs, tests/Agent/UnitTests/Core.UnitTest/BrowserMonitoring/BrowserMonitoringScriptMakerTests.cs
When running in Serverless mode, the Agent License Key is not required to be set (either in config or via an environment variable). 
This PR fixes #2499 by adding a check for serverless mode in `AgentManager.AssertAgentEnabled()`. Additionally,  when browser monitoring is enabled but the license key is not set, we now log a message rather than throwing an exception.
=> fix: Agent license key should be optional in Serverless mode.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/NServiceBus/Handlers/AsyncCommandHandler.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/NServiceBus/Handlers/AsyncEventHandler.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/NServiceBus/NServiceBusDriver.cs
Updates unbounded tests to use NServiceBus v8.2.0 and v9.0.0. 
Required a couple minor changes to the test code but no changes in instrumentation.
=> test: Update NServiceBus tests to include v8 and v9

tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/BasicMvcApplication.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj
This package appears to be unused.
=> tests: Remove references to Common.Logging

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/OpenTracingWrapper.cs
We've learned that our legacy OpenTracing solution will break our Agent running in serverless mode. To catch these use cases early, this will log a warning if the `LambdaTracer` constructor is called. It will look something like this:
```
2024-05-28 20:56:16,925 NewRelic   INFO: [pid: 19112, tid: 1] The New Relic agent is operating in serverless mode.
2024-05-28 20:56:16,964 NewRelic   INFO: [pid: 19112, tid: 1] The New Relic .NET Agent v10.25.0.3 started (pid 19112) on app domain 'My.Application'
2024-05-28 20:57:05,129 NewRelic   WARN: [pid: 19112, tid: 1] OpenTracing is not compatible with the full .NET Agent and may result in undefined behavior. Please remove OpenTracing from your application.
```
Since this is logging-only behavior, I didn't think an integration test was necessary.
=> chore: Warn if OpenTracing is detected

src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs, tests/Agent/UnitTests/CompositeTests/CrossAgentTests/SecurityPolicies/SecurityPoliciesCrossAgentTests.cs
Adds a new supportability metric, `Supportability/FeatureEnabled/CSP` when `IConfiguration.SecurityPoliciesTokenExists` is `true`, indicating that CSP is enabled. 
Also adds an assert in cross-agent tests for CSP to verify the metric is emitted.
Resolves #2265
=> chore: Adds a supportability metric when CSP is enabled

src/Agent/NewRelic/Agent/Core/Logging/Logger.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Logging/ILogger.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/MicrosoftLoggingWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/ContextDataTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/DummyMELAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/ILoggingAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/Log4NetLoggingAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/LoggingTester.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/MicrosoftLoggingLoggingAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/NLogExtensionsLoggingAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/NLogLoggingAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/SerilogExtensionsLoggingAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/SerilogLoggingAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/SerilogLoggingWebAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/SitecoreAdapter.cs
Fixes #2508 by modifying our logic for extracting context key/value pairs so that we retain the "innermost" value in cases where multiple contexts have the same key. 
Also updates Integration tests to verify this fix and adds an overload to `NewRelic.Agent.Extensions.Logging.ILogger` that allows an extension to report an exception in the same format that we use in the rest of the Agent.
=> fix: Nested logging contexts should not disable context data for Microsoft.Extensions.Logging

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RestSharp/RestSharp107andBeyondExerciser.cs
Updates the versions of elastic search and restsharp that we test against to the latest versions.
Resolves: #2504, #2517, #2515
=> chore: Update elasticsearch and restsharp libraries to latest versions in test apps.

tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaSmokeTest.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaTestToolFixture.cs
The lambda smoke tests will sometimes fail when the lambda method runs long enough to trigger a transaction trace when the test doesn't expect a transaction trace to be generated. In this PR we are flipping the logic around to ensure that a transaction trace is generated, and verify that it is included in the payload.
=> test: Fix lambda smoke test flicker.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MsSql/MicrosoftDataSqlClientExerciser.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlQueryParamTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj
Resolves #2522 
Edit: this also adds back testing for Microsoft.Data.SqlClient with the latest version of .NET (8.0); it was removed due to a gap in time where we had to update our testing to support 8.0 and this library didn't support 8.0 yet (it does now).
=> chore: Update latest tested version of Microsoft.Data.SqlClient to 5.2.1

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaEventHelpers.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaAPIGatewayHttpApiV2ProxyRequestTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaAPIGatewayRequestTest.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaAPIGatewayHttpApiV2ProxyRequestTriggerFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaAPIGatewayProxyRequestTriggerFixture.cs
This fixes a null reference exception that could occur when a minimal JSON payload was sent to to a Lambda function that take an `APIGatewayProxyRequest` or `APIGatewayHttpApiV2ProxyRequest`.
Includes integration tests to validate the fix.
Fixes #2528
=> fix: Prevent NullReferenceExeption on APIGatewayProxyRequest

tests/Agent/IntegrationTests/IntegrationTests/Errors/ExpectedErrorTests.cs
Need a bit more detail in the logs to figure out why ExpectedErrorTests sometimes fails
=> test: Set finest-level logging in ExpectedErrorTests for troubleshooting flickers

src/Agent/NewRelic/Agent/Core/DataTransport/Client/HttpClientBase.cs, src/Agent/NewRelic/Agent/Core/DataTransport/Client/HttpContentWrapper.cs, src/Agent/NewRelic/Agent/Core/DataTransport/Client/HttpResponse.cs, src/Agent/NewRelic/Agent/Core/DataTransport/Client/Interfaces/IHttpClient.cs, src/Agent/NewRelic/Agent/Core/DataTransport/Client/Interfaces/IHttpContentWrapper.cs, src/Agent/NewRelic/Agent/Core/DataTransport/Client/Interfaces/IHttpResponse.cs, src/Agent/NewRelic/Agent/Core/DataTransport/Client/NRHttpClient.cs, src/Agent/NewRelic/Agent/Core/DataTransport/Client/NRWebRequestClient.cs, src/Agent/NewRelic/Agent/Core/DataTransport/Client/WebRequestClientResponse.cs, src/Agent/NewRelic/Agent/Core/DataTransport/HttpCollectorWire.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/Client/HttpResponseTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/Client/NRHttpClientTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/Client/NRWebRequestClientTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/Client/WebRequestClientResponseTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/HttpCollectorWireTests.cs
Refactors `HttpCollectorWire.Send()` to remove usage of `.GetAwaiter().GetResult()`, which required additional refactoring in `IHttpClient` and `IHttpContentWrapper`. 
With this change, there are now no usages of `.GetAwaiter().GetResult()` in code built for the .NET Framework target.
Resolves #2534
=> fix: Refactor to eliminate usage of `.GetAwaiter().GetResult()` in Framework builds. (#2534)

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Log4NetLogging/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Log4NetLogging/SitecoreLoggingWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/ContextDataTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/LoggingTester.cs
A customer attempted to use Sitecore.Logging and log4net in the same application. Sitecore.Logging uses an old fork of log4net that has different properties, and the instrumentation was not built to handle both at once. The wrapper would throw errors and eventually be disabled. Now they will work side by side.
This also adds the ability to run integration tests on multiple loggers at once, in case we run into other similar logging conflicts in the future.
=> feat: Add support for using Sitecore.Logging and log4net together

.github/workflows/nuget_slack_notifications.yml, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Updates Serilog packages to latest version for the net481 and net8.0 build targets. These should have been caught by Dotty but were missed somehow. 
Also updates Dotty config to scan for additional serilog package updates.
=> chore(deps): Bump Serilog packages to latest version for net481 and net8.0 targets

Directory.Build.props, tests/Agent/IntegrationTests/Directory.Build.props
Adds a new `Directory.Build.props` file at `tests\Agent\IntegrationTests` and takes out the warnings that were suppressed in the global `Directory.Build.props` file at the root of the repo. 
I looked at whether it would be possible to update the code so we don't get those warnings, but it would have been a lot of work for almost zero gain. The specific warnings that are being suppressed aren't serious enough to warrant code changes, especially not in our integration test apps.
Resolve #1924
=> test: Move suppressed warnings closer to the integration test projects that generate them

.github/workflows/nuget_slack_notifications.yml, .github/workflows/scripts/nugetSlackNotifications/Program.cs, .github/workflows/scripts/nugetSlackNotifications/nugetSlackNotifications.csproj
This PR:
1. Fixes a bug in recent runs of this tool by updating to the latest Oktokit
2. Upgrades the tool to net8.0
3. Updates other dependencies
4. Updates the workflow to publish the tool and run from that location rather than hardcoding the output path including the .NET version TFM
Here's a successful run of the workflow from this branch: https://github.com/newrelic/newrelic-dotnet-agent/actions/runs/9503813056/job/26195081810
=> chore: Update core tech version scan tool dependencies

build/BuildTools.sln, build/NugetVersionDeprecator/NugetVersionDeprecator.csproj
Major version bump for Oktokit in `NugetVersionDeprecator`. 
Added `nugetSlackNotifications` project (Dotty) to the `BuildTools` solution so we can manage it along with our other tooling.
=> chore(deps): Bump Oktokit in NugetVersionDeprecator. Also adds Dotty to the BuildTools solution.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Resolves #2550 
Resolves #2551 
Docs site PR: https://github.com/newrelic/docs-website/pull/17655
=> chore: core tech updates 2024-06-14

tests/Agent/UnitTests/Core.UnitTest/BrowserMonitoring/BrowserMonitoringConfigurationDataTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ConnectModelTests.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LogEventWireModelCollectionJsonConverterTests.cs, tests/Agent/UnitTests/NewRelic.Agent.TestUtilities/JsonExtensions.cs
This ended up being more tedious than expected. Using raw string literals makes the code much more readable, but the tests are expecting an exact match, and I couldn't just strip the whitespace because some values contain spaces. For that I added an "unformatting" helper function.
=> test: Refactor tests using large single-line JSON strings

tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Add a pair of missing test cases for DisableFileSystemWatcher.
=> chore: Add missing test cases for DisableFileSystemWatcher setting.

src/Agent/NewRelic/Agent/Core/Utilization/VendorHttpApiRequestor.cs
For netstandard2.0, use HttpClient in VendorHttpApiRequestor.  Uses directives to switch between builds types.  No additional tests were needed.
Manual validation of changes was successful.
=> chore: For netstandard2.0, use HttpClient in VendorHttpApiRequestor.

src/Agent/NewRelic/Agent/Core/Wrapper/WrapperService.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/WrapperService.cs
As per our [documentation](https://docs.newrelic.com/docs/apm/agents/net-agent/other-features/async-support-net/#task-not-void), we only support instrumenting `async` methods that return a `Task`. If we find another return type, log a Warning. This should make it easier to track down problems caused by using e.g. `ValueTask`. The logging will only occur once since the Wrapper is cached. 
Sample line:
```
2024-06-18 20:12:10,856 NewRelic   WARN: [pid: 37628, tid: 24] Instrumenting async methods that return a type other than Task or Task<> is not supported and may result in inconsistent data. 'MyAsyncMethod' has a return type of 'ValueTask'.
```
=> chore: Warn about unsupported async return types

build/Packaging/NugetAgent/NewRelic.Agent.nuspec, build/Packaging/NugetAgentApi/NewRelic.Agent.Api.nuspec, build/Packaging/NugetAzureCloudServices/NewRelicWindowsAzure.nuspec, build/Packaging/NugetAzureWebSites-x64/NewRelic.Azure.WebSites.x64.nuspec, build/Packaging/NugetAzureWebSites-x86/NewRelic.Azure.WebSites.nuspec
A few things that came up during my attempt to integrate SourceLink - these aren't critical updates but will improve the appearance of our packages on Nuget. 
* Updates `nuget.exe` to the most recent version (6.10)
* Updates the `.nuspec` files to add a `<repository>` element and remove the (deprecated) `iconUrl` element
=> chore: Update nuget.exe to latest, update .nuspec files

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchElasticClient.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchNestClient.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchNetClient.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchTestClient.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Elasticsearch/ElasticsearchTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj
In the latest Elastic.Clients.Elasticsearch versions, non-async methods are deprecated.  We previously ignored the deprecation warnings and continued testing these methods.  This PR:
1. Uses preprocessor directives to avoid compiling the non-async methods in the latest ConsoleMF TFMs (net481 and net8.0), which are tied to the latest Elastic.Clients.Elasticsearch library versions.
2. Adds logic to the test code to skip testing the non-async methods for the latest version of Elastic.Clients.Elasticsearch
3. Modifies the `Connect` and `GenerateError` methods to be "async all the way" in order to use `PingSync()` instead of `Ping()` for those methods.
This also introduces the use of a 3rd-party library `XUnit.SkippableFact` to skip tests based on runtime conditions.  I wanted to be explicit …
=> tests: Skip testing deprecated non-async client methods in latest Elastic.Clients.Elasticsearch versions

tests/Agent/IntegrationTests/UnboundedIntegrationTests/Elasticsearch/ElasticsearchTests.cs
Simplify the logic in the Elasticsearch integration tests which skips testing non-async methods in the latest versions of Elastic.Clients.Elasticsearch.
=> tests: Simplify logic in Elasticsearch integration tests for skipping non-async methods

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Dotty updates
Closes #2573
Closes #2571
Closes #2570
Closes #2563
=> chore: Update integration test dependencies to latest.

tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkExerciser/AwsSdkExerciser.cs, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/Controllers/AwsSdkController.cs, tests/Agent/IntegrationTests/ContainerApplications/docker-compose-awssdk.yml, tests/Agent/IntegrationTests/ContainerIntegrationTests/Fixtures/AwsSdkContainerTestFixtures.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/AwsSdkTests.cs
* Adds `SendMessageBatch` and `PurgeQueue` calls to the SQS container tests
* Update docker-compose to make LocalStack ports internal  and to change the container name to avoid conflicts if running LocalStack in a separate service.
=> test: More SQS tests

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/AwsSdk/SqsHelper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/AwsSdkPipelineWrapper.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Helpers/SqsHelperTests.cs
Adds distributed tracing support to SQS instrumentation.
Tests to follow in a separate PR after this one completes.
=> SQS: Distributed Tracing support

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Everything passed locally. I didn't see anything in the MySQL release notes of concern, even though it's a major rev.
=> test: Dotty updates

build/Linux/build/rpm/Dockerfile
Updates RPM dockerfile to adjust urls for yum repos as per https://serverfault.com/a/1161847. This is a temporary fix until we can rebuild the RPM packaging process.
=> ci: Update RPM dockerfile to hack around mirrorlist EOL

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/ServerConfiguration.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/ConsoleDynamicMethodFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/LLM/LLMAccountDisabledTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ConnectModelTests.cs
Add support for disabling LLM monitoring at the account level.  
Includes integration tests that will require an update to the gh secrets - tests will fail till then.
Closes #2593
=> feat: Add support for disabling LLM monitoring at the account level.

src/Agent/NewRelic/Agent/Core/WireModels/LoadedModuleWireModelCollection.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LoadedModuleWireModelCollectionJsonConverterTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LoadedModuleWireModelCollectionTests.cs
Our vulnerability management backend uses the assemblies from update_loaded_modules to locate which nuget packages the customer is using.  Pre-compiled assemblies are made from local files and are not part of any nuget package. Likewise, dynamically created assemblies are also not going to be found in nuget packages.
The Assembly type already have a property for IsDynamic that we can read, but there is no such property for pre-compiled assemblies (from [ASP.NET Precompilation](https://learn.microsoft.com/en-us/previous-versions/aspnet/bb398860(v=vs.100))).  I noticed that all of my test pre-compiled assemblies reported 0.0.0.0 as the version unlike any of the other assemblies in my apps.  While it is possible that non pre-compiled  assemblies could have a zerod version, such an assembly …
=> chore: Exclude pre-compiled modules from update_loaded_modules payload.

src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/IAgentExperimental.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/AwsSdk/SqsHelper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/AwsSdkPipelineWrapper.cs, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkExerciser/AwsSdkExerciser.cs, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkTestApp.csproj, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/Controllers/AwsSdkController.cs, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/Program.cs, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/SQSBackgroundService/ISQSReceiverService.cs, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/SQSBackgroundService/ISQSRequestQueue.cs, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/SQSBackgroundService/ISQSResponseQueue.cs, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/SQSBackgroundService/SQSReceiverService.cs, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/SQSBackgroundService/SQSRequestQueue.cs, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/SQSBackgroundService/SQSResponseQueue.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests.sln, tests/Agent/IntegrationTests/ContainerIntegrationTests/Fixtures/AwsSdkContainerTestFixtures.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/AwsSdkTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/AgentWrapperApiTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Helpers/SqsHelperTests.cs
Reworks the SQS container test app to use a background service to receive messages, rather than directly receiving them from an API endpoint. The solution is (mildly) convoluted, but works well. 
Updated tests to verify the trace id and parent id match in the produce and consume sides.
=> SQS: Rework distributed trace tests

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/AwsSdkPipelineWrapper.cs
Refactors `AwsSdkPipelineWrapper` to encapsulate handling for SQS messages and ensure we don't accidentally process a non-SQS request that happens to match one of the names we're looking for.
=> chore: Refactor AwsSDKPipelineWrapper to encapsulate SQS handling

build/Linux/build/rpm/Dockerfile, build/Linux/build/rpm/build.sh, build/Linux/docker-compose.yml
Modifies the RPM build process to use Ubuntu instead of CentOS. Surprisingly, only a few minor changes were required. 
Successful CI run: https://github.com/newrelic/newrelic-dotnet-agent/actions/runs/9943833300/job/27468784640?pr=2627
Verified by pulling latest Fedora docker image, copying the .rpm file from the build artifact to the container and running `rpm -i` on it.
=> ci: Build RPM on Ubuntu

build/ReleaseNotesBuilder/data.yml, deploy/release_notes_template.md
The docs team corrected this link in our last release notes PR. (I'm not sure why we have the same link in two different files, so I updated both. I'm assuming only the `data.yml` file is actually used when generating the release notes.)
=> chore: Updated a URL in the release notes template

src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, src/Agent/NewRelic/Agent/Core/Segments/MessageBrokerSegmentData.cs, src/Agent/NewRelic/Agent/Core/Transactions/NoOpTransaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ITransaction.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/AwsSdk/SqsHelper.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/AwsSdk/AwsSdkSQSTest.cs, tests/Agent/UnitTests/Core.UnitTest/Segments/MessageBrokerSegmentDataTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Helpers/SqsHelperTests.cs
Adds additional attributes to enable SQS entity relationships to be formed. Includes unit and integration test updates.
=> AWS-APM Entity Relatipnships: SQS

src/Agent/NewRelic/Agent/Core/Utilities/ExtensionsLoader.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/KafkaBuilderWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/KafkaConsumerWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/KafkaHelper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/KafkaProducerWrapper.cs, tests/Agent/IntegrationTests/ContainerApplications/KafkaTestApp/Controllers/KafkaController.cs, tests/Agent/IntegrationTests/ContainerApplications/KafkaTestApp/Program.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Fixtures/KafkaTestFixtures.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/KafkaTests.cs
Adds new attributes used in forming AWS to APM entity relationships
=> APM-AWS Entity Relationships: Kafka

.github/workflows/all_solutions.yml, tests/Agent/IntegrationTests/IntegrationTests.sln, tests/Agent/IntegrationTests/SharedApplications/Common/MFALatestPackages/MFALatestPackages.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests.sln
This PR extracts the latest (net481 and net8.0) package references in `MultiFunctionApplicationHelpers` to a separate project (`MFALatestPackages`) for easier maintenance. This also lays the groundwork for possible future automation of update PRs via Dotty.
Notes:
* All packages were updated to the latest version (except as noted below) and a docs PR will follow to update the compatibility docs to reflect these versions.
* NServiceBus v9.x only targets `net8.0`, so the `net481` build target continues to use the latest `"8.*"` version which is still maintained. The `net8.0` target uses the latest `"9.*"` version. Integration tests pass on v9.
=> test: Refactor "latest" integration test NuGet package references to a separate project

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/SQSRequestHandler.cs, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkExerciser/AwsSdkExerciser.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Fixtures/AwsSdkContainerTestFixtures.cs
Modifies SQS instrumentation to clone the existing `ReceiveMessageRequest.MessageAttributeNames` collection prior to adding our distributed trace headers to the collection. 
Fixes #2645, where the customer was re-using the same source collection on each new `ReceiveMessageRequest` instance.
=> fix: SQS instrumentation could cause InvalidOperationException #2645

src/Agent/MsiInstaller/Installer/Product.wxs, src/Agent/MsiInstaller/InstallerActions/CustomActions.cs
This PR:
1. Enables setting the application name (in the global `newrelic.config` file) with the command line parameter `NR_APP_NAME` when using the .msi installer.
2. Enables setting the global `newrelic.config` to use application pool naming (see https://docs.newrelic.com/docs/apm/agents/net-agent/configuration/name-your-net-application/#app-pool) by setting the command line parameter `NR_USE_APP_POOL_NAMING="True"` when using the .msi installer.
Examples:
To set the application name at install time:
`msiexec.exe /i C:\path\to\NewRelicAgent_x64_10.28.0.0.msi /qb NR_APP_NAME="My Application Name"`
To configure the agent to use app pool naming at install time:
`msiexec.exe /i C:\path\to\NewRelicAgent_x64_10.28.0.0.msi /qb NR_USE_APP_POOL_NAMING="True"`
Notes and cautions:
1. Setting the …
=> feat: Set application name via command line with the .msi installer

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/HandlerMethodWrapper.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaAPIGatewayHttpApiV2ProxyRequestTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaAPIGatewayRequestTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaApplicationLoadBalancerRequestTest.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaAPIGatewayHttpApiV2ProxyRequestTriggerFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaAPIGatewayProxyRequestTriggerFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaApplicationLoadBalancerRequestTriggerFixture.cs
Adds checking for required parameters (Http Method and Path) for Lambda web requests (`APIGatewayProxyRequest`, `APIGatewayHttpApiV2ProxyRequest` or `ApplicationLoadBalancerRequest`). 
If either or both are missing, we log a message (`Invalid or missing web request parameters. HttpMethod and Path are required for <request type>. Not instrumenting this function invocation.`) and return a NoOp Delegate. 
Resolves #2652
=> fix: Better Lambda web request input parameter validation.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/KafkaBuilderWrapper.cs
The Producer and Consumer are both generics, so just using the type name wasn't sufficient; we'll cache on the full `Type` now instead.
=> fix: Kafka bootstrap servers cache wasn't implemented correctly

src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h, src/Agent/NewRelic/Profiler/ConfigurationTest/InstrumentationConfigurationTest.cpp
Modifies the Profiler to look for the `NEW_RELIC_LAMBDA_HANDLER` environment variable before looking for `_HANDLER`.  
If `NEW_RELIC_LAMBDA_HANDLER` isn't found or can't be parsed successfully, the profiler then looks for `_HANDLER` and applies the same parsing test. If neither variable exists or can be parsed correctly, serverless mode is not enabled.
Resolves #2659
=> feat: Improve serverless mode detection

.github/workflows/all_solutions.yml, .github/workflows/build_profiler.yml, .github/workflows/deploy_agent.yml, build/Linux/linux_packaging.md, build/build.ps1, deploy/linux/README.md, src/Agent/NewRelic/Profiler/build/scripts/build_linux.ps1, tests/Agent/IntegrationTests/UnboundedServices/README.md, tests/Agent/IntegrationTests/UnboundedServices/unbounded-services-control.ps1
Migrate all our workflows and scripts to use docker compose v2.  See issue linked below for details about the change.
Relates to actions/runner-images#9692
=> ci: Change to docker compose v2 due to GH deprecations.

.github/workflows/build_profiler.yml, src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/Common/CorStandIn.h, src/Agent/NewRelic/Profiler/Configuration/Configuration.h, src/Agent/NewRelic/Profiler/Configuration/IgnoreInstrumentation.h, src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h, src/Agent/NewRelic/Profiler/Configuration/InstrumentationPoint.h, src/Agent/NewRelic/Profiler/MethodRewriter/ExceptionHandlerManipulator.h, src/Agent/NewRelic/Profiler/MethodRewriter/FunctionManipulator.h, src/Agent/NewRelic/Profiler/MethodRewriter/InstructionSet.h, src/Agent/NewRelic/Profiler/MethodRewriter/InstrumentFunctionManipulator.h, src/Agent/NewRelic/Profiler/MethodRewriter/MethodRewriter.h, src/Agent/NewRelic/Profiler/ModuleInjector/ModuleInjector.h, src/Agent/NewRelic/Profiler/Profiler/CorProfilerCallbackImpl.h, src/Agent/NewRelic/Profiler/Profiler/CorTokenResolver.h, src/Agent/NewRelic/Profiler/Profiler/CorTokenizer.h, src/Agent/NewRelic/Profiler/Profiler/Function.h, src/Agent/NewRelic/Profiler/Profiler/FunctionHeaderInfo.h, src/Agent/NewRelic/Profiler/Profiler/FunctionPreprocessor.h, src/Agent/NewRelic/Profiler/Profiler/OpCodes.h, src/Agent/NewRelic/Profiler/Profiler/SystemCalls.h, src/Agent/NewRelic/Profiler/Profiler/stdafx.h, src/Agent/NewRelic/Profiler/RapidXML/rapidxml.hpp, src/Agent/NewRelic/Profiler/SignatureParser/Types.h
We're seeing some instability in some customer applications that seems related to these recent Profiler changes: https://github.com/newrelic/newrelic-dotnet-agent/pull/2545
Reverting while we investigate.
=> fix: Revert recent Profiler warning fixes

.github/dependabot.yml
The [current Dependabot config was incorrect](https://github.com/newrelic/newrelic-dotnet-agent/network/updates/865576988), resulting in no update PRs for the limited set of NuGet packages we want to update in our Integration tests. 
I also added a rule to update the same limited set of packages in our unit test projects and removed the configuration for the (now deleted) NewRelic.Core project.
=> ci: Better Dependabot configuration for tests

.github/dependabot.yml
I missed this in my previous update, but there is a [recently-released `directories` config option](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directories) for dependabot.yml that allows us to streamline our configuration.
=> ci: Update dependabot to use `directories` config

.github/dependabot.yml
Removes xunit from the list of packages we want Dependabot to montior.
=> ci: Remove xunit from dependabot package list

.github/dependabot.yml, tests/Agent/IntegrationTests/ContainerIntegrationTests/ContainerIntegrationTests.csproj, tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/IntegrationTestHelpers.csproj, tests/Agent/IntegrationTests/IntegrationTests/IntegrationTests.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj, tests/Agent/Shared/TestSerializationHelpers.Test/TestSerializationHelpers.Test.csproj
This PR does the following:
* Re-applies the XUnit 2.9.0 upgrade to all integration test projects
* Modifies `AgentLogBase.GetReportingAppLink()` to use `TryGetLogLine()` instead of `WaitForLogLine()`
* Removes logging that I added in [this commit](https://github.com/newrelic/newrelic-dotnet-agent/commit/cbf4248c1a61c3741dbaf533d4d4793c8ebafd13#diff-6f30640a5ec218e443bcbf334bb43947f57e9f10a1af059525d16eddc5ef3df8R160) several months ago.
These fixes should address the `System.InvalidOperationException : There is no currently active test.` errors we started seeing after the previous upgrade attempt. 
Fixes #2684 (probably...)
=> test: Upgrade to XUnit 2.9.0, fix some test failures

tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkTestApp.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MFALatestPackages/MFALatestPackages.csproj
Resolves #2688
Resolves #2689 
Resolves #2690 
Resolves #2691 
Note: the reference for `Confluent.Kafka` was already updated to `2.5.2` in this PR from last week: https://github.com/newrelic/newrelic-dotnet-agent/pull/2678
=> chore: Update latest tested versions for core tech packages

src/Agent/NewRelic/Agent/Core/Config/BootstrapConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/HandlerMethodWrapper.cs, tests/Agent/UnitTests/Core.UnitTest/Config/BootstrapConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ExhaustiveTestConfiguration.cs
Changes the default behavior in Serverless mode to use the function name rather than "My Application" if no name is set.
Unit tests included.
=> feat: Use Lambda function name if application name is not set

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Parsing/ParsedSqlStatement.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Parsing/SqlParser.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Parsing/SqlParserTests.cs
The agent caches a "null parsed statement" per datastore vendor which is returned when parsing a SQL statement is unsuccessful.
This fix modifies that behavior in the case where a custom query name has been specified such that we return a new "null parsed statement", with the custom query name preserved. 
Includes unit test to verify.
Fixes #2708
=> fix: Preserve custom query name even if statement can't be parsed. (#2708)

.github/workflows/all_solutions.yml, tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml, tests/Agent/IntegrationTests/UnboundedServices/oracle/Dockerfile
* Updates our unbounded services configuration to use the [free Oracle 23ai](https://www.oracle.com/database/free/) container image
* Updates the all_solutions workflow to restore Oracle namespace in the unbounded tests project
The updated services config was deployed to our test EC2 instance and Github secrets were updated appropriately.
=> test: Update Oracle server image, restore unbounded tests

tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaAPIGatewayRequestTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaApplicationLoadBalancerRequestTest.cs
Updates two more AWS Lambda tests to try to eliminate flickers
=> test: Fix a couple more flickers in AWS Lambda integration tests

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Utilities/ExtensionsLoader.cs, src/Agent/NewRelic/Profiler/ConfigurationTest/ConfigurationTest.cpp, src/Agent/NewRelic/Profiler/Logging/Logger.h, src/Agent/NewRelic/Profiler/LoggingTest/LoggerTest.cpp, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transactions/TransactionTests.cs
Adds unit tests for Azure function code in agent and profiler
=> Azure functions: Unit tests

tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkTestApp.csproj, tests/Agent/IntegrationTests/IntegrationTests/LLM/BedrockTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MFALatestPackages/MFALatestPackages.csproj
Resolves #2730 
Resolves #2729 
Resolves #2728 
Resolves #2727
=> chore: core tech updates, 2024-09-04

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore6Plus/WrapPipelineMiddleware.cs, tests/Agent/IntegrationTests/Applications/AzureFunctionApplication/HttpTriggerFunctionUsingAspNetCorePipeline.cs, tests/Agent/IntegrationTests/IntegrationTests/AzureFunction/AzureFunctionHttpTriggerTests.cs
Disables the AspNetCore middleware wrapper (`NewRelic.Providers.Wrapper.AspNetCore6Plus.WrapPipelineMiddleware`) when running in Azure function mode, to prevent duplicate transactions from being created. 
Updates integration tests to add checking of transaction sample attributes.
=> Feature work: Disable AspNetCore middleware wrapper

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AzureFunction/TriggerTypeExtensions.cs, tests/Agent/IntegrationTests/Applications/AzureFunctionApplication/AzureFunctionApplication.csproj, tests/Agent/IntegrationTests/Applications/AzureFunctionApplication/QueueTriggerFunction.cs, tests/Agent/IntegrationTests/Applications/AzureFunctionApplication/local.settings.json, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/AzureFuncTool.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplicationFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/AzureFunction/AzureFunctionQueueTriggerTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AzureFunctionApplicationFixture.cs
Adds a QueueTrigger function to integration tests.
=> Feature work: Added QueueTrigger function to integration tests

src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionManager.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ConnectionManagerTests.cs
=> chore: Remove System.Net.Http reference on .NET Framework. Resolves #2750

tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkTestApp.csproj, tests/Agent/IntegrationTests/ContainerApplications/KafkaTestApp/KafkaTestApp.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MFALatestPackages/MFALatestPackages.csproj
Resolves #2741 
Resolves #2742 
Resolves #2743 
Resolves #2744 
Note: some of the packages have gotten further updates since the core tech scanner (Dotty) ran on Monday, so the version each package was bumped to may be newer than specified in the associated issues.
=> chore: Update latest tested versions of core tech libraries, 09/12/24

tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkTestApp.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MFALatestPackages/MFALatestPackages.csproj
Resolves #2762 
Resolves #2763
Resolves #2765 
Resolves #2766 
Resolves #2767 
Note: this no longer addresses the issue numbered 2764, which is a major version bump of log4net.  This change broke some tests and will need additional troubleshooting and testing.
=> chore: Update latest tested versions of core tech, week of 2024-09-16

.github/dependabot.yml, .github/workflows/nuget_slack_notifications.yml, .github/workflows/scripts/nugetSlackNotifications/packageInfo.json
A few changes, intended to reduce the burden of managing dependency updates:
* Dependabot will scan for github actions updates monthly instead of weekly
* Dependabot will scan for NuGet package updates for unit/integration tests monthly instead of weekly 
* Dotty will run on the 1st and 15th of the month instead of weekly on Mondays (note that it already uses the "last run" date as the starting timestamp for it's package searching, so we shouldn't miss any updates).
* Based on recent history, a few Dotty packages will now ignore patch version updates:
* `AWSSDK.BedrockRuntime`
* `AWSSDK.SQS`
* `StackExchange.Redis`
=> chore: Dotty / Dependabot updates

FullAgent.sln, build/ArtifactBuilder/CoreAgentComponents.cs, build/ArtifactBuilder/FrameworkAgentComponents.cs, src/Agent/MsiInstaller/Installer/Product.wxs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Memcached/EnyimMemcachedCoreWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Memcached/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Memcached/Memcached.csproj, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Memcached/MemcachedHelpers.cs, tests/Agent/IntegrationTests/ContainerApplications/MemcachedTestApp/BlogPost.cs, tests/Agent/IntegrationTests/ContainerApplications/MemcachedTestApp/BlogPostService.cs, tests/Agent/IntegrationTests/ContainerApplications/MemcachedTestApp/Controllers/MemcachedController.cs, tests/Agent/IntegrationTests/ContainerApplications/MemcachedTestApp/Dockerfile, tests/Agent/IntegrationTests/ContainerApplications/MemcachedTestApp/IBlogPostService.cs, tests/Agent/IntegrationTests/ContainerApplications/MemcachedTestApp/MemcachedTestApp.csproj, tests/Agent/IntegrationTests/ContainerApplications/MemcachedTestApp/Program.cs, tests/Agent/IntegrationTests/ContainerApplications/MemcachedTestApp/appsettings.Development.json, tests/Agent/IntegrationTests/ContainerApplications/MemcachedTestApp/appsettings.json, tests/Agent/IntegrationTests/ContainerApplications/docker-compose-memcached.yml, tests/Agent/IntegrationTests/ContainerIntegrationTests.sln, tests/Agent/IntegrationTests/ContainerIntegrationTests/Fixtures/MemcachedTestFixtures.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/MemcachedTests.cs
- Adds support for EnyimMemcachedCore versions 2.X and 3.X with nearly all methods except MultiGet methods, sync and async.
- Adds ContainerIntegration tests: (I expect these will change when net9.0 releases)
- net8.0 with EnyimMemcachedCore  v2.1.9
- net6.0 with EnyimMemcachedCore  v3.2.2
=> feat: Add support for the EnyimMemcachedCore client.

.github/workflows/deploy_agent.yml, .github/workflows/deploy_siteextension.yml
Windows Server 2019 reached its initial servicing EOL date on Jan 9, 2024.  We need to migrate the two workflows off that version to windows-2022 or windows-latest.  I prefer us to be pinned to a specific version of windows, so I moved the two workflows to windows-2022.
There shouldn't be an impact from the change, however these are deploy scripts so we won't be 100% sure until the next release.
Resolves #2752
=> ci:Migrate runner types from windows-2019 to windows-2022.

src/Agent/NewRelic/Agent/Core/DataTransport/Client/HttpClientBase.cs, src/Agent/NewRelic/Agent/Core/DataTransport/Client/Interfaces/IHttpClientWrapper.cs
Minor cleanup to place the last few `using System.Net.Http;` lines behind conditional compilation for non-NETFRAMEWORK build targets.
=> chore: Ensure all `using System.Net.Http;` are conditionally compiled

tests/Agent/IntegrationTests/ContainerIntegrationTests/ContainerIntegrationTests.csproj, tests/Agent/IntegrationTests/IntegrationTests/BasicInstrumentation/WebApiAsyncForceNewTransactionTests.cs, tests/Agent/IntegrationTests/IntegrationTests/IntegrationTests.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj
Fix a build problem in our integration tests caused by an incomplete update of xunit package references by Dependabot (🤖 🙅)
=> chore: Update all xunit(assert,core) references to 2.9.2

src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/AgentManager.cs, src/Agent/NewRelic/Agent/Core/Aggregators/AbstractAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/CustomEventAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/ErrorEventAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/ErrorTraceAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/LogEventAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/SpanEventAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/TransactionEventAggregator.cs, src/Agent/NewRelic/Agent/Core/DataTransport/Client/NRWebRequestClient.cs, src/Agent/NewRelic/Agent/Core/DependencyInjection/AgentContainer.cs, src/Agent/NewRelic/Agent/Core/Samplers/AbstractSampler.cs, src/Agent/NewRelic/Agent/Core/Samplers/GCSamplerNetCore.cs, src/Agent/NewRelic/Agent/Core/Samplers/ThreadStatsSampler.cs, src/Agent/NewRelic/Agent/Core/SharedInterfaces/PerformanceCounterProxy.cs, src/Agent/NewRelic/Agent/Core/Time/Scheduler.cs
Minor refactoring of our Dispose() pattern to ensure that any base-class `Dispose()` method is called *after* the derived class has cleaned up its own resources. Should have zero impact on agent functionality; this is primarily a cosmetic change. 
Also removed a couple of unnecessary `Dispose()` overrides and modified a couple of log messages. The final "agent has been shutdown" message will only show in the logs when everything else related to shutdown is complete; failure to observe that message is an indicator that the shutdown process did not complete for some reason. 
Resolves #2795
=> chore: `Dispose()` refactoring

src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/Configuration/Configuration.h, src/Agent/NewRelic/Profiler/ConfigurationTest/ConfigurationTest.cpp, tests/Agent/IntegrationTests/IntegrationTests/AzureFunction/AzureFunctionHttpTriggerTests.cs
Updates the Profiler to inspect the `NEW_RELIC_AZURE_FUNCTION_MODE_ENABLED` environment variable. 
If the variable doesn't exist, we don't exclude any Azure function processes from instrumentation, which matches behavior prior to implementing Azure function support. 
If the variable does exist, Azure function mode is only enabled if the variable has a value of `1` or `true`.
=> fix: Update Profiler to check whether Azure function mode support is enabled

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/CosmosDb/Instrumentation.xml, tests/Agent/IntegrationTests/SharedApplications/Common/MFALatestPackages/MFALatestPackages.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests/CosmosDB/CosmosDBTests.cs
Updates CosmosDB instrumentation to support the latest version (3.43.0). There was a change in the signature of the method we instrument for database queries somewhere between 3.23.0 and 3.43.0. 
Includes integration tests for both the old and new version.
=> feat: Update CosmosDB instrumentation to support latest version

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ITransaction.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/AwsSdkPipelineWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Bedrock/InvokeModelAsyncWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Elasticsearch/RequestWrapper.cs
Discovered that calling ITransaction.DetachFromPrimary when in the middle of a transaction can result in `Transaction was garbage collected without ever ending` errors due to the AsyncLocal context being forward only and the other contexts being cleared.
Removed the call from AWS SDK, AWS Bedrock, and Elastisearch instrumentation where the call was made in the middle of transaction.  Left the method call in all other locations since it was done immediately after CreateTransaction was called.
Updated the summary for ITransaction.DetachFromPrimary to include a warning about this use case.
=> fix: Fix potential race condition in AWS SDK, AWS Bedrock, and Elastisearch that could lead to an orphaned Transaction.

.github/dependabot.yml
Adds a specific set of folders for Dependabot scanning in the Docker ecosystem, with a monthly schedule. 
If the recommendations turn out to be unhelpful, we can back this change out later.
=> chore: Add docker ecosystem to Dependabot config

.github/dependabot.yml
It turns out we can't update any of our Dockerfile dependencies until we modernize the Profiler build. Commenting out that section for now; we can revisit once the profiler build is updated.
=> chore: disable Docker ecosystem in Dependabot

src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ExhaustiveTestConfiguration.cs
Adds the ability to provide an AWS Account ID, which can be used to help link related entities.
This functionality is needed for multiple feature branches which is why I'm merging to `main` first, even though this won't be used yet.
=> feat: Add config option for providing AWS account ID for linking

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/AwsSdkPipelineWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/SQSRequestHandler.cs
Use `ConcurrentHashSet<T>` instead of `HashSet<T>` in AWSSdk wrapper to resolve a threading issue. 
Resolves #2855. Replaces #2856.
Co-authored-by: Gideon @gjunge
=> fix: Remove usage of non-thread safe HashSet in AwsSdk pipeline wrappers. (#2855)

tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Parsing/StringsHelperTest.cs
Unit test a new helper method introduced for DynamoDB instrumentation.
=> Add unit tests for ToSnakeCase()

tests/Agent/IntegrationTests/ContainerIntegrationTests/Applications/ContainerApplication.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/AzureFuncTool.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/DotnetTool.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplication.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplicationFixture.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteConsoleApplication.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/MockNewRelicFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/OwinRemotingFixture.cs
An intermittent integration test failure I've noticed: if a `RemoteProcess` is hung, we can still send it shutdown signals without getting an error back, so we never force it to close. Then when we make our final attempt to shut it down in `Dispose`, it throws because the test logger is no longer available.
=> test: Force terminate helper processes still running at dispose time

tests/Agent/IntegrationTests/IntegrationTests/LLM/BedrockTests.cs, tests/Agent/IntegrationTests/IntegrationTests/LLM/LLMAccountDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/LLM/LLMApiTests.cs
Llama 2 reached EOL today, and all calls using it fail. I'll add a ticket to come back and rework these tests.
=> test: Disable tests using deprecated AI models

build/Linux/build/common/setenv.sh
Fixes a syntax error that was introduced in #2852. 
Resolves #2863
=> fix: Fix syntax error in `setenv.sh`

.github/workflows/scripts/nugetSlackNotifications/PackageInfo.cs, .github/workflows/scripts/nugetSlackNotifications/Program.cs, .github/workflows/scripts/nugetSlackNotifications/packageInfo.json
Minor update to Dotty that adds an `ignoreMajor` property to `packageInfo.json`. 
Modifies `log4net` and `MongoDB.Driver` to set that new flag since both have breaking changes that we can't incorporate at present.
=> chore: Add ignoreMajor config to Dotty

.github/workflows/multiverse_run.yml, src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/Configuration/Configuration.h, src/Agent/NewRelic/Profiler/ConfigurationTest/ShouldInstrumentTest.cpp
Updates the Profiler to exclude `kuduagent.dll` and `DiagServer` processes from instrumentation. These are both part of the most recent Azure Linux App Services deployments and should not be instrumented.
Verified correct behavior in an Azure Linux app service:
```
[Trace] 2024-11-04 18:05:16 Checking to see if we should instrument this process. 
[Info ] 2024-11-04 18:05:16 Command line: /appservice/dotnet/dotnet /appservice/kuduagent/kuduagent.dll 
[Info ] 2024-11-04 18:05:16 This process will not be instrumented. Command line identified as invalid invocation for instrumentation 
[Info ] 2024-11-04 18:05:16 This process should not be instrumented, unloading profiler.
```
Resolves #2871
=> fix: Update excluded processes for Azure Linux App Service

FullAgent.sln, tests/Agent/IntegrationTests/IntegrationTests/LLM/BedrockTests.cs
The Cohere LLM model reached EOL on October 4. Not sure why it just now started to fail in tests, however. This PR removes `cohere` from the list of models to test.
=> test: Remove deprecated `cohere` LLM model from testing

.github/workflows/scripts/nugetSlackNotifications/CsprojHandler.cs, .github/workflows/scripts/nugetSlackNotifications/Program.cs, .github/workflows/scripts/nugetSlackNotifications/nugetSlackNotifications.csproj, .github/workflows/scripts/nugetSlackNotifications/packageInfo.json, .github/workflows/scripts/nugetSlackNotifications/projectInfo.json, build/NugetValidator/NugetValidator.csproj, build/NugetVersionDeprecator/NugetVersionDeprecator.csproj
* Updates list of projects that Dotty monitors, as well as the list of packages
* Fixes a bug in Dotty where multi-line `<PackageReference>` elements in csproj files weren't parsed correctly
* Updates some NuGet packages that had vulnerabilities, as reported by the .NET 9 updated version of nuget.exe.
=> chore: Update Dotty project and package lists, other fixes

src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionManager.cs
Adds some logging in the exception handling code in `ConnectionManager.Connect()` which will potentially help us diagnose unexpected exceptions that cause the agent to shutdown and determine if we can handle those specific exceptions in a less ham-fisted manner.
=> chore: Additional exception logging in `ConnectionManager.Connect()`

.github/workflows/all_solutions.yml
Disables starting the CosmosDB emulator in `all_solutions.yml`; we are using an Azure instance of CosmosDB now.
=> ci: disable cosmosdb emulator startup

.github/workflows/multiverse_run.yml, tests/Agent/MultiverseTesting/ConsoleScanner/ConsoleScanner.csproj, tests/Agent/MultiverseTesting/MultiverseScanner/MultiverseScanner.csproj, tests/Agent/MultiverseTesting/ReportBuilder/Program.cs, tests/Agent/MultiverseTesting/ReportBuilder/ReportBuilder.csproj
Why not .NET 9?  I didn't want to deal with temporarily configuring the CI to install the .NET 9 SDK.  Going with an LTS version of .NET and we can bump it to .NET 10 next year.
=> chore: Update multiverse scanner solution to .NET 8

src/Agent/NewRelic/Agent/Core/Core.csproj, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/MicrosoftExtensionsLogging.csproj
Resolves #2898. See the linked Jira ticket for an analysis of potentially affected libraries.
=> fix: Remove .NET Standard libraries from .NET Framework target

.github/workflows/build_profiler.yml
Updates the token used by the `peter-evans/create-pull-request` action in `build_profiler.yml` to use our custom token instead of `GITHUB_TOKEN` - this change allows us to remove the `contents: write` permission that has been the subject of repeated [Code Scanning Alerts](https://github.com/newrelic/newrelic-dotnet-agent/security/code-scanning/375).
=> ci: Update token for build_profiler workflow

.gitignore, src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/MethodRewriter/Instrumentors.h
The profiler is supposed to allow instrumentation of constructors, but we found that the string comparison operator being used didn't work correctly under Linux. This PR changes the comparison to use a cross-platform version of `wcscmp()` instead.
Fixes #2918
=> fix: Incorrect string comparison in the profiler caused constructor instrumentation to fail on Linux

src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, src/Agent/NewRelic/Agent/Core/Segments/NoOpSegment.cs, src/Agent/NewRelic/Agent/Core/Segments/Segment.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ISpan.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ITransaction.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/RequestHandlers/LambdaInvokeRequestHandler.cs, tests/Agent/UnitTests/Core.UnitTest/Transactions/TransactionTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Helpers/SqsHelperTests.cs
Using this separate PR to discuss the pros and cons of moving the new Cloud SDK attributes out of Transaction metadata. The goal would be to support multiple AWS services per transaction.
=> Moving cloud SDK attributes to Segments

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/NewRelic.Agent.Extensions.csproj, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Parsing/SqlWrapperHelper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Sql/OdbcCommandWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Sql/Sql.csproj
Per team pairing last week, we should not add a reference to `System.Data.Odbc` to the `Sql` wrapper project nor the `Extensions` project with the helper code.
I initially went down a rabbit hole of using visibility bypasser to get the necessary data out of the `OdbcCommand` object.  However, I eventually realized that we can treat the `OdbcCommand` object as an `IDbCommand` interface type and get almost everything we need directly that way.  The one exception is the `Driver` string (needed to get the DatastoreVendor), which is not a part of the `IDbCommand` interface.  However, it can be easily parsed from the ODBC connection string (and cached based on the full connection string).
=> Remove references to System.Data.Odbc from wrapper and extensions

.github/workflows/markdowncheck.yml
Updates the schedule for `markdowncheck.yml` to run once a month. There's really no reason to run it daily, and by running just once a month, we can subscribe the team Slack channel to notifications for that workflow so that I'm not the only one who gets notified when it fails... ;-)
=> ci: Run markdown link check once a month instead of daily

.github/workflows/scripts/nugetSlackNotifications/packageInfo.json, tests/Agent/IntegrationTests/SharedApplications/Common/MFALatestPackages/MFALatestPackages.csproj
Updates NuGet packages to test log4net v3.0.3, removes Dotty exclusions.
Closes #2764
=> test: log4net v3 support

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Parsing/SqlWrapperHelper.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MFALatestPackages/MFALatestPackages.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MsSql/SystemDataExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MsSql/SystemDataOdbcExerciser.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureUsingOdbcDriverTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Parsing/SqlWrapperHelperTests.cs
Update the MSSQL integration tests to test the ODBC instrumentation.
* A new `SystemDataOdbcExerciser` is added to exercise the ODBC instrumentation
* The existing `MsSqlTests` are updated to test the ODBC instrumentation
* The existing `MsSqlStoredProcedureUsingOdbcDriverTests` are updated to use the new ODBC exerciser, and account for some changes
Things to note:
* The ODBC instrumentation does not instrument `Connect{Async}` or the DB read iteration methods.  The test logic accounts for this.
* The DB vendor for ODBC is no longer `Other`, but whatever DB we can detect as the underlying destination based on the connection string, in this case `MSSQL`
=> ODBC integration tests

.github/workflows/scripts/nugetSlackNotifications/CsprojHandler.cs, .github/workflows/scripts/nugetSlackNotifications/NugetVersionData.cs, .github/workflows/scripts/nugetSlackNotifications/PackageInfo.cs, .github/workflows/scripts/nugetSlackNotifications/PackageReference.cs, .github/workflows/scripts/nugetSlackNotifications/Program.cs, .github/workflows/scripts/nugetSlackNotifications/packageInfo.json
Updated Dotty PR creation logic to commit the changes to the new branch before creating a PR. Not sure why this was necessary now, but I'm assuming it's related to the OctoKit major version bump that was applied recently. 
Also added a config in `packageInfo.json` to allow updates for specific TFMs to be ignored (case in point: `NServiceBus` v9 isn't supported on `net481` but we still want to update the `net9.0` reference.)
=> ci: Dotty Fixes

.github/workflows/post_deploy_agent.yml
We are getting rid of the internal [auto-layer-releases repo](https://source.datanerd.us/aws-lambda/auto-layer-releases/blob/master/app.py) and moving creating of the release tags into each agent's GHA deploy flow.
=> Move init container release from lambda to GHA

.github/workflows/build_profiler.yml, .github/workflows/run_unit_tests.yml
Updates `run_unit_tests.yml` so that the workflow runs on every push to `main`, which is required to keep CodeCov in sync and make the reports it generates more relevant. Also updates `build_profiler.yml` for the same reason.
I probably removed that trigger at some point in the past, in an attempt to minimize unnecessary workflow runs, but it looks like we actually need it. It was messages like this that clued me in:
=> ci: Update unit tests workflow to run on push to main

tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTests/CSP/AspNetCoreLocalHSMDisabledAndServerSideHSMEnabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CSP/AspNetCoreLocalHSMEnabledAndServerSideHSMDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CSP/HighSecurityModeServerDisabled.cs, tests/Agent/IntegrationTests/IntegrationTests/CSP/HighSecurityModeServerEnabled.cs
Updates a few regex patterns used in integration tests to be a little bit less selective. Discovered during testing of the pipeline control gateway endpoint. None of the changes causes any behavioral change in the integration tests.
=> test: Integration test regex updates

.github/workflows/post_deploy_agent.yml
The post-deploy step for releasing the lambda layer and K8s init container failed for release 10.35.0: https://github.com/newrelic/newrelic-dotnet-agent/actions/runs/12918327015/job/36027065472
Given the error message: `stat Relic: no such file or directory`, I think the issue was that some of the arguments to `gh release create` need to be quoted because they contain whitespace, e.g. `--title="New Relic .NET Agent v10.35.0.0"`
=> ci: for Lambda layer/K8s init container release, quote arguments that aren't single strings

tests/Agent/IntegrationTests/ContainerIntegrationTests/Applications/ContainerApplication.cs
Modify container test shutdown logic to wait for the docker compose command to complete. Also extends the timeout from 5 seconds to 20 seconds.
=> test: Update container test shutdown logic

tests/Agent/IntegrationTests/ContainerApplications/CustomBaseContainerBuild/README.md
Corrects the README instructions for building the customer Alpine / Fedora images we use in container integration tests.
=> chore: Fix incorrect commands for custom container builds

tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaTestToolFixture.cs
There's a [.NET 9 specific version of the Lambda test tool](https://www.nuget.org/packages/Amazon.Lambda.TestTool-9.0#readme-body-tab) that we install to run our Lambda integration tests. 
This PR updates our tooling to use that version. Don't know if it will make any difference at all in the recent Lambda test failures we've been seeing, but it can't hurt.
=> test: Use latest version of Lambda test tool (9.0)

.github/workflows/run_linux_container_tests.yml
Modifies the container test workflow to archive the test results (*.trx) so they're available for inspection regardless of whether tests succeed or fail.
=> test: Archive container test results

.github/workflows/run_linux_container_tests.yml
I forgot that artifacts require unique names. Oops.
=> test: Fix name collision on archive test results step

src/Agent/NewRelic/Agent/Core/Aggregators/CustomEventAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/ErrorEventAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/ErrorTraceAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/LogEventAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/MetricAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/SpanEventAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/SqlTraceAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/TransactionEventAggregator.cs, src/Agent/NewRelic/Agent/Core/Aggregators/TransactionTraceAggregator.cs
Adds logging in the `HandleResponse()` method of all aggregators to indicate whether data was sent successfully, retained or discarded.
=> chore: Log non-successful DataTransportResponseStatus during harvest

src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/Metrics/MetricNames.cs
Adds `Supportability/Dotnet/AzureFunctionMode/Enabled` metric when Azure Function mode is enabled and the agent is running in an Azure Function.
=> chore: Add supportabililty metric when Azure Function mode is enabled

src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinition.cs, tests/Agent/UnitTests/Core.UnitTest/Attributes/AttributeTests.cs, tests/Agent/UnitTests/Core.UnitTest/CustomEvents/CustomEventWireModelTests.cs, tests/Agent/UnitTests/NewRelic.Agent.TestUtilities/AttributeComparer.cs
Custom attribute values of type float or decimal could, in some cases, be serialized with a different precision than the original value (i.e., `0.2f` would be serialized as `0.20000000298023224`) due to a conversion to `double` prior to serialization.
Adds unit tests to verify correct behavior.
fixes #2945
=> fix: Custom attribute values of type float and decimal were not serialized correctly.

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AzureFunction/InvokeFunctionAsyncWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/AzureFunction/AzureFunctionHttpTriggerTests.cs, tests/Agent/IntegrationTests/IntegrationTests/AzureFunction/AzureFunctionQueueTriggerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ExhaustiveTestConfiguration.cs
Update the `faas.name` attribute on Azure Function transactions to include the Azure Function app name as a prefix. This change is for consistency with [OpenTelemetry semantic conventions](https://opentelemetry.io/docs/specs/semconv/attributes-registry/faas/#faas-name) for this attribute. 
The `faas.name` attribute will now have the format `{azure_function_app_name}/{function_name}` where it previously contained only `{function_name}`. 
Also renamed the related config property to better reflect that it is the Azure Function app name.
=> fix: Add Azure Function app name prefix to `faas.name` attribute in Azure Function transactions.

tests/Agent/UnitTests/Core.UnitTest/CustomEvents/CustomEventWireModelTests.cs
Updated `CustomEvents_UserAttributes_AllAttributeTypesSerializeCorrectly()` (introduced yesterday) to make sure we use the same Jsonconverter for the "expected" serialization result. There was a slight difference in how `DateTime` values were being serialized without this change.
=> test: Fix flaky CustomEventWireModelTests

.gitignore, build/Packaging/AzureSiteExtension/Content/install.ps1
Update the Azure Websites Site Extension Nuget package to detect when it's being added to an Azure Function. 
If the `FUNCTIONS_WORKER_RUNTIME` environment variable is detected, the extension adds `NEW_RELIC_AZURE_FUNCTION_MODE_ENABLED=1` and `NEW_RELIC_LOG_DIRECTORY=%HOME%\LogFiles\NewRelic` to `applicationHost.xdt`.
With this change, the customer only needs to add the `NEW_RELIC_LICENSE_KEY` environment variable manually and the agent will "just work" in an Azure function. The `NEW_RELIC_AGENT_VERSION_OVERRIDE` environment variable is supported as usual.
=> chore: Update Azure Site Extension to include support for Azure Functions

src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/Configuration/Configuration.h, src/Agent/NewRelic/Profiler/ConfigurationTest/ConfigurationTest.cpp
=> reverting in-proc mode changes

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Utilization/VendorInfo.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore6Plus/WrapPipelineMiddleware.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AzureFunction/FunctionsHttpProxyingMiddlewareWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AzureFunction/InvokeFunctionAsyncWrapper.cs, src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/Configuration/Configuration.h, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/AzureFuncTool.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Azure Function instrumentation is now enabled by default. 
To disable Azure Function instrumentation, set the `NEW_RELIC_AZURE_FUNCTION_MODE_ENABLED=0` environment variable.
=> feat: Enable Azure Function instrumentation by default

.github/workflows/codeql.yml, .github/workflows/codeql/codql-config.yml
Updates CodeQL to only scan files in the `/src` folder - this should stop the false positive alerts we get for things in the `/tests` folder and elsewhere.
=> ci: Update CodeQL to only scan the src directory

src/Agent/NewRelic.Api.Agent/NewRelic.Api.Agent.csproj
Fixes #3018.  The agent API assembly has stub methods that contain System.Diagnostics.Tracing.WriteLine calls, mainly so that those methods have a body and use the parameters.  When the agent is actually attached to a process that uses the API, these methods get rewired by the profiler to be the actual API implementations inside the agent.  When running a program that makes agent API calls without the agent attached, the trace calls are made, harmlessly, or so we thought.  Turns out that for a while now, the TRACE constant has been set by msbuild by default, and must be actively disabled to avoid having these calls result in tracing output in certain circumstances (e.g. running your program in Visual Studio).
The fix is just to set …
=> fix: Remove diagnostics tracing output from agent API calls

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/StackExchangeRedisExerciser.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Redis/StackExchangeRedisTests.cs
Minor update to unbounded integration tests for StackExchange.Redis, to include `LockTake()` and `LockRelease()`. This was spurred by a support question where we needed to verify that these methods were being properly instrumented.
=> test: Update Redis integration tests to include `LockTake` and `LockRelease` calls.

src/Agent/NewRelic/Agent/Core/AgentManager.cs, src/Agent/NewRelic/Agent/Core/Core.csproj
Removes an unnecessary dependency on `System.Runtime.InteropServices.RuntimeInformtion` for .NET 4.6.2 builds. This has the helpful side effect of also removing a dependency on `System.Runtime` that was reportedly causing the .NET agent to crash for some users running the agent on a .NET Framework 4.8 application. 
Fixes #3032
=> fix: Remove unnecessary dependency on `System.Runtime.InteropServices.RuntimeInformation` in .NET 4.6.2  builds.

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/AwsSdk/KinesisHelper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/RequestHandlers/FirehoseRequestHandler.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/RequestHandlers/KinesisRequestHandler.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Helpers/KinesisHelperTests.cs
Clean up the POC branch.  Refactored some of the helper methods into a separate helpers class and added unit tests.  Also attempted to add caching of values for performance, and (based on reading online) avoid using try/catch as a control flow mechanism for request types without properties we're looking for, and use reflection instead.
=> Feature work: Kinesis POC cleanup

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Added a check for the `ASPNETCORE_IIS_APP_POOL_ID` environment variable if the `APP_POOL_ID` environment variable isn't available.
Fixes #3035
=> fix: Look for `ASPNETCORE_IIS_APP_POOL_ID` if `APP_POOL_ID` isn't found.

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/SharedInterfaces/Environment.cs, src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/MethodRewriter/ISystemCalls.h, src/Agent/NewRelic/Profiler/MethodRewriterTest/SystemCallsTest.cpp, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Updates the profiler logic to check for `ASPNETCORE_IIS_APP_POOL_ID` as a fallback when `APP_POOL_ID` isn't available.
Also includes a minor refactor in the agent related to the app pool id lookup work from yesterday.
Unit tests are updated as appropriate.
=> chore: Refactor app pool id lookup in profiler and agent

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AzureFunction/AzureFunctionInProcessExecuteWithWatchersAsyncWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AzureFunction/AzureFunctionIsolatedInvokeFunctionAsyncWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/AzureFunction/AzureFunctionHttpTriggerTests.cs, tests/Agent/IntegrationTests/IntegrationTests/AzureFunction/AzureFunctionQueueTriggerTests.cs, tests/Agent/IntegrationTests/IntegrationTests/AzureFunction/AzureFunctionServiceBusTriggerTests.cs
Updates naming of supportability metrics for Azure Functions so they all consistently start with `Supportability\Dotnet` - previously, we had a mixture of `Dotnet` and `DotNet`
=> chore: Update supportability metric names for Azure Function so they're consistent

src/Agent/NewRelic/Agent/Core/Core.csproj, tests/Agent/UnitTests/Core.UnitTest/Core.UnitTest.csproj
Updates to allow latest `System.ValueTuple` package to be used in `Core.csproj` without breaking `Core.UnitTest.csproj`. 
The trick was, apparently, to add a `System.ValueTuple` reference from the GAC for the `net481` build. 🤷
=> chore: Rework System.ValueTuple updates to use latest version

build/ArtifactBuilder/Artifacts/AzureSiteExtension.cs, build/ArtifactBuilder/Artifacts/NugetAgent.cs, build/ArtifactBuilder/Artifacts/NugetAgentApi.cs, build/ArtifactBuilder/Artifacts/NugetAzureCloudServices.cs, build/ArtifactBuilder/Artifacts/NugetAzureWebSites.cs, build/NewRelic.NuGetHelper/Utils.cs, build/Packaging/AzureSiteExtension/NewRelic.Azure.WebSites.Extension.nuspec, build/Packaging/AzureSiteExtension/README.md, build/Packaging/NugetAgent/NewRelic.Agent.nuspec, build/Packaging/NugetAgent/README.md, build/Packaging/NugetAgentApi/NewRelic.Agent.Api.nuspec, build/Packaging/NugetAgentApi/README.md, build/Packaging/NugetAzureCloudServices/NewRelicWindowsAzure.nuspec, build/Packaging/NugetAzureCloudServices/README.md, build/Packaging/NugetAzureWebSites-x64/NewRelic.Azure.WebSites.x64.nuspec, build/Packaging/NugetAzureWebSites-x64/README.md, build/Packaging/NugetAzureWebSites-x86/NewRelic.Azure.WebSites.nuspec, build/Packaging/NugetAzureWebSites-x86/README.md
Add README files to the NuGet packages we produce.
I also removed the `<summary>....</summary>` element from .nuspec files where it was present, as this field is deprecated in favor of the required `description` field. 
The content of the new REAME files is generally sourced from a combination of the existing description and summary fields, although in some cases I added additional links to our examples and/or documentation.  I also fixed outdated links to our documentation.
=> chore: Add READMEs to NuGet packages

src/Agent/NewRelic/Agent/Core/AgentInstallConfiguration.cs, src/Agent/NewRelic/Agent/Core/Config/BootstrapConfiguration.cs, src/Agent/NewRelic/Agent/Core/Config/ConfigurationLoader.cs, src/Agent/NewRelic/Agent/Core/Config/ConfigurationTracker.cs, src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs, src/Agent/NewRelic/Agent/Core/Instrumentation/InstrumentationWatcher.cs, src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs, src/Agent/NewRelic/Agent/Core/RuntimeEnvironmentInfo.cs, src/Agent/NewRelic/Agent/Core/Utilities/DirectoryWrapper.cs, src/Agent/NewRelic/Agent/Core/Utilities/ExtensionsLoader.cs, src/Agent/NewRelic/Agent/Core/Utilities/FileWrapper.cs, src/Agent/NewRelic/Agent/Core/Utilities/SystemInfo.cs, src/Agent/NewRelic/Agent/Core/Utilization/UtilizationStore.cs, src/Agent/NewRelic/Agent/Core/Utilization/VendorInfo.cs, src/Agent/NewRelic/Agent/Core/WireModels/LoadedModuleWireModelCollection.cs, tests/Agent/UnitTests/CompositeTests/CrossAgentTests/Utilization/UtilizationCrossAgentTests.cs, tests/Agent/UnitTests/Core.UnitTest/Utilization/VendorInfoTests.cs
* Refactors usage of `File.` and `Directory.` to use `IFileWrapper` and `IDirectoryWrapper` instead.
* Adds methods to `IFileWrapper` and `IDirectoryWrapper` as needed with default pass-through implementation.
* Adds a static `Instance` property to `FileWrapper` and `DirectoryWrapper` for use in static methods
* Removes `IFileReaderWrapper` and moves implementation to `IFileWrapper` and `FileWrapper`
* Does not alter any unit tests (aside from required argument refactoring); this change simply reduces friction for future unit tests that may need to mock file and directory operations.
* Did not attempt to refactor usages of `Path.` as that usage is ubiquitous throughout the codebase and we haven't previously had a need to mock that functionality for tests.
=> chore: Refactor usages of `File.` and `Directory.` to use wrappers

tests/Agent/IntegrationTests/IntegrationTests/AgentMetrics/DotNetPerfMetricsTests.cs
Trying to address test flakiness in DotNetPerfMetricsTests by adding a wait for metrics harvest log line
=> test: Added a wait for metrics harvest log line

tests/Agent/IntegrationTests/UnboundedServices/couchbase/Dockerfile
Adds a sha to the Couchbase `Dockerfile` to address https://github.com/newrelic/newrelic-dotnet-agent/security/code-scanning/407
=> test: Adds sha to Couchbase dockerfile to address security issue

src/Agent/NewRelic/Agent/Core/AgentInstallConfiguration.cs, src/Agent/NewRelic/Agent/Core/Config/BootstrapConfiguration.cs, src/Agent/NewRelic/Agent/Core/Config/ConfigurationLoader.cs, src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs, src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs, src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs, src/Agent/NewRelic/Agent/Core/RuntimeEnvironmentInfo.cs, src/Agent/NewRelic/Agent/Core/Utilities/DirectoryWrapper.cs, src/Agent/NewRelic/Agent/Core/Utilities/ExtensionsLoader.cs, src/Agent/NewRelic/Agent/Core/Utilities/FileWrapper.cs, src/Agent/NewRelic/Agent/Core/Utilities/SystemInfo.cs, src/Agent/NewRelic/Agent/Core/Utilization/UtilizationStore.cs, src/Agent/NewRelic/Agent/Core/WireModels/LoadedModuleWireModelCollection.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Couchbase/Couchbase3Exerciser.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Couchbase/Couchbase3Tests.cs, tests/Agent/UnitTests/CompositeTests/CrossAgentTests/SecurityPolicies/SecurityPoliciesCrossAgentTests.cs, tests/Agent/UnitTests/CompositeTests/CrossAgentTests/Utilization/UtilizationCrossAgentTests.cs, tests/Agent/UnitTests/CompositeTests/EventHarvestConfigSupportabilityMetricsTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ConnectionHandlerTests.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/ConvertMetricDataToJsonTests.cs, tests/Agent/UnitTests/Core.UnitTest/Utilization/UtilizationStoreTest.cs, tests/Agent/UnitTests/Core.UnitTest/Utilization/VendorInfoTests.cs
* Removes the static `FileWrapper.Instance` and `DirectoryWrapper.Instance` properties that were added in #3058, reverting to using `File.` and `Directory.` instead.
* Refactors unit tests to use a mock IFileWrapper in places where `File` was used previously.
Additional unit tests for changes in #3058 that use `IFileWrapper` will follow in a separate PR
=> chore: Revert static FileWrapper.Instance usage

src/Agent/NewRelic/Profiler/Configuration/Configuration.h
Recently I noticed some confusing profiler log messages when trying to troubleshoot a customer issue:
`[Info ] 2025-03-28 01:33:06 Process C:\HOME\SITE\WWWROOT\MYAPP.EXE with parent process  is not IIS.`
Note the extra space between "parent process" and "is not IIS".  This happens when this line is logged for a .NET Framework process; the profiler code explicitly passes an empty string for the parent process parameter to the function that logs this message.  This is because .NET framework web apps are expected to run inside the w3wp (IIS) process.
However, if you don't know all that, you might think the lack of a parent process in this log message indicates a problem.
This PR modifies that logging call to only log the "with parent process" bit if the parent process path string is …
=> fix: Profiler should not log "with parent process" unless parent process is non-empty

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore6Plus/AddNewRelicStartupFilter.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore6Plus/BrowserInjectingStreamWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore6Plus/ResponseCompressionBodyOnWriteWrapper.cs
Adds additional null checking in Asp.NET Core 6+ browser instrumentation to prevent null reference exceptions.
Fixes #3069
=> fix: Add more null checks to Asp.NET Core 6+ browser instrumentation logic

.github/workflows/pr-title-checker-config.json, .github/workflows/pr_title_checker.yml
Take two.  Use an available action to check PR titles for the correct prefix.  Should only apply to PRs into `main`.
=> ci: Add workflow and configuration file to check PR titles for correct format.

.github/workflows/pr_title_checker.yml
This also cleans up the `on` section to only have one trigger event type.
=> ci: Restrict PR title check job permissions

build/Dotty/CsprojHandler.cs, build/Dotty/Dotty.csproj, build/Dotty/Program.cs, build/Dotty/ProjectPackageInfo.cs
A quick update to Dotty that uses the [`Microsoft.Build`](https://www.nuget.org/packages/Microsoft.Build) package to parse csproj files and manage updates to package versions.  We now report the version in the project file as the "old" version and the latest Nuget package version as the "updated to" version.
This work lays the foundation for later work to extract the current set of package versions used in our project files for purposes of building the compatibility documentation.
=> ci: Update Dotty to use `Microsoft.Build` package for csproj parsing

.github/workflows/pr_title_checker.yml, src/Agent/NewRelic/Agent/Core/DataTransport/Client/NRHttpClient.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/Client/NRHttpClientFactoryTests.cs
Use the configured collector timeout value instead of a hard-coded `Timespan.Infinite` when creating `HttpClient` and `SocketsHttpHandler` instances. 
Fixes #3083
=> fix: Specify a non-infinite timeout when creating `HttpClient` and `SocketsHttpHandler` instances.

.github/workflows/pr_title_checker.yml
Required status check rules look at the job name, not the workflow name. This sets a name for the job run by the PR title checking workflow so we can make it a required status.
=> ci: Update name of PR title check job

.github/dependabot.yml
Due to licensing issues we want to avoid upgrading any WIX components to version 6+.
=> chore: Configure dependabot to avoid upgrading WIX to 6+.

tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/InfiniteTracingContainerTests.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/KafkaTests.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/LinuxContainerTests.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/LinuxUnicodeLogFileTest.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/MemcachedTests.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/AspNet/AllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/AspNet/AllowAllHeadersEnabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/AspNetCore/AllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/AspNetCore/AllowAllHeadersEnabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/EnvironmentVariables/AllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/EnvironmentVariables/AllowAllHeadersEnabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/Owin/AllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/Owin/AllowAllHeadersEnabledTestsBase.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/Owin/AsyncAllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/Owin/AsyncAllowAllHeadersEnabledTestsBase.cs
This one came up while troubleshooting container tests - even though the tests pass, the logline they're waiting for will never appear (because it's been refactored) and doesn't really do what the name implied. 
So I removed `HarvestLogLineRegex` and `HarvestFinishedLogLineRegex` and updated references to wait for one of the harvest data loglines instead.
=> test: Removes a couple of outdated logline regexes and refactors tests to wait for something more appropriate.

.github/workflows/dotty.yml, build/Dotty/Dotty.csproj
I forgot that you have to install .NET 9.0 on `ubuntu-latest` runners when I updated Dotty a week or two ago.
=> ci: Update Dotty workflow to install .NET 9.0

src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore6Plus/BrowserInjectionMiddleware.cs
In some cases, neither of the instrumentation wrappers for Asp.NET Core 6+ will be hit (for example, when OpenAPI and Swagger is configured), which means that no transaction will be created and can result in a null reference exception. 
Also updates the pipeline that executes the browser injection wrapper to check for a valid transaction, which will keep the wrapper from running when there is no transaction.
Fixes #3101
=> fix: Null reference exception in Asp.NET Core 6+ browser monitoring injection. 

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/WrapPipelineMiddleware.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore6Plus/WrapPipelineMiddleware.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/LoadHandlersConnectorWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Owin/OwinStartupMiddleware.cs
Updates a few instrumentation wrappers to move DT header acceptance prior to creation of the first segment, for better consistency with OTel.
=> chore: Where possible, refactored existing implementation to accept DT headers prior to first transaction segment

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs, src/Agent/NewRelic/Agent/Core/OpenTelemetryBridge/ActivityBridge.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/UnitTests/CompositeTests/CrossAgentTests/HybridAgent/HybridAgentTests.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ConnectModelTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ExhaustiveTestConfiguration.cs
Add `appSettings` configuration support for the list of Activity Sources that should included and excluded. Adds a (placeholder) list of default included activity sources.
=> Activity Source configuration

tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogFile.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplicationFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/ConfigBuilderDeadlock.cs
Adds the ability to include asserts in all integration tests (unbounded as well) that will run after the test app has finished writing to the agent log that can check for common problems.  This runs inside the Initialize method and within the retry loop to ensure they are run with every test and retry.  Has some logic to look for the log file prior to checking for matches to speed things up.
Currently, this only checks for transaction garbage collected.
Calling Fixture.KnownProblemsToCheck() will allow for adding new checks to the defaults, replacing them completely, or removing them.
Updates ConfigBuilderDeadlock tests to not require an agent log speeding up the test by ~3 minutes.
=> test: Add an assert to all integration tests for common errors and warnings

.github/dependabot.yml
* For some reason, Dependabot stopped adding conventional commit prefixes to PRs within the last month or so. This update specifies an explicit commit prefix that meets our requirements. 
* The version exclusion configuration for `WixToolset.*` was incorrect; this update fixes it to use the NuGet-specific version pattern. as per the [Dependabot docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#versions-ignore).
=> chore: Update Dependabot config

src/Agent/NewRelic/Agent/Core/AgentManager.cs, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/HandlerMethodWrapper.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaSmokeTest.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaTestToolFixture.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ExhaustiveTestConfiguration.cs
https://source.datanerd.us/agents/agent-specs/pull/733
Serverless APM Mode is a new agent mode required by the Lambda Fusion project, and which would allow Lambda telemetry to be displayed in the APM UI. Some of the requirements are handled by Serverless Team, as in the case of the Lambda Extension. One requirement, however, will (with some exceptions, such as Python) need to be handled by agents.
For this mode, the Function Name segment of the the transaction name will need to have the event source type added before the function name, separated from the function name by a space character. WebTransaction/Function/myFunction, for example, would be renamed WebTransaction/Function/apiGateway myFunction if triggered by API Gateway.
=> feat: Added transaction renaming requirement for Serverless APM mode

tests/Agent/IntegrationTests/HostedWebCore/Program.cs
This is a workaround for some environment variables introduced by newer versions of Visual Studio that include multi-line environment vars. These environment vars are written to the hostedwebcore logs, and these multi-line environment variables break our hostedwebcore log validator. By removing the newlines we can still get an idea of what the environment variable value is, and not need to increase the complexity in our hostedwebcore log validator.
=> test: strip newlines from environment variables in hostedwebcore tests

.github/workflows/linux_container_tests.yml, tests/Agent/IntegrationTests/Applications/AzureFunctionApplication/AzureFunctionApplication.csproj, tests/Agent/IntegrationTests/Applications/AzureFunctionApplication/ServiceBusTriggerFunction.cs, tests/Agent/IntegrationTests/Applications/AzureFunctionInProcApplication/AzureFunctionInProcApplication.csproj, tests/Agent/IntegrationTests/Applications/AzureFunctionInProcApplication/ServiceBusTriggerFunction.cs, tests/Agent/IntegrationTests/ContainerApplications/CustomBaseContainerBuild/README.md, tests/Agent/IntegrationTests/ContainerApplications/SmokeTestApp/Dockerfile.amazon, tests/Agent/IntegrationTests/ContainerApplications/SmokeTestApp/Dockerfile.fedora, tests/Agent/IntegrationTests/ContainerApplications/docker-compose.yml, tests/Agent/IntegrationTests/ContainerIntegrationTests/Applications/ContainerApplication.cs, tests/Agent/IntegrationTests/IntegrationTests/AzureFunction/AzureFunctionServiceBusTriggerTests.cs, tests/Agent/IntegrationTests/Shared/AzureServiceBusConfiguration.cs, tests/Agent/IntegrationTests/Shared/IntegrationTestConfiguration.cs
Updates the container integration tests to reference the new Azure container repository. Also slightly modifies the Azure Function service bus trigger tests to use a constant for the queue name.
=> ci: Update container tests to use new Azure container registry

src/Agent/NewRelic/Profiler/MethodRewriter/InstrumentFunctionManipulator.h, src/Agent/NewRelic/Profiler/MethodRewriter/Instrumentors.h, src/Agent/NewRelic/Profiler/Profiler/Function.h, src/Agent/NewRelic/Profiler/Profiler/FunctionPreprocessor.h, src/Agent/NewRelic/Profiler/RapidXML/rapidxml.hpp, src/Agent/NewRelic/Profiler/SignatureParser/Types.h
The latest Visual Studio update seems to have changed the compiler, and we were getting some warnings we weren't before. And since we have Warnings-as-Errors enabled, builds were failing. I think these are all safe changes but please look closely. :)
=> fix: Fix Profiler build errors with latest VS

.github/workflows/deploy-k8s-unboundedservices.yml
Adds a placeholder workflow for k8s deployment testing to allow for manual trigger from the branch where that workflow is being implemented.
=> ci: placeholder workflow for k8s deployment testing

.github/workflows/build_profiler.yml
Modifies the description of the automated profiler NuGet package reference update PR to include the commit reference that was used when building the profiler and the NuGet package.
=> chore: Add source commit info to profiler Nuget PR description

tests/Agent/IntegrationTests/UnboundedServices/build_and_push_acr.sh, tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml, tests/Agent/IntegrationTests/UnboundedServices/elastic8/Dockerfile, tests/Agent/IntegrationTests/UnboundedServices/elastic9/Dockerfile, tests/Agent/IntegrationTests/UnboundedServices/k8s/elastic8.yaml, tests/Agent/IntegrationTests/UnboundedServices/k8s/elastic9.yaml
Updates the unbounded services config (K8s and docker-compose) to deploy Elastic search v7, 8 and 9 servers, in preparation for our eventual support of testing on Elastic v9. 
For now, the v9 service will start and run but will not be used anywhere. Test secrets are not affected by this change (though they will get updated eventually so the Elastic / OTel bridge PR can run tests successfully).
Kibana was commented out of the docker-compose configuration, as we never really used it for anything anyway (it's a GUI tool for inspecting Elastic, which we haven't needed). We didn't (and won't) deploy Kibana on K8s.
=> ci: Update unbounded services config to include Elastic 7, 8 and 9 services.

.github/dependabot.yml, src/Agent/NewRelic/Agent/Core/Core.csproj, tests/Agent/NewRelic.Testing.Assertions/NewRelic.Testing.Assertions.csproj, tests/Agent/UnitTests/Core.UnitTest/Core.UnitTest.csproj, tests/Agent/UnitTests/Core.UnitTest/DataTransport/Client/NRHttpClientTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/Client/NRWebRequestClientTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/NewRelic.Agent.Extensions.Tests.csproj, tests/Agent/UnitTests/NewRelic.Agent.TestUtilities/NewRelic.Agent.TestUtilities.csproj, tests/Agent/UnitTests/NewRelic.Testing.Assertions.UnitTests/NewRelic.Testing.Assertions.UnitTests.csproj, tests/Agent/UnitTests/PublicApiChangeTests/PublicApiChangeTests.csproj
* Updates some Nuget packages that Dependabot seems unable to handle. Why does Dependabot skip them? Who knows. 
* Updates a couple of unit tests that reference `testhost.com` to use `google.com` instead, which avoids triggering CloudFlare WARP blocking when running the tests locally.
=> ci: Update Nuget packages that Dependabot won't. 

.github/dependabot.yml
Fix the ignore rule for Microsoft.Extensions.Configuration* to actually match Microsoft.Extensions.Configuration as well as its sub-namespaces.
=> chore: Fix ignore rule for Microsoft.Extensions.Configuration

.github/workflows/post_deploy_agent.yml, deploy/validation/validate-debian-latest/Dockerfile, deploy/validation/validate-debian-latest/check-version.sh, deploy/validation/validate-debian-oldest/Dockerfile, deploy/validation/validate-debian-oldest/check-version.sh, deploy/validation/validate-yum/check-version.sh
This PR updates the post-deploy APT/YUM repo install tests to:
1. Test Debian 13 (latest) and 11 (oldest-ish), using new repo signing key configuration logic that works equally well on both (see #3240 for context)
2. Use the new repo signing key config command for the `ubuntu-latest` case
3. Tweak the commands to get the version of the agent that was installed to output just the version, simplifying the version check logic
4. Made the names of the various validation jobs unique and descriptive
=> ci: Add more post-deploy Linux install tests

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Elasticsearch/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/Instrumentation.xml, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Minor updates to enable ElasticSearch and RabbitMQ instrumentation via OpenTelemetry Bridge. Adds the activity sources for Elastic and Rabbit to the default set of sources we listen to. 
Does NOT automatically enable OpenTelemetry Bridge. 
OpenTelemetry Bridge can be enabled in two ways: 
* Set an environment variable:
`NEW_RELIC_OPEN_TELEMETRY_BRIDGE_ENABLED=true`
* Edit the `<appSettings>` section in `newrelic.config`:
```
<appSettings>
<add key="OpenTelemetry.Enabled" value="true" />
</appSettings>
```
=> chore: Update ElasticSearch and RabbitMQ configuration for release with OpenTelemetry Bridge support
