newrelic/newrelic-dotnet-agent

src/Agent/NewRelic/Agent/Core/Attributes/AttributeValueCollection.cs
* Removes Dictionaries that track attribute values and counts by classification.  Since there are only 3 possible options, use switch statement instead to avoid object allocation
* AttributeValue Dictionaries created on demand to help avoid object allocation.
=> Infinite Tracing - Remove unnecessary dictionaries

docs/development.md
=> a few edits

docs/integration-tests.md
=> Some light edits

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
* Modify default for Count Consumers = 10
=> Infinite Tracing - Default Consumer Count = 10

src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/IAgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs, src/Agent/NewRelic/Agent/Core/DataTransport/IStreamingModel.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/MetricNames.cs, src/Agent/NewRelic/Agent/Core/Segments/SpanEventWireModel.cs, src/Agent/NewRelic/Agent/Core/WireModels/IMetricBuilder.cs, src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
* Created ability to Report Summary metric in the Agent Health Reporter.
* Created Supportability metric for Average Batch Size for Infinite Tracing.
* Test of the values
=> Infinite Tracing - Supportability Metric for Avg Batch Size

src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/IAgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/Aggregators/SpanEventAggregatorInfiniteTracing.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/MetricNames.cs, src/Agent/NewRelic/Agent/Core/WireModels/IMetricBuilder.cs, src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventAggregatorInfiniteTracingTests.cs
* Added supportability metric for Infinite Tracing Span Queue Size (number of items waiting to send)
* Associated Tests
=> Infinite Tracing - Supportability Metric for Queue Size

Build/Scripts/DotNet-Agent-CI-Build.ps1, Tests/UnitTests/Core.UnitTest/NewRelic.Agent.Core.FromLegacy/AgentLoggerTest.cs
Comments out integrations tests until they have been readded back to the repo
=> DOTNET-4768 Comments out integration tests

src/Agent/CHANGELOG.md
Adding a bug fix that we missed when documenting the changes in the 8.28 release.
=> Adding missing bug fix for 8.28 release

src/Agent/CHANGELOG.md
* Release note about performance improvement to Infinite Tracing
* Docs link to publish upon release
=> Infinite Tracing - Release Note

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Combines ExpectedStatusCodes property into ExpectedErrorsInfo.
=> Combines ExpectedStatusCodes property into ExpectedErrorsInfo

src/Agent/CHANGELOG.md, src/AwsLambda/CHANGELOG.md
Add open source announcement to changelogs for agent and lambda agent.
=> Release note open source announcement

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Asp35/IntegratedPipeline/ExecuteStepWrapper.cs, tests/Agent/UnitTests/Core.UnitTest/NewRelic.Agent.Core.FromLegacy/AgentLoggerTest.cs
Re-enables LoggerBootstrapperTests
=> uncomment previously failing tests

src/Agent/NewRelic/Agent/Core/Samplers/GcSampler.cs
* Reformatted GCSampler to use Spaces instead of tabs.
=> Tabs to Spaces

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/MatchRule.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Parse the `expectedStatusCodes` configuration into a list of matching status code rules. This list includes rules that match either exact status code or a range of status codes.
=> Expected status code parser

build/ArtifactBuilder/AgentComponents.cs, build/ArtifactBuilder/Artifacts/Artifact.cs, build/ArtifactBuilder/Artifacts/DowloadSiteArtifact.cs, build/ArtifactBuilder/Artifacts/MsiInstaller.cs, build/ArtifactBuilder/Artifacts/NugetAgentApi.cs, build/ArtifactBuilder/Artifacts/NugetAzureCloudServices.cs, build/ArtifactBuilder/Artifacts/NugetAzureWebSites.cs, build/ArtifactBuilder/Artifacts/ScriptableInstaller.cs, build/ArtifactBuilder/Artifacts/ZipArchive.cs, build/ArtifactBuilder/FileHelpers.cs, build/ArtifactBuilder/FrameworkAgentComponents.cs, build/ArtifactBuilder/NuGetHelpers.cs, build/ArtifactBuilder/Program.cs, build/package.ps1
Updates the package.ps1 and ArtifactBuilder to better match main branch and fixes a scripting issue
=> Update package.ps1 to match main agent and fix issue

tests/Agent/IntegrationTests/Applications/AspNetCoreMvcBasicRequestsApplication/Controllers/ExpectedErrorTestController.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs, tests/Agent/IntegrationTests/IntegrationTests/ExpectedErrorTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AspNetCoreMvcBasicRequestsFixture.cs
Adds integration tests for expected errors.
=> Adds integration tests for expected errors

src/Agent/NewRelic/Profiler/README.md
The README for the profiler was wildly out of date. This is a quick rough pass, though probably needs another pass.
=> Clean up profiler readme

src/Agent/NewRelic/Agent/Core/Errors/ErrorData.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/CustomErrorDataTransformerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/ErrorEventMakerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionEventMakerTests.cs
=> Refactoring ErrorData class

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs, src/Agent/NewRelic/Agent/Core/Errors/ErrorService.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs, tests/Agent/UnitTests/Core.UnitTest/Errors/ErrorServiceTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTransformerTests.cs
=> Ignore error logic modification to honor new configurations.

.github/PULL_REQUEST_TEMPLATE.md
Thank you for submitting a pull request.  Please review our [contributing guidelines](/CONTRIBUTING.md) and [code of conduct](/CODE_OF_CONDUCT.md).
I'm updating the PR template to be more streamlined and get rid of the HTML comments which just seemed like clutter.  Note: I've updated this PR's text to use the new template so this is what it will look like.
What unit or integration tests were added or modified, or why no testing changes were required.
This PR only modifies the PR template so no test changes are needed.
Please remember to update our [changelog](/src/Agent/CHANGELOG.md) if applicable (or [this changelog](/src/AwsLambda/CHANGELOG.md) for Lambda agent changes),
Updates to the PR template do not require a changelog entry.
=> Update PR template to see if it's easier to deal with

tests/Agent/IntegrationTests/UnboundedIntegrationTests/StackExchangeRedisStrongNameTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/StackExchangeRedisTests.cs, tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml, tests/Agent/IntegrationTests/UnboundedServices/redis/Dockerfile
Adds dockerized Redis service for UnboundedIntegrationTests.
Redis tests updated to change server name in generated Metrics.
No Changelog entry necessary.
=> adds docker container for redis

src/Agent/CHANGELOG.md
ChangeLog updates for Poxy Password Obfuscation
n/a
=> Proxy Password Obfuscation - Changelog updates

src/Agent/CHANGELOG.md
=> Change Log Updates for 6.26 release

tests/Agent/IntegrationTests/Shared/MsSqlOleDbConfiguration.cs, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/BasicMvcApplication.csproj, tests/Agent/IntegrationTests/UnboundedApplications/MongoDB2_6Application/MongoDB2_6Application.csproj, tests/Agent/IntegrationTests/UnboundedApplications/MongoDB2_6CoreApplication/MongoDB2_6CoreApplication.csproj, tests/Agent/IntegrationTests/UnboundedApplications/MongoDBApplication/MongoDBApplication.csproj, tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusReceiverHost/NServiceBusReceiverHost.csproj
Modifies project files in the unbounded int. tests solution to reduce build warnings.
The solution builds cleanly with fewer warnings, and the tests still pass.
N/A
=> Modify project files to reduce warnings when building

src/Agent/CHANGELOG.md
* Updates the release notes for v8.32
* moves unreleased .NET5 item to unreleased.
=> v832 ChangeLog Updates

.github/workflows/all_solutions.yml, src/Agent/NewRelic/Profiler/docker-compose.yml, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/Controllers/IbmDb2Controller.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/IbmDb2AsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/IbmDb2StoredProcedureTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/IbmDb2Tests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/IbmDb2BasicMvcFixture.cs
Resolves #231 
This adds a workflow that builds all the agent solutions and runs unit tests for the agent and our AWS Lambda SDK.
Unit tests
Since Actions does not have way to visualize test results I put together a solution that gets most of the way there.
- Tests output results in HTML.  These are interactive and highlight errors automatically
- Uses GitHub Pages to host test html pages
- Store in the gh-pages branch as recommended by GH
- Job in workflow push test results to gh-pages branch
- Job in workflow adds a "check-run" to workflow run that has links to test results.
All jobs in the workflow build without errors
n/a
=> Pr builder actions

.github/workflows/all_solutions.yml
I mainly want to test creating a PR from my fork, but this is also a positive change.
=> Correct spelling of solution

src/Agent/CHANGELOG.md
Update the changelog for v8.33
=> Update CHANGELOG.md for v8.33

tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/BasicMvcApplication.csproj, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/Controllers/MySqlConnectorController.cs, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/Web.config, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySqlConnectorTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/MySqlConnectorBasicMvcFixture.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj
This adds integration tests for MySqlConnector and fixes #200.
So far, this is just a copy/paste of the existing MySQL tests and only tests one code path; I want to make it more comprehensive. Opening this PR to demonstrate WIP and for any initial feedback.
=> Add integration tests for MySqlConnector

.github/workflows/all_solutions.yml
Add back the workflow job that combines the integration test results.  It also disables enhanced logging since it doesn't appear to be valuable anymore.
N/A
N/A
=> Add back combined artifacts

.github/workflows/all_solutions.yml
Removes some caching prework steps that should not have been added yet.
Just removes the extra steps.
N/A
=> Removes some prework that got committed.

.github/workflows/all_solutions.yml, build/Linux/docker-compose.yml
Updated Linux/docker-compose.yml to chomd 755 the `/deb` directory
Added script to build debian packages.
=> Build debian package

.github/workflows/all_solutions.yml
Resolves #343 
Note: the secrets needed for these changes have already been added to repo.
- Removes self-signing step
- Add step to convert SIGNING_CERT to PFX
- Adds step to install cert
New steps should build successfully and MSI must build successfully.
n/a
=>  Add the PFX for code signing into the workflow and remove self-signing

.github/workflows/deploy.yml, deploy/linux/docker-compose.yml
- deploy-downloadsite: fixed bad artifacts pathing
- Changed Setup NuGet API Key step to use pwsh
- deploy-linux: added chmods to bash scripts
=> Deploy fixes

.github/workflows/deploy.yml
Another deploy workflow fix.  Need to convert line ending format of files before running docker container for deploying linux packages to APT and YUM.
=> dos2unix all files for container

.github/workflows/deploy.yml
- Removes AWS config step and uses env vars instead
- switches shell over to pwsh from powershell since it handles secrets a bit better.
=> Downloadsite deploy fixes

.github/workflows/deploy.yml
=> Use different secrets for Linux deploy

build/build.ps1
Signing the .rpm package for the core agent is only required on release.  For local builds, it is optional.  Before this PR, the `build.ps1` script would skip building either the .deb or the .rpm if the signing key was not supplied.  This would prevent community contributors from using this script to build the Linux packages because they will not have our signing key.
I tested both cases (either supplying the signing key or not) and the Linux install packages were built in both cases.
Note: I am having a problem where I am unable to run the `build.ps1` script multiple times in the same Powershell session.  On running it the second time, it will end abnormally the first time it tries using Docker.  This seems to be due to some Powershell/Docker interaction that is not yet understood.  The …
=> build.ps1 should build linux packages with or without the RPM signing key

tests/Agent/UnitTests/CompositeTests/Samplers/GcSamplerNetCoreTests.cs
=> fix unit test

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Adds environment variable MAX_TRANSACTION_SAMPLES_STORED and associated unit tests.
Resolves Issue #404.
Unit tests.
=> Adds MAX_TRANSACTION_SAMPLES_STORED

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Adds environment variable MAX_EVENT_SAMPLES_STORED (for custom events) and associated unit tests.
Resolves Issue #405.
Unit tests.
Note: Additional commits are from an already-merged-to-main branch.
=> Adds MAX_EVENT_SAMPLES_STORED

build/build_functions.ps1, src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Core.csproj
Fixes #394 by updating GRPC nuget package to fix loading on Linux hosts for .NET 5.0.
Ran existing tests with updated dependency.
=> Update GRPC packages

src/Agent/CHANGELOG.md
Updates the agent's changelog for the 8.38 release.
=> Update changelog for 8.38 release

src/Agent/CHANGELOG.md
Update the agent's changelog on the net35/main branch for the 6.27 release.
N/A
N/A
=> Update CHANGELOG for 6.27 release

.github/workflows/all_solutions.yml, .github/workflows/awslambda_release.yml
Remove always if the condition for Win and Linux profiler
Added path to tracer test project and wrapper test project so that actions can find the unit tests
=> Lambda release fixes

.github/workflows/awslambda_release.yml
Fixed artifact builder paths to build properties.
=> Fixed artifact builder paths to build properties

.github/workflows/deploy_siteextension.yml, .github/workflows/siteextension_release.yml
What unit or integration tests were added or modified, or why no testing changes were required.
Please remember to update our [changelog](/src/Agent/CHANGELOG.md) if applicable (or [this changelog](/src/AwsLambda/CHANGELOG.md) for Lambda agent changes),
=> fix site extension release GHA.

.github/workflows/deploy_siteextension.yml, .github/workflows/siteextension_release.yml
Fix site extension release script. Need to build the NewRelic.NuGetHelper for the New Relic Azure Site Extension.
=> Fix site extension release script

.github/workflows/deploy_awslambda.yml, .github/workflows/deploy_siteextension.yml, .github/workflows/siteextension_release.yml, build/Packaging/AzureSiteExtension/Content/install.ps1, build/generateBuildProperties.ps1, src/Agent/CHANGELOG.md
Matched the deploy upload path to the download path in row 30 so that the script can find the artifacts.
=> Matched the deploy upload path to the download path in row 30

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/ChannelFactoryWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/DispatcherBuilderWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/MethodInvokerWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/ServiceChannelProxyWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/WcfIgnoreOuterTransactionWrapper.cs
Fix for [issue #507](https://github.com/newrelic/newrelic-dotnet-agent/issues/507).
Integration tests passed.
=> Remove hardcoded instrumentation points in wcf wrappers.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/BulkWriteOperationExecuteWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/MongoCollectionDefaultWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/MongoCollectionFindWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/MongoCollectionInsertWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/MongoCollectionRemoveWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/MongoCursorWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/MongoDatabaseDefaultWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/AsyncCursorWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/MongoCollectionBaseWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/MongoCollectionImplWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/MongoDatabaseWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/MongoIndexManagerBaseWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/MongoIndexManagerWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/MongoQueryProviderImplWrapper.cs
Fix for issue #503 and issue #504 .
Integration tests passed.
=> Remove hardcoded instrumentation points in MongoDb wrappers.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/BasicGetWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/BasicPublishWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/BasicPublishWrapperLegacy.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/HandleBasicDeliverWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/QueuePurgeWrapper.cs
Fixes for #505 and #506 issues.
=> Removes hard coded instrumentation points in rabbit wrappers.

.github/workflows/all_solutions.yml, tests/Agent/MultiverseTesting/ConsoleScanner/ConsoleScanner.csproj, tests/Agent/MultiverseTesting/ConsoleScanner/InstrumentationSet.cs, tests/Agent/MultiverseTesting/ConsoleScanner/Program.cs, tests/Agent/MultiverseTesting/ConsoleScanner/Properties/launchSettings.json, tests/Agent/MultiverseTesting/ConsoleScanner/README.md, tests/Agent/MultiverseTesting/ConsoleScanner/ScannerConfiguration.cs, tests/Agent/MultiverseTesting/ConsoleScanner/config.yml, tests/Agent/MultiverseTesting/MultiverseScanner/AssemblyAnalyzer.cs, tests/Agent/MultiverseTesting/MultiverseScanner/ExtensionSerialization/ExactMethodMatcher.cs, tests/Agent/MultiverseTesting/MultiverseScanner/ExtensionSerialization/Extension.cs, tests/Agent/MultiverseTesting/MultiverseScanner/ExtensionSerialization/Instrumentation.cs, tests/Agent/MultiverseTesting/MultiverseScanner/ExtensionSerialization/Match.cs, tests/Agent/MultiverseTesting/MultiverseScanner/ExtensionSerialization/TracerFactory.cs, tests/Agent/MultiverseTesting/MultiverseScanner/InstrumentationValidator.cs, tests/Agent/MultiverseTesting/MultiverseScanner/Models/AssemblyAnalysis.cs, tests/Agent/MultiverseTesting/MultiverseScanner/Models/AssemblyModel.cs, tests/Agent/MultiverseTesting/MultiverseScanner/Models/ClassModel.cs, tests/Agent/MultiverseTesting/MultiverseScanner/Models/InstrumentationModel.cs, tests/Agent/MultiverseTesting/MultiverseScanner/Models/MethodModel.cs, tests/Agent/MultiverseTesting/MultiverseScanner/MultiverseScanner.csproj, tests/Agent/MultiverseTesting/MultiverseScanner/README.md, tests/Agent/MultiverseTesting/MultiverseScanner/Reporting/ClassValidation.cs, tests/Agent/MultiverseTesting/MultiverseScanner/Reporting/InstrumentationReport.cs, tests/Agent/MultiverseTesting/MultiverseScanner/Reporting/MethodValidation.cs, tests/Agent/MultiverseTesting/MultiverseTesting.sln, tests/Agent/MultiverseTesting/README.md
Resolves: #511  
Resolves: #513 
Initial setup of Multiverse testing tool.
- Includes basic readme's
- Includes updated all_solutions.yml that builds and uploads multiverse binaries to S3 (new bucket in our team account with new secrets!)
It should build and upload to S3
n/a
=> Initial setup of Multiverse testing

tests/Agent/MultiverseTesting/ConsoleScanner/DownloadedNugetInfo.cs, tests/Agent/MultiverseTesting/ConsoleScanner/NugetClient.cs, tests/Agent/MultiverseTesting/ConsoleScanner/Program.cs, tests/Agent/MultiverseTesting/ConsoleScanner/Properties/launchSettings.json, tests/Agent/MultiverseTesting/ConsoleScanner/README.md, tests/Agent/MultiverseTesting/ConsoleScanner/config.yml, tests/Agent/MultiverseTesting/MultiverseScanner/AssemblyAnalyzer.cs, tests/Agent/MultiverseTesting/MultiverseScanner/Models/AssemblyModel.cs, tests/Agent/MultiverseTesting/MultiverseScanner/Reporting/AssemblyReport.cs, tests/Agent/MultiverseTesting/MultiverseScanner/Reporting/InstrumentationReport.cs
Resolves #517 
The tool now outputs the validation results to a yaml file.  You can specify the path and file name of this file.
Fix some minor issues, bugs, and formatting along the way.
Should build without issue.
=> Mvs write report

.github/workflows/multiverse_run.yml
Resolves #518 
- Fixes sudo issue when setting dependencies
- Improves pathing for artifacts uploada
- Now checks out the repo to validate
- Properly gets the date from powershell
- Moves the .NET setup to later in the workflow - better flow
=> Fixes problems with initial setup of MVS

src/Agent/Configuration/newrelic.config, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs
Lowercase request header attributes.
=> Lowercase request header attributes.

.github/workflows/all_solutions.yml
Allows scheduled runs to occur.
=> Updates conditional to allow scheduled ruhns

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/WrapPipelineMiddleware.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AspNetCoreMvcBasicRequestsFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/AspNetCore/AllowAllHeadersDisabled.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/AspNetCore/AllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/AspNetCore/AllowAllHeadersEnabledTests.cs
Add support for request headers capture for AspNetCore application.
Integration tests.
=> Request headers capture support for AspNetCore application.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Asp35/Shared/HttpContextActions.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/BasicMvcApplicationTestFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/Asp35/AllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/Asp35/AllowAllHeadersEnabledTests.cs
Resolves #558 
Added two new integration tests for validating enabled/disabled behavior.
=> Request Header capturing support for Asp35 

docs/integration-tests.md
Added a full powershell sample to install all required windows features for the unbounded integration tests.
I tested that the powershell sample that I added runs.
N/A
=> Update integration-tests.md with helpful powershell snippet

src/Agent/CHANGELOG.md
=> Update CHANGELOG.md for explain plans

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/MethodInvokerWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/WCF/AllowAllHeadersDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/WCF/AllowAllHeadersEnabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFClientTests.cs, tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFEmptyTestBase.cs, tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFLegacyTestBase.cs, tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFServiceExternalCallsTests.cs, tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFServiceExternalCallsTestsBase.cs, tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFServiceTests.cs, tests/Agent/IntegrationTests/Shared/WCF/IWcfClient.cs, tests/Agent/IntegrationTests/Shared/WCF/IWcfService.cs, tests/Agent/IntegrationTests/Shared/WCF/WcfClient.cs, tests/Agent/IntegrationTests/Shared/WCF/WcfEnums.cs, tests/Agent/IntegrationTests/Shared/WCF/WcfService.cs, tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationFW/NetFrameworkLibraries/WCF/WCFClient.cs
=> Fix missing external call instrumentation.

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Profiler/Configuration/Configuration.h, src/Agent/NewRelic/Profiler/ConfigurationTest/ShouldInstrumentTest.cpp
Resolves #616 with an updated Kudu check string for the Profiler.
Added a new unit test to validate this new Kudu command is ignored.
=> Updated Kudu check string and added new command to unit test

src/AwsLambda/CHANGELOG.md
=> Update Lambda CHANGELOG.md

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs
Resolves #627 with some updates to not clear headers.
Played around with adding some tests for this but couldn't find a consistent way to do it, though this change is relatively low impact.
=> Fix gRPC license key header issue

.github/workflows/multiverse_run.yml
Bad file name agent-version to agent_version
=> Bad file name agent-version to agent_version

.github/workflows/all_solutions.yml
Enabling CI builds for PRs against the 9x feature branch
About to test it after I merge to main :)
=> enable ci builds for 9x-feature-branch

.github/workflows/all_solutions.yml
Perhaps I need to merge this in to the actual feature branch, instead of main....
=> enable ci builds for 9x-feature-branch (#688)

tests/Agent/MultiverseTesting/ReportBuilder/HtmlMaker.cs, tests/Agent/MultiverseTesting/ReportBuilder/VersionComparer.cs
Sorts the index for the Multiverse Testing Report from newest oldest to make it more readable.
=> Sort versions from newest to oldest

src/Agent/CHANGELOG.md
What unit or integration tests were added or modified, or why no testing changes were required.
Please remember to update our [changelog](/src/Agent/CHANGELOG.md) if applicable (or [this changelog](/src/AwsLambda/CHANGELOG.md) for Lambda agent changes),
=> Update CHANGELOG.md to call out CAT deprecation.

src/Agent/CHANGELOG.md
Make sure all changes are in changelog prior to releasing 9.0.0
=> Ready v9 changelog

src/Agent/CHANGELOG.md
=> Fixed grammatical errors and reworded #532

src/Agent/CHANGELOG.md
Update changelog to mark 9.0.0 as released
Don't merge till v9 is released!
=> Update changelog to mark 9.0.0 as released

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Samplers/GcSampler.cs
Currently we handle some exceptions without logging them.  This makes it very difficult to troubleshoot problems outside of some very specific cases. 
Moves detection of UnauthorizedAccessException into Sample method
Removes HandleException since all it did was pull out UnauthorizedAccessException
Adds finest log message to first try-catch in Sample to ensure we are logging all exceptions
- [x ] Unit tests, Integration tests, and Unbounded tests completed
- [ x] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated
=> Refactor gcsampler log all exceptions

.github/workflows/multiverse_run.yml
JamesIves/github-pages-deploy-action doesn't support base versions
=> JamesIves/github-pages-deploy-action doesn't support base versions

.github/workflows/multiverse_run.yml
Path to reports was in correct preventing upload of artifacts.
=> Fix pathing issue in workflow

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/CosmosDB/CosmosDBExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/CosmosDB/SalesOrder.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/CosmosDB/CosmosDBTests.cs
Adds integration tests to test CosmosDB item related api calls.
Calls tested:
- `Container.CreateItemStreamAsync()` and `Container.CreateItemAsync()`
- `Container.UpsertItemStreamAsync()` and `Container.UpsertItemAsync()`
- `FeedIterator.ReadNextAsync()`
- `Container.ReadManyItemsStreamAsync()` and `Container.ReadManyItemsAsync()`
=> Cosmosdb item management operations tests

build/ArtifactBuilder/ArtifactBuilder.csproj, build/ArtifactBuilder/CoreAgentComponents.cs, build/ArtifactBuilder/FrameworkAgentComponents.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/CosmosDB/CosmosDBExerciser.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/CosmosDB/CosmosDBTests.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
Resolves #785 by adding tests for Cosmos DB query methods.
=> Cosmosdb query method tests

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/CosmosDB/CosmosDBExerciser.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/CosmosDB/CosmosDBTests.cs
=> Adds CosmosDb batch operation related tests.

.github/workflows/deploy_agent.yml
Renames deploy.yml to deploy_agent.yml (fixes an issue in vs code with schema)
Add fastly cache clearing step
Resolves #777
=> Updates deploy.yml for fastly

.github/workflows/multiverse_run.yml
Fixing pathing in MVS. 
Growing pains due to making this a reusable workflow.
=> Fixing pathing in MVS

.github/workflows/multiverse_run.yml, tests/Agent/MultiverseTesting/ConsoleScanner/config.yml
Adds Postgres to MVS with some fixes.
=> Mvs add postgres

.github/workflows/multiverse_run.yml
Hopefully that last fix for MVS publishing
Had to split it back into 2 jobs and use artifacts again since we need to be on the gh-pages branch to ensure we keep all the past data.
=> Publishing fixed for MVS

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Providers/Wrapper/Delegates.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/LoadHandlersConnectorWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/NServiceBus.csproj, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/NServiceBusHelpers.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/ReceiveMessageWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/SendMessageWrapper.cs
Adds the `LoadHandlersConnectorWrapper` wrapper to instrument NServiceBus 6/7 message receive.
=> Adds NServiceBus 6/7 message receive instrumentation.

.github/workflows/all_solutions.yml
=> Adds back on build

.github/workflows/all_solutions.yml, tests/Agent/MultiverseTesting/ConsoleScanner/config.yml
Resolves #823 by uncommenting the NServiceBus section that already existed in the Multiverse Scanner `config.yml` and adding the latest versions.  Tested locally and it worked as expected.
=> Add NServiceBus to Multiverse Scanner

build/ArtifactBuilder/CoreAgentComponents.cs
Adds NServiceBus to CoreComponents in ArtifactBuilder
=> Adds NServiceBus to CoreComponents in ArtifactBuilder

tests/Agent/UnitTests/CompositeTests/DistributedTracingTests.cs
Resolves #141 with a new unit test targeting `http` span events.
=> Added unit test for http span event category.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/LoadHandlersConnectorWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/NServiceBusHelpers.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/PipelineWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/ReceiveMessageWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/SendMessageWrapper.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbAsyncCmdHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbAsyncEventHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbCmdHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbEventHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbPublishTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbSendTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbThrowingHandlerTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus5/NServiceBus5SendTests.cs
- Split out the various calls to the VisibiltyBypasser from the NSB wrappers into their own functions
- Updated tests to account for names now appearing
- Added support for noticing errors from the LoadHandlersConnectorWrapper with test
- Minor formatting and naming changes
=> NServiceBus updates, clean up and working pass

src/Agent/CHANGELOG.md
Changelog update for 9.4.0 release
=> 9.4.0 release changelog update

tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/DistributedTracing/DistributedTracePayloadHandlerTests.cs
Made the same typo in a search box and was surprised to see this =) I didn't test the change, simply renamed in a gitHub web editor
=> tracepararent is a typo

build/Packaging/NugetAgent/NewRelic.Agent.nuspec, build/Packaging/NugetAgentApi/NewRelic.Agent.Api.nuspec, build/Packaging/NugetAzureWebSites-x64/NewRelic.Azure.WebSites.x64.nuspec, build/Packaging/NugetAzureWebSites-x86/NewRelic.Azure.WebSites.nuspec
Fixes #883 by updating URLs in NuGet package metadata.
=> Fix broken/obsolete URLs in NuGet package metadata

build/Packaging/AzureSiteExtension/NewRelic.Azure.WebSites.Extension.nuspec, build/Packaging/NugetAgent/NewRelic.Agent.nuspec, build/Packaging/NugetAgentApi/NewRelic.Agent.Api.nuspec, build/Packaging/NugetAwsLambdaOpenTracer/NewRelic.OpenTracing.AmazonLambda.Tracer.nuspec, build/Packaging/NugetAzureCloudServices/NewRelicWindowsAzure.nuspec, build/Packaging/NugetAzureWebSites-x64/NewRelic.Azure.WebSites.x64.nuspec, build/Packaging/NugetAzureWebSites-x86/NewRelic.Azure.WebSites.nuspec, build/Packaging/ScriptableInstaller/NewRelic.Net.Agent.nuspec, build/Packaging/ScriptableInstaller/NewRelic.Net.Agent.x64.nuspec
This should fix #896 by updating the `<iconUrl>` element in all of our .nuspec files.  Thanks to @jtim08515 for bringing this issue to our attention.
=> Update iconUrl in nuspec files

src/Agent/CHANGELOG.md
Update CHANGELOG with items for 9.5.0 release.
=> Add 9.5.0 changelog items

src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/EventHarvestConfig.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
- Update XSD with new config settings for log fowarding, defaulting to enabled and 50000 samples (will likely change prior to EA)
- Updates faster event harvest to support log forwarding
- Updates DefaultConfiguration with new values from XSD and faster event harvest.
- Adds unit tests for the new configuration
=> Adds configuration for log forwarding

src/Agent/NewRelic/Agent/Core/JsonConverters/LogEventWireModelCollectionJsonConverter.cs, src/Agent/NewRelic/Agent/Core/WireModels/LogEventWireModel.cs, src/Agent/NewRelic/Agent/Core/WireModels/LogEventWireModelCollection.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LogEventWireModelCollectionJsonConverterTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelCollectionTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelTests.cs
Closes #902.
Adds wire models and a JSON serializer for new log data feature. Includes unit tests
=> Add wire models and json serializer for Logging Instrumentation

src/Agent/CHANGELOG.md
9.5.0 post-release changelog update.
=> Update changelog for 9.5.0 release

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs
* Uses VisibilityBypasser for performance reasons
* No testing until integration tests (when all stories are done)
Resolves #906
=> Update log4net wrapper to call RecordLogMessage

tests/Agent/IntegrationTests/IntegrationTestHelpers/SkipAttributes.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Utilities.cs, tests/Agent/IntegrationTests/IntegrationTests/InfiniteTracing/InfiniteTracingTests.cs
Changes necessary to get our integration tests to pass on Alpine Linux.
=> Integration tests pass on Alpine

src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TestTransactions.cs
=> Update application logging config names and default values

src/Agent/CHANGELOG.md
Fix one broken link in the agent changelog.
=> Update broken link in CHANGELOG

src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/IAgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/Aggregators/LogEventAggregator.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/MetricNames.cs, src/Agent/NewRelic/Agent/Core/WireModels/IMetricBuilder.cs, src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/IAgentExperimental.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/Log4netMetricsAndForwardingTests.cs, tests/Agent/UnitTests/Core.UnitTest/AgentHealth/AgentHealthReporterTests.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/AgentWrapperApiTests.cs
Closes #937 
Renames several supportability metrics, and adds a few new ones for log forwarding. 
Introduced a way to use the agent health reporter to send metrics once on startup, or after any configuration change.
=> Supportability Metrics for log forwarding

src/Agent/NewRelic/Agent/Core/Agent.cs
Change MISSING_LEVEL to UNKNOWN for no log level
=> Loglevel naming update

src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/EventHarvestConfig.cs
- Added missing harvest limits for log forwarding to faster event harvest.
- Updated config to properly override local and env var with server value.
- No tests were broken
=> Missed pulling limits for logging

src/Agent/CHANGELOG.md
=> update changelog for imdsv2

src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/LoggingHelpers.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/Log4netJsonLayoutDecorationTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/Log4netPatternLayoutDecorationTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/Log4netTester.cs
- Updates max samples to 10000
- Updates linking blob as a positional blob to match brief `NR-LINKING|{entity.guid}|{hostname}|{trace.id}|{span.id}|`
- Updated integration tests to use new format, all passed
=> Sync up with brief before cutting EA release

src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Enable logging metrics by default.
=> Set application logging and metrics enabled to true by default

src/Agent/CHANGELOG.md
Update CHANGELOG.md for v9.6.0 release
=> Update CHANGELOG.md for v9.6.0 release

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/SerilogWrapper.cs
- Updates the Serilog local log decoration code to use the helper method and align with log4net
Resolves #969
=> Updates serilog decoration to match log4net style

tests/Agent/IntegrationTests/IntegrationTests/Logging/SerilogHSMOrCSPDisablesForwardingTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/SerilogJsonLayoutDecorationTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/SerilogMaxSamplesStoredTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/SerilogPatternLayoutDecorationTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/SerilogLoggingAdapter.cs
- Adds new integration tests for serilog local log decoration
- Also adds max samples and HSM tests for serilog as well.
Resolves #976
=> Adds serilog decoration tests

FullAgent.sln, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Logging/LogProviders.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/SerilogWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/LoggerFactoryWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/MicrosoftExtensionsLogging.csproj
Merge sub-feature branches into one feature branch
Step 1: msl-extensions-feature-branch into serilog-instrumentation-feature-branch
=> Merge sub-feature branches into one feature branch

src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/MetricNames.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/Log4netMetricsAndForwardingTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/SerilogMetricsAndForwardingTests.cs, tests/Agent/UnitTests/Core.UnitTest/AgentHealth/AgentHealthReporterTests.cs
- Updates `Supportability/Logging/{enabled}/{language}/{framework}` to `Supportability/Logging/{language}/{framework}/{enabled}` to match spec
=> Updates framework supportability metric to match spec

src/Agent/CHANGELOG.md
Post-deploy update of changelog for 9.6.1 release
=> Update changelog for 9.6.1 release

src/Agent/CHANGELOG.md
Adds deprecation notices for scriptable installers and established release.
=> Updates changelong with deprecations

src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Core/JsonConverters/LogEventWireModelCollectionJsonConverter.cs, src/Agent/NewRelic/Agent/Core/WireModels/LogEventWireModel.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Models/LogData.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/MaxSamplesStoredTests.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/MetricsAndForwardingTests.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LogEventWireModelCollectionJsonConverterTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelCollectionTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/AgentWrapperApiTests.cs
- Updates applicationLogging level to be log.level
- Updates tests with new name and changes some variable names to match
All tests passed.
Closes #1044
=> Updates applicationLogging level to be log.level

src/Agent/CHANGELOG.md
=> v.9.7.0 change log

src/Agent/MsiInstaller/Installer/Product.wxs
* Add missing components to MSI installer wix config.
* Double checked on my test server that the files are present now
* Also double checks zipped/linux packages and they also have the files.
=> Add missing logging components to MSI Wix config

src/Agent/CHANGELOG.md
=> Update changelog for 9.7.1 release

build/Packaging/AzureSiteExtension/CHANGELOG.md
Update changelog for 1.5.3 release of azure site extension
=> Update azure site extension changelog for 1.5.3 release

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
* Adds environment variables for all proxy settings
* Updates string version of EnvironmentOverrides to properly handle whitespace
* Adds unit tests for each proxy setting, testing local and env vars
* change log updates!!!!!!
Closes #878
=> Adds environment variables for all proxy settings

src/Agent/CHANGELOG.md
=> Update changelog for v9.8.0

docs/integration-tests.md, tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/Rules.cs
Documented at a high-level the requirements for everything (mostly) that broke on me upon setting up Integration tests locally, including prior to using the shared account the team typically uses internally.
This does make the doc a bit verbose and nested pretty deep. We might consider splitting out the instructions for Visual Studio VS Linux at some point.
=> Adds requirement clarification to Integration test docs and fixes a link.

src/Agent/CHANGELOG.md
=> Update changelog for v9.8.1

tests/Agent/UnitTests/Core.UnitTest/Samplers/MemorySamplerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
Makes unit tests less likely to fail locally, and in CI
=> Harden unit tests

src/Agent/CHANGELOG.md
Create section for 9.9.0 release. Remove unsupported versions
=> .NET Agent v9.9.0 changelog update

.github/workflows/all_solutions.yml, tests/Agent/IntegrationTests/Shared/CosmosDBConfiguration.cs
Changes the GHA All Solutions workflow to start the CosmosDB Emulator for the CosmosDB Unbounded Test. A separate secrets update will also be required (outside of public code).
=> Use GHA native CosmosDB emulator for CI

.github/workflows/all_solutions.yml
Per discussion with @angelatan2, we would like to run CI daily. If anyone objects, please add some comments! :)
=> Change CI to run daily

.github/ISSUE_TEMPLATE/story.md
My internal spell-checker noticed a typo when I was looking at git history
=> Fix Typo in story.md

tests/Agent/IntegrationTests/IntegrationTests/DataTransmission/ConnectResponseHandlingTests.cs
Increases the robustness of the test by waiting for all 4 relevant agent harvest events to occur before querying the mock collector to see if they had been called.
These changes were motivated by this failure:
https://github.com/newrelic/newrelic-dotnet-agent/runs/7868767951?check_suite_focus=true#step:10:206
=> Make ConnectResponseHandling test wait for relevant agent events

build/Packaging/AzureSiteExtension/NewRelic.Azure.WebSites.Extension.nuspec, build/Packaging/NugetAgent/NewRelic.Agent.nuspec, build/Packaging/NugetAgentApi/NewRelic.Agent.Api.nuspec, build/Packaging/NugetAwsLambdaOpenTracer/NewRelic.OpenTracing.AmazonLambda.Tracer.nuspec, build/Packaging/NugetAzureCloudServices/NewRelicWindowsAzure.nuspec, build/Packaging/NugetAzureWebSites-x64/NewRelic.Azure.WebSites.x64.nuspec, build/Packaging/NugetAzureWebSites-x86/NewRelic.Azure.WebSites.nuspec
Fixes #1235, as well as other issues with links in our .nuspec files in general:
1. Use https everywhere
2. Some links were working, but with redirects.  Just link to the real page.
3. one.newrelic.com instead of rpm.newrelic.com
=> Update links in NuSpec files

.github/workflows/nuget_slack_notifications.yml
This workflow doesn't do anything, it's just to make the workflow available in the Actions tab
=> Add skeleton workflow for testing Dotty Slack app

.github/workflows/nuget_slack_notifications.yml, .github/workflows/scripts/nugetSlackNotifications/Program.cs, .github/workflows/scripts/nugetSlackNotifications/nugetSlackNotifications.csproj
Adds the Dotty Slack bot to notify team of updates to our core technologies.
=> Add Dotty slack bot.

src/Agent/CHANGELOG.md
Update changelog for log exception attributes
=> Update changelog for log exception attributes

.github/workflows/scripts/nugetSlackNotifications/Program.cs
Makes some improvements to our Dotty slack bot:
- Adds links to release on nuget.org
- Filters out prerelease versions
- Includes semver2 packages
=> Dotty improvements

src/Agent/NewRelic/Agent/Core/BrowserMonitoring/BrowserMonitoringWriter.cs
=> update link to Browser injection specification

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/AgentManager.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/AspNetCoreMvcCodeAttributeTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/FrameworkAspNetMvcCodeAttributeTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/FrameworkCustomInstrumentationCodeAttributeTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/NetCoreCustomInstrumentationCodeAttributeTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/OwinWebApi2CodeAttributeTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/WebApi2CodeAttributeTests.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
This PR Enables code level metrics by default, and updates associated test cases.
It also includes a few new environment variables in the application startup debug logging to give support a more complete picture of how an agent is configured.
=> Enable Code Level Metrics by default

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/JsonConverters/JsonSerializerHelpers.cs
This PR fixes the issue where the NewtonSoft JsonWriter failed to serialize non primitive types.
=> Fix NewtonSoft JsonWriter

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RabbitMQ.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqDistributedTracingTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqTests.cs, tests/Agent/MultiverseTesting/ConsoleScanner/config.yml
- Updates the versions we test in our unbounded tests to cover the different major versions and to use available nuget packages
- Updates the test names to match the pattern we use for other ConsoleMF-based fixtures.
- Updates the versions in MVS to match the ones we test.
https://issues.newrelic.com/browse/NEWRELIC-4188
=> Updates RabbitMQ unbounded tests with different versions

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/MultiverseTesting/ConsoleScanner/config.yml
* Updates NLog tests to use latest version
* Adds NLog to Multiverse Scanner
=> Updating NLog tests to latest

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlAsyncParameterizedQueryTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlWithParameterizedQueryTests.cs, tests/Agent/MultiverseTesting/ConsoleScanner/config.yml
Add tests for Microsoft.Data.SqlClient ver 1.0.19239.1
=> Add tests for Microsoft.Data.SqlClient ver 1.0.19239.1

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/MultiverseTesting/ConsoleScanner/config.yml
=> MySQL Core tech update

build/Packaging/AzureSiteExtension/CHANGELOG.md, build/Packaging/AzureSiteExtension/Content/install.ps1, build/Packaging/AzureSiteExtension/NewRelic.Azure.WebSites.Extension.nuspec
* Updates the title of the NewRelic.Azure.WebSites.Extension nuget package to match the new format used by the recently deployed Java Agent nuget package. Changed from "New Relic" to "New Relic .NET Agent".
* Updates the copyright date since I was in there.
* Updates the scripting to also use the full title in any logs
* Updates the changelog for for the site extension to call out the name change
=> Updates Azure Site Extension title and scripting

build/Packaging/AzureSiteExtension/NewRelic.Azure.WebSites.Extension.nuspec
Change copyright on site extension to 2022
=> Change copyright on site extension to 2022

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/DataTransport/SpanGrpcWrapper.cs
Addresses a potential crash in gRPC. Customer reported that the test build containing this change fixed their problem.
=> use deadline in ConnectAsync()

src/Agent/CHANGELOG.md
Update CHANGELOG.md for v10.4.0
=> Update CHANGELOG.md for v10.4.0

README.md
Updated our banner to the new logo
=> Update README.md to show new logo

README.md, src/AwsLambda/CHANGELOG.md
Adding a deprecation notice to allow our users to discover that the support of this offering is changing.  
- [N/A] Unit tests, Integration tests, and Unbounded tests completed
- [N/A] Performance testing completed with satisfactory results (if required)
- [Lambda Only] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated
=> .NET AWS Lambda Deprecation notice

src/Agent/CHANGELOG.md
=> Update Changelog for v10.5.0

src/Agent/CHANGELOG.md
=> Changelog update for 10.5.1

.github/workflows/run_unit_tests.yml
Allows us to run the workflow on demand
=> Added workflow_dispatch to run_unit_tests.yml

.github/workflows/run_unit_tests.yml
Unit Test / Code Coverage Workflow will now run on any push to `main` (which should only be when  a PR to `main` completes), as well as on a PR to any branch.
=> Change triggers for Unit Test / Code Coverage Workflow

src/Agent/CHANGELOG.md
Updating changelog for 10.6.0 release
=> 10.6.0 release

.github/workflows/all_solutions.yml
Update branch name pattern to match for enabling the full CI on feature branches.
=> Change feature branch name pattern

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Update the latest version of MongoDB.Driver tested to 2.19.0.
=> Update latest MongoDB.Driver version tested to 2.19.0

src/Agent/CHANGELOG.md, src/NewRelic.Core/NewRelic.Collections/PartitionedBlockingCollection.cs, tests/Agent/UnitTests/ParsingTests/SqlParserTests.cs
There are a few warnings we see in every PR. I have removed the ones that are related to unused variables and outdated API usage. There is a Spec related `#warning` that I left.
=> Cleanup code analysis warnings

build/Packaging/AzureSiteExtension/CHANGELOG.md, build/Packaging/AzureSiteExtension/Content/applicationHost.xdt
Adds a new environment variable to capture the app service name at startup.
=> Added app service name to Azure Site Extensions xdt

build/Packaging/AzureSiteExtension/CHANGELOG.md
Updated the changelog for the Azure Website Extension v1.5.5 release.
=> Updated changelog for Azure website extension release

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTests/InfiniteTracing/InfiniteTracingFlakyTests.cs, tests/Agent/IntegrationTests/IntegrationTests/InfiniteTracing/InfiniteTracingTests.cs
Adds missing error supportability metric generation to gRPC response streams.
Changes the log lines that are waited on in Infinite Tracing integration tests to allow more deterministic test results.
Introduces a new Integration test log helper to wait on captured count totals for log line regexes.
=> Add missing error metrics and stabilize Infinite Tracing integration tests 

src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/MetricNames.cs, tests/Agent/UnitTests/Core.UnitTest/AgentHealth/AgentHealthReporterTests.cs, tests/Agent/UnitTests/Core.UnitTest/Metrics/MetricNamesTests.cs
Adds a supportability metric that represents whether or not compression was enabled or disabled for infinite tracing.
- ~~[ ] Performance testing completed with satisfactory results (if required)~~ Performance testing is being tested separately
- ~~[ ] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated~~ Nothing new to add to the changelog
=> Add Infinite Tracing compression supportability metric

deploy/linux/Dockerfile, src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/MicrosoftLoggingWrapper.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/Common.cs, tests/Agent/IntegrationTests/IntegrationTests/Logging/ContextDataNotSupportedTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/DummyMELAdapter.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/LoggingTester.cs
Merges latest code from `main` in to `feature/grpc-hybrid-solution`, resolves a couple of minor merge conflicts.
=> Merge main into grpc-hybrid-solution feature branch

src/Agent/CHANGELOG.md
Updating the changelog to include the 10.7.0 release.
- ~~[ ] Unit tests, Integration tests, and Unbounded tests completed~~ Just a changelog update
- ~~[ ] Performance testing completed with satisfactory results (if required)~~ Just a changelog update
=> Update changelog to mark 10.7.0 as released

licenses/THIRD_PARTY_NOTICES.txt
=> Move THIRD_PARTY_NOTICES.txt back to licenses folder

src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs, src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/ApiSupportabilityMetricCounters.cs, src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/ErrorEventMaker.cs, src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/ErrorTraceMaker.cs
Updates the error group fingerprint attribute name, definition, and enum to match the names specified in #1399. 
- ~~[ ] Unit tests, Integration tests, and Unbounded tests completed~~ Just a rename.
- ~~[ ] Performance testing completed with satisfactory results (if required)~~ Just a rename
- ~~[ ] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated~~ Just a rename
=> Rename error group fingerprint to error group

src/Agent/NewRelic.Api.Agent/Transaction.cs, src/Agent/NewRelic/Agent/Core/Api/AgentApiImplementation.cs, src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Core/Transformers/CustomErrorDataTransformer.cs
Minor cleanup to address requirements changes. Removed `userId` references from `ProcessNoticedError()`, added `IsNullOrEmpty()` check before attempting to set the userId in `CustomErrorDataTransformer.Transform()`, updated `EndUserId` to include `TransactionTrace` and `TransactionEvent` as destination types.
- ~~[ ] Performance testing completed with satisfactory results (if required)~~
- ~~[ ] [Agent Changelog](/src/Agent/CHANGELOG.md) or [Lambda Agent changelog](/src/AwsLambda/CHANGELOG.md) updated~~
=> User Tracking cleanup

src/Agent/NewRelic.Api.Agent/ITransaction.cs, src/Agent/NewRelic.Api.Agent/Transaction.cs, src/Agent/NewRelic/Agent/Core/Api/TransactionBridgeApi.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ITransaction.cs, tests/Agent/IntegrationTests/IntegrationTests/Api/TransactionUserIdTests.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/ApiCalls.cs, tests/Agent/UnitTests/Core.UnitTest/Api/TransactionBridgeApiTests.cs, tests/Agent/UnitTests/Core.UnitTest/Transformers/CustomErrorDataTransformerTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/Builders/TransactionTests.cs
Adds unit and integration tests for User Tracking.
=> User Tracking Unit and Integration Tests

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
MySql released version 8.0.32.1 of their driver. This PR updates our tests that were using the 8.0.32 driver to now use the 8.0.32.1 driver.
=> Update MySql tests to test most recent version

src/Agent/CHANGELOG.md
Add error grouping and user tracking to agent changelog
=> Add error grouping and user tracking to agent changelog

src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/Environment.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/RuntimeEnvironmentInfo.cs, tests/Agent/UnitTests/Core.UnitTest/Utilities/RuntimeEnvironmentInfoTests.cs
Added two new environment settings `Linux Distro Name` and `Linux Distro Version` that will report the name and version when the agent is running on a Linux host.
=> feat: add new settings to report linux distro name and version

licenses/THIRD_PARTY_NOTICES.txt, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/RuntimeEnvironmentInfo.cs
Updates third party notices file and header in RuntimeEnvironmentInfo.cs to comply with guidance from legal regarding copyright statements.
=> chore: update license / copyright info for legal compliance

src/Agent/CHANGELOG.md
Added missing release dates to `CHANGELOG.md`
=> chore: add missing release dates to changelog

src/Agent/CHANGELOG.md, src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/IAgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/Aggregators/LogEventAggregator.cs, src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/MetricNames.cs, src/Agent/NewRelic/Agent/Core/WireModels/IMetricBuilder.cs, src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs, src/NewRelic.Core/NewRelic.Collections/ConcurrentPriorityQueue.cs, src/NewRelic.Core/NewRelic.Collections/IResizableCappedCollection.cs, tests/Agent/UnitTests/Core.UnitTest/Aggregators/LogEventAggregatorTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/ConcurrentPriorityQueueTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/AgentWrapperApiTests.cs
Adds support for the `Supportability/Logging/Forwarding/Dropped` metric by reporting the number of log messages that get dropped due to capacity constraints. Also included in the metric are logs that are dropped because they have an empty message and no exception.
=> feat: support for Supportability/Logging/Forwarding/Dropped metric

src/Agent/CHANGELOG.md
Update CHANGELOG.md for 10.9.0
=> Update CHANGELOG.md for 10.9.0

src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionManager.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ConnectionManagerTests.cs
Adds a missing handler for `HttpRequestException` during connect, so that we schedule a restart instead of immediately shutting down the agent.
=> fix: Retry connection on HttpRequestException error (#1484)

.github/dependabot.yml, .github/workflows/all_solutions.yml, .github/workflows/assignproj.yml, .github/workflows/build_download_site_index_files.yml, .github/workflows/multiverse_run.yml, .github/workflows/repolinter.yml, .github/workflows/scorecard.yml, .github/workflows/stale_issue.yml, .github/workflows/stale_pr.yml
Updates several Github actions used in our workflows to the latest version, as prompted by Dependabot.
=> ci: version bumps for github actions

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Updates integration tests to use RestSharp v110.2.0
=> test: Update RestSharp support to version 110.2.0

.github/workflows/build_download_site_index_files.yml, .github/workflows/deploy_agent.yml
The workflow that indexes files on the download site got broken with recent security best practice changes. This fixes the issue.
=> ci: Fix S3 Indexer Workflow.

.github/workflows/assignproj.yml
Consolidate to use GITHUB_TOKEN.
=> Use GITHUB_TOKEN that are used in other workflows

src/Agent/NewRelic/Agent/Core/BrowserMonitoring/BrowserMonitoringScriptMaker.cs
Adds a couple of additional debug-level log messages when RUM injection is being skipped, to help with troubleshooting.
=> feat: Add additional logging when RUM injection is being skipped. (#1557)

src/Agent/NewRelic/Agent/Core/ThreadProfiling/ThreadProfilingService.cs, src/NewRelic.Core/CodeAttributes/NrExcludeFromCodeCoverageAttribute.cs, tests/Agent/UnitTests/Core.UnitTest/ThreadProfiling/ThreadProfilingServiceTests.cs, tests/UnitTests.runsettings
Adds more unit tests for public methods in ThreadProfilingService.
Code coverage increases from 17.9% to 88.6%
=> test: Increase unit test coverage for ThreadProfilingService.

build/ArtifactBuilder/Artifacts/MsiInstaller.cs
Adds logic to the ArtifactBuilder so that it can extract the contents of the msi and validate that it contains all of the items that we expect. The validation logic was tested locally.
- ~~[ ] Unit tests, Integration tests, and Unbounded tests completed~~
=> test: Add msi content validation.

build/ArtifactBuilder/Artifacts/Artifact.cs, build/ArtifactBuilder/Artifacts/AzureSiteExtension.cs, build/ArtifactBuilder/Artifacts/DownloadSiteArtifact.cs, build/ArtifactBuilder/Artifacts/LinuxPackage.cs, build/ArtifactBuilder/Artifacts/MsiInstaller.cs, build/ArtifactBuilder/Artifacts/NugetAgent.cs, build/ArtifactBuilder/Artifacts/NugetAgentApi.cs, build/ArtifactBuilder/Artifacts/NugetAgentExtensions.cs, build/ArtifactBuilder/Artifacts/NugetAwsLambdaOpenTracer.cs, build/ArtifactBuilder/Artifacts/NugetAzureCloudServices.cs, build/ArtifactBuilder/Artifacts/NugetAzureWebSites.cs, build/ArtifactBuilder/Artifacts/ZipArchive.cs
Refactors the way content verification is stubbed out so that we can release support for content verification incrementally.
=> test: Enable content verification for some artifacts.

.github/workflows/all_solutions.yml, .github/workflows/assignproj.yml, .github/workflows/build_profiler.yml, .github/workflows/deploy_agent.yml, .github/workflows/deploy_awslambda.yml, .github/workflows/deploy_siteextension.yml, .github/workflows/get_release_checksums.yml, .github/workflows/markdowncheck.yml, .github/workflows/multiverse_run.yml, .github/workflows/nuget_slack_notifications.yml, .github/workflows/release-please.yml, .github/workflows/repolinter.yml, .github/workflows/run_integration_tests.yml, .github/workflows/run_unit_tests.yml, .github/workflows/scorecard.yml, .github/workflows/set_community_label.yml, .github/workflows/stale_issue.yml, .github/workflows/stale_pr.yml
This PR contains the commits from the three Dependabot-generated PRs currently waiting with failed CI checks.  I'm mainly doing this as an experiment to see if the CI failures seen in those PRs are due to a permissions issue with the Dependabot user (i.e., if an actual team member does the PR, does the CI pass).
=> chore(deps): Dependabot roundup 2023-04-27

build/ArtifactBuilder/AgentInfo.cs, build/ArtifactBuilder/Artifacts/MsiInstaller.cs, build/ArtifactBuilder/Artifacts/ZipArchive.cs, build/ArtifactBuilder/ValidationHelpers.cs
This PR completes the POC work for doing Windows ZIP archive content validation.  I liked @nrcventura's approach used for the MSI better, so I ended up doing that instead.  This created some code duplication so I refactored the common code into a helper class.
=> test: complete Windows zip archive content validation from POC

build/ArtifactBuilder/Artifacts/NugetAgent.cs, build/ArtifactBuilder/Artifacts/NugetAgentApi.cs, build/ArtifactBuilder/NuGetHelpers.cs
Adds content validation to the Agent NuGet package and the Agent Api NuGet package. Not everything in the nuget packages were validated. Instead, the focus is on validating the components that are defined in the nuspec files.
=> test: Add content validation to Agent and Agent Api NuGets.

build/ArtifactBuilder/Artifacts/NugetAzureWebSites.cs
Adds content validation to the Azure WebSites NuGet packages within the artifact builder.
=> test: Add content validation to Azure WebSites NuGet packages.

build/ArtifactBuilder/Artifacts/AzureSiteExtension.cs
Adds content verification to the Azure Site Extension.
=> test: Add content validation to Azure Site Extension.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/README.md
Some C# code samples in the readme was marked as XML, so it didn't format correctly on github.
=> chore: Correct language type in README

.github/workflows/scorecard.yml
Maybe this time I'll get it right... ;-)
=> chore(deps): bump github/codeql-action from 2.3.1 to 2.3.3

src/Agent/NewRelic/Agent/Core/ThreadProfiling/ThreadProfilingSampler.cs, tests/Agent/UnitTests/Core.UnitTest/ThreadProfiling/ThreadProfilingSamplerTests.cs
Adds unit tests for `ThreadProfilingSampler`, code coverage is around 90%
=> test: Added unit tests for ThreadProfilingSampler

src/Agent/NewRelic/Agent/Core/BrowserMonitoring/BrowserMonitoringStreamInjector.cs, src/Agent/NewRelic/Agent/Core/BrowserMonitoring/BrowserMonitoringWriter.cs, tests/Agent/UnitTests/Core.UnitTest/BrowserMonitoring/BrowserMonitoringStreamInjectorTests.cs
Adds unit tests for `BrowserMonitoringStreamInjector`, achieves about 96% code coverage for this class.
I also removed `BrowserMonitoringStreamInjector.GetStreamWriter()`, as it was unnecessarily trying to handle exceptions that can't occur -- the method simply returns an action, but doesn't execute it.
=> test: Added unit tests for BrowserMonitoringStreamInjector

src/Agent/NewRelic/Agent/Core/WireModels/IMetricBuilder.cs, src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/MetricWireModelTests.cs
Adds tests to cover the testing gaps in MetricWireModel.cs. Some of the unused code were also removed. 
The tests only partially cover the `ToString` method because the generated IL treats the `MetricName` field as nullable, and there is not a simple way to make that field `null` without changing the production code.
=> test: Add tests for MetricWireModel.

.github/workflows/build_profiler.yml
Modifies profiler build workflow so that it updates the profiler nuget package reference in `Home.csproj` and creates a PR for that change.
=> Feature work/more ci workflow optimization

.github/workflows/all_solutions.yml, .github/workflows/assignproj.yml, .github/workflows/build_profiler.yml, .github/workflows/deploy_agent.yml, .github/workflows/deploy_awslambda.yml, .github/workflows/deploy_siteextension.yml, .github/workflows/get_release_checksums.yml, .github/workflows/markdowncheck.yml, .github/workflows/multiverse_run.yml, .github/workflows/nuget_slack_notifications.yml, .github/workflows/release-please.yml, .github/workflows/repolinter.yml, .github/workflows/run_integration_tests.yml, .github/workflows/scorecard.yml, .github/workflows/set_community_label.yml, .github/workflows/stale_issue.yml, .github/workflows/stale_pr.yml
=> chore(deps): weekly dependabot roundup 2023-05-12

tests/Agent/UnitTests/ParsingTests/MockDbCommand.cs, tests/Agent/UnitTests/ParsingTests/MockDbConnection.cs, tests/Agent/UnitTests/ParsingTests/MySqlExplainPlanActionTests.cs, tests/Agent/UnitTests/ParsingTests/ParsingTests.csproj, tests/Agent/UnitTests/ParsingTests/SqlServerExplainPlanActionTests.cs
Adds unit tests for the MySql and SqlServer explain plan action classes. Not all of the code in the MySql class is covered, because not all of the code is reachable, and can be removed in a separate PR.
=> test: Add unit tests for the explain plan actions.

src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs
Found an unused property in Transaction.cs.
=> chore: remove unused property from Transaction.cs

tests/Agent/IntegrationTests/ApplicationHelperLibraries/ApplicationLifecycle/AppLifecycleManager.cs, tests/Agent/IntegrationTests/Applications/AgentApiExecutor/Program.cs, tests/Agent/IntegrationTests/Applications/ApiAppNameChange/Program.cs, tests/Agent/IntegrationTests/Applications/AspNetCoreMvcCoreFrameworkApplication/Program.cs, tests/Agent/IntegrationTests/Applications/AspNetCoreMvcFrameworkApplication/Program.cs, tests/Agent/IntegrationTests/Applications/AspNetCoreMvcFrameworkAsyncApplication/Program.cs, tests/Agent/IntegrationTests/Applications/ConsoleAsyncApplication/Program.cs, tests/Agent/IntegrationTests/Applications/CustomAttributesWebApi/Program.cs, tests/Agent/IntegrationTests/Applications/DistributedTracingApiApplication/Program.cs, tests/Agent/IntegrationTests/Applications/Owin2WebApi/Program.cs, tests/Agent/IntegrationTests/Applications/Owin3WebApi/Program.cs, tests/Agent/IntegrationTests/Applications/OwinRemotingClient/Program.cs, tests/Agent/IntegrationTests/Applications/OwinRemotingServer/Program.cs, tests/Agent/IntegrationTests/Applications/ThreadProfileStressTest/Program.cs, tests/Agent/IntegrationTests/HostedWebCore/HostedWebCore.cs, tests/Agent/IntegrationTests/Shared/Util/IntegrationTestingFrameworkUtil.cs, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcCoreApplication/Program.cs
Refactors usages of `EventWaitHandle` to ensure proper resource cleanup. This may potentially alleviate some test flakiness due to errors like 
```
HostedWebCore: HostedWebCore.exe failed: Reason unknown.: System.IO.FileLoadException: The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
at HostedWebCore.HostedWebCore.Run() in …
```
=> test: Wrap all usages of EventWaitHandle in a using block to ensure proper cleanup.

.github/workflows/run_unit_tests.yml
=> chore(deps): bump codecov/codecov-action from 3.1.3 to 3.1.4

tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresExecuteScalarAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresExecuteScalarTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresIteratorAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresIteratorTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresSimpleQueryAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresSimpleQueryTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresStoredProcedureAsyncTests.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresStoredProcedureTests.cs
Adds:
- Additional WaitForLogLine for Postgress traces to be sure the tests are okay to proceed
- Updates Postgress unbounded integration tests to use SQL trace override with other overrides
=> test: Add additional WaitForLogLine and faster harvests for Postgres tests.

src/Agent/NewRelic/Agent/Core/Core.csproj, src/Agent/NewRelic/Agent/Core/Logging/LogLevelExtensions.cs, src/Agent/NewRelic/Agent/Core/Logging/LoggerBootstrapper.cs
Also enables Event Log output for .NET Framework apps only.
=> Add Serilog.Async sink, wrap Console and File sinks with Async sink.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Updates the Unbounded tests to test against the latest MongoDB.Driver version (2.19.2).
=> test: Update MongoDB driver in unbounded tests.

src/Agent/NewRelic/Agent/Core/Utilities/UpdatedLoadedModulesService.cs, src/Agent/NewRelic/Agent/Core/WireModels/LoadedModuleWireModelCollection.cs, tests/Agent/UnitTests/CompositeTests/CompositeTestAgent.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LoadedModuleWireModelCollectionJsonConverterTests.cs, tests/Agent/UnitTests/Core.UnitTest/Utilities/UpdatedLoadedModulesServiceTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LoadedModuleWireModelCollectionTests.cs, tests/Agent/UnitTests/Core.UnitTest/WireModels/LoadedModuleWireModelTests.cs
Adds:
- Refactors UpdatedLoadedModulesService and LoadedModuleWireModelCollection to move the collection creation out of hte service class.  Makes it possible to test the creation methods.
- Unit tests for various new classes and code related to vulnerability management
=> Add unit tests for vulnerability management

src/Agent/NewRelic/Profiler/ProfiledMethods/newrelic.config
The ProfiledMethods test tool project, which is now out of date, has some old settings should be removed (these settings should be pulled from the environment instead). This PR removes those hard-coded settings.
=> chore: Remove old settings from profiler testing tool.

.github/workflows/repolinter.yml
Updates repolinter.yml to allow it to create issues in our rep.
=> ci: Give repolinter write permission for issues

README.md
Updates the Community support url.
=> chore: Update community support url.

tests/Agent/MultiverseTesting/ConsoleScanner/ConsoleScanner.csproj, tests/Agent/MultiverseTesting/MultiverseScanner/MultiverseScanner.csproj, tests/Agent/MultiverseTesting/ReportBuilder/ReportBuilder.csproj
Updates all of the dependencies for the multiverse scanner to the latest versions. I ran the scanner locally to ensure that it is still working as expected.
=> chore: Update multiverse scanner dependencies.

.github/workflows/build_download_site_index_files.yml, .github/workflows/build_profiler.yml
=> chore: weekly dependabot roundup 20230623

.github/workflows/all_solutions.yml, .github/workflows/assignproj.yml, .github/workflows/build_profiler.yml, .github/workflows/deploy_agent.yml, .github/workflows/deploy_awslambda.yml, .github/workflows/deploy_siteextension.yml, .github/workflows/get_release_checksums.yml, .github/workflows/markdowncheck.yml, .github/workflows/multiverse_run.yml, .github/workflows/nuget_slack_notifications.yml, .github/workflows/release-please.yml, .github/workflows/repolinter.yml, .github/workflows/run_integration_tests.yml, .github/workflows/scorecard.yml, .github/workflows/set_community_label.yml, .github/workflows/stale_issue.yml, .github/workflows/stale_pr.yml
=> chore: Weekly dependabot roundup 20230630

src/Agent/NewRelic/Agent/Core/Core.csproj
All Infinite Tracing integration tests pass locally.
=> security: Update Grpc.Net.Client library to address Dependabot alerts (#1768)

.github/workflows/multiverse_run.yml
=> ci: bump JamesIves/github-pages-deploy-action from 4.4.2 to 4.4.3

.github/workflows/all_solutions.yml, .github/workflows/assignproj.yml, .github/workflows/build_profiler.yml, .github/workflows/deploy_agent.yml, .github/workflows/deploy_awslambda.yml, .github/workflows/deploy_siteextension.yml, .github/workflows/get_release_checksums.yml, .github/workflows/markdowncheck.yml, .github/workflows/multiverse_run.yml, .github/workflows/nuget_slack_notifications.yml, .github/workflows/release-please.yml, .github/workflows/repolinter.yml, .github/workflows/run_integration_tests.yml, .github/workflows/run_linux_smoke_tests.yml, .github/workflows/scorecard.yml, .github/workflows/set_community_label.yml, .github/workflows/stale_issue.yml, .github/workflows/stale_pr.yml
* Bump step-security/harden-runner to 2.5.0
* Bump google-github-actions/release-please-action to 3.7.11
=> chore: weekly dependabot roundup

.github/workflows/all_solutions.yml, .github/workflows/run_linux_smoke_tests.yml
Invokes the linux smoke test workflow from the all solutions build.
=> test: Run smoke tests from all solutions build

build/BuildTools.sln, build/S3Validator/Configuration.cs, build/S3Validator/ExitCode.cs, build/S3Validator/FileDetails.cs, build/S3Validator/Options.cs, build/S3Validator/Program.cs, build/S3Validator/S3Validator.csproj, build/S3Validator/config.yml
=> Add S3 Validation tool.

.github/workflows/deploy_agent.yml
Same as my last PR, except using the correct base branch...
=> Update APM version on deploy

build/BuildTools.sln, build/NugetValidator/NugetValidator.csproj, build/NugetValidator/Program.cs
Simple console app that checks for existence of a specified NuGet package name and version. Returns 0 on success, -1 on failure.
=> NuGet Version Validator

.github/workflows/post_deploy_agent.yml, deploy/validation/validate-yum/Dockerfile, deploy/validation/validate-yum/check-version.sh
- Add APT and Yum validation with new workflow to be their home.
- Uses pure GHA script for APT
- Uses a dockerfile and script for YUM, but still validates in GHA
- Adds a `validation` directory to /deploy with the docker bits in it.
=> Add APT and Yum validation with new workflow

.github/workflows/post_deploy_agent.yml
Add S3Validator to post_deploy_agent.yml.
=> chore: Add S3Validator to post_deploy_agent.yml.

.github/workflows/post_deploy_agent.yml, build/NugetValidator/Configuration.cs, build/NugetValidator/ConsoleNugetLogger.cs, build/NugetValidator/ExitCode.cs, build/NugetValidator/NugetValidator.csproj, build/NugetValidator/Options.cs, build/NugetValidator/Program.cs, build/NugetValidator/config.yml
Refactored NugetValidator to use the same pattern as S3Validator. 
Added validate-nuget-packages job to post_deploy_agent.yml
=> NugetValidator Refactor, Workflow

.github/workflows/post_deploy_agent.yml
Fix issues in post deploy workflow.
Passes: https://github.com/newrelic/newrelic-dotnet-agent/actions/runs/5754478470
=> chore: Fix issues in post deploy workflow.

.github/workflows/publish_release_notes.yml
Added so we can test the new workflow.
=> chore: Create publish_release_notes.yml.

build/BuildTools.sln, build/ReleaseNotesBuilder/ChangelogParser.cs, build/ReleaseNotesBuilder/Entry.cs, build/ReleaseNotesBuilder/ExitCode.cs, build/ReleaseNotesBuilder/Options.cs, build/ReleaseNotesBuilder/PersistentData.cs, build/ReleaseNotesBuilder/Program.cs, build/ReleaseNotesBuilder/ReleaseNotesBuilder.csproj, build/ReleaseNotesBuilder/ReleaseNotesModel.cs, build/ReleaseNotesBuilder/data.yml
=> chore: Add ReleaseNotesBuilder.

.github/workflows/publish_release_notes.yml, build/ReleaseNotesBuilder/ReleaseNotesModel.cs
Release notes workflow.
Includes moving the security section ahead of the new features section.
Test results:
https://github.com/newrelic/docs-website/pull/14127
https://github.com/newrelic/docs-website/branches/all?query=dotnet-re
=> chore: Add workflow for creating release notes.

.github/workflows/deploy_agent.yml
Adds calls to post deploy and publish release notes workflows from the deploy agent workflow.
=> Add post deploy and publish release notes workflows.

.github/workflows/release-please.yml
Replace the default GH token with one from the new team bot account.  This will enable the release please automation to start the release workflow on its own when the release PR is merged and the release is created.
=> chore: Replace the default GH token with bot account token.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Updates the NLog integration tests to test version 5.2.3 instead of 5.2.2.
Resolves #1829.
=> Test: Update nlog 5.2.2 to 5.2.3.

deploy/validation/validate-yum/Dockerfile
Updates dockerfile image with SHA to resolve code scan alert 224
=> ci: Resolves code scan alert 224

.github/workflows/deploy_agent.yml
chore: Update deploy_agent.yml to set permissions for child job.
=> chore: Update deploy_agent.yml to set permissions for child job.

.github/workflows/deploy_agent.yml
chore: Update deploy_agent.yml with more perms.
=> chore: Update deploy_agent.yml with more perms.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Updates the MongoDB driver version used by the integration tests from 2.20.0 to 2.21.0.
Resolves #1846.
=> Test: Update MongoDB driver version for tests from 2.20.0 to 2.21.0.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
=> chore(deps): Bump NLog to 5.2.4, NLog.Extensions.Logging to 5.3.4 in integration tests

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
=> chore(deps): Bump ElasticSearch to 8.9.2 in integration tests

tests/Agent/IntegrationTests/Applications/ConsoleAsyncApplication/AsyncFireAndForgetUseCases.cs, tests/Agent/IntegrationTests/Applications/ServiceStackApplication/Web.config, tests/Agent/IntegrationTests/Applications/WebApiAsyncApplication/Web.config, tests/Agent/IntegrationTests/ContainerApplications/SmokeTestApp/Program.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplication.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/ThreadProfileStressTestWithCollectorFixture.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MongoDB/MongoDBDriverExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RestSharp/RestSharpExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RestSharp/RestSharpService.cs, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/StackExchangeRedisExerciser.cs, tests/Agent/IntegrationTests/SharedApplications/WcfAppIisHosted/WcfAppIisHosted.csproj, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/BasicMvcApplication.csproj, tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/Web.config, tests/Agent/IntegrationTests/UnboundedApplications/MongoDBApplication/MongoDBApplication.csproj, tests/Agent/IntegrationTests/UnboundedApplications/MongoDBApplication/Web.config, tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlAsyncTests.cs, tests/AwsLambda/UnitTests/AwsLambdaOpenTracerTests/AwsLambdaOpenTracerTests.csproj, tests/Directory.Build.props
Resolves #1883.
This PR includes fixes for the remaining warnings for all of the tests. This includes resolving all of the remaining dependency mismatch warnings.
To help prevent unexpected changes in dependencies, this PR also includes enabling the setting to treat warnings as errors.
=> Chore: Resolve warnings for all tests

src/Agent/NewRelic/Agent/Core/AgentManager.cs
Correct the spelling error in the unsupported framework agent log message.
=> chore: Correct the spelling in unsupported framework message.

src/Agent/NewRelic/Agent/Core/Core.csproj
Resolves the protoc warnings that occur when building the agent. This fix is ported from https://github.com/alanwest/newrelic-dotnet-agent/commit/4eaf6bcb8dd626bf87fcb4bc67ff4644fbb97caf.
=> chore: Fix protoc warnings.

.github/workflows/scripts/nugetSlackNotifications/Program.cs
This PR does the following:
1. Improves Dotty's handling of array indexing issues when looking for current and previous release catalog entries.
2. Improves Dotty's error output to indicate which package is causing the problem.
3. Prevents Dotty from sending a Slack message to the team if an exception is caught while in test mode.
=> ci: improve Dotty error handling and output

src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/IAgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/WireModels/IMetricBuilder.cs, src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/IAgentExperimental.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/KafkaConsumerWrapper.cs
Adds additional metrics related to message count and size, as well as a custom attribute for message size, as per the Kafka spec.
=> Feature work/kafka -- Add more metrics

src/Agent/NewRelic/Agent/Core/AgentShim.cs, src/Agent/NewRelic/Agent/Core/ProfilerAgentMethodCallCache.cs
Update the ProfilerAgentMethodCache with the following changes.
- Remove debugging Console.Write calls
- Add comments and cleanup method visibility
- Move the class to its own file
- Use a struct instead of a local function to reduce heap allocations
=> chore: method cache cleanup

tests/Agent/UnitTests/Core.UnitTest/ProfilerAgentMethodCallCacheTests.cs
Adds tests for the logic in the ProfilerAgentMethodCache class.
=> chore: Add tests for Profiler method cache.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Resolves #1967
Resolves #1974 
Resolves #1977 
Resolves #2013 
Corresponding docs update PR: https://github.com/newrelic/docs-website/pull/15011
=> Core tech test update roundup

src/Agent/NewRelic/Agent/Core/Utilities/ExtensionsLoader.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Providers/Wrapper/Constants.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore6Plus/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore6Plus/PageActionInvokeHandlerAsyncWrapper6Plus.cs
Adds auto-instrumentation support for Razor pages.
Integration tests will follow in a separate PR.
=> Feature work (ASP.NET Core 6 Plus) - Auto instrument Razor pages

tests/Agent/IntegrationTests/ContainerIntegrationTests/LinuxKafkaTests.cs
.. in hopes of getting the SmokeTests job to run successfully
=> test: Configure Kafka container tests to run sequentially rather than in parallel.

.github/workflows/publish_release_notes.yml
Fixing the bug I introduced this morning. 🤦‍♂️
=> ci: Fix quote char bug in release notes automation workflow

.github/workflows/deploy_agent.yml
- Disable updating agent version in staging, but leaving the command just in case we bring it back.  Leaving prod since that still works.
=> Disable updating agent version in staging.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Updates integration tests to use NLog v5.2.6
Resolves #2086
=> chore: Update integration tests to NLog v5.2.6

.github/workflows/deploy_agent.yml
Removes the system config update job from the agent deploy workflow. Resolves #2134.
=> ci: Remove system config update from agent deploy workflow.

tests/Agent/IntegrationTests/IntegrationTests/CSP/AspNetCoreLocalHSMDisabledAndServerSideHSMEnabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CSP/AspNetCoreLocalHSMEnabledAndServerSideHSMDisabledTests.cs, tests/Agent/IntegrationTests/IntegrationTests/CSP/HighSecurityModeServerDisabled.cs, tests/Agent/IntegrationTests/IntegrationTests/CSP/HighSecurityModeServerEnabled.cs
=> test: Update CSP tests to look for "Conflict" instead of "Gone" in connect response body

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
=> test: Update packages for Redis and MongoDB tests

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
=> test: Update MySql tests to use 2.3.3

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Bump NLog to v5.2.8. Resolves #2163
=> test(deps): Bump NLog to v5.2.8

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Updates mysqlconnector to 2.3.5, mysql.data to 8.3.0, stackexchange.redis to 2.7.17
Fixes #2196 
Fixes #2195 
Fixes #2201
=> test(deps): Update mysqlconnector, mysql.data, stackexchange.redis to latest in tests

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Updates the latest tested version of Elastic.Clients.ElasticSearch to 8.12.0
=> tests: Update most recent tested version of Elastic.Clients.ElasticSearch to 8.12.0

.github/workflows/build_profiler.yml, .github/workflows/run_unit_tests.yml
Updates Codecov to v4.0.1 and addresses breaking changes.
=> chore(deps): Update Codecov to v4.0.1

src/Agent/NewRelic/Agent/Core/Config/Configuration.cs, src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/CommonUtils.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs, tests/Agent/IntegrationTests/IntegrationTests/ReJit/NetCore/AddIgnoredInstrumentation.cs, tests/Agent/IntegrationTests/IntegrationTests/ReJit/NetCore/RemoveIgnoredInstrumentation.cs, tests/Agent/IntegrationTests/IntegrationTests/ReJit/NetFramework/AddIgnoredInstrumentation.cs, tests/Agent/IntegrationTests/IntegrationTests/ReJit/NetFramework/RemoveIgnoredInstrumentation.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Adds integration tests to verify that the ignore list can be enabled and disabled. It also validates that the supportability metric is generated if there is an ignore list present when the first agent starts.
This PR also includes a change to make the `assemblyName` and `className` attributes consistent with the casing used for other attributes.
=> test: Add disabled instrumentation integration tests

README.md
Fixes a broken link in README.md, resolves #2243
=> chore: Fix broken link in README.md

src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Core/Wrapper/AgentWrapperApi/Builders/CandidateTransactionName.cs, tests/Agent/UnitTests/Core.UnitTest/Transactions/TransactionTests.cs
The results of playing with Github Copilot for about an hour. Increases unit test code coverage significantly in `Transaction.cs` 
It started out pretty dumb, but the more I used it, the smarter it got - even recognizing code changes I made in one unit test an using the same construct in a unit test it generated later. There's some promise to this tool, I think....
=> test: Additional unit tests for the Transaction class, courtesy of Github Copilot.

.github/dependabot.yml, build/NugetVersionDeprecator/NugetVersionDeprecator.csproj, build/NugetVersionDeprecator/Program.cs
Updating the Oktokit dependency is the main thing that solved the issue. Also update other dependencies.
Also added guard code.
Also updated to .NET 8.
=> ci: Fix exception when creating GitHub issue in NugetVersionDeprecator

tests/Agent/UnitTests/Core.UnitTest/DependencyInjection/AgentServicesTests.cs
Add a unit test with two testcases, serverless mode either enabled or disabled, to verify which services are registered in the agent (or not) DI container based on serverless mode.
=> Add unit tests for agent services registered based on serverless mode

src/Agent/NewRelic/Agent/Core/JsonConverters/JsonArrayConverter.cs, src/Agent/NewRelic/Agent/Core/WireModels/LogEventWireModel.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/JsonArrayConverterTests.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/JsonSerializerHelpersTests.cs, tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LogEventWireModelCollectionJsonConverterTests.cs
Adds / updates unit tests to improve code coverage for `JsonArrayConverter`, `JsonSerializerHelpers` and `LogEventWireModelCollection`.
=> test: Improve code coverage

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests/Redis/StackExchangeRedisTests.cs
Update latest tested versions of the following instrumented libraries:
* Stackexchange.Redis
* MongoDB.Driver
* Microsoft.Data.SqlClient
* Log4Net
Corresponding docs site PR: https://github.com/newrelic/docs-website/pull/16550
=> chore: Update tested core tech library versions

tests/Agent/IntegrationTests/IntegrationTests/LLM/BedrockTests.cs, tests/Agent/IntegrationTests/IntegrationTests/LLM/LLMApiTests.cs, tests/Agent/IntegrationTests/IntegrationTests/LLM/LLMErrorTests.cs, tests/Agent/IntegrationTests/IntegrationTests/LLM/LLMHelpers.cs
Removed an unused local variable, as well as some unused usings.
=> Minor cleanup of integration tests

.github/workflows/deploy_agent.yml
Fix agent deploy booleans to make them literals instead of text
=> ci:Fix agent deploy boolens to make them literals

src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs, src/Agent/NewRelic/Agent/Core/Api/AgentApiImplementation.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/IAgentApi.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/InternalApi.cs, tests/Agent/UnitTests/CompositeTests/AgentApiTests.cs, tests/Agent/UnitTests/Core.UnitTest/Api/AgentApiImplementationTests.cs
Refactors `RecordLlmFeedbackEvent` and adds appropriate unit tests.
=> Refactoring and tests for RecordLlmFeedbackEvent

.github/workflows/build_profiler.yml, .github/workflows/codeql.yml, .github/workflows/multiverse_run.yml, .github/workflows/scorecard.yml
Updates workflows as per the current Dependabot PR, but excludes the changes to `actions/checkout`.
=> ci: Partial dependabot update (excludes actions/checkout)

src/Agent/NewRelic/Agent/Core/DataTransport/ServerlessModeDataTransportService.cs
This was already pretty much working, but now will output the spec-appropriate compressed payload. If Finest level logs are enabled, we will log the uncompressed payload. This can also be used in a real environment by enabling Console logging. I also fixed a couple properties that weren't matching the spec.
Here is a sample from one of my test runs:
```
[2,"NR_LAMBDA_MONITORING",{"arn":"arn:aws:lambda:::function:BasicTestLambda::BasicTestLambda.Function::FunctionHandler","protocol_version":17,"function_version":"$LATEST","execution_environment":"AWS_DOTNET_LAMDBA_TEST_TOOL_BLAZOR_0.15.1","agent_version":"10.21.1.66","metadata_version":2,"agent_language":"dotnet"},"H4sIAAAAAAAACuxW227jNhD9Fz47sqi79NZ4d7EB3Gxbu3kJgmBMjR2iMqlSVFI32H/foWzH3lyQRHb6VASOaWp05nbmkPdsidZIcV2CBVZcqraqBjzlnIdpmsdeHGR …
```
=> Log uncompressed serverless payloads at Finest level

src/Agent/NewRelic/Agent/Core/Agent.cs, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Disable AI Monitoring when HSM is enabled. Updates tests accordingly.
=> Bedrock - HSM updates

src/Agent/NewRelic/Agent/Core/AgentInstallConfiguration.cs, src/Agent/NewRelic/Agent/Core/AgentManager.cs, src/Agent/NewRelic/Agent/Core/Config/BootstrapConfiguration.cs, src/Agent/NewRelic/Agent/Core/Config/ConfigurationLoader.cs, src/Agent/NewRelic/Agent/Core/Configuration/ConfigurationService.cs, src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs, src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/Config/BootstrapConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/Config/BootstrapLogConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/Config/ServerlessModeConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/ConfigurationService.cs, tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ConnectModelTests.cs, tests/Agent/UnitTests/Core.UnitTest/DataTransport/ExhaustiveTestConfiguration.cs, tests/Agent/UnitTests/Core.UnitTest/NewRelic.Agent.Core.FromLegacy/LoggerBootstrapperTest.cs
Refactors the LogConfig code so that it makes it clearer which logging related configuration options can change at runtime, which ones are used at bootstrap time, and which ones are used at both bootstrap and runtime. With these changes all configuration logic is located in either a bootstrap config or default configuration.
The BootstrapConfig was updated to grab its environment variables in the same manner as the DefaultConfiguration, to make it easier to maintain consistency with the overriding and parsing logic.
Settings that were no longer being accessed via AgentInstallConfiguration (for testability reasons) …
=> chore: Refactor LogConfig into BootstrapConfig and DefaultConfiguration

.github/workflows/all_solutions.yml, .github/workflows/run_integration_tests.yml, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/.config/dotnet-tools.json, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/LambdaSelfExecutingAssembly.csproj, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/Program.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Models/ServerlessPayload.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/DotnetTool.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplication.cs, tests/Agent/IntegrationTests/IntegrationTests.sln, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaSmokeTest.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/LambdaSelfExecutingAssemblyFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/LambdaTestToolFixture.cs, tests/Agent/IntegrationTests/Shared/IntegrationTestConfiguration.cs
Adds an initial smoke test for validating the behavior of the new Lambda instrumentation. These changes include many of the building blocks that we can use for building out the other integration tests we want to create for lambda instrumentation.
=> test: Add initial AWS Lambda smoke test

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/HandlerMethodWrapper.cs
Refactors `InvokeTryProcessResponse()` to move the segment / transaction `.End()` calls to a `finally` block to ensure the transaction is always ended.
=> Async response handling refactor

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaEventHelpers.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/HandlerMethodWrapper.cs
Added an exception handler in `AddEventTypeAttributes` to log the event type and actual input object type.
Very minor tweak in the wrapper class to do double-check locking as an optimization.
=> Lambda Tweaks

tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/LambdaSelfExecutingAssembly.csproj, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/Program.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Models/ServerlessPayload.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaContextOnlyParameterTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaCustomEventsTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaCustomParametersTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaMultipleInvocationsTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaOutOfOrderParameterTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaStreamParameterTest.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaContextOnlyParameterFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaCustomEventsTriggerFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaCustomParametersFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaOutOfOrderParameterFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaStreamParameterFixture.cs
Adds more integration tests for different types of lambda methods.
- Methods that generate New Relic custom events
- Methods without any parameters
- Methods without a lambda context
- Methods with a lambda context in different locations (different parameter orders)
- Methods with stream input and output types
Also tests that cold start is reported correctly
=> test: Adds more tests for different lambda methods.

src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, src/Agent/NewRelic/Agent/Core/Transactions/NoOpTransaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ITransaction.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaAttributeExtensions.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaEventHelpers.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaSnsEventTest.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/LambdaEventHelpersTests.cs
Refactors AddLambdaAttribute to support any object type as value.  Updates AttributeDefs, unit tests, and integration tests to allow or test the same.
=> Fix: Refactors AddLambdaAttribute to support any object type as value.

tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/LambdaSelfExecutingAssembly.csproj, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/Program.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaS3EventTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaSnsEventTest.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaS3EventTriggerFixture.cs
Adds tests to validate S3 event attributes.
Also simplifies the assertions used to validate the SNS event attributes.
=> test: Add S3 event tests

.github/workflows/post_deploy_agent.yml, .github/workflows/publish_release_notes.yml
Updates path references in deployment workflows for our release tools that were recently updated to build under .NET8
=> chore: Update .NET 7 path references to .NET 8 in deployment workflows

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/AwsLambdaEventTypeExtensions.cs, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/LambdaSelfExecutingAssembly.csproj, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/Program.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaS3EventTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaSesEventTest.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaSesEventTriggerFixture.cs
Adds tests for SES events, and updates Lambda instrumentation to support to support new versions of the SES library.
Previous library versions used a SimpleEmailEvent, but newer versions use a SimpleEmailEvent<TReceiptAction>.
Also removes an unused constant.
=> Adds tests for SES events, and updates instrumentation to support newer versions of SES.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/HandlerMethodWrapper.cs
Uses `Type.GetInterface()` to look for `ILambdaContext`. Thanks @nrcventura for the idea!
=> Use a more bullet-proof method of checking for the lambda context.

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/AwsLambdaEventType.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/AwsLambdaEventTypeExtensions.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaEventHelpers.cs, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/LambdaSelfExecutingAssembly.csproj, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/Program.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaDynamoDbEventTest.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaDynamoDbEventTriggerFixture.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/AwsLambdaEventTypeExtensionsTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/LambdaEventHelpersTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/Models/AmazonDynamoDBEventsModel.cs
Adds support for handling DynamoDBEvent Lambda triggers.
The lambda agent spec only defines 2 attributes for these events, so those are the only 2 attributes being added and validated (other than the attributes applicable to all event triggers).
=> Adds DynamoDB event support for lambdas.

src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Lambda/LambdaEventHelpers.cs, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/LambdaSelfExecutingAssembly.csproj, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/Program.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaScheduledCloudWatchEventTest.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaScheduledCloudWatchEventTriggerFixture.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Lambda/LambdaEventHelpersTests.cs
Adds tests for scheduled cloudwatch events, and handles missing or empty resources for scheduled cloudwatch events.
=> Add tests for scheduled cloud watch events and handle null or empty resources.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsLambda/HandlerMethodWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaCustomParametersTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaOutOfOrderParameterTest.cs, tests/Agent/IntegrationTests/IntegrationTests/AwsLambda/AwsLambdaStreamParameterTest.cs
Updates the handling of "Unknown" lambda event types to not add an the event type attribute to match the behavior defined in the agent spec.
Adds tests to validate that the appropriate attributes are added to lambdas with an "Unknown" event type.
=> Test that unrecognized lambda event triggers have appropriate attributes.

tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaDynamoDbEventTriggerFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaS3EventTriggerFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaSesEventTriggerFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaSnsEventTriggerFixture.cs
Convert several uber-quoted json string literals to raw string literals.
=> Lambda cleanup: raw string literals aplenty

tests/Agent/IntegrationTests/IntegrationTestHelpers/Models/ServerlessPayload.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaKinesisEventTriggerFixture.cs, tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AwsLambda/LambdaKinesisFirehoseEventTriggerFixture.cs
Updates the remaining lambda test fixtures to use raw strings for the json events.
Fixes transaction trace parsing in the serverless payload tests.
=> test: Lambda test fixes

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/Elasticsearch/ElasticsearchElasticClient.cs
Dotty updates
closes #2445
closes #2454
closes #2460
=> test: Dotty updates

tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/KafkaTests.cs
=> test: Fix intermittent Kafka test failure

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Updates the npgsql versions used by our integration tests. These updates should resolve the problems reported by dependabot following the guidance in the dependabot report for each version being used.
=> test: Update ngpgsql versions used in the tests.

build/Linux/yum/README.md, build/Linux/yum/newrelic-dotnet-agent.repo
Adds the YUM repo definition file and a README with instructions for uploading. 
Related docs PR: https://github.com/newrelic/docs-website/pull/17356
=> chore: Add YUM repo file and upload instructions.

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Resolves #2462
Docs site PR: https://github.com/newrelic/docs-website/pull/17365
=> chore: Update most recent tested version of Elastic.Clients.Elasticsearch to 8.13.12

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
=> chore(deps): Bumps Elastic.Clients.ElasticSearch to 8.14.0

tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkExerciser/AwsSdkExerciser.cs, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/Controllers/AwsSdkController.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Fixtures/AwsSdkContainerTestFixtures.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/AwsSdkTests.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs
Adds some additional methods to the test application and checks for DT headers in the MessageAttributes collection when receiving a message. Maybe not the best way to go, but it seems to work.
=> Additional tests for SQS

tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Resolves #2604 
Docs site update: https://github.com/newrelic/docs-website/pull/17961
=> chore: Update latest tested version of Elastic.Clients.Elasticsearch to 8.14.5

build/NugetVersionDeprecator/NugetVersionDeprecator.csproj, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkTestApp.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Package updates for integration tests (plus a little extra). 
Closes #2624 
Closes #2619 
Closes #2608
=> chore: Dotty roundup

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/AwsSdkPipelineWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AwsSdk/SQSRequestHandler.cs
Minor refactor to split the SQS request handler out to a separate class.
=> chore: Refactor SQS handler to a separate class

src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinition.cs, src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, src/Agent/NewRelic/Agent/Core/Segments/MessageBrokerSegmentData.cs, src/Agent/NewRelic/Agent/Core/Transactions/NoOpTransaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ITransaction.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/BasicGetWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/BasicPublishWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/BasicPublishWrapperLegacy.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/HandleBasicDeliverWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/QueuePurgeWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/RabbitMqHelper.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqTests.cs, tests/Agent/UnitTests/Core.UnitTest/Segments/MessageBrokerSegmentDataTests.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Helpers/SqsHelperTests.cs
- Adds the required attributes to the RabbitMQ spans for entity relationships.
- Adds missing attributes from latest messaging and span specs
- Do not change the segment or transaction naming, or existing attribute values to reduce impact of existing customers.
- Includes integration tests.
=> AWS-APM Entity Relationships: RabbitMQ

.github/workflows/scripts/nugetSlackNotifications/packageInfo.json, tests/Agent/IntegrationTests/Applications/LambdaSelfExecutingAssembly/LambdaSelfExecutingAssembly.csproj, tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkTestApp.csproj, tests/Agent/IntegrationTests/ContainerApplications/KafkaTestApp/KafkaTestApp.csproj, tests/Agent/IntegrationTests/ContainerIntegrationTests/ContainerIntegrationTests.csproj, tests/Agent/IntegrationTests/IntegrationTestHelpers/IntegrationTestHelpers.csproj, tests/Agent/IntegrationTests/IntegrationTests/BasicInstrumentation/WebApiAsyncForceNewTransactionTests.cs, tests/Agent/IntegrationTests/IntegrationTests/IntegrationTests.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MFALatestPackages/MFALatestPackages.csproj, tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj, tests/Agent/Shared/TestSerializationHelpers.Test/TestSerializationHelpers.Test.csproj
Updates several core tech package references (plus some non-core tech), adds a few more packages to the Dotty watchlist.
Closes #2665 
Closes #2666 
Closes #2667 
Closes #2668
=> chore: Update core tech package references, modify Dotty config

src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinition.cs, src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs, src/Agent/NewRelic/Agent/Core/Segments/MessageBrokerSegmentData.cs, src/Agent/NewRelic/Agent/Core/Transactions/NoOpTransaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Core/Utilities/ExtensionsLoader.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ITransaction.cs, src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/AwsSdk/SqsHelper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/Instrumentation.xml, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/KafkaBuilderWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/KafkaConsumerWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/KafkaHelper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Kafka/KafkaProducerWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/BasicGetWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/BasicPublishWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/BasicPublishWrapperLegacy.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/HandleBasicDeliverWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/QueuePurgeWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/RabbitMqHelper.cs, tests/Agent/IntegrationTests/ContainerApplications/KafkaTestApp/Controllers/KafkaController.cs, tests/Agent/IntegrationTests/ContainerApplications/KafkaTestApp/Program.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Fixtures/KafkaTestFixtures.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/AwsSdk/AwsSdkSQSTest.cs, tests/Agent/IntegrationTests/ContainerIntegrationTests/Tests/KafkaTests.cs, tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqTests.cs, tests/Agent/UnitTests/Core.UnitTest/Segments/MessageBrokerSegmentDataTests.cs, tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs, tests/Agent/UnitTests/NewRelic.Agent.Extensions.Tests/Helpers/SqsHelperTests.cs
Adds some additional metrics and attributes for Kafka, Amazon SQS and RabbitMQ libraries.
=> feat: Additional metrics and attributes for some instrumented libraries

tests/Agent/IntegrationTests/ContainerApplications/AwsSdkTestApp/AwsSdkTestApp.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MFALatestPackages/MFALatestPackages.csproj, tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
Resolves #2696 
Resolves #2697 
Resolves #2698
=> chore: Update most recent tested versions of core tech

.github/workflows/nuget_slack_notifications.yml, .github/workflows/scripts/nugetSlackNotifications/CsprojHandler.cs, .github/workflows/scripts/nugetSlackNotifications/NugetVersionData.cs, .github/workflows/scripts/nugetSlackNotifications/PackageInfo.cs, .github/workflows/scripts/nugetSlackNotifications/PackageReference.cs, .github/workflows/scripts/nugetSlackNotifications/Program.cs, .github/workflows/scripts/nugetSlackNotifications/ProjectInfo.cs, .github/workflows/scripts/nugetSlackNotifications/nugetSlackNotifications.csproj, .github/workflows/scripts/nugetSlackNotifications/projectInfo.json, tests/Agent/IntegrationTests/SharedApplications/Common/MFALatestPackages/MFALatestPackages.csproj
- Dotty now creates a PR for all the library updates it finds.
- A new json file was added to tell dotty which csproj files to update.
- Dotty no longer will create issues, only a single PR
- The Slack alert includes the PR link.
=> ci:.NET Innovation Days Q3FY25: Update Dotty to update test library versions automatically via PR

.github/workflows/nuget_slack_notifications.yml
Update dotty to fix PR creation.
=> chore:Update dotty to fix PR creation.

src/Agent/NewRelic/Agent/Core/DistributedTracing/TracingState.cs, tests/Agent/UnitTests/Core.UnitTest/DistributedTracing/TracingStateTests.cs
NUnit got a little smarter about enforcing types.
=> test: Fix unit tests broken after NUnit update

docs/integration-tests.md
Update SDK download URLs. Closes #2934
=> chore: Update SDK download URLs.

.github/workflows/build_buildtools.yml, .github/workflows/scripts/nugetSlackNotifications/Program.cs, .github/workflows/scripts/nugetSlackNotifications/nugetSlackNotifications.csproj
* Minor tweaks to Dotty, mostly about adding a reminder to update the compatibility docs in the body of the PR. 
* Removed some unused variables.
* Added a workflow to build the BuildTools solution when relevant files are modified.
=> chore: Minor Dotty tweak

tests/Agent/IntegrationTests/IntegrationTests/AzureFunction/AzureFunctionHttpTriggerTests.cs
Minor timing tweak to address flaky tests
=> test: Adjust timing for azure function tests

build/Packaging/AzureSiteExtension/CHANGELOG.md
=> docs: Fix bad markdown in AzureSiteExtension CHANGELOG.md

.github/workflows/all_solutions.yml
LLM tests are failing due to our account "not being active".  This is only temporary until the issue is resolved.
=> test: Update all_solutions.yml to disable LLM tests.

.github/workflows/all_solutions.yml
Temporarily disables Couchbase integration tests
=> ci: Temporarily disable Couchbase integration tests

build/Dotty/Program.cs
Minor Dotty tweak to help us remember to update documentation.
=> chore: Enhance Dotty PR body with developer checklist and documentation reminder

.github/workflows/all_solutions.yml
=> test: fix error in test matrix namespace for LLM

.github/workflows/deploy_agent.yml
Updates the deploy workflow to clear both the Fastly and Cloudflare CDN caches, and updates those steps in the workflow to continue on error to give us more timing flexibility for dealing with the migration process.
The shell commands were tested manually.
=> chore: Update deploy steps to clear both CDN caches.

src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/AgentHealth/IAgentHealthReporter.cs, src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs, src/Agent/NewRelic/Agent/Core/Transactions/TransactionFinalizer.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AzureServiceBus/AzureServiceBusReceiveWrapper.cs, tests/Agent/IntegrationTests/UnboundedIntegrationTests/AzureServiceBus/AzureServiceBusW3CTests.cs, tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/TransactionFinalizerTests.cs
Fixes garbage collected error and improves logging slightly.
=> fix: Fixes garbage collected error and improves logging slightly.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AzureServiceBus/AzureServiceBusReceiveWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AzureServiceBus/AzureServiceBusReceiverManagerWrapper.cs, tests/Agent/UnitTests/CompositeTests/SegmentsTests.cs
Clean up comments, code, and tests.
=> chore: Clean up comments, code, and tests.

tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml, tests/Agent/IntegrationTests/UnboundedServices/mssql/backup-database.ps1, tests/Agent/IntegrationTests/UnboundedServices/mssql/backup.sql
Also adds scripts for backing up the NewRelic database (for manual execution via Powershell when needed) and an updated NewRelic.BAK, created from the current container - eliminates the "upgrading" steps when the container restores the backup.
Tested locally with no issues.
=> ci: Fixes an error in docker-compose for mssql.

.github/workflows/deploy-k8s-unboundedservices.yml
Missed a workflow update. Oops.
=> ci: Fix k8s deployment workflow to work with elastic9 change

src/Agent/NewRelic/Home/Home.csproj, src/Agent/NewRelic/Profiler/Configuration/Configuration.h, src/Agent/NewRelic/Profiler/ConfigurationTest/ConfigurationTest.cpp
=> fix: Exclude Azure Function webhost (Linux) process from instrumentation.

tests/Agent/IntegrationTests/UnboundedServices/create_k8s_secrets.sh
Also adds validation that all secrets were successfully parsed from the secrets json file.
=> ci: Update k8s secrets script to fix an error related to elastic. 

deploy/linux/Dockerfile, deploy/linux/deploy_scripts/deploy-packages.bash, deploy/linux/deploy_scripts/libexec/repoman-rebuild.bash
Move back to gpg version 1 and update scripts for the same.
=> chore: Move back to gpg version 1 and update scripts for the same.

deploy/linux/Dockerfile, deploy/linux/deploy_scripts/deploy-packages.bash, deploy/linux/deploy_scripts/libexec/repoman-rebuild.bash
Move back to gpg2.
Yum is working, but APT is now having issues with an option.
=> chore: Move back to gpg2.

src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Bedrock/ConverseAsyncWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Bedrock/InvokeModelAsyncWrapper.cs, src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/OpenAI/OpenAIChatWrapper.cs, tests/Agent/IntegrationTests/IntegrationTests/LLM/AzureOpenAITests.cs, tests/Agent/IntegrationTests/IntegrationTests/LLM/BedrockConverseTests.cs, tests/Agent/IntegrationTests/IntegrationTests/LLM/BedrockInvokeTests.cs, tests/Agent/IntegrationTests/IntegrationTests/LLM/OpenAITests.cs
Adds supportability metrics to report which LLM instrumentation is used. This will help us track adoption of our various instrumentations.
=> chore: Additional supportability metrics for tracking LLM adoption
